import { WorldDef } from "@/types";

// 14 mundos organizados según la Planificación Anual de Matemática de 3º
// grado, en progresión real por trimestre:
// - Trimestre 1 (mundos 1-4, "básico"): números, sumas y restas, cálculo
//   mental, espacio y primeras medidas. Base accesible también para grados
//   más chicos (lectura en voz alta gratis).
// - Trimestre 2 (mundos 5-10, "avanzado"): tablas de multiplicar (agrupadas
//   por dificultad real, no en orden 1 a 10), reparto/división, figuras y
//   medidas de capacidad y peso.
// - Trimestre 3 (mundos 11-14, "avanzado"): integración de las 4
//   operaciones, fracciones, números grandes y cuerpos geométricos/tiempo.
export const WORLDS: WorldDef[] = [
  {
    id: 1,
    name: "La Aldea de los Números",
    emoji: "🏘️",
    subject: "matematica",
    category: "numeros",
    description: "Leé, escribí y ordená números hasta 1.500.",
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
  },
  {
    id: 2,
    name: "El Bosque de las Sumas y Restas",
    emoji: "🌲",
    subject: "matematica",
    category: "sumas-restas",
    description: "Sumar y restar para agregar, quitar, ganar o perder.",
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
  },
  {
    id: 3,
    name: "El Camino del Cálculo Mental",
    emoji: "🧮",
    subject: "matematica",
    category: "calculo-mental",
    description: "Sumas repetidas, cálculo mental y estimación.",
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
  },
  {
    id: 4,
    name: "La Plaza del Espacio Cercano",
    emoji: "📐",
    subject: "matematica",
    category: "espacio",
    description: "Ubicación, medidas de longitud y primeros croquis.",
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
  },
  {
    id: 5,
    name: "La Torre de las Tablas Fáciles",
    emoji: "🏰",
    subject: "matematica",
    category: "tabla",
    tables: [2, 5, 10],
    description: "Practicá las tablas del 2, del 5 y del 10.",
    colorFrom: "#a7f3d0",
    colorTo: "#10b981",
    difficulty: "avanzado",
  },
  {
    id: 6,
    name: "La Ciudad de las Tablas Medias",
    emoji: "🏙️",
    subject: "matematica",
    category: "tabla",
    tables: [3, 4, 6],
    description: "Practicá las tablas del 3, del 4 y del 6.",
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "avanzado",
  },
  {
    id: 7,
    name: "El Desafío de las Tablas Difíciles",
    emoji: "⛰️",
    subject: "matematica",
    category: "tabla",
    tables: [7, 8, 9],
    description: "Animate con las tablas del 7, del 8 y del 9.",
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "avanzado",
  },
  {
    id: 8,
    name: "El Valle de los Repartos",
    emoji: "🍰",
    subject: "matematica",
    category: "reparto",
    description: "Aprendé a repartir en partes iguales.",
    colorFrom: "#fbcfe8",
    colorTo: "#db2777",
    difficulty: "avanzado",
  },
  {
    id: 9,
    name: "El Reino de las Figuras",
    emoji: "🔺",
    subject: "matematica",
    category: "geometria",
    description: "Círculos, cuadrados, rectángulos y triángulos.",
    colorFrom: "#e9d5ff",
    colorTo: "#a855f7",
    difficulty: "avanzado",
  },
  {
    id: 10,
    name: "El Mercado de las Medidas",
    emoji: "🧺",
    subject: "matematica",
    category: "medidas",
    description: "Capacidad y peso: litros, kilos, medios y cuartos.",
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "avanzado",
  },
  {
    id: 11,
    name: "La Plaza de los Problemas",
    emoji: "🧩",
    subject: "matematica",
    category: "problemas",
    description: "Situaciones problemáticas con las cuatro operaciones.",
    colorFrom: "#fde68a",
    colorTo: "#d97706",
    difficulty: "avanzado",
  },
  {
    id: 12,
    name: "La Isla de las Fracciones",
    emoji: "🍕",
    subject: "matematica",
    category: "fracciones",
    description: "Mitades y cuartos en situaciones de reparto.",
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "avanzado",
  },
  {
    id: 13,
    name: "El Puente de los Números Grandes",
    emoji: "🌉",
    subject: "matematica",
    category: "numeros-grandes",
    description: "Sumas y restas con números de 2 y 3 cifras.",
    colorFrom: "#bfdbfe",
    colorTo: "#2563eb",
    difficulty: "avanzado",
  },
  {
    id: 14,
    name: "El Observatorio del Tiempo y los Cuerpos",
    emoji: "🔭",
    subject: "matematica",
    category: "cuerpos-tiempo",
    description: "Cuerpos geométricos y equivalencias de tiempo.",
    colorFrom: "#c4b5fd",
    colorTo: "#7c3aed",
    difficulty: "avanzado",
  },

  // ---------------------------------------------------------------------
  // Lengua: 12 mundos según la Planificación Anual de Lengua de 3º grado.
  // - Trimestre 1 (15-18, "básico"): oralidad y juegos de palabras, cuentos
  //   compartidos, primeras palabras escritas, clases de palabras.
  // - Trimestre 2 (19-22, "avanzado"): leyendas e historietas, textos
  //   informativos, cartas e historietas propias, cómo cambian las palabras.
  // - Trimestre 3 (23-26, "avanzado"): debates, lectura autónoma, cuentos
  //   propios, el sentido de las palabras.
  // ---------------------------------------------------------------------
  {
    id: 15,
    name: "La Feria de las Palabras",
    emoji: "🎪",
    subject: "lengua",
    category: "oralidad-inicial",
    description: "Rimas, adivinanzas y trabalenguas para jugar con las palabras.",
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
  },
  {
    id: 16,
    name: "La Biblioteca de los Cuentos",
    emoji: "📖",
    subject: "lengua",
    category: "lectura-cuentos",
    description: "Cuentos, fábulas y poesías para leer juntos.",
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
  },
  {
    id: 17,
    name: "El Taller de las Primeras Palabras",
    emoji: "✏️",
    subject: "lengua",
    category: "escritura-inicial",
    description: "Textos cortos, mayúsculas, puntos y comas.",
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
  },
  {
    id: 18,
    name: "La Casa de las Clases de Palabras",
    emoji: "🏠",
    subject: "lengua",
    category: "clases-palabras",
    description: "Sustantivos, adjetivos, verbos, sinónimos y antónimos.",
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
  },
  {
    id: 19,
    name: "El Castillo de las Leyendas",
    emoji: "🏯",
    subject: "lengua",
    category: "lectura-narrativa",
    description: "Leyendas, historietas y la estructura de una historia.",
    colorFrom: "#a7f3d0",
    colorTo: "#10b981",
    difficulty: "avanzado",
  },
  {
    id: 20,
    name: "El Museo de los Textos Informativos",
    emoji: "🏛️",
    subject: "lengua",
    category: "lectura-informativa",
    description: "Textos informativos, tapa, índice y contratapa.",
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "avanzado",
  },
  {
    id: 21,
    name: "La Oficina de Correos",
    emoji: "✉️",
    subject: "lengua",
    category: "escritura-narrativa",
    description: "Cartas, historietas propias y conectores.",
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "avanzado",
  },
  {
    id: 22,
    name: "El Laboratorio de las Palabras",
    emoji: "🧪",
    subject: "lengua",
    category: "formacion-palabras",
    description: "Concordancia, prefijos, sílaba tónica y ortografía.",
    colorFrom: "#fbcfe8",
    colorTo: "#db2777",
    difficulty: "avanzado",
  },
  {
    id: 23,
    name: "La Plaza de los Debates",
    emoji: "🗣️",
    subject: "lengua",
    category: "oralidad-debate",
    description: "Opinar, argumentar y escuchar con respeto.",
    colorFrom: "#e9d5ff",
    colorTo: "#a855f7",
    difficulty: "avanzado",
  },
  {
    id: 24,
    name: "El Faro de la Lectura Autónoma",
    emoji: "🗼",
    subject: "lengua",
    category: "lectura-autonoma",
    description: "Información explícita, implícita y síntesis de textos.",
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "avanzado",
  },
  {
    id: 25,
    name: "El Estudio de los Cuentos Propios",
    emoji: "🖋️",
    subject: "lengua",
    category: "escritura-creativa",
    description: "Escribir cuentos e instructivos, paso a paso.",
    colorFrom: "#fde68a",
    colorTo: "#d97706",
    difficulty: "avanzado",
  },
  {
    id: 26,
    name: "El Observatorio del Sentido",
    emoji: "🔮",
    subject: "lengua",
    category: "sentido-palabras",
    description: "Sentido literal y figurado, y ortografía avanzada.",
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "avanzado",
  },

  // ---------------------------------------------------------------------
  // Ciencias Naturales: 12 mundos según la Planificación Anual de Ciencias
  // Naturales de 3º grado, cruzando los 4 ejes NAP (seres vivos, materiales,
  // mundo físico, Tierra y Universo) por los 3 trimestres:
  // - Trimestre 1 (27-30, "básico"): exploración y bases — fauna y flora
  //   local, mezclas sencillas, fenómenos térmicos y mecánicos básicos,
  //   paisajes y primera orientación espacial.
  // - Trimestre 2 (31-34, "avanzado"): profundización y relaciones —
  //   cadenas alimentarias, cambios de estado, sonido y vibración, cielo y
  //   fenómenos atmosféricos.
  // - Trimestre 3 (35-38, "avanzado"): integración y mirada global —
  //   comparación de seres vivos, informes de investigación, integración de
  //   fenómenos físicos, ciclos del cielo y tiempo atmosférico.
  // ---------------------------------------------------------------------
  {
    id: 27,
    name: "La Reserva de la Fauna y Flora",
    emoji: "🦫",
    subject: "naturales",
    category: "seres-vivos-diversidad",
    description: "Animales y plantas de la zona, y el cuerpo humano.",
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
  },
  {
    id: 28,
    name: "El Laboratorio de las Mezclas",
    emoji: "🧫",
    subject: "naturales",
    category: "materiales-mezclas",
    description: "Mezclas sencillas: agua con arena, sal y azúcar.",
    colorFrom: "#bae6fd",
    colorTo: "#0ea5e9",
    difficulty: "basico",
  },
  {
    id: 29,
    name: "El Taller del Calor y el Movimiento",
    emoji: "🔥",
    subject: "naturales",
    category: "fenomenos-fisicos-basicos",
    description: "Calor, frío y acciones mecánicas: empujar, estirar, aplastar.",
    colorFrom: "#fed7aa",
    colorTo: "#ea580c",
    difficulty: "basico",
  },
  {
    id: 30,
    name: "El Mirador de los Paisajes",
    emoji: "🏞️",
    subject: "naturales",
    category: "paisajes-orientacion",
    description: "Paisajes locales y provinciales, y puntos cardinales.",
    colorFrom: "#fef08a",
    colorTo: "#ca8a04",
    difficulty: "basico",
  },
  {
    id: 31,
    name: "La Red de la Naturaleza",
    emoji: "🕸️",
    subject: "naturales",
    category: "seres-vivos-interacciones",
    description: "Cadenas alimentarias, higiene y agua potable.",
    colorFrom: "#a7f3d0",
    colorTo: "#059669",
    difficulty: "avanzado",
  },
  {
    id: 32,
    name: "La Fábrica de las Transformaciones",
    emoji: "🧊",
    subject: "naturales",
    category: "materiales-cambios-estado",
    description: "Cambios de estado del agua y separación de mezclas.",
    colorFrom: "#c7d2fe",
    colorTo: "#4f46e5",
    difficulty: "avanzado",
  },
  {
    id: 33,
    name: "El Estudio del Sonido",
    emoji: "🔔",
    subject: "naturales",
    category: "sonido-vibracion",
    description: "Sonido, vibración y conducción del calor.",
    colorFrom: "#fbcfe8",
    colorTo: "#db2777",
    difficulty: "avanzado",
  },
  {
    id: 34,
    name: "El Observatorio del Cielo",
    emoji: "🌙",
    subject: "naturales",
    category: "cielo-fenomenos-atmosfericos",
    description: "Fenómenos atmosféricos y movimientos del Sol y la Luna.",
    colorFrom: "#ddd6fe",
    colorTo: "#7c3aed",
    difficulty: "avanzado",
  },
  {
    id: 35,
    name: "El Gran Atlas de la Vida",
    emoji: "🌍",
    subject: "naturales",
    category: "seres-vivos-comparacion",
    description: "Seres vivos de acá y de otras regiones, y el cuerpo humano.",
    colorFrom: "#bbf7d0",
    colorTo: "#15803d",
    difficulty: "avanzado",
  },
  {
    id: 36,
    name: "El Instituto de Investigación",
    emoji: "🔬",
    subject: "naturales",
    category: "materiales-informes",
    description: "Transformaciones de materiales e informes de investigación.",
    colorFrom: "#bae6fd",
    colorTo: "#0369a1",
    difficulty: "avanzado",
  },
  {
    id: 37,
    name: "El Gran Experimento",
    emoji: "🧪",
    subject: "naturales",
    category: "fenomenos-fisicos-integracion",
    description: "Luz, sonido y calor: experimentos integradores.",
    colorFrom: "#fde68a",
    colorTo: "#d97706",
    difficulty: "avanzado",
  },
  {
    id: 38,
    name: "La Brújula del Tiempo",
    emoji: "🧭",
    subject: "naturales",
    category: "tiempo-orientacion",
    description: "Ciclos del cielo, tiempo atmosférico y puntos cardinales.",
    colorFrom: "#fecaca",
    colorTo: "#dc2626",
    difficulty: "avanzado",
  },

  // ---------------------------------------------------------------------
  // Ciencias Sociales: 9 mundos según la Planificación Anual de Ciencias
  // Sociales de 3º grado, cruzando los 3 ejes NAP (espacios geográficos,
  // sociedades en el tiempo, actividades humanas y organización social) por
  // los 3 trimestres:
  // - Trimestre 1 (39-41, "básico"): paisajes urbanos y rurales de la zona;
  //   grupos sociales coloniales y su vida cotidiana; autoridades locales y
  //   normas de convivencia.
  // - Trimestre 2 (42-44, "avanzado"): circuitos productivos regionales;
  //   cambios/continuidades y patrimonio; funciones del gobierno municipal.
  // - Trimestre 3 (45-47, "avanzado"): transporte, recursos y ambiente;
  //   nociones temporales y procesos históricos; diversidad cultural y
  //   ciudadanía.
  // ---------------------------------------------------------------------
  {
    id: 39,
    name: "El Mirador de los Paisajes Urbanos y Rurales",
    emoji: "🏘️",
    subject: "sociales",
    category: "paisajes-urbano-rural",
    description: "Paisajes urbanos y rurales, y sus elementos en croquis.",
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
  },
  {
    id: 40,
    name: "El Pueblo Colonial",
    emoji: "🏺",
    subject: "sociales",
    category: "sociedad-colonial",
    description: "Grupos sociales coloniales y su vida cotidiana.",
    colorFrom: "#fed7aa",
    colorTo: "#c2410c",
    difficulty: "basico",
  },
  {
    id: 41,
    name: "El Cabildo y las Autoridades",
    emoji: "🏛️",
    subject: "sociales",
    category: "autoridades-convivencia",
    description: "Autoridades locales, normas y resolución de conflictos.",
    colorFrom: "#bfdbfe",
    colorTo: "#2563eb",
    difficulty: "basico",
  },
  {
    id: 42,
    name: "La Ruta de los Circuitos Productivos",
    emoji: "🚛",
    subject: "sociales",
    category: "circuitos-productivos",
    description: "Actores, componentes y etapas de un circuito productivo.",
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "avanzado",
  },
  {
    id: 43,
    name: "El Museo del Patrimonio",
    emoji: "🏺",
    subject: "sociales",
    category: "patrimonio-cambios",
    description: "Cambios, continuidades y bienes patrimoniales.",
    colorFrom: "#ddd6fe",
    colorTo: "#7c3aed",
    difficulty: "avanzado",
  },
  {
    id: 44,
    name: "El Palacio Municipal",
    emoji: "🏢",
    subject: "sociales",
    category: "gobierno-municipal",
    description: "Intendente, Concejo Deliberante y ordenanzas municipales.",
    colorFrom: "#fbcfe8",
    colorTo: "#db2777",
    difficulty: "avanzado",
  },
  {
    id: 45,
    name: "La Red de Transportes y Ambiente",
    emoji: "🚚",
    subject: "sociales",
    category: "transporte-ambiente",
    description: "Transporte, recursos naturales y cuidado del ambiente.",
    colorFrom: "#a7f3d0",
    colorTo: "#059669",
    difficulty: "avanzado",
  },
  {
    id: 46,
    name: "La Línea del Tiempo Argentina",
    emoji: "📜",
    subject: "sociales",
    category: "linea-tiempo-historica",
    description: "Nociones temporales, procesos históricos y conmemoraciones.",
    colorFrom: "#fef08a",
    colorTo: "#ca8a04",
    difficulty: "avanzado",
  },
  {
    id: 47,
    name: "El Mosaico Cultural",
    emoji: "🌐",
    subject: "sociales",
    category: "diversidad-ciudadania",
    description: "Diversidad cultural, derechos y proyectos colectivos.",
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "avanzado",
  },
];

export function getWorld(id: number): WorldDef | undefined {
  return WORLDS.find((w) => w.id === id);
}
