import { WorldDef } from "@/types";

// Los 10 mundos originales (recuperados de la planificación de AI Studio)
// más 4 mundos nuevos: reparto, geometría, problemas y números grandes.
export const WORLDS: WorldDef[] = [
  {
    id: 1,
    name: "La Aldea de las Sumas",
    emoji: "🏘️",
    category: "tabla",
    table: 1,
    description: "Practicá la tabla del 1 y calentá motores.",
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
  },
  {
    id: 2,
    name: "El Bosque de las Restas",
    emoji: "🌲",
    category: "tabla",
    table: 2,
    description: "Explorá el bosque resolviendo la tabla del 2.",
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
  },
  {
    id: 3,
    name: "El Mercado de los Grupos",
    emoji: "🧺",
    category: "tabla",
    table: 3,
    description: "Agrupá y contá con la tabla del 3.",
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
  },
  {
    id: 4,
    name: "La Fábrica de las Tablas",
    emoji: "🏭",
    category: "tabla",
    table: 4,
    description: "Fabricá resultados con la tabla del 4.",
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
  },
  {
    id: 5,
    name: "El Valle de los Repartos",
    emoji: "🏞️",
    category: "tabla",
    table: 5,
    description: "Repartí y multiplicá con la tabla del 5.",
    colorFrom: "#a7f3d0",
    colorTo: "#10b981",
    difficulty: "basico",
  },
  {
    id: 6,
    name: "La Ciudad de los Cienes",
    emoji: "🏙️",
    category: "tabla",
    table: 6,
    description: "Construí la ciudad con la tabla del 6.",
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
  },
  {
    id: 7,
    name: "El Parque Geométrico",
    emoji: "🎡",
    category: "tabla",
    table: 7,
    description: "Divertite en el parque con la tabla del 7.",
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
  },
  {
    id: 8,
    name: "El Taller del Tiempo",
    emoji: "⏱️",
    category: "tabla",
    table: 8,
    description: "Contra el reloj con la tabla del 8.",
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
  },
  {
    id: 9,
    name: "La Isla de las Monedas",
    emoji: "🏝️",
    category: "tabla",
    table: 9,
    description: "Juntá tesoros con la tabla del 9.",
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
  },
  {
    id: 10,
    name: "La Cumbre de los Desafíos",
    emoji: "🏔️",
    category: "tabla",
    table: 10,
    description: "El desafío final con la tabla del 10.",
    colorFrom: "#bae6fd",
    colorTo: "#0ea5e9",
    difficulty: "basico",
  },
  {
    id: 11,
    name: "El Valle de la División",
    emoji: "🍰",
    category: "reparto",
    description: "Aprendé a repartir en partes iguales.",
    colorFrom: "#fbcfe8",
    colorTo: "#db2777",
    difficulty: "avanzado",
  },
  {
    id: 12,
    name: "El Reino de las Figuras",
    emoji: "🔺",
    category: "geometria",
    description: "Círculos, cuadrados, rectángulos y triángulos.",
    colorFrom: "#e9d5ff",
    colorTo: "#a855f7",
    difficulty: "avanzado",
  },
  {
    id: 13,
    name: "La Plaza de los Problemas",
    emoji: "🧩",
    category: "problemas",
    description: "Situaciones problemáticas para resolver en equipo.",
    colorFrom: "#fde68a",
    colorTo: "#d97706",
    difficulty: "avanzado",
  },
  {
    id: 14,
    name: "El Puente de los Números Grandes",
    emoji: "🌉",
    category: "numeros-grandes",
    description: "Sumas y restas con números de 2 y 3 cifras.",
    colorFrom: "#bfdbfe",
    colorTo: "#2563eb",
    difficulty: "avanzado",
  },
];

export function getWorld(id: number): WorldDef | undefined {
  return WORLDS.find((w) => w.id === id);
}
