// Habilidades de 2.º grado: seguimiento por habilidad y materia según el
// Diseño Curricular de Santa Cruz. Cada actividad declara qué habilidades
// trabaja y las respuestas alimentan el progreso del alumno.
import { WorldSubject } from "@/types";

export interface SkillDef {
  id: string;
  subject: WorldSubject;
  label: string;
  axis: string;
  description: string;
  practice: string;
}

export const GRADE2_SKILLS: SkillDef[] = [
  // ---------- Lengua ----------
  {
    id: "l2-fluidez",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Lectura fluida de palabras y oraciones",
    description: "Lee palabras y oraciones con fluidez y precisión, sin deletreo vacilante.",
    practice: "Lectura diaria en voz alta de oraciones breves y tarjetas de palabras.",
  },
  {
    id: "l2-trabadas",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Sílabas trabadas y complejas",
    description: "Reconoce y lee grupos consonánticos con L y R (bl, br, cl, cr, dr, fl, fr, gl, gr, pl, pr, tr).",
    practice: "Jugar con trabalenguas y tarjetas de sílabas trabadas.",
  },
  {
    id: "l2-ortografia-c-q",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Ortografía: C y Q",
    description: "Distingue el uso de ca, co, cu frente a que, qui y el sonido suave de ce, ci.",
    practice: "Armar parejas de palabras con que/qui y ca/co/cu.",
  },
  {
    id: "l2-ortografia-g",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Ortografía: G, GU y GÜ",
    description: "Distingue ga, go, gu, gue, gui, ge, gi y el uso de la diéresis en güe, güi.",
    practice: "Clasificar palabras con sonido suave (manguera) y fuerte (gente).",
  },
  {
    id: "l2-ortografia-r",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Uso de R y RR",
    description: "Identifica el sonido suave de la r y el sonido fuerte (inicial o doble rr entre vocales).",
    practice: "Comparar pares como careta/carreta y pero/perro.",
  },
  {
    id: "l2-ortografia-mb-mp",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Regla de MB y MP",
    description: "Aplica la convención ortográfica de escribir m antes de b y p.",
    practice: "Buscar palabras con mb y mp en canciones y poesías.",
  },
  {
    id: "l2-ortografia-h-ch",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Uso de H y dígrafo CH",
    description: "Reconoce palabras que se escriben con h muda y palabras con el dígrafo ch.",
    practice: "Fichas de palabras con h ilustradas para recordar su escritura.",
  },
  {
    id: "l2-puntuacion",
    subject: "lengua",
    axis: "Escritura y norma",
    label: "Mayúscula y punto",
    description: "Empieza oraciones con mayúscula y coloca punto seguido o final.",
    practice: "Revisar oraciones para encontrar dónde falta el punto o la mayúscula.",
  },
  {
    id: "l2-sustantivos",
    subject: "lengua",
    axis: "Reflexión sobre el lenguaje",
    label: "Sustantivos comunes y propios",
    description: "Distingue nombres comunes (objetos, animales) de nombres propios (personas, lugares).",
    practice: "Jugar al Tutti Frutti con nombres de personas, ciudades y animales.",
  },
  {
    id: "l2-genero-numero",
    subject: "lengua",
    axis: "Reflexión sobre el lenguaje",
    label: "Género y número",
    description: "Identifica singular/plural y masculino/femenino en palabras y frases.",
    practice: "Transformar oraciones de uno a muchos (el gato duerme → los gatos duermen).",
  },
  {
    id: "l2-adjetivos",
    subject: "lengua",
    axis: "Reflexión sobre el lenguaje",
    label: "Adjetivos y concordancia",
    description: "Reconoce cualidades y mantiene la concordancia con el sustantivo.",
    practice: "Elegir adjetivos que describan mascotas o personajes de cuentos.",
  },
  {
    id: "l2-familias-palabras",
    subject: "lengua",
    axis: "Reflexión sobre el lenguaje",
    label: "Familias de palabras y derivación",
    description: "Reconoce palabras de la misma familia, diminutivos (-ito) y aumentativos (-ote).",
    practice: "Armar trenes de palabras: pan → panadero → panadería → pancito.",
  },
  {
    id: "l2-abecedario",
    subject: "lengua",
    axis: "Reflexión sobre el lenguaje",
    label: "Abecedario y orden alfabético",
    description: "Ordena alfabéticamente palabras por su primera y segunda letra.",
    practice: "Ordenar listas de compras o nombres de amigos según el abecedario.",
  },
  {
    id: "l2-comprension-cuento",
    subject: "lengua",
    axis: "Literatura y comprensión",
    label: "Comprensión de narraciones y fábulas",
    description: "Reconoce situación inicial, problema y resolución en cuentos y fábulas.",
    practice: "Renarrar oralmente qué pasó primero, qué se complicó y cómo terminó.",
  },
  // Comprensión lectora por tipo de pregunta (mundos de cuentos, src/lib/cuentos).
  {
    id: "l2-comp-literal",
    subject: "lengua",
    axis: "Comprensión lectora",
    label: "Información explícita",
    description: "Encuentra en el texto quién, qué, dónde y cuándo.",
    practice: "Después de leer, buscar juntos en el texto la frase que responde una pregunta.",
  },
  {
    id: "l2-comp-secuencia",
    subject: "lengua",
    axis: "Comprensión lectora",
    label: "Secuencia de hechos",
    description: "Ordena los hechos del cuento: antes, después, al final.",
    practice: "Recortar las escenas de un cuento y ordenarlas; contar qué pasó entre una y otra.",
  },
  {
    id: "l2-comp-inferencial",
    subject: "lengua",
    axis: "Comprensión lectora",
    label: "Inferencias",
    description: "Deduce lo que no está escrito: causas, intenciones y sentimientos de los personajes.",
    practice: "Preguntar «¿por qué lo habrá hecho?» y «¿cómo se habrá sentido?» y buscar pistas en el texto.",
  },
  {
    id: "l2-comp-vocabulario",
    subject: "lengua",
    axis: "Comprensión lectora",
    label: "Vocabulario en contexto",
    description: "Deduce el significado de palabras nuevas por el contexto.",
    practice: "Subrayar una palabra difícil y pensar entre todos qué querrá decir según la oración.",
  },
  {
    id: "l2-comp-critica",
    subject: "lengua",
    axis: "Comprensión lectora",
    label: "Estructura y opinión",
    description: "Reconoce inicio, conflicto y desenlace, la enseñanza y opina con fundamentos.",
    practice: "Inventar otro final y explicar por qué les gusta más o menos que el original.",
  },
  {
    id: "l2-poesia-rimas",
    subject: "lengua",
    axis: "Literatura",
    label: "Poesía, coplas y trabalenguas",
    description: "Aprecia el ritmo, la rima y la musicalidad en poesías y trabalenguas.",
    practice: "Desafíos de trabalenguas en familia aumentando la velocidad.",
  },
  {
    id: "l2-textos-instructivos",
    subject: "lengua",
    axis: "Lectura y escritura",
    label: "Textos instructivos",
    description: "Comprende y sigue instrucciones en orden (recetas, reglas de juego).",
    practice: "Seguir los pasos de una receta sencilla de cocina.",
  },
  {
    id: "l2-textos-sociales",
    subject: "lengua",
    axis: "Lectura y escritura",
    label: "Cartas, notas e historietas",
    description: "Comprende la estructura de notas breves, mensajes, cartas e historietas.",
    practice: "Escribir un mensaje de saludo o una esquela para un amigo.",
  },
  {
    id: "l2-escritura-oraciones",
    subject: "lengua",
    axis: "Escritura",
    label: "Escritura de oraciones coherentes",
    description: "Produce oraciones completas con sentido propio y separación convencional entre palabras.",
    practice: "Escribir epígrafes o comentarios breves para fotos familiares.",
  },

  // ---------- Matemática ----------
  {
    id: "m2-numeros-100",
    subject: "matematica",
    axis: "Número",
    label: "Cuadro numérico hasta 100",
    description: "Identifica regularidades en filas de dieces y columnas de unos en el cuadro de 100.",
    practice: "Buscar números escondidos o tapados en el cuadro del 100.",
  },
  {
    id: "m2-numeros-1000",
    subject: "matematica",
    axis: "Número",
    label: "Números hasta 1000",
    description: "Lee, escribe y ordena números hasta el 1000 reconociendo los cienes.",
    practice: "Contar de 100 en 100 y ubicar números en rectas numéricas.",
  },
  {
    id: "m2-valor-posicional",
    subject: "matematica",
    axis: "Número",
    label: "Valor posicional (cienes, dieces, unos)",
    description: "Descompone y compone números según el valor posicional de sus cifras.",
    practice: "Desarmar números en dieces y unos: 348 = 300 + 40 + 8.",
  },
  {
    id: "m2-dinero",
    subject: "matematica",
    axis: "Número y operaciones",
    label: "Billetes y monedas",
    description: "Resuelve pagos y equivalencias usando billetes de $100, $10 y monedas de $1.",
    practice: "Juegos de compraventa y cálculo de vueltos con dinero de juguete.",
  },
  {
    id: "m2-comparar-ordenar",
    subject: "matematica",
    axis: "Número",
    label: "Comparar y ordenar hasta 1000",
    description: "Compara números de 2 y 3 cifras (mayor que, menor que, igual) y halla anterior/siguiente.",
    practice: "Ordenar tarjetas con números de tres cifras de menor a mayor.",
  },
  {
    id: "m2-calculo-mental",
    subject: "matematica",
    axis: "Operaciones",
    label: "Cálculo mental aditivo",
    description: "Resuelve mentalmente dobles, mitades, complementos a 10 y 100, sumas y restas de 10 y 100.",
    practice: "Jugar al cálculo veloz: ¿cuánto le falta al 40 para llegar a 100?",
  },
  {
    id: "m2-suma-algoritmos",
    subject: "matematica",
    axis: "Operaciones",
    label: "Sumas con y sin dificultad",
    description: "Resuelve sumas desarmando números o en columna, con reagrupación de unos a dieces.",
    practice: "Sumar precios de dos productos y verificar con billetes.",
  },
  {
    id: "m2-resta-algoritmos",
    subject: "matematica",
    axis: "Operaciones",
    label: "Restas con y sin dificultad",
    description: "Resuelve restas desarmando dieces cuando no alcanza la cifra de los unos.",
    practice: "Practicar restas vinculadas a situaciones de vuelto o pérdida.",
  },
  {
    id: "m2-problemas-aditivos",
    subject: "matematica",
    axis: "Operaciones",
    label: "Problemas de suma y resta",
    description: "Interpreta y resuelve problemas de agregar, quitar, comparar, completar y avanzar/retroceder.",
    practice: "Plantear problemas a partir de situaciones cotidianas del hogar.",
  },
  {
    id: "m2-multiplicacion-inicio",
    subject: "matematica",
    axis: "Operaciones",
    label: "Inicio de la multiplicación",
    description: "Reconoce la multiplicación como sumas repetidas de sumandos iguales y organizaciones rectangulares.",
    practice: "Contar patas de animales o ruedas de autos sumando en grupos iguales.",
  },
  {
    id: "m2-tablas",
    subject: "matematica",
    axis: "Operaciones",
    label: "Tablas del 2, del 5 y del 10",
    description: "Construye y memoriza progresivamente los productos de las tablas del 2, 5 y 10.",
    practice: "Cantar y practicar las tablas del 2, del 5 y del 10 con juegos de palmas.",
  },
  {
    id: "m2-reparto",
    subject: "matematica",
    axis: "Operaciones",
    label: "Reparto equitativo y partición",
    description: "Resuelve situaciones de repartir en partes iguales con dibujos o sumas sucesivas.",
    practice: "Repartir caramelos o lápices entre hermanos de manera equitativa.",
  },
  {
    id: "m2-geometria-2d",
    subject: "matematica",
    axis: "Geometría",
    label: "Figuras geométricas planas",
    description: "Describe figuras planas por sus bordes (rectos/curvos), cantidad de lados y vértices.",
    practice: "Plegar papel y reconocer triángulos, cuadrados y rectángulos.",
  },
  {
    id: "m2-geometria-3d",
    subject: "matematica",
    axis: "Geometría",
    label: "Cuerpos geométricos",
    description: "Identifica cubos, prismas, pirámides, cilindros y esferas; reconoce caras, aristas y vértices.",
    practice: "Clasificar cajas y envases reciclables según su forma geométrica.",
  },
  {
    id: "m2-espacio-planos",
    subject: "matematica",
    axis: "Espacio",
    label: "Ubicación, croquis y planos",
    description: "Interpreta y describe recorridos y ubicaciones en planos sencillos (aula, plaza, casa).",
    practice: "Dibujar el plano de la propia habitación con sus muebles.",
  },
  {
    id: "m2-medidas-longitud",
    subject: "matematica",
    axis: "Medida",
    label: "Medición de longitudes (metro y cm)",
    description: "Mide objetos con regla y cinta métrica; conoce la relación entre metro y centímetro.",
    practice: "Medir con regla útiles escolares y compararlos.",
  },
  {
    id: "m2-medidas-capacidad-peso",
    subject: "matematica",
    axis: "Medida",
    label: "Peso y capacidad (kilo y litro)",
    description: "Compara pesos y capacidades usando el kilo y el litro en paquetes y botellas.",
    practice: "Observar envases de alimentos para encontrar etiquetas de 1 kg y 1 L.",
  },
  {
    id: "m2-tiempo-reloj",
    subject: "matematica",
    axis: "Medida",
    label: "El reloj y el calendario",
    description: "Lee la hora en punto y media en relojes analógicos y digitales; usa el calendario.",
    practice: "Mirar el reloj para marcar la hora de la merienda o de ir a dormir.",
  },

  // ---------- Ciencias Sociales ----------
  {
    id: "s2-paisajes",
    subject: "sociales",
    axis: "Las sociedades y los espacios",
    label: "Paisajes rurales y urbanos de Santa Cruz",
    description: "Describe y compara características del campo y de las ciudades santacruceñas.",
    practice: "Comparar postales o fotos del campo y de la ciudad identificando diferencias.",
  },
  {
    id: "s2-espacio-urbano",
    subject: "sociales",
    axis: "Las sociedades y los espacios",
    label: "Espacio urbano y servicios públicos",
    description: "Reconoce el uso del suelo urbano y la importancia de los servicios para la comunidad.",
    practice: "Identificar los servicios públicos que llegan al hogar (luz, gas, agua).",
  },
  {
    id: "s2-circuitos",
    subject: "sociales",
    axis: "Las sociedades y los espacios",
    label: "Circuitos productivos y manufactura",
    description: "Comprende la transformación de la materia prima en producto elaborado (lana, trigo, pesca).",
    practice: "Dibujar las etapas de la lana desde la oveja hasta el pulóver.",
  },
  {
    id: "s2-trabajos-tecnologia",
    subject: "sociales",
    axis: "Las actividades humanas y la organización social",
    label: "Trabajos, herramientas y tecnologías",
    description: "Identifica actores sociales, herramientas y tecnologías en la producción.",
    practice: "Conversar sobre las herramientas que usan los trabajadores de la comunidad.",
  },
  {
    id: "s2-transportes",
    subject: "sociales",
    axis: "Las sociedades a través del tiempo",
    label: "Transportes de ayer y de hoy",
    description: "Compara el transporte tradicional patagónico (carrero, carretas) con los modernos.",
    practice: "Construir una línea de tiempo con medios de transporte antiguos y actuales.",
  },
  {
    id: "s2-recursos-ambiente",
    subject: "sociales",
    axis: "Las sociedades y los espacios",
    label: "Recursos naturales y cuidado ambiental",
    description: "Reconoce recursos naturales (agua, suelo, pasturas) y la importancia de su preservación.",
    practice: "Elaborar un cartel sobre el cuidado del agua en la Patagonia.",
  },
  {
    id: "s2-familias-diversidad",
    subject: "sociales",
    axis: "Las actividades humanas y la organización social",
    label: "Diversidad familiar y vida cotidiana",
    description: "Reconoce que existen diversas formas de familias con diferentes costumbres y roles.",
    practice: "Dibujar a los integrantes de la familia realizando actividades compartidas.",
  },
  {
    id: "s2-pueblos-originarios",
    subject: "sociales",
    axis: "Las sociedades a través del tiempo",
    label: "Pueblos originarios de la Patagonia",
    description: "Conoce los modos de vida, viviendas y costumbres de Aonikenk y Selk'nam.",
    practice: "Investigar sobre los quillangos de guanaco y las pinturas tehuelches.",
  },
  {
    id: "s2-tecnologia-tiempo",
    subject: "sociales",
    axis: "Las sociedades a través del tiempo",
    label: "Tecnología en la vida cotidiana",
    description: "Analiza cambios en la iluminación, la cocción de alimentos y el abrigo en el tiempo.",
    practice: "Preguntar a abuelos o adultos mayores cómo se iluminaban o calentaban antes.",
  },
  {
    id: "s2-patrimonio-huellas",
    subject: "sociales",
    axis: "Las sociedades a través del tiempo",
    label: "Huellas del pasado y patrimonio",
    description: "Valora sitios y monumentos patrimoniales de Santa Cruz (Cueva de las Manos, estancias).",
    practice: "Buscar información o fotos de Cueva de las Manos en Santa Cruz.",
  },
  {
    id: "s2-instituciones-normas",
    subject: "sociales",
    axis: "Las actividades humanas y la organización social",
    label: "Instituciones y convivencia",
    description: "Reconoce la función de instituciones comunitarias y el valor del diálogo para acordar normas.",
    practice: "Debatir en familia cómo resolver un desacuerdo escuchando a todos.",
  },
  {
    id: "s2-efemerides",
    subject: "sociales",
    axis: "Las sociedades a través del tiempo",
    label: "Efemérides y fechas históricas",
    description: "Comprende el significado de conmemoraciones patrias y celebraciones comunitarias.",
    practice: "Recordar juntos por qué celebramos el 25 de Mayo o el 9 de Julio.",
  },

  // ---------- Ciencias Naturales ----------
  {
    id: "n2-seres-vivos-ambientes",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Seres vivos del bosque y la estepa",
    description: "Caracteriza plantas y animales de los ambientes cercanos de Santa Cruz.",
    practice: "Nombrar tres animales del bosque andino y tres de la estepa patagónica.",
  },
  {
    id: "n2-animales-adaptaciones",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Adaptaciones de los animales patagónicos",
    description: "Relaciona el comportamiento y estructuras de animales con el frío y el viento.",
    practice: "Observar cómo el pelaje del zorro o del huemul los abriga en invierno.",
  },
  {
    id: "n2-plantas-bosque",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Plantas del bosque andino patagónico",
    description: "Identifica árboles y arbustos nativos (lenga, ñire, calafate) y sus cambios.",
    practice: "Recolectar hojas caídas de diferentes árboles y comparar sus formas.",
  },
  {
    id: "n2-necesidades-factores",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Factores físicos y necesidades vitales",
    description: "Reconoce la relación entre agua, luz solar, suelo y aire con la vida vegetal y animal.",
    practice: "Cuidar una plantita asegurando que reciba luz y agua en cantidades adecuadas.",
  },
  {
    id: "n2-cambios-estacionales",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Los seres vivos y las estaciones",
    description: "Vincula comportamientos (migración, letargo, caída de hojas) con los cambios estacionales.",
    practice: "Registrar qué pájaros o plantas se ven en cada época del año.",
  },
  {
    id: "n2-cuerpo-crecimiento",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Crecimiento y desarrollo corporal",
    description: "Reconoce cambios en el propio cuerpo desde el nacimiento y la dentición.",
    practice: "Ver fotos de bebé y notar cuánto creció la altura, pies y manos.",
  },
  {
    id: "n2-salud-prevencion",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Salud, prevención y vacunas",
    description: "Aprende acciones básicas de prevención: vacunas, higiene y alimentación variada.",
    practice: "Repasar los pasos de un correcto lavado de manos antes de comer.",
  },
  {
    id: "n2-cuerpo-movimiento",
    subject: "naturales",
    axis: "Los seres vivos: diversidad, unidad e interrelaciones",
    label: "Huesos, músculos y articulaciones",
    description: "Reconoce cómo huesos, músculos y articulaciones trabajan coordinados en el movimiento y sostén del cuerpo.",
    practice: "Sentir el codo, rodilla y tobillo al flexionarse y tocar el bíceps al hacer fuerza.",
  },
  {
    id: "n2-fuerzas-movimiento",
    subject: "naturales",
    axis: "Los fenómenos del mundo físico",
    label: "Fuerzas, empujes y máquinas simples",
    description: "Experimenta con fuerzas de empuje, tracción, rozamiento y máquinas simples como palancas y planos inclinados.",
    practice: "Hacer rodar un autito sobre piso liso y alfombra, y usar una rampa para deslizar objetos.",
  },
  {
    id: "n2-materiales-propiedades",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Propiedades y origen de los materiales",
    description: "Clasifica materiales por su origen (natural o artificial) y propiedades como dureza, flexibilidad y flotación.",
    practice: "Explorar en un tazón con agua qué objetos flotan (madera, corcho) y cuáles se hunden (piedra, metal).",
  },
  {
    id: "n2-luz-sonido",
    subject: "naturales",
    axis: "Los fenómenos del mundo físico",
    label: "Luces, sombras y vibración sonora",
    description: "Explora la formación de sombras con objetos opacos y transparentes, y la producción del sonido por vibración.",
    practice: "Hacer sombras en la pared con linterna y hacer vibrar una bandita elástica sobre una cajita.",
  },
  {
    id: "n2-materiales-luz",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Materiales y la luz",
    description: "Clasifica materiales en transparentes, translúcidos y opacos según su comportamiento con la luz.",
    practice: "Probar con una linterna qué objetos dejan pasar la luz y cuáles no.",
  },
  {
    id: "n2-materiales-mezclas",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Mezclas de materiales",
    description: "Identifica mezclas en la naturaleza y en la cocina (sólido-sólido, sólido-líquido).",
    practice: "Preparar agua con azúcar o una ensalada y observar qué componentes se ven.",
  },
  {
    id: "n2-movimiento-fuerzas",
    subject: "naturales",
    axis: "Los fenómenos del mundo físico",
    label: "Movimiento, trayectorias y fuerzas",
    description: "Clasifica movimientos según su trayectoria (recta, curva) y fuerzas (empujar, tirar).",
    practice: "Hacer rodar una pelotita por diferentes pistas rectas y con curvas.",
  },
  {
    id: "n2-luz-calor",
    subject: "naturales",
    axis: "Los fenómenos del mundo físico",
    label: "Fuentes de luz y efectos del calor",
    description: "Distingue fuentes lumínicas naturales y artificiales; observa cambios por calor (derretir).",
    practice: "Observar qué ocurre con un cubito de hielo al recibir calor.",
  },
  {
    id: "n2-geoformas",
    subject: "naturales",
    axis: "La Tierra, el universo y sus cambios",
    label: "Geoformas de Santa Cruz",
    description: "Reconoce montañas, mesetas, costas, llanuras y glaciares en el paisaje santacruceño.",
    practice: "Modelar con plastilina una montaña, una meseta plana y un valle.",
  },
  {
    id: "n2-cielo-ciclos",
    subject: "naturales",
    axis: "La Tierra, el universo y sus cambios",
    label: "El cielo y sus ciclos (día, noche, Luna)",
    description: "Observa y describe los cuerpos celestes diurnos y nocturnos y las fases lunares.",
    practice: "Mirar la Luna durante varias noches y dibujar cómo cambia su forma.",
  },
  {
    id: "n2-fenomenos-tiempo",
    subject: "naturales",
    axis: "La Tierra, el universo y sus cambios",
    label: "Fenómenos meteorológicos patagónicos",
    description: "Identifica lluvia, nieve, escarcha, viento y tipos de nubes en el clima local.",
    practice: "Registrar el estado del tiempo patagónico durante una semana completa.",
  },
  // ---------- Dictado (Lengua y Matemática) ----------
  {
    id: "l2-dictado-palabra",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Dictado de palabras",
    description: "Escribe palabras al dictado respetando la correspondencia fonema-grafema y reglas ortográficas.",
    practice: "Dictados breves de palabras cotidianas y del entorno patagónico.",
  },
  {
    id: "l2-dictado-oracion",
    subject: "lengua",
    axis: "Sistema de escritura",
    label: "Dictado de oraciones",
    description: "Escribe oraciones al dictado usando mayúscula inicial y punto final.",
    practice: "Escritura de oraciones breves al dictado con revisión guiada.",
  },
  {
    id: "m2-num-dictado",
    subject: "matematica",
    axis: "Número y operaciones",
    label: "Dictado de números",
    description: "Escribe en cifras números dictados en palabras identificando su valor posicional.",
    practice: "Dictado de números en la grilla y con billetes.",
  },
];

export function getGrade2Skill(id: string): SkillDef | undefined {
  return GRADE2_SKILLS.find((s) => s.id === id);
}
