// Catálogo de mundos de 2.º grado según el Diseño Curricular de Santa Cruz.
// Ids: 2 + materia + número
//   - Lengua: 21001 a 21038 (38 mundos)
//   - Matemática: 22001 a 22028 (28 mundos)
//   - Ciencias Sociales: 23001 a 23018 (18 mundos)
//   - Ciencias Naturales: 24001 a 24016 (16 mundos)
// Total: 100 mundos.

import { WorldDef, WorldDifficultyVars, WorldSubject } from "@/types";
import { withStories } from "@/lib/cuentos/recorrido";

const SUBJECT_BASE: Record<WorldSubject, number> = {
  lengua: 21000,
  matematica: 22000,
  sociales: 23000,
  naturales: 24000,
};

const PALETTES: Record<WorldSubject, [string, string][]> = {
  lengua: [["#fde68a", "#f59e0b"], ["#fbcfe8", "#ec4899"], ["#ddd6fe", "#8b5cf6"], ["#fed7aa", "#f97316"]],
  matematica: [["#bfdbfe", "#3b82f6"], ["#bbf7d0", "#22c55e"], ["#fecaca", "#ef4444"], ["#c7d2fe", "#6366f1"]],
  sociales: [["#bae6fd", "#0284c7"], ["#fde68a", "#ca8a04"], ["#fecdd3", "#e11d48"], ["#d9f99d", "#65a30d"]],
  naturales: [["#bbf7d0", "#16a34a"], ["#a5f3fc", "#0891b2"], ["#fef08a", "#eab308"], ["#e9d5ff", "#9333ea"]],
};

interface Spec {
  n: number;
  name: string;
  emoji: string;
  description: string;
  objective: string;
  contents: string[];
  skills: string[];
  after?: number[];
  vars?: WorldDifficultyVars;
  kind?: WorldDef["kind"];
  activityCount?: number;
}

function build(subject: WorldSubject, specs: Spec[]): WorldDef[] {
  return specs.map((s) => {
    const pal = PALETTES[subject][(s.n - 1) % PALETTES[subject].length];
    return {
      id: SUBJECT_BASE[subject] + s.n,
      grade: 2,
      worldNumber: s.n,
      name: s.name,
      emoji: s.emoji,
      subject,
      category: "oralidad-inicial", // En 2.º se despacha por grado a grade2/content
      description: s.description,
      objective: s.objective,
      contents: s.contents,
      skills: s.skills,
      prerequisites: (s.after ?? (s.n > 1 ? [s.n - 1] : [])).map((x) => SUBJECT_BASE[subject] + x),
      difficultyVars: s.vars,
      kind: s.kind ?? "normal",
      activityCount: s.activityCount ?? 8,
      colorFrom: pal[0],
      colorTo: pal[1],
      difficulty: "basico",
      assessment:
        "Logrado con 85% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
    };
  });
}

// ------------------------------------------------------------------
// LENGUA (21001 - 21038)
// ------------------------------------------------------------------
// Cada dos mundos va uno de lectura de cuento (posiciones 3, 6, 9…): ver src/lib/cuentos/recorrido.ts.
export const GRADE2_LENGUA: WorldDef[] = withStories(2, build("lengua", [
  {
    n: 1,
    name: "El Gran Desafío de Leer",
    emoji: "📖",
    description: "Palabras y oraciones para leer con ritmo y fluidez.",
    objective: "Consolidar la lectura fluida de palabras decodificables con todas las letras trabajadas.",
    contents: ["Lectura asidua de palabras y oraciones", "Comprensión lectora autónoma"],
    skills: ["l2-fluidez"],
    after: [],
  },
  {
    n: 2,
    name: "El Dragón y la Piedra",
    emoji: "🐉",
    description: "dra, dre, dri, dro, dru: dragón, madre, cocodrilo.",
    objective: "Reconocer y leer palabras con el grupo consonántico DR.",
    contents: ["Correspondencia fonema-grafema en sílabas trabadas con r", "Lectura de palabras complejas"],
    skills: ["l2-trabadas", "l2-fluidez"],
    after: [1],
  },
  {
    n: 3,
    name: "El Tren de la Pradera",
    emoji: "🚂",
    description: "tra, tre, tri, tro, tru: tren, estrella, cuatro.",
    objective: "Reconocer y leer palabras con el grupo consonántico TR.",
    contents: ["Correspondencia fonema-grafema en sílabas trabadas con r", "Lectura de palabras con tr"],
    skills: ["l2-trabadas", "l2-fluidez"],
    after: [2],
  },
  {
    n: 4,
    name: "El Castillo de Cristal",
    emoji: "🔮",
    description: "cra, cre, cri, cro, cru: cristal, recreo, cruz.",
    objective: "Reconocer y leer palabras con el grupo consonántico CR.",
    contents: ["Grupos consonánticos con r", "Lectura y escritura de palabras"],
    skills: ["l2-trabadas"],
    after: [3],
  },
  {
    n: 5,
    name: "El Clavel del Claro",
    emoji: "🌸",
    description: "cla, cle, cli, clo, clu: clavel, bicicleta, ancla.",
    objective: "Reconocer y leer palabras con el grupo consonántico CL.",
    contents: ["Grupos consonánticos con l", "Lectura y escritura de palabras con cl"],
    skills: ["l2-trabadas"],
    after: [4],
  },
  {
    n: 6,
    name: "El Fruto del Fresno",
    emoji: "🍓",
    description: "fra, fre, fri, fro, fru: fruta, cofre, frutilla.",
    objective: "Reconocer y leer palabras con el grupo consonántico FR.",
    contents: ["Grupos consonánticos con r", "Lectura de palabras con fr"],
    skills: ["l2-trabadas"],
    after: [5],
  },
  {
    n: 7,
    name: "La Flecha y la Flor",
    emoji: "🏹",
    description: "fla, fle, fli, flo, flu: flor, flecha, flauta.",
    objective: "Reconocer y leer palabras con el grupo consonántico FL.",
    contents: ["Grupos consonánticos con l", "Lectura de palabras con fl"],
    skills: ["l2-trabadas"],
    after: [6],
  },
  {
    n: 8,
    name: "El Grillo en la Gruta",
    emoji: "🦗",
    description: "gra, gre, gri, gro, gru: grillo, tigre, ogro.",
    objective: "Reconocer y leer palabras con el grupo consonántico GR.",
    contents: ["Grupos consonánticos con r", "Lectura de palabras con gr"],
    skills: ["l2-trabadas"],
    after: [7],
  },
  {
    n: 9,
    name: "El Globo en el Glaciar",
    emoji: "🎈",
    description: "gla, gle, gli, glo, glu: globo, regla, glaciar.",
    objective: "Reconocer y leer palabras con el grupo consonántico GL.",
    contents: ["Grupos consonánticos con l", "Lectura de palabras con gl"],
    skills: ["l2-trabadas"],
    after: [8],
  },
  {
    n: 10,
    name: "La Bruja y el Broche",
    emoji: "🧙‍♀️",
    description: "bra, bre, bri, bro, bru: bruja, libro, brazo.",
    objective: "Reconocer y leer palabras con el grupo consonántico BR.",
    contents: ["Grupos consonánticos con r", "Lectura de palabras con br"],
    skills: ["l2-trabadas"],
    after: [9],
  },
  {
    n: 11,
    name: "El Blanco de la Nieve",
    emoji: "⚪",
    description: "bla, ble, bli, blo, blu: blanco, tabla, cable.",
    objective: "Reconocer y leer palabras con el grupo consonántico BL.",
    contents: ["Grupos consonánticos con l", "Lectura de palabras con bl"],
    skills: ["l2-trabadas"],
    after: [10],
  },
  {
    n: 12,
    name: "La Pluma y el Plato",
    emoji: "🪶",
    description: "pla, ple, pli, plo, plu: pluma, plato, playa.",
    objective: "Reconocer y leer palabras con el grupo consonántico PL.",
    contents: ["Grupos consonánticos con l", "Lectura de palabras con pl"],
    skills: ["l2-trabadas"],
    after: [11],
  },
  {
    n: 13,
    name: "El Premio del Prado",
    emoji: "🏆",
    description: "pra, pre, pri, pro, pru: premio, primo, primero.",
    objective: "Reconocer y leer palabras con el grupo consonántico PR.",
    contents: ["Grupos consonánticos con r", "Lectura de palabras con pr"],
    skills: ["l2-trabadas"],
    after: [12],
  },
  {
    n: 14,
    name: "¡Fiesta de Trabadas!",
    emoji: "🎉",
    description: "¡Desafío con todas las sílabas trabadas juntas!",
    objective: "Integrar la lectura y escritura de grupos consonánticos con L y R.",
    contents: ["Integración de sílabas trabadas", "Lectura fluida de textos breves"],
    skills: ["l2-trabadas", "l2-fluidez"],
    after: [13],
    kind: "integracion",
  },
  {
    n: 15,
    name: "La Casa del Queso",
    emoji: "🧀",
    description: "ca, co, cu y que, qui: casa, cuna, queso, paquete.",
    objective: "Distinguir las grafías C y QU para el fonema /k/.",
    contents: ["Convenciones ortográficas: ca, co, cu y que, qui"],
    skills: ["l2-ortografia-c-q"],
    after: [14],
  },
  {
    n: 16,
    name: "El Cine y la Cebolla",
    emoji: "🎬",
    description: "ce, ci: sonido suave como en cielo, cine y ciruela.",
    objective: "Reconocer el sonido suave de la C delante de E e I.",
    contents: ["Convenciones ortográficas: ce, ci"],
    skills: ["l2-ortografia-c-q"],
    after: [15],
  },
  {
    n: 17,
    name: "El Gato y el Guiso",
    emoji: "🐱",
    description: "ga, go, gu y gue, gui: gato, manguera, guitarra.",
    objective: "Diferenciar el sonido suave de la G con U muda (gue, gui).",
    contents: ["Convenciones ortográficas: ga, go, gu y gue, gui"],
    skills: ["l2-ortografia-g"],
    after: [16],
  },
  {
    n: 18,
    name: "Los Gigantes del Bosque",
    emoji: "🗿",
    description: "ge, gi: sonido fuerte como en gigante y girasol.",
    objective: "Reconocer el fonema /x/ representado por G delante de E e I.",
    contents: ["Convenciones ortográficas: ge, gi"],
    skills: ["l2-ortografia-g"],
    after: [17],
  },
  {
    n: 19,
    name: "El Pingüino Cigüeña",
    emoji: "🐧",
    description: "güe, güi: ¡dos puntitos sobre la u para que suene!",
    objective: "Comprender el uso de la diéresis en güe y güi.",
    contents: ["Convención ortográfica: diéresis (güe, güi)"],
    skills: ["l2-ortografia-g"],
    after: [18],
  },
  {
    n: 20,
    name: "El Ratón y el Carro",
    emoji: "🐭",
    description: "R suave y RR fuerte: pera, loro, perro, carro.",
    objective: "Distinguir el valor fonológico de R suave y RR fuerte intervocálica.",
    contents: ["Oposición fonológica r / rr", "Norma ortográfica"],
    skills: ["l2-ortografia-r"],
    after: [19],
  },
  {
    n: 21,
    name: "El Tambor y la Trompeta",
    emoji: "🥁",
    description: "Antes de B y P siempre va M: tambor, campana.",
    objective: "Aplicar la regla ortográfica de MB y MP.",
    contents: ["Reglas ortográficas sin excepción: mb y mp"],
    skills: ["l2-ortografia-mb-mp"],
    after: [20],
  },
  {
    n: 22,
    name: "El Hada del Huerto",
    emoji: "🧚",
    description: "La letra H no suena, pero se escribe: hoja, helado.",
    objective: "Reconocer palabras de uso frecuente con H muda.",
    contents: ["Uso de la h en palabras frecuentes"],
    skills: ["l2-ortografia-h-ch"],
    after: [21],
  },
  {
    n: 23,
    name: "El Chocolate del Chajá",
    emoji: "🍫",
    description: "cha, che, chi, cho, chu: chocolate, leche, noche.",
    objective: "Leer y escribir palabras con el dígrafo CH.",
    contents: ["Dígrafo ch: lectura y escritura"],
    skills: ["l2-ortografia-h-ch"],
    after: [22],
  },
  {
    n: 24,
    name: "Mayúscula al Empezar",
    emoji: "🔠",
    description: "Al iniciar una oración o en un nombre, va mayúscula.",
    objective: "Identificar y aplicar el uso de mayúscula inicial y en nombres propios.",
    contents: ["Signos de puntuación y mayúsculas: inicio de oración y nombres propios"],
    skills: ["l2-puntuacion", "l2-sustantivos"],
    after: [23],
  },
  {
    n: 25,
    name: "El Punto Final y el Punto Seguido",
    emoji: "🔴",
    description: "Un punto para terminar cada idea y seguir.",
    objective: "Comprender la función del punto seguido y el punto final.",
    contents: ["La oración: unidad gráfica y de sentido", "Punto seguido y final"],
    skills: ["l2-puntuacion", "l2-escritura-oraciones"],
    after: [24],
  },
  {
    n: 26,
    name: "Nombres de Todas las Cosas",
    emoji: "📦",
    description: "Mesa, gato, río, árbol: son sustantivos comunes.",
    objective: "Reconocer sustantivos comunes en textos y oraciones.",
    contents: ["Clases de palabras: sustantivos comunes"],
    skills: ["l2-sustantivos"],
    after: [25],
  },
  {
    n: 27,
    name: "Nombres Propios de Amigos",
    emoji: "🏷️",
    description: "Pedro, Sofía, Santa Cruz: ¡se escriben con mayúscula!",
    objective: "Reconocer sustantivos propios y su ortografía.",
    contents: ["Clases de palabras: sustantivos propios y mayúscula"],
    skills: ["l2-sustantivos", "l2-puntuacion"],
    after: [26],
  },
  {
    n: 28,
    name: "Uno o Muchos",
    emoji: "🔢",
    description: "Singular (uno) y plural (muchos): gato → gatos.",
    objective: "Identificar y formar el número singular y plural en sustantivos.",
    contents: ["Morfología: número (singular y plural)"],
    skills: ["l2-genero-numero"],
    after: [27],
  },
  {
    n: 29,
    name: "El y La, Los y Las",
    emoji: "👫",
    description: "Femenino y masculino: la casa, el bosque.",
    objective: "Reconocer el género masculino y femenino en artículos y sustantivos.",
    contents: ["Morfología: género (masculino y femenino)"],
    skills: ["l2-genero-numero"],
    after: [28],
  },
  {
    n: 30,
    name: "¿Cómo Es?",
    emoji: "✨",
    description: "Palabras que dicen cómo es algo: grande, dorado, suave.",
    objective: "Identificar adjetivos calificativos y concordancia con el sustantivo.",
    contents: ["Clases de palabras: adjetivos calificativos", "Concordancia"],
    skills: ["l2-adjetivos"],
    after: [29],
  },
  {
    n: 31,
    name: "El Árbol de las Palabras",
    emoji: "🌳",
    description: "Pan, panadero, panadería: familias que comparten raíz.",
    objective: "Reconocer familias de palabras y relaciones semánticas.",
    contents: ["Formación de palabras: raíz común y familias de palabras"],
    skills: ["l2-familias-palabras"],
    after: [30],
  },
  {
    n: 32,
    name: "Gigantes y Pequeñitos",
    emoji: "🔍",
    description: "Aumentativos (-ón, -ote) y diminutivos (-ito, -ita).",
    objective: "Construir aumentativos y diminutivos a partir de palabras base.",
    contents: ["Sufijación: aumentativos y diminutivos"],
    skills: ["l2-familias-palabras"],
    after: [31],
  },
  {
    n: 33,
    name: "El Desfile del Abecedario",
    emoji: "🔤",
    description: "¿Quién va primero? Ordená palabras de la A a la Z.",
    objective: "Utilizar el abecedario para ordenar listas y buscar en diccionarios.",
    contents: ["Uso del abecedario para ordenar palabras"],
    skills: ["l2-abecedario"],
    after: [32],
  },
  {
    n: 34,
    name: "El Tesoro del Cuento",
    emoji: "📚",
    description: "¿Qué pasó al inicio, en el problema y en el final?",
    objective: "Comprender la estructura canónica de los cuentos tradicionales.",
    contents: ["Estructura narrativa: inicio, complicación y desenlace"],
    skills: ["l2-comprension-cuento"],
    after: [33],
  },
  {
    n: 35,
    name: "La Fábula de la Zorra",
    emoji: "🦊",
    description: "Historias con animales que nos dejan una enseñanza.",
    objective: "Leer e interpretar fábulas identificando la moraleja.",
    contents: ["Lectura de fábulas: personajes y enseñanza"],
    skills: ["l2-comprension-cuento"],
    after: [34],
  },
  {
    n: 36,
    name: "Trabalenguas y Adivinanzas",
    emoji: "🎭",
    description: "Versos que enredan la lengua y enigmas para resolver.",
    objective: "Disfrutar y reconocer recursos sonoros en trabalenguas y rimas.",
    contents: ["Poesía y juegos del lenguaje: trabalenguas y adivinanzas"],
    skills: ["l2-poesia-rimas"],
    after: [35],
  },
  {
    n: 37,
    name: "El Recetario del Bosque",
    emoji: "🧁",
    description: "Ingredientes y pasos ordenados para cocinar algo rico.",
    objective: "Interpretar y ordenar instrucciones en recetas y consignas.",
    contents: ["Textos instructivos: ingredientes y orden de pasos"],
    skills: ["l2-textos-instructivos"],
    after: [36],
  },
  {
    n: 38,
    name: "Cartas y Mensajes del Refugio",
    emoji: "✉️",
    description: "Para quién es, qué le decimos y la firma.",
    objective: "Comprender el propósito y estructura de notas, cartas e historietas.",
    contents: ["Textos epistolares breves e historietas", "Destinatario y mensaje"],
    skills: ["l2-textos-sociales", "l2-escritura-oraciones"],
    after: [37],
    kind: "integracion",
  },
]));

// ------------------------------------------------------------------
// MATEMÁTICA (22001 - 22028)
// ------------------------------------------------------------------
export const GRADE2_MATEMATICA: WorldDef[] = build("matematica", [
  {
    n: 1,
    name: "El Cuadro del 1 al 100",
    emoji: "🔢",
    description: "Filas de dieces y columnas de unos: ¡buscá los números!",
    objective: "Reconocer regularidades en la serie numérica del 1 al 100 en cuadros numéricos.",
    contents: ["Exploración de regularidades en el cuadro numérico hasta 100"],
    skills: ["m2-numeros-100"],
    after: [],
  },
  {
    n: 2,
    name: "Vecinos en el Cuadro",
    emoji: "🧭",
    description: "+1, -1, +10 y -10: ¿quién vive al lado, arriba y abajo?",
    objective: "Relacionar los movimientos en el cuadro con sumar y restar 1 y 10.",
    contents: ["Análisis de relaciones numéricas: cómo cambia al sumar o restar 1 y 10"],
    skills: ["m2-numeros-100", "m2-calculo-mental"],
    after: [1],
  },
  {
    n: 3,
    name: "¡Llegan los Cienes!",
    emoji: "💯",
    description: "100, 200, 300… ¡hasta 900!",
    objective: "Leer y escribir números redondos de tres cifras (los cienes).",
    contents: ["Uso de información sobre números redondos (100, 200, 300...)"],
    skills: ["m2-numeros-1000"],
    after: [2],
  },
  {
    n: 4,
    name: "Explorando hasta 500",
    emoji: "🌲",
    description: "Lectura, escritura y orden de números de tres cifras hasta 500.",
    objective: "Leer, escribir y comparar números hasta 500.",
    contents: ["Lectura, escritura y orden de números hasta 500"],
    skills: ["m2-numeros-1000", "m2-comparar-ordenar"],
    after: [3],
  },
  {
    n: 5,
    name: "Rumbo al 1000",
    emoji: "🏔️",
    description: "¡Números de tres cifras que se acercan al mil!",
    objective: "Ampliar el campo numérico hasta 1000 reconociendo regularidades.",
    contents: ["Lectura, escritura y orden de números hasta 1000"],
    skills: ["m2-numeros-1000", "m2-comparar-ordenar"],
    after: [4],
  },
  {
    n: 6,
    name: "Cienes, Dieces y Unos",
    emoji: "🧱",
    description: "348 = 300 + 40 + 8. ¿Cuánto vale cada cifra?",
    objective: "Analizar el valor posicional de las cifras en términos de cienes, dieces y unos.",
    contents: ["Valor de la cifra según la posición que ocupa: unos, dieces y cienes"],
    skills: ["m2-valor-posicional"],
    after: [5],
  },
  {
    n: 7,
    name: "El Banco del Bosque",
    emoji: "💵",
    description: "Pagá con billetes de $100, de $10 y monedas de $1.",
    objective: "Resolver composiciones aditivas en el contexto del dinero.",
    contents: ["Escrituras aditivas en el contexto del dinero: billetes de $100, $10 y monedas"],
    skills: ["m2-dinero", "m2-valor-posicional"],
    after: [6],
  },
  {
    n: 8,
    name: "La Recta Numérica",
    emoji: "📏",
    description: "Ubicá números en la recta: ¿cuál es mayor y cuál es menor?",
    objective: "Comparar y ordenar números en escalas de 10 en 10 y de 50 en 50.",
    contents: ["Orden y comparación en la recta numérica"],
    skills: ["m2-comparar-ordenar"],
    after: [7],
  },
  {
    n: 9,
    name: "Dobles y Mitades",
    emoji: "♊",
    description: "El doble de 20 es 40; la mitad de 100 es 50.",
    objective: "Construir un repertorio mental de dobles y mitades de números redondos.",
    contents: ["Estrategias de cálculo mental: dobles y mitades"],
    skills: ["m2-calculo-mental"],
    after: [8],
  },
  {
    n: 10,
    name: "Amigos del 100",
    emoji: "🤝",
    description: "30 + 70 = 100, 60 + 40 = 100. ¡Cálculos que completan 100!",
    objective: "Automatizar complementos a 100 para agilizar el cálculo mental.",
    contents: ["Cálculo mental: complementos a 100"],
    skills: ["m2-calculo-mental"],
    after: [9],
  },
  {
    n: 11,
    name: "Sumas Rápidas con Redondos",
    emoji: "⚡",
    description: "300 + 200 = 500, 450 + 50 = 500.",
    objective: "Utilizar sumas de números redondos para resolver otros cálculos.",
    contents: ["Cálculo mental: sumas de cienes y dieces redondos"],
    skills: ["m2-calculo-mental"],
    after: [10],
  },
  {
    n: 12,
    name: "Sumas en el Cuaderno",
    emoji: "📝",
    description: "Desarmá los números para sumar: 143 + 235.",
    objective: "Sumar números de dos y tres cifras sin dificultad por descomposición.",
    contents: ["Procedimientos de suma sin dificultad por descomposición"],
    skills: ["m2-suma-algoritmos"],
    after: [11],
  },
  {
    n: 13,
    name: "Sumas que Llevan Dieces",
    emoji: "🎒",
    description: "Cuando los unos suman 10 o más, ¡se pasa un diez!",
    objective: "Comprender la reagrupación en la suma con dificultad.",
    contents: ["Algoritmos de la suma con reagrupación"],
    skills: ["m2-suma-algoritmos"],
    after: [12],
  },
  {
    n: 14,
    name: "Restas Desarmando Números",
    emoji: "✂️",
    description: "Restas sin dificultad: 268 − 135.",
    objective: "Resolver restas sin dificultad mediante descomposición aditiva.",
    contents: ["Procedimientos de resta sin dificultad"],
    skills: ["m2-resta-algoritmos"],
    after: [13],
  },
  {
    n: 15,
    name: "Restas que Piden Ayuda",
    emoji: "🆘",
    description: "Si no alcanzan los unos, desarmamos un diez.",
    objective: "Comprender la descomposición de dieces en restas con dificultad.",
    contents: ["Algoritmos de la resta con dificultad"],
    skills: ["m2-resta-algoritmos"],
    after: [14],
  },
  {
    n: 16,
    name: "Problemas de Sumar y Restar",
    emoji: "🧩",
    description: "Juntar, agregar, quitar, comparar y calcular cuánto falta.",
    objective: "Identificar la operación adecuada para resolver problemas aditivos.",
    contents: ["Sentidos de la suma y la resta: unir, agregar, quitar, comparar"],
    skills: ["m2-problemas-aditivos"],
    after: [15],
    kind: "integracion",
  },
  {
    n: 17,
    name: "Pasos que se Repiten",
    emoji: "🐾",
    description: "Sumas de números iguales: 3 + 3 + 3 + 3 = 12.",
    objective: "Reconocer la multiplicación como suma abreviada de sumandos iguales.",
    contents: ["Problemas de series que se repiten y sumas sucesivas"],
    skills: ["m2-multiplicacion-inicio"],
    after: [16],
  },
  {
    n: 18,
    name: "Filas y Columnas",
    emoji: "🧇",
    description: "Baldosas, ventanas y chocolates organizados en filas y columnas.",
    objective: "Calcular cantidades en organizaciones rectangulares usando multiplicación.",
    contents: ["Organizaciones rectangulares: filas y columnas"],
    skills: ["m2-multiplicacion-inicio"],
    after: [17],
  },
  {
    n: 19,
    name: "La Tabla del 2",
    emoji: "✌️",
    description: "2, 4, 6, 8, 10… ¡los dobles de cada número!",
    objective: "Construir y memorizar la tabla de multiplicar del 2.",
    contents: ["Tablas de multiplicar: tabla del 2"],
    skills: ["m2-tablas"],
    after: [18],
  },
  {
    n: 20,
    name: "La Tabla del 5",
    emoji: "🖐️",
    description: "5, 10, 15, 20… ¡como los dedos de la mano!",
    objective: "Construir y memorizar la tabla de multiplicar del 5.",
    contents: ["Tablas de multiplicar: tabla del 5"],
    skills: ["m2-tablas"],
    after: [19],
  },
  {
    n: 21,
    name: "La Tabla del 10",
    emoji: "🔟",
    description: "10, 20, 30… ¡multiplicar por 10 es agregar un cero!",
    objective: "Reconocer la regularidad de multiplicar por 10 en el sistema decimal.",
    contents: ["Multiplicación por 10 y regularidades numéricas"],
    skills: ["m2-tablas"],
    after: [20],
  },
  {
    n: 22,
    name: "Reparto en Partes Iguales",
    emoji: "🥧",
    description: "Repartir caramelos entre amigos sin que sobre ninguno.",
    objective: "Resolver situaciones de reparto equitativo mediante dibujos y sumas.",
    contents: ["Problemas de reparto y partición equitativa"],
    skills: ["m2-reparto"],
    after: [21],
  },
  {
    n: 23,
    name: "Lados y Vértices",
    emoji: "🔺",
    description: "Triángulos (3 lados), cuadrados y rectángulos (4 lados), círculos (curvos).",
    objective: "Caracterizar figuras planas por sus bordes, número de lados y vértices.",
    contents: ["Figuras geométricas: lados rectos y curvos, vértices"],
    skills: ["m2-geometria-2d"],
    after: [22],
  },
  {
    n: 24,
    name: "Cuerpos con Caras",
    emoji: "🧊",
    description: "Cubos, prismas, pirámides y cilindros: caras, aristas y vértices.",
    objective: "Identificar y describir cuerpos geométricos según sus caras y vértices.",
    contents: ["Cuerpos geométricos: cubos, prismas, pirámides, cilindros"],
    skills: ["m2-geometria-3d"],
    after: [23],
  },
  {
    n: 25,
    name: "El Plano del Refugio",
    emoji: "🗺️",
    description: "¿Dónde está la cama? ¿Por dónde salimos? Planos y recorridos.",
    objective: "Interpretar planos de espacios conocidos e itinerarios con referencias.",
    contents: ["Planos sencillos de espacios conocidos y puntos de vista"],
    skills: ["m2-espacio-planos"],
    after: [24],
  },
  {
    n: 26,
    name: "Metros y Centímetros",
    emoji: "📏",
    description: "1 metro son 100 centímetros. Medí con regla y cinta.",
    objective: "Utilizar la regla y cinta métrica; equivalencia básica entre m y cm.",
    contents: ["Medición de longitudes: unidades convencionales (metro y centímetro)"],
    skills: ["m2-medidas-longitud"],
    after: [25],
  },
  {
    n: 27,
    name: "Kilos y Litros",
    emoji: "⚖️",
    description: "¿Cuánto pesa la mochila? ¿Cuánto jugo entra en la jarra?",
    objective: "Reconocer el kilo y el litro como unidades de peso y capacidad de uso social.",
    contents: ["Medición de peso y capacidad: kilo y litro"],
    skills: ["m2-medidas-capacidad-peso"],
    after: [26],
  },
  {
    n: 28,
    name: "La Hora y el Calendario",
    emoji: "⏰",
    description: "En punto e y media en el reloj; meses y semanas en el calendario.",
    objective: "Leer la hora en relojes analógicos y digitales y orientarse en el calendario.",
    contents: ["Lectura de la hora (en punto y media)", "Uso del calendario"],
    skills: ["m2-tiempo-reloj"],
    after: [27],
    kind: "integracion",
  },
]);

// ------------------------------------------------------------------
// CIENCIAS SOCIALES (23001 - 23018)
// ------------------------------------------------------------------
export const GRADE2_SOCIALES: WorldDef[] = build("sociales", [
  {
    n: 1,
    name: "Paisajes de Santa Cruz",
    emoji: "🏞️",
    description: "La costa, la meseta, el bosque y las ciudades de nuestra provincia.",
    objective: "Describir y contrastar paisajes rurales y urbanos de Santa Cruz.",
    contents: ["Observación y descripción de diversos paisajes rurales y urbanos de la provincia"],
    skills: ["s2-paisajes"],
    after: [],
  },
  {
    n: 2,
    name: "Vivir en la Ciudad",
    emoji: "🏙️",
    description: "Calles, comercios, plazas, tránsito y edificios en Río Gallegos y Calafate.",
    objective: "Reconocer las características de las ciudades y la concentración de servicios.",
    contents: ["Reconocimiento de las ciudades como concentración de población, bienes y servicios"],
    skills: ["s2-espacio-urbano"],
    after: [1],
  },
  {
    n: 3,
    name: "Vivir en el Campo Patagónico",
    emoji: "🏡",
    description: "Estancias, puestos, corrales y distancias en la estepa y cordillera.",
    objective: "Identificar características del espacio rural patagónico y modos de vida.",
    contents: ["El espacio rural: asentamientos, trabajos y modos de vida"],
    skills: ["s2-paisajes"],
    after: [2],
  },
  {
    n: 4,
    name: "Los Servicios Públicos",
    emoji: "🚰",
    description: "Agua de red, gas natural, luz eléctrica, recolección y salud pública.",
    objective: "Valorar los servicios públicos y su relación con las necesidades de la comunidad.",
    contents: ["Función de los servicios públicos en los espacios urbanos"],
    skills: ["s2-espacio-urbano"],
    after: [3],
  },
  {
    n: 5,
    name: "Del Campo a la Mesa: La Lana",
    emoji: "🧶",
    description: "La oveja en la estancia, la esquila, el fardo, el hilado y la prenda abrigada.",
    objective: "Comprender el circuito productivo de la lana ovina en la Patagonia.",
    contents: ["Circuitos productivos: transformación de materia prima en producto manufacturado"],
    skills: ["s2-circuitos", "s2-trabajos-tecnologia"],
    after: [4],
  },
  {
    n: 6,
    name: "Del Trigo al Pan",
    emoji: "🥖",
    description: "La siembra del trigo, la cosecha, el molino harinero y la panadería.",
    objective: "Describir el proceso de producción de un alimento básico y sus actores.",
    contents: ["Proceso de producción de bienes secundarios: tecnología y trabajos"],
    skills: ["s2-circuitos"],
    after: [5],
  },
  {
    n: 7,
    name: "Los Frutos del Mar Austral",
    emoji: "🎣",
    description: "Los barcos pesqueros en Puerto Deseado y Caleta Olivia y el procesamiento de pescado.",
    objective: "Reconocer la actividad pesquera y portuaria de Santa Cruz.",
    contents: ["Actividades económicas regionales y transformación de recursos marinos"],
    skills: ["s2-circuitos", "s2-trabajos-tecnologia"],
    after: [6],
  },
  {
    n: 8,
    name: "Trabajadores y Herramientas",
    emoji: "🛠️",
    description: "Herramientas de campo, talleres, comercios y tecnología en los trabajos de hoy.",
    objective: "Identificar herramientas, máquinas y tecnologías en distintas ocupaciones.",
    contents: ["Actores sociales, herramientas, trabajos y tecnologías en la producción"],
    skills: ["s2-trabajos-tecnologia"],
    after: [7],
  },
  {
    n: 9,
    name: "Transporte Patagónico: Antes y Ahora",
    emoji: "🚛",
    description: "De los carros de bueyes y diligencias a los camiones y aviones modernos.",
    objective: "Comparar medios de transporte del pasado patagónico con los actuales.",
    contents: ["Evolución de los medios de transporte: carretas, carreros patagónicos y transportes modernos"],
    skills: ["s2-transportes"],
    after: [8],
  },
  {
    n: 10,
    name: "Vías y Rieles de Santa Cruz",
    emoji: "🚂",
    description: "El histórico tren carbonero de Río Turbio y los ferrocarriles patagónicos.",
    objective: "Conocer la historia del ferrocarril en Santa Cruz y su impacto social.",
    contents: ["El tren en la historia regional y la conexión de comunidades"],
    skills: ["s2-transportes", "s2-patrimonio-huellas"],
    after: [9],
  },
  {
    n: 11,
    name: "El Agua y el Suelo que Cuidamos",
    emoji: "🌱",
    description: "Cuidar las pasturas contra el viento y proteger los ríos y lagos.",
    objective: "Reconocer recursos naturales clave de Santa Cruz y prácticas de conservación.",
    contents: ["Recursos naturales (suelo, agua, pasturas) y problemáticas ambientales"],
    skills: ["s2-recursos-ambiente"],
    after: [10],
  },
  {
    n: 12,
    name: "Familias Diferentes, Familias Queridas",
    emoji: "👨‍👩‍👧‍👦",
    description: "Grandes, chicas, con abuelos, con tíos: cada familia tiene su historia.",
    objective: "Reconocer la diversidad familiar y el respeto por las costumbres de cada hogar.",
    contents: ["Diversas formas de organización familiar y costumbres de la vida cotidiana"],
    skills: ["s2-familias-diversidad"],
    after: [11],
  },
  {
    n: 13,
    name: "Los Primeros Habitantes: Aonikenk",
    emoji: "🏹",
    description: "Los cazadores tehuelches: toldos de piel de guanaco, quillangos y respeto por la tierra.",
    objective: "Conocer la vida cotidiana, vestimenta y vivienda de los pueblos Aonikenk.",
    contents: ["Vida cotidiana de sociedades indígenas del territorio patagónico: Aonikenk"],
    skills: ["s2-pueblos-originarios"],
    after: [12],
  },
  {
    n: 14,
    name: "Cazadores del Fuego: Selk'nam",
    emoji: "🔥",
    description: "Familias del extremo sur: abrigos de piel, canoas y relatos ancestrales.",
    objective: "Conocer modos de vida y adaptación al frío de los pueblos originarios australes.",
    contents: ["Sociedades originarias del sur: formas de vida, vivienda y vestimenta"],
    skills: ["s2-pueblos-originarios"],
    after: [13],
  },
  {
    n: 15,
    name: "Cocinar y Calentar: Cambios en el Hogar",
    emoji: "💡",
    description: "Del fuego de leña y la vela a la cocina a gas y la lámpara eléctrica.",
    objective: "Analizar el impacto del desarrollo tecnológico en la vida cotidiana familiar.",
    contents: ["Desarrollo tecnológico a través del tiempo: iluminación, cocción y calefacción"],
    skills: ["s2-tecnologia-tiempo"],
    after: [14],
  },
  {
    n: 16,
    name: "Cueva de las Manos y Huellas del Pasado",
    emoji: "🖐️",
    description: "Pinturas de miles de años en el cañadón del Río Pinturas: patrimonio de la humanidad.",
    objective: "Valorar los sitios patrimoniales e históricos protegidos en Santa Cruz.",
    contents: ["Bienes patrimoniales y huellas materiales del pasado en la provincia"],
    skills: ["s2-patrimonio-huellas"],
    after: [15],
  },
  {
    n: 17,
    name: "Instituciones de Nuestra Comunidad",
    emoji: "🏛️",
    description: "El Municipio, los Bomberos Voluntarios, la Escuela, la Policía y el Hospital.",
    objective: "Identificar las funciones de las principales instituciones comunitarias.",
    contents: ["Instituciones que atienden necesidades sociales de la comunidad"],
    skills: ["s2-instituciones-normas"],
    after: [16],
  },
  {
    n: 18,
    name: "Normas y Acuerdos de Convivencia",
    emoji: "🤝",
    description: "Escuchar, dialogar y cumplir acuerdos para vivir en armonía.",
    objective: "Reconocer las normas y el diálogo para la resolución pacífica de conflictos.",
    contents: ["Funciones de las normas y mecanismos de resolución pacífica de conflictos"],
    skills: ["s2-instituciones-normas", "s2-efemerides"],
    after: [17],
    kind: "integracion",
  },
]);

// ------------------------------------------------------------------
// CIENCIAS NATURALES (24001 - 24016)
// ------------------------------------------------------------------
export const GRADE2_NATURALES: WorldDef[] = build("naturales", [
  {
    n: 1,
    name: "El Bosque de Lengas",
    emoji: "🌲",
    description: "Árboles altos, troncos con musgo, pájaros carpinteros y suelo húmedo.",
    objective: "Caracterizar los seres vivos del bosque andino patagónico y su ambiente.",
    contents: ["Caracterización de plantas y animales respecto a los ambientes cercanos"],
    skills: ["n2-seres-vivos-ambientes", "n2-plantas-bosque"],
    after: [],
  },
  {
    n: 2,
    name: "Animales de la Patagonia",
    emoji: "🦌",
    description: "El huemul, el zorro colorado, el cóndor andino, el choique y el guanaco.",
    objective: "Reconocer especies autóctonas de Santa Cruz y sus adaptaciones corporales.",
    contents: ["Identificación de fauna local y modos de vida relacionados con el ambiente"],
    skills: ["n2-animales-adaptaciones"],
    after: [1],
  },
  {
    n: 3,
    name: "Plantas con Historia: Calafate y Ñire",
    emoji: "🫐",
    description: "Arbustos con espinas que resisten el viento fuerte y dan ricas bayas.",
    objective: "Identificar adaptaciones de la flora nativa patagónica a las condiciones del clima.",
    contents: ["Estructuras y adaptaciones de las plantas autóctonas frente al ambiente"],
    skills: ["n2-plantas-bosque"],
    after: [2],
  },
  {
    n: 4,
    name: "El Bosque en las Cuatro Estaciones",
    emoji: "🍂",
    description: "Hojas doradas en otoño, ramas blancas en invierno y flores en primavera.",
    objective: "Relacionar los ciclos estacionales con los cambios visibles en la vegetación.",
    contents: ["Comportamiento de los seres vivos frente a los cambios estacionales"],
    skills: ["n2-cambios-estacionales", "n2-plantas-bosque"],
    after: [3],
  },
  {
    n: 5,
    name: "¿Qué Necesitan los Seres Vivos?",
    emoji: "💧",
    description: "Agua pura, luz del sol, aire limpio y nutrientes del suelo.",
    objective: "Reconocer la interacción entre factores físicos del ambiente y las necesidades vitales.",
    contents: ["Relaciones entre factores físicos del ambiente y necesidades básicas"],
    skills: ["n2-necesidades-factores"],
    after: [4],
  },
  {
    n: 6,
    name: "Sobrevivir al Invierno",
    emoji: "❄️",
    description: "Pelajes gruesos, aves que viajan al norte y animales que duermen protegidos.",
    objective: "Comprender estrategias de migración, hibernación y letargo en fauna patagónica.",
    contents: ["Modos de adaptación animal al frío extremo y escasez invernal"],
    skills: ["n2-animales-adaptaciones", "n2-cambios-estacionales"],
    after: [5],
  },
  {
    n: 7,
    name: "Crecemos y Cambiamos",
    emoji: "📏",
    description: "¡Mirá cuánto creciste desde bebé! Medir la altura y los pies.",
    objective: "Reconocer cambios en el cuerpo humano como resultado del crecimiento y desarrollo.",
    contents: ["Cambios en el cuerpo humano desde el nacimiento hasta la actualidad"],
    skills: ["n2-cuerpo-crecimiento"],
    after: [6],
  },
  {
    n: 8,
    name: "Nuestros Dientes y la Sonrisa",
    emoji: "🦷",
    description: "Los dientes de leche que caen y los nuevos dientes definitivos.",
    objective: "Conocer la dentición humana, tipos de dientes y su cuidado mediante el cepillado.",
    contents: ["Cambio de dentición y pautas de higiene bucodental"],
    skills: ["n2-cuerpo-crecimiento", "n2-salud-prevencion"],
    after: [7],
  },
  {
    n: 9,
    name: "Cuidar la Salud y las Vacunas",
    emoji: "💉",
    description: "Las vacunas nos protegen de enfermedades y lavarse las manos aleja microbios.",
    objective: "Comprender la importancia de la vacunación y la higiene para prevenir enfermedades.",
    contents: ["Acciones básicas de prevención primaria de enfermedades y hábitos saludables"],
    skills: ["n2-salud-prevencion"],
    after: [8],
  },
  {
    n: 10,
    name: "Huesos y Músculos en Acción",
    emoji: "🦴",
    description: "El esqueleto duro que nos sostiene y los músculos que mueven el cuerpo.",
    objective: "Reconocer las partes del sistema locomotor: huesos, músculos y articulaciones.",
    contents: ["El cuerpo humano: huesos, músculos y articulaciones en el movimiento corporal"],
    skills: ["n2-cuerpo-movimiento"],
    after: [9],
  },
  {
    n: 11,
    name: "La Fuerza que Empuja y Frena",
    emoji: "🛝",
    description: "Fuerzas de empuje, de tiro y el rozamiento que frena sobre distintas superficies.",
    objective: "Experimentar con fuerzas de contacto y la acción del rozamiento.",
    contents: ["Fuerzas de contacto: empuje, tracción y rozamiento sobre el movimiento"],
    skills: ["n2-fuerzas-movimiento"],
    after: [10],
  },
  {
    n: 12,
    name: "Máquinas Simples que nos Ayudan",
    emoji: "⚙️",
    description: "Ruedas, planos inclinados (rampas) y palancas que multiplican la fuerza humana.",
    objective: "Identificar la utilidad cotidiana de máquinas simples como ruedas, rampas y palancas.",
    contents: ["Máquinas simples: rueda, plano inclinado y palanca en la vida diaria"],
    skills: ["n2-fuerzas-movimiento"],
    after: [11],
  },
  {
    n: 13,
    name: "Materiales del Bosque y la Estepa",
    emoji: "🪵",
    description: "Madera, lana, piedra, metales y plásticos: orígenes naturales y artificiales.",
    objective: "Clasificar materiales según su origen natural (vegetal, animal, mineral) o artificial.",
    contents: ["Origen y propiedades de los materiales naturales y manufacturados"],
    skills: ["n2-materiales-propiedades"],
    after: [12],
  },
  {
    n: 14,
    name: "¿Flota o se Hunde?",
    emoji: "🛶",
    description: "Experimentos en el agua: por qué la madera y el corcho flotan y las piedras caen al fondo.",
    objective: "Predecir y comprobar la flotabilidad de diferentes materiales en líquidos.",
    contents: ["Comportamiento de materiales en líquidos: flotación y densidad"],
    skills: ["n2-materiales-propiedades"],
    after: [13],
  },
  {
    n: 15,
    name: "Luces, Sombras y Reflejos",
    emoji: "🔦",
    description: "Fuentes de luz, objetos transparentes y opacos, y cómo se forman las sombras.",
    objective: "Explorar la propagación de la luz, formación de sombras y superficies reflectoras.",
    contents: ["Propiedades ópticas: fuentes luminosas, sombras y reflexión"],
    skills: ["n2-luz-sonido"],
    after: [14],
  },
  {
    n: 16,
    name: "Sonidos del Bosque y el Viento",
    emoji: "🎶",
    description: "Vibraciones que producen sonidos en la naturaleza, instrumentos y el oído.",
    objective: "Comprender la producción del sonido por vibración y distinguir sonidos naturales de ruidos.",
    contents: ["El sonido: vibración de fuentes sonoras y propagación en el medio"],
    skills: ["n2-luz-sonido"],
    after: [15],
    kind: "integracion",
  },
]);

export const GRADE2_WORLDS: WorldDef[] = [
  ...GRADE2_LENGUA,
  ...GRADE2_MATEMATICA,
  ...GRADE2_SOCIALES,
  ...GRADE2_NATURALES,
];

export function getGrade2World(id: number): WorldDef | undefined {
  return GRADE2_WORLDS.find((w) => w.id === id);
}
