// Catálogo de cuentos de los mundos de comprensión (1.º, 2.º y 3.º).
//
// Relatos del canon literario infantil de dominio público: fábulas de Esopo,
// cuentos tradicionales, Perrault, Grimm, Andersen, Horacio Quiroga y
// leyendas tehuelches, guaraníes y del norte argentino, contados de nuevo con palabras simples. Cada cuento
// tiene 6 escenas, una por ilustración en
// public/theme/grados/1/cuentos/<id>-<n>.jpg (las mismas para todos los
// grados). Las preguntas están aparte, una colección por grado
// (preguntas-g1.ts, preguntas-g2.ts, preguntas-g3.ts).
import type { Cuento } from "./tipos";

export const CUENTOS: Cuento[] = [
  {
    id: "liebre-tortuga",
    title: "La liebre y la tortuga",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🐢",
    description: "Escuchá el cuento y contá qué pasó.",
    scenes: [
      "Había una vez una liebre muy rápida que siempre se reía de la tortuga. —¡Qué lenta sos! —le decía.",
      "Un día la tortuga le dijo: —Te desafío a una carrera. Todos los animales del bosque vinieron a mirar.",
      "¡Empezó la carrera! La liebre salió corriendo a toda velocidad y la tortuga caminó despacito, paso a paso.",
      "Como iba tan adelante, la liebre pensó: «Tengo tiempo de sobra». Se acostó debajo de un árbol y se quedó dormida.",
      "Mientras tanto, la tortuga siguió caminando sin parar, despacito pero sin detenerse, y pasó al lado de la liebre dormida.",
      "Cuando la liebre se despertó, corrió con todas sus fuerzas, pero ya era tarde: ¡la tortuga había ganado la carrera!",
    ],
  },
  {
    id: "leon-raton",
    title: "El león y el ratón",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🦁",
    description: "Una fábula sobre ayudar.",
    scenes: [
      "Un gran león dormía la siesta en la selva. Un ratoncito que jugaba por ahí le pasó por arriba de la nariz.",
      "El león se despertó enojado y atrapó al ratón con su pata. —¡Te voy a comer! —rugió.",
      "—¡Por favor, dejame ir! —le pidió el ratón—. Algún día yo te voy a ayudar. El león se rió, pero lo dejó ir.",
      "Unos días después, el león cayó en una red de cazadores. Por más que tiraba, no se podía soltar.",
      "El ratoncito escuchó sus rugidos, vino corriendo y mordió la red con sus dientitos, cuerda por cuerda.",
      "¡El león quedó libre! Le dio las gracias al ratón y desde ese día fueron grandes amigos.",
    ],
  },
  {
    id: "tres-chanchitos",
    title: "Los tres chanchitos",
    origin: "Cuento tradicional",
    genre: "cuento",
    emoji: "🐷",
    description: "¿Qué casa aguantó al lobo?",
    scenes: [
      "Había una vez tres chanchitos hermanos que decidieron construir cada uno su casa.",
      "El primero, que quería jugar, hizo su casa de paja muy rápido. El segundo la hizo de palitos de madera.",
      "El tercero trabajó mucho y construyó su casa con ladrillos fuertes. Sus hermanos se reían porque tardaba tanto.",
      "Llegó el lobo y sopló y sopló: ¡la casa de paja se voló! Después sopló la casa de palitos y también se cayó.",
      "Los dos chanchitos corrieron a la casa de ladrillos. El lobo sopló y sopló, pero la casa no se movió.",
      "El lobo, cansado, se fue para no volver. Los tres hermanos se abrazaron y aprendieron que vale la pena trabajar bien.",
    ],
  },
  {
    id: "ricitos-osos",
    title: "Ricitos de Oro y los tres osos",
    origin: "Cuento tradicional",
    genre: "cuento",
    emoji: "🐻",
    description: "Tres osos y una nena curiosa.",
    scenes: [
      "En una casita del bosque vivían tres osos: papá oso, mamá osa y el osito. Un día salieron a pasear mientras se enfriaba la sopa.",
      "Una nena de pelo rubio, Ricitos de Oro, encontró la casa, vio la puerta abierta y entró sin permiso.",
      "Probó las tres sopas: una muy caliente, otra muy fría y la del osito, ¡justo como le gustaba! Se la tomó toda.",
      "Se sentó en las sillas y la sillita del osito se rompió. Después subió y se durmió en la camita más chiquita.",
      "Los osos volvieron. —¡Alguien tomó mi sopa! —lloró el osito—. ¡Y rompió mi silla! Subieron y encontraron a la nena dormida.",
      "Ricitos de Oro se despertó asustada y salió corriendo. Desde ese día aprendió a no entrar a una casa sin permiso.",
    ],
  },
  {
    id: "gallinita-roja",
    title: "La gallinita roja",
    origin: "Cuento tradicional",
    genre: "cuento",
    emoji: "🐔",
    description: "¿Quién la ayudó a hacer el pan?",
    scenes: [
      "Una gallinita roja encontró unos granos de trigo. —¿Quién me ayuda a sembrarlos? —preguntó. —Yo no —dijeron el pato, el gato y el chancho.",
      "—Entonces lo haré yo sola —dijo la gallinita, y sembró el trigo.",
      "El trigo creció alto y dorado. —¿Quién me ayuda a cortarlo? —Yo no —dijeron otra vez los tres amigos.",
      "La gallinita cortó el trigo, lo llevó al molino y lo convirtió en harina, siempre sola.",
      "Con la harina amasó un pan riquísimo. —¿Quién me ayuda a comerlo? —¡Yo, yo, yo! —gritaron el pato, el gato y el chancho.",
      "—No me ayudaron a sembrar, ni a cortar, ni a amasar —dijo la gallinita—. Este pan lo comeré con mis pollitos. Y así lo hizo.",
    ],
  },
  {
    id: "caperucita",
    title: "Caperucita Roja",
    origin: "Cuento tradicional (Perrault y los hermanos Grimm)",
    genre: "cuento",
    emoji: "🧺",
    description: "Un paseo por el bosque.",
    scenes: [
      "Caperucita Roja llevaba siempre una capa roja. Un día su mamá le dio una canasta con comida para su abuela, que estaba enferma. —No te salgas del camino —le dijo.",
      "En el bosque apareció el lobo. —¿A dónde vas? —A la casa de mi abuela —contestó Caperucita. El lobo le dijo que juntara flores para ella.",
      "Mientras Caperucita juntaba flores, el lobo corrió por un atajo hasta la casa de la abuela, que se escondió en el ropero, y él se metió en su cama.",
      "Caperucita llegó y se acercó a la cama. —Abuela, ¡qué orejas tan grandes tenés! —Son para escucharte mejor. —¡Y qué dientes tan grandes! —¡Son para comerte mejor!",
      "Caperucita gritó muy fuerte. Un leñador que pasaba por ahí la escuchó, entró corriendo y el lobo escapó al bosque para no volver.",
      "La abuela salió del ropero y abrazó a Caperucita. Comieron juntas la merienda, y Caperucita prometió no volver a hablar con desconocidos.",
    ],
  },
  {
    id: "patito-feo",
    title: "El patito feo",
    origin: "Cuento de Hans Christian Andersen",
    genre: "cuento",
    emoji: "🦢",
    description: "Un patito distinto a los demás.",
    scenes: [
      "Mamá pata esperaba que nacieran sus patitos. De los huevos salieron unos patitos amarillos, y del último, el más grande, salió uno gris y distinto.",
      "Los otros animales se burlaban de él: —¡Qué feo es! —le decían, y nadie quería jugar con él.",
      "Muy triste, el patito se fue del corral y caminó solo por el campo y por la laguna.",
      "Llegó el invierno, hacía mucho frío y el patito se escondió entre los juncos, esperando que volviera el calor.",
      "En primavera vio unas aves blancas y hermosas nadando en el lago. Se acercó despacito y miró su reflejo en el agua.",
      "¡No era un pato! Se había convertido en un hermoso cisne. Los otros cisnes lo recibieron con cariño y por fin tuvo amigos.",
    ],
  },
  {
    id: "raton-campo-ciudad",
    title: "El ratón de campo y el ratón de ciudad",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🐭",
    description: "¿Campo tranquilo o ciudad con sustos?",
    scenes: [
      "Un ratón de campo vivía tranquilo en una cueva junto al trigal. Un día invitó a su primo, el ratón de ciudad, a comer.",
      "Le sirvió granos, raíces y agua fresca. El ratón de ciudad dijo: —¡Qué comida tan simple! Vení a mi casa y vas a ver.",
      "En la ciudad vivía en una casa enorme. En la mesa había quesos, panes y tortas. —¡Cuánta comida! —dijo el ratón de campo.",
      "Pero cuando empezaron a comer, ¡apareció el gato! Los dos ratones corrieron a esconderse en un agujero.",
      "Después entraron unas personas haciendo ruido con escobas, y otra vez tuvieron que escapar, con mucho miedo.",
      "—Gracias, primo —dijo el ratón de campo—, pero prefiero mi comida simple y tranquila a tus tortas con sustos. Y volvió feliz a su campo.",
    ],
  },
  {
    id: "leyenda-calafate",
    title: "La leyenda del calafate",
    origin: "Leyenda tehuelche (aonikenk) de la Patagonia",
    genre: "leyenda",
    emoji: "🫐",
    description: "Una leyenda tehuelche de la Patagonia.",
    scenes: [
      "Hace mucho tiempo, en la Patagonia, el pueblo tehuelche viajaba con las estaciones: en otoño se iba al norte, donde hacía menos frío.",
      "Koonek era una abuela muy anciana que ya no podía caminar tanto. Cuando su pueblo partió, ella se quedó sola en la meseta.",
      "Llegó el invierno. El viento soplaba fuerte y la nieve cubría todo. Las aves que pasaban la extrañaban y le preguntaban por qué se había quedado.",
      "Koonek se quedó tan quieta y tan sola que, poco a poco, se convirtió en un arbusto con espinas.",
      "En primavera el arbusto se llenó de flores amarillas, y en verano, de frutos violetas muy dulces. ¡Era el calafate! Las aves volvieron para comerlos.",
      "Por eso se dice que quien come calafate siempre vuelve a la Patagonia. Y Koonek, en cada fruto, nos da la bienvenida.",
    ],
  },
  {
    id: "zorro-cuervo",
    title: "El zorro y el cuervo",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🦊",
    description: "Un zorro muy halagador y un queso.",
    scenes: [
      "Un cuervo encontró un pedazo de queso y voló a la rama más alta de un árbol para comerlo tranquilo.",
      "Un zorro que pasaba olió el queso y se le hizo agua la boca. Pensó: «Ese queso va a ser mío».",
      "—¡Buen día, señor cuervo! ¡Qué plumas tan brillantes tiene! —le dijo el zorro con voz dulce.",
      "—Seguro que su voz es tan linda como sus plumas. ¿Me canta una canción? El cuervo se puso muy orgulloso.",
      "El cuervo abrió el pico para cantar… ¡y el queso se le cayó! El zorro lo atrapó en el aire.",
      "—Amigo cuervo —dijo el zorro—, no creas en todo lo que te dicen para adularte. Y se fue con el queso.",
    ],
  },
  {
    id: "cigarra-hormiga",
    title: "La cigarra y la hormiga",
    origin: "Fábula de Esopo (versión de La Fontaine)",
    genre: "fabula",
    emoji: "🐜",
    description: "Cantar en verano, ¿y en invierno?",
    scenes: [
      "Era verano. La cigarra cantaba todo el día debajo de un árbol, feliz con su guitarra.",
      "La hormiga pasaba cargando granos de trigo, una y otra vez, hasta su hormiguero.",
      "—¿Por qué trabajás tanto? Vení a cantar conmigo —le dijo la cigarra. —Estoy guardando comida para el invierno —contestó la hormiga.",
      "Llegó el invierno. Hacía frío, nevaba y la cigarra no tenía nada para comer.",
      "Temblando, golpeó la puerta del hormiguero. —Hormiga, ¿me convidás un poco de comida?",
      "La hormiga la hizo pasar y compartió su comida. La cigarra aprendió la lección: el verano siguiente cantó y también trabajó.",
    ],
  },
  {
    id: "pastorcito-mentiroso",
    title: "El pastorcito mentiroso",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🐑",
    description: "¿Quién le cree a quien miente?",
    scenes: [
      "Un pastorcito cuidaba las ovejas en una loma, cerca del pueblo. Se aburría mucho.",
      "Para divertirse, gritó: —¡Socorro, viene el lobo! Los vecinos subieron corriendo para ayudarlo.",
      "No había ningún lobo. El pastorcito se reía. Los vecinos volvieron enojados al pueblo.",
      "Otro día volvió a gritar: —¡El lobo, el lobo! Los vecinos corrieron otra vez… y otra vez era mentira.",
      "Una tarde apareció el lobo de verdad. —¡Socorro, el lobo! —gritó el pastorcito, pero esta vez nadie le creyó y nadie vino.",
      "Las ovejas, asustadas, se escaparon por todo el campo. El pastorcito aprendió que a quien miente después no le creen, aunque diga la verdad.",
    ],
  },
  {
    id: "gallina-huevos-oro",
    title: "La gallina de los huevos de oro",
    origin: "Fábula de Esopo",
    genre: "fabula",
    emoji: "🥚",
    description: "Una gallina muy especial y un granjero apurado.",
    scenes: [
      "Un granjero y su esposa tenían una gallina muy especial: cada mañana ponía un huevo de oro.",
      "Vendían cada huevo en el pueblo y, poco a poco, tuvieron una casa linda y todo lo que necesitaban.",
      "Pero el granjero empezó a querer más y más. —¡Un huevo por día es muy poco! —se quejaba.",
      "Quiso que la gallina pusiera muchos huevos de golpe: la despertaba de noche, la apuraba y no la dejaba descansar.",
      "La gallina, cansada y asustada, se escapó del gallinero y se fue lejos, al bosque.",
      "Desde ese día no hubo más huevos de oro. El granjero entendió que, por querer todo de golpe, había perdido lo que tenía.",
    ],
  },
  {
    id: "musicos-bremen",
    title: "Los músicos de Bremen",
    origin: "Cuento de los hermanos Grimm",
    genre: "cuento",
    emoji: "🫏",
    description: "Cuatro amigos que quieren ser músicos.",
    scenes: [
      "Un burro ya viejo no podía cargar bolsas. Decidió irse a la ciudad de Bremen a ser músico.",
      "En el camino encontró a un perro, a un gato y a un gallo, también viejos. —¡Vengan conmigo a tocar música! —les dijo.",
      "Al llegar la noche vieron una casa iluminada en el bosque. Adentro, unos ladrones comían y contaban monedas.",
      "Los animales se subieron uno arriba del otro: el perro sobre el burro, el gato sobre el perro y el gallo arriba de todo.",
      "Y todos juntos «cantaron»: ¡rebuznos, ladridos, maullidos y quiquiriquíes! Los ladrones se asustaron tanto que salieron corriendo.",
      "Los cuatro amigos se quedaron a vivir en la casita, tocando música juntos. Nunca llegaron a Bremen, ¡pero no les importó!",
    ],
  },
  {
    id: "juan-porotos",
    title: "Juan y los porotos mágicos",
    origin: "Cuento tradicional inglés",
    genre: "cuento",
    emoji: "🌱",
    description: "Una planta que llega hasta las nubes.",
    scenes: [
      "Juan vivía con su mamá en una casita muy pobre. Un día fue al mercado a vender la vaca.",
      "En el camino, un señor le cambió la vaca por cinco porotos. —Son mágicos —le dijo. La mamá se enojó y los tiró por la ventana.",
      "A la mañana siguiente había crecido una planta de porotos gigante, ¡que llegaba hasta las nubes! Juan trepó y trepó.",
      "Arriba de las nubes había un castillo donde vivía un gigante gruñón con una gallina que ponía huevos de oro.",
      "Mientras el gigante dormía la siesta, Juan tomó la gallina y bajó rapidísimo por la planta. El gigante se despertó y lo siguió.",
      "Juan llegó abajo, cortó la planta con un hacha y el gigante se quedó arriba, en las nubes. Juan y su mamá nunca más pasaron necesidad.",
    ],
  },
  {
    id: "medias-flamencos",
    title: "Las medias de los flamencos",
    origin: "Cuentos de la selva, de Horacio Quiroga",
    genre: "cuento",
    emoji: "🦩",
    description: "¿Por qué los flamencos tienen las patas coloradas?",
    scenes: [
      "Una vez las víboras hicieron un gran baile a la orilla del río e invitaron a todos los animales.",
      "Los flamencos, que entonces tenían las patas blancas, querían ir muy elegantes y salieron a buscar medias.",
      "Un tatú bromista les dio unas «medias» coloradas, blancas y negras: ¡eran cueros de víboras de coral!",
      "Los flamencos bailaron toda la noche con sus medias rayadas, hasta que las víboras de coral miraron bien y descubrieron el engaño.",
      "Las víboras, enojadas, les mordieron las patas. Los flamencos corrieron a meterlas en el agua fresca del río.",
      "Desde entonces los flamencos tienen las patas coloradas y se pasan el día parados en el agua para que se les pase el ardor.",
    ],
  },
  {
    id: "traje-emperador",
    title: "El traje nuevo del emperador",
    origin: "Cuento de Hans Christian Andersen",
    genre: "cuento",
    emoji: "👑",
    description: "Una tela que nadie puede ver.",
    scenes: [
      "Había un emperador al que le encantaba la ropa nueva. Tenía un traje distinto para cada hora del día.",
      "Un día llegaron dos tramposos: —Tejemos una tela mágica que solo pueden ver las personas inteligentes.",
      "Hacían como que tejían en telares vacíos. Nadie veía nada, pero todos decían «¡qué tela hermosa!» para no parecer tontos.",
      "El emperador tampoco veía la tela, pero no quiso decirlo. Se «puso» el traje nuevo y salió a desfilar por la ciudad.",
      "La gente aplaudía y decía: «¡Qué traje tan lindo!», hasta que un nene gritó: —¡Pero si el emperador está en calzoncillos!",
      "Todos empezaron a reírse, porque era verdad. El emperador, colorado de vergüenza, aprendió que es mejor decir la verdad que aparentar.",
    ],
  },
  {
    id: "tortuga-gigante",
    title: "La tortuga gigante",
    origin: "Cuentos de la selva, de Horacio Quiroga",
    genre: "cuento",
    emoji: "🐢",
    description: "Una tortuga que devuelve un favor.",
    scenes: [
      "Un hombre que vivía en Buenos Aires estaba muy enfermo. El médico le dijo que se fuera a vivir al monte, al aire libre.",
      "En el monte encontró una tortuga gigante que estaba lastimada. La llevó a su refugio y la curó con paciencia.",
      "Tiempo después el hombre volvió a enfermarse, con mucha fiebre. Ahora era la tortuga la que lo cuidaba y le traía agua y frutas.",
      "—Si nos quedamos acá, mi amigo no se va a curar —pensó la tortuga—. Lo voy a llevar a Buenos Aires.",
      "Lo cargó sobre su caparazón y caminó días y noches por el monte y los caminos, muy cansada, sin rendirse.",
      "Al fin llegó a la ciudad y el hombre se curó. Agradecido, la llevó al zoológico, donde vivió tranquila, y él la visitaba todos los días.",
    ],
  },
  {
    id: "leyenda-elal",
    title: "La leyenda de Elal",
    origin: "Leyenda tehuelche (aonikenk) de la Patagonia",
    genre: "leyenda",
    emoji: "🦢",
    description: "El héroe tehuelche que trajo el fuego.",
    scenes: [
      "Hace muchísimo tiempo la Patagonia estaba vacía y helada. Lejos, del otro lado del mar, nació un niño muy especial llamado Elal.",
      "Para ponerlo a salvo, un cisne de cuello negro lo llevó volando sobre su espalda hasta la Patagonia.",
      "Elal llegó a la cima de un cerro muy alto, el Chaltén. Por eso, dicen, ese cerro tiene casi siempre una nube en la punta, como si humeara.",
      "Hacía mucho frío. Elal golpeó dos piedras, saltaron chispas… ¡y les regaló el fuego a las personas!",
      "Enseñó a los tehuelches a hacer arcos y flechas, a cazar guanacos y a coser quillangos para abrigarse.",
      "Cuando terminó su trabajo, Elal se subió otra vez al cisne y se fue volando hacia donde sale el sol. Dicen que desde allá sigue cuidando la Patagonia.",
    ],
  },
  {
    id: "leyenda-koonch",
    title: "Kóoch y el origen del mundo",
    origin: "Leyenda tehuelche (aonikenk) de la Patagonia",
    genre: "leyenda",
    emoji: "🌬️",
    description: "Cómo nacieron el mar, el viento y la luz.",
    scenes: [
      "Al principio no había tierra, ni sol, ni luz. Solo existía Kóoch, rodeado de una oscuridad enorme.",
      "Kóoch se sentía muy solo. Lloró tanto, tanto, que sus lágrimas formaron el mar.",
      "Después dio un suspiro larguísimo y así nació el viento. El viento sopló, apartó la oscuridad y apareció la luz.",
      "Kóoch hizo el sol para que diera calor, y las nubes para que trajeran la lluvia.",
      "Del medio del mar levantó una gran isla. Allí aparecieron los pájaros, los peces, los insectos y los animales.",
      "El sol, la lluvia y el viento hicieron crecer las plantas. Por eso, cuando sopla fuerte el viento en Santa Cruz, dicen que es Kóoch que todavía suspira.",
    ],
  },
  {
    id: "leyenda-hornero",
    title: "La leyenda del hornero",
    origin: "Leyenda guaraní del litoral argentino",
    genre: "leyenda",
    emoji: "🐦",
    description: "Un pájaro que construye su casa de barro.",
    scenes: [
      "Hace mucho tiempo, en la selva, vivía un joven guaraní muy trabajador al que le encantaba construir.",
      "Estaba enamorado de una joven del pueblo y quería casarse con ella.",
      "El cacique le dijo: —Primero tenés que pasar una prueba de paciencia: quedarte tres días envuelto en un cuero, sin moverte.",
      "El joven aceptó. Cuando pasaron los tres días y abrieron el cuero, ¡ya no estaba! Salió volando un pajarito color canela.",
      "El pajarito juntó barro y pajitas con el pico y construyó una casita redonda, con forma de horno.",
      "Así nació el hornero, que todavía hoy arma su casa de barro con trabajo y paciencia. Es el ave nacional de la Argentina.",
    ],
  },
  {
    id: "leyenda-yerba-mate",
    title: "La leyenda de la yerba mate",
    origin: "Leyenda guaraní (Misiones y Corrientes)",
    genre: "leyenda",
    emoji: "🧉",
    description: "Un regalo de la luna y la nube.",
    scenes: [
      "Yasí, la luna, y Araí, la nube, tenían muchas ganas de conocer la selva. Un día bajaron a la tierra convertidas en dos muchachas.",
      "Caminaron entre árboles, flores y mariposas, mirando todo con alegría.",
      "De pronto apareció un yaguareté que las miraba con hambre. Las muchachas se quedaron quietas, muy asustadas.",
      "Un anciano que pasaba por ahí lo vio, lo espantó con su arco y las salvó.",
      "Esa noche el anciano compartió su comida con ellas sin saber quiénes eran. Mientras él dormía, Yasí y Araí le dejaron un regalo: una planta nueva.",
      "Era la yerba mate. Desde entonces, el mate se comparte como señal de amistad y de agradecimiento.",
    ],
  },
  {
    id: "leyenda-siete-colores",
    title: "El Cerro de los Siete Colores",
    origin: "Leyenda de Purmamarca (Jujuy)",
    genre: "leyenda",
    emoji: "⛰️",
    description: "Los chicos que pintaron un cerro.",
    scenes: [
      "Hace mucho tiempo, en Purmamarca, un pueblito de Jujuy, los cerros eran todos grises y marrones.",
      "Los chicos del pueblo se aburrían de mirar siempre el mismo color. Un día tuvieron una idea secreta.",
      "Esa noche, mientras los grandes dormían, salieron calladitos con pinturas y pinceles y pintaron el cerro de un color.",
      "Cada noche pintaron un color nuevo: rojo, amarillo, verde, violeta… ¡y así durante siete noches!",
      "La mañana del octavo día, la gente del pueblo se despertó y vio el cerro lleno de colores. ¡No lo podían creer!",
      "Desde entonces lo llaman el Cerro de los Siete Colores, y dicen que es un regalo de los chicos de Purmamarca.",
    ],
  },
  {
    id: "leyenda-ballena",
    title: "Cómo llegó la ballena al mar",
    origin: "Leyenda tehuelche (aonikenk) de la costa patagónica (versión adaptada)",
    genre: "leyenda",
    emoji: "🐋",
    description: "Una ballena que caminaba por la tierra.",
    scenes: [
      "Dicen los tehuelches que hace muchísimo tiempo las ballenas no vivían en el mar. Góos era una ballena enorme que caminaba por la tierra con patitas cortas.",
      "Vivía en un cañadón cerca de la costa y tenía tanta hambre que se tragaba todo lo que pasaba: zorros, guanacos, pájaros… ¡y hasta cazadores!",
      "Elal, el héroe de los tehuelches, se enteró de que faltaban animales y personas, y decidió ayudarlos.",
      "Se convirtió en un tábano, un bichito volador muy chiquito, y se dejó tragar por Góos.",
      "Adentro encontró a todos, asustados pero sanos. Elal le hizo tantas cosquillas por dentro que Góos abrió la boca y todos salieron corriendo.",
      "Entonces Elal empujó a Góos hasta el mar y le dijo que viviera allí. Por eso, dicen, hoy las ballenas nadan en el mar patagónico.",
    ],
  },
  {
    id: "leyenda-iguazu",
    title: "La leyenda de las Cataratas del Iguazú",
    origin: "Leyenda guaraní (Misiones)",
    genre: "leyenda",
    emoji: "🌈",
    description: "Una serpiente, un río y un arcoíris.",
    scenes: [
      "En la selva de Misiones vivía Mboi, una serpiente gigante que cuidaba el río Iguazú. Los guaraníes la respetaban mucho.",
      "Cada año, una joven del pueblo debía ir a vivir a la orilla del río para servir a Mboi. Ese año eligieron a Naipí.",
      "Pero Naipí y Tarobá, un joven guaraní, se querían mucho. Tarobá preparó una canoa y escaparon juntos por el río.",
      "Mboi se enojó muchísimo. Se metió en la tierra, se retorció con fuerza y partió el río en dos: así se formaron las cataratas.",
      "Naipí quedó convertida en una gran roca en medio de las cataratas, y Tarobá en una palmera en la orilla, mirándola.",
      "Dicen que cuando aparece el arcoíris sobre las cataratas es un puente que une a Naipí y Tarobá, que se siguen queriendo.",
    ],
  },
];

export function getCuento(id: string): Cuento | undefined {
  return CUENTOS.find((c) => c.id === id);
}

export function cuentoImage(id: string, n: number): string {
  return `/theme/grados/1/cuentos/${id}-${n}.jpg`;
}
