// Preguntas de comprensión LECTORA de 2.º grado (los chicos leen el cuento).
// 8 preguntas por cuento, opciones de 3 y 4 (mínimo 3 de 4 opciones).
// Distribución: 2 literal, 2 secuencia, 2 inferencial, 1 vocabulario, 1 estructura/valoración.
// Todos los distractores plausibles del contexto del relato.
// La opción correcta es la de `answer` (el runner las mezcla al jugar).
import type { ComprehensionKind, CuentoOpt, CuentoQuestion } from "./tipos";

const q = (kind: ComprehensionKind) => (text: string, options: CuentoOpt[], answer: number, hint: string): CuentoQuestion => ({
  q: text,
  kind,
  options,
  answer,
  hint,
});

const L = q("literal");
const S = q("secuencia");
const I = q("inferencial");
const V = q("vocabulario");
const E = q("estructura");

export const PREGUNTAS_G2: Record<string, CuentoQuestion[]> = {
  // 1. Caperucita Roja (cuento)
  caperucita: [
    L("¿Para quién era la comida que llevaba Caperucita en su canasta?", [["👵", "Para su abuela que estaba enferma"], ["👧", "Para una amiga de la escuela"], ["🐺", "Para alimentar a los animales del bosque"], ["🪓", "Para convidar la merienda al leñador"]], 0, "Pista: releé la primera escena del cuento."),
    L("¿Dónde se escondió la abuela cuando vio llegar al lobo?", [["🚪", "En el ropero"], ["🛏️", "Debajo de la cama"], ["🌳", "Detrás de un árbol del jardín"]], 0, "Pista: mirá qué hizo la abuela al ver al lobo entrar a su casa."),
    S("¿Qué hizo el lobo mientras Caperucita se entretenía juntando flores?", [["🏃", "Corrió por un atajo hasta la casa de la abuela"], ["😴", "Se durmió una siesta debajo de un árbol"], ["🧺", "Escondió la canasta con comida en el bosque"], ["🪓", "Fue a conversar con el leñador"]], 0, "Pista: fijate qué camino tomó el lobo para llegar primero."),
    S("¿Qué pasó inmediatamente después de que Caperucita gritó al ver los dientes del lobo?", [["🪓", "El leñador la escuchó y entró corriendo"], ["👵", "La abuela salió del ropero a defenderla"], ["🐺", "El lobo se escapó antes de que entrara nadie"]], 0, "Pista: leé la escena donde alguien escucha los gritos de auxilio."),
    I("¿Por qué el lobo le sugirió a Caperucita que juntara flores en el bosque?", [["⏳", "Para ganar tiempo y llegar antes que ella a la casa de la abuela"], ["💐", "Porque quería que la abuela tuviera un ramo colorido"], ["🧺", "Porque tenía hambre y quería comerse las flores"], ["🛤️", "Porque quería enseñarle el camino correcto"]], 0, "Pista: pensá qué hizo el lobo apenas la nena se puso a juntar flores."),
    I("¿Qué aprendió Caperucita al final de la historia?", [["⚠️", "A no desobedecer a su mamá ni hablar con desconocidos"], ["🌸", "A juntar flores más rápido en el bosque"], ["👵", "A visitar a su abuela solo cuando esté sana"]], 0, "Pista: leé la promesa que hace Caperucita en la última escena."),
    V("En el texto dice que el lobo corrió por un «atajo». ¿Qué significa «atajo»?", [["🛤️", "Un camino más corto para llegar más rápido"], ["🌲", "Un bosque muy espeso y oscuro"], ["🚪", "Una puerta escondida de madera"], ["🛑", "Un camino peligroso con piedras"]], 0, "Pista: pensá por dónde fue el lobo para adelantarse a Caperucita."),
    E("¿Qué tipo de texto es «Caperucita Roja»?", [["📖", "Un cuento tradicional que relata una historia de ficción"], ["🫐", "Una leyenda que explica el origen de las plantas"], ["🦊", "Una fábula con moraleja sobre animales que hablan"]], 0, "Pista: es una narración clásica transmitida a lo largo del tiempo."),
  ],

  // 2. Kóoch y el origen del mundo (leyenda)
  "leyenda-koonch": [
    L("Según la leyenda, ¿qué formaron las abundantes lágrimas de Kóoch?", [["🌊", "El mar"], ["🌧️", "Las nubes de tormenta"], ["🏔️", "Los grandes cerros nevados"], ["🌬️", "El viento patagónico"]], 0, "Pista: buscá en la segunda escena qué nació cuando Kóoch lloró."),
    L("¿Qué levantó Kóoch del medio del mar para que vivieran los animales?", [["🏝️", "Una gran isla"], ["🪵", "Un bosque de árboles altos"], ["🪨", "Una cueva de piedra"]], 0, "Pista: leé la quinta escena sobre el lugar donde aparecieron los pájaros y peces."),
    S("¿Qué ocurrió inmediatamente después de que Kóoch dio su primer suspiro larguísimo?", [["🌬️", "Nació el viento y apartó la oscuridad para que apareciera la luz"], ["☀️", "Apareció el sol con su calor brillante"], ["🌱", "Crecieron las primeras plantas en la isla"], ["🌧️", "Comenzaron a caer las primeras lluvias"]], 0, "Pista: fijate qué sucedió en la tercera escena tras el suspiro."),
    S("¿Qué hizo Kóoch para que hubiera calor en la tierra?", [["☀️", "Hizo el sol"], ["🔥", "Encendió una fogata gigante"], ["🌬️", "Sopló aire caliente sobre la meseta"]], 0, "Pista: leé la cuarta escena sobre el sol y las nubes."),
    I("¿Por qué lloró tanto Kóoch al comienzo del relato?", [["😔", "Porque estaba completamente solo en medio de una gran oscuridad"], ["❄️", "Porque sentía mucho frío en la Patagonia"], ["🌊", "Porque el mar tapaba toda la tierra"], ["🌧️", "Porque las nubes no dejaban ver el sol"]], 0, "Pista: fijate cómo se sentía Kóoch en la segunda escena."),
    I("¿Qué recuerdan los tehuelches cuando sopla un viento muy fuerte en Santa Cruz?", [["🌬️", "Sienten que es Kóoch que todavía sigue suspirando"], ["🌧️", "Creen que va a llover durante muchos días"], ["🌊", "Piensan que el mar va a cubrir los cerros"]], 0, "Pista: mirá la última escena del relato sobre el viento santacruceño."),
    V("En el texto dice que Kóoch dio un «suspiro». ¿Qué significa «suspiro»?", [["💨", "Una respiración profunda y prolongada al sentir una emoción"], ["🗣️", "Un grito fuerte de enojo"], ["🌧️", "Una gota de lluvia que cae del cielo"], ["🎵", "Un canto suave para dormir"]], 0, "Pista: pensá en la forma en que Kóoch soltó el aire."),
    E("¿Qué explica principalmente esta leyenda tehuelche?", [["🌍", "El origen del mar, la luz, el viento y la vida según los tehuelches"], ["🐦", "Cómo aprendieron a volar los pájaros de la Patagonia"], ["🏹", "Las técnicas de caza de los antiguos pobladores"]], 0, "Pista: las leyendas explican el origen del mundo y los elementos de la naturaleza."),
  ],

  // 3. El león y el ratón (fábula)
  "leon-raton": [
    L("¿Qué estaba haciendo el ratoncito cuando despertó al león?", [["🐭", "Jugaba y le pasó por arriba de la nariz"], ["🧀", "Buscaba pedacitos de comida en la selva"], ["🕸️", "Intentaba escapar de una trampa"], ["😴", "Dormía la siesta junto a sus patas"]], 0, "Pista: mirá qué hacía el ratón en la primera escena."),
    L("¿Con qué trampa atraparon los cazadores al león?", [["🕸️", "Con una red"], ["🕳️", "En un pozo profundo"], ["🏹", "Con flechas de madera"]], 0, "Pista: leé la cuarta escena sobre la trampa."),
    S("¿Qué hizo el ratón para liberar al león atrapado?", [["🦷", "Mordió la red cuerda por cuerda con sus dientitos"], ["📣", "Fue corriendo a pedir auxilio a otros animales"], ["🪓", "Cortó los nudos con una piedra filosa"], ["💪", "Empujó la red con todas sus fuerzas"]], 0, "Pista: fijate cómo usó sus dientes en la quinta escena."),
    S("¿Qué ocurrió entre el león y el ratón al final de la historia?", [["🤝", "El león le agradeció y se hicieron grandes amigos"], ["🏃", "El ratón se fue corriendo con miedo a ser comido"], ["🦁", "El león volvió a dormir sin decir nada"]], 0, "Pista: revisá la última oración de la fábula."),
    I("¿Por qué el león se rió cuando el ratón le prometió que algún día lo ayudaría?", [["😂", "Porque creyó que un animal tan diminuto jamás podría ayudar al rey de la selva"], ["🧀", "Porque el ratón le contó una historia divertida"], ["🍖", "Porque pensó que el ratón le traería un festín de comida"], ["🦁", "Porque estaba contento de haber dormido su siesta"]], 0, "Pista: pensá en la diferencia de tamaño y fuerza entre los dos animales."),
    I("¿Por qué el ratón decidió acudir en ayuda del león cuando escuchó sus rugidos?", [["💛", "Porque recordó su promesa y quiso salvar a quien le perdonó la vida"], ["🦁", "Porque tenía miedo de que el león se enojara más"], ["🕸️", "Porque quería quedarse con la red de los cazadores"]], 0, "Pista: pensá en el compromiso que el ratón había asumido antes."),
    V("En la escena 5 dice que el ratón mordió la «cuerda». ¿Qué es una «cuerda»?", [["🧵", "Un hilo grueso o soga resistente que formaba la red"], ["🪵", "Una rama seca de árbol"], ["🍃", "Una hoja grande de la selva"], ["🪨", "Una piedra puntiaguda"]], 0, "Pista: pensá de qué material estaba tejida la red de los cazadores."),
    E("¿Cuál es la moraleja o enseñanza principal de esta fábula?", [["💡", "Que ningún acto de bondad es en vano y hasta el más pequeño puede ayudar"], ["🦁", "Que los leones siempre deben cazar solos en la selva"], ["😴", "Que es peligroso dormir la siesta al aire libre"]], 0, "Pista: las fábulas transmiten una enseñanza sobre la solidaridad y el respeto."),
  ],

  // 4. El patito feo (cuento)
  "patito-feo": [
    L("¿De qué color eran los hermanos del patito feo al salir del cascarón?", [["💛", "Amarillos"], ["🩶", "Grises"], ["🤍", "Blancos"], ["🤎", "Marrones"]], 0, "Pista: leé la primera escena sobre los huevos que nacieron primero."),
    L("¿Dónde se refugió el patito durante los meses fríos de invierno?", [["🌾", "Escondido entre los juncos de la laguna"], ["🏡", "En el calor del corral con los otros animales"], ["🌳", "En el hueco de un árbol del bosque"]], 0, "Pista: buscá en la cuarta escena dónde esperó que volviera el calor."),
    S("¿Qué hizo el patito cuando vio que todos los animales del corral se burlaban de él?", [["🚶", "Se fue del corral y caminó solo por el campo y la laguna"], ["🦢", "Se escondió en el nido de su mamá para siempre"], ["😤", "Peleó con sus hermanos para defenderse"], ["🏊", "Se puso a nadar alegremente en el estanque"]], 0, "Pista: fijate qué decisión tomó en la tercera escena por estar tan triste."),
    S("¿Qué descubrió el protagonista al mirar su reflejo en el agua en primavera?", [["🦢", "Que se había transformado en un hermoso cisne"], ["🦆", "Que sus plumas se habían vuelto amarillas"], ["🩶", "Que seguía siendo igual que cuando nació"]], 0, "Pista: leé lo que vio reflejado en el lago en las dos últimas escenas."),
    I("¿Por qué los animales del corral se burlaban del protagonista al principio?", [["😔", "Porque era diferente a ellos en tamaño y color de plumas"], ["🦢", "Porque no sabía nadar en la laguna"], ["🗣️", "Porque cantaba demasiado fuerte"], ["🏃", "Porque corría más rápido que los demás"]], 0, "Pista: pensá en cómo reaccionaron al ver que no era amarillo."),
    I("¿Cómo cambió la vida del protagonista al encontrarse con los cisnes en el lago?", [["🤗", "Fue recibido con cariño y por fin tuvo amigos que lo aceptaban"], ["😢", "Tuvo que esconderse de nuevo por temor al rechazo"], ["🚶", "Decidió marcharse a vivir solo a otra laguna lejana"]], 0, "Pista: mirá cómo termina el cuento en la escena 6."),
    V("En la escena 4 dice que el patito se escondió entre los «juncos». ¿Qué son los «juncos»?", [["🌿", "Plantas de tallo largo y flexible que crecen cerca del agua"], ["🪵", "Ramas caídas de los sauces del bosque"], ["🪨", "Piedras grandes que bordean la orilla"], ["❄️", "Capas gruesas de nieve helada"]], 0, "Pista: pensá en la vegetación que crece en las lagunas."),
    E("¿Qué tipo de texto es «El patito feo»?", [["📖", "Un cuento de autor escrito por Hans Christian Andersen"], ["🫐", "Una leyenda tradicional sobre el nacimiento de los lagos"], ["🦊", "Una fábula en verso sobre animales salvajes"]], 0, "Pista: revisá los datos sobre el origen del relato al inicio."),
  ],

  // 5. La leyenda del hornero (leyenda)
  "leyenda-hornero": [
    L("¿Qué prueba de paciencia le impuso el cacique al joven guaraní?", [["⏳", "Quedarse tres días envuelto en un cuero sin moverse"], ["🏹", "Cazar un animal peligroso en la selva"], ["🪵", "Construir una choza entera en una sola noche"], ["🏊", "Nadar de una orilla a otra del río sin parar"]], 0, "Pista: leé la exigencia del cacique en la escena 3."),
    L("¿Qué materiales usó el pajarito para construir su casita con forma de horno?", [["🪵", "Barro y pajitas con el pico"], ["🍃", "Hojas secas y ramitas del suelo"], ["🪨", "Piedras pequeñas y arena del río"]], 0, "Pista: mirá qué recolectó el hornero en la quinta escena."),
    S("¿Qué ocurrió al cumplirse los tres días cuando abrieron el cuero?", [["🐦", "El joven ya no estaba y salió volando un pajarito color canela"], ["🎉", "El cacique felicitó al joven y celebraron la boda"], ["😴", "El joven seguía profundamente dormido en el suelo"], ["🏃", "El joven se escapó corriendo hacia la orilla del río"]], 0, "Pista: leé la transformación sorprendente en la escena 4."),
    S("¿Qué reconocimiento tiene el hornero en nuestro país según el texto?", [["🇦🇷", "Es el ave nacional de la Argentina"], ["👑", "Es el pájaro más veloz de la selva"], ["🦅", "Es el guardián de los ríos del litoral"]], 0, "Pista: revisá la última oración de la leyenda."),
    I("¿Por qué el joven aceptó cumplir una prueba tan difícil e incómoda?", [["❤️", "Porque estaba enamorado de la joven y quería casarse con ella"], ["👑", "Porque quería convertirse en el nuevo cacique del pueblo"], ["🐦", "Porque deseaba transformarse en un pájaro volador"], ["🏹", "Porque quería demostrar que era el más fuerte de la tribu"]], 0, "Pista: fijate cuál era su mayor deseo en la segunda escena."),
    I("¿Qué cualidad del joven guaraní se ve reflejada en el hornero que construye hoy?", [["🏡", "La paciencia y la dedicación para trabajar y construir su hogar"], ["🏃", "La velocidad para volar distancias muy largas"], ["🗣️", "La habilidad para cantar canciones a la comunidad"]], 0, "Pista: pensá en lo que más le gustaba hacer al joven en la primera escena."),
    V("En la escena 4 dice que el pajarito era «color canela». ¿Qué significa ese color?", [["🟤", "Un color marrón claro y suave"], ["🟡", "Un amarillo muy brillante como el sol"], ["⚪", "Un blanco puro como la nieve"], ["🔴", "Un rojo intenso como el fuego"]], 0, "Pista: pensá en el tono de las plumas del hornero."),
    E("¿Qué propósito tiene esta leyenda guaraní?", [["🐦", "Explicar el origen del hornero y por qué construye su nido de barro"], ["🌾", "Enseñar recetas tradicionales para cocinar en hornos de barro"], ["📜", "Dar instrucciones para curar el cuero de los animales"]], 0, "Pista: las leyendas buscan explicar el origen de seres y costumbres."),
  ],

  // 6. El zorro y el cuervo (fábula)
  "zorro-cuervo": [
    L("¿Dónde se ubicó el cuervo para comer su queso tranquilo?", [["🌳", "En la rama más alta de un árbol"], ["🪨", "Arriba de una gran roca del camino"], ["🌾", "En medio de un campo de trigo"], ["🏠", "En el techo de una granja vecina"]], 0, "Pista: mirá a dónde voló el cuervo en la primera escena."),
    L("¿Qué cualidad del cuervo elogió primero el zorro para llamar su atención?", [["🪶", "El brillo hermoso de sus plumas"], ["🧀", "El tamaño del queso que había encontrado"], ["👀", "Su mirada atenta desde las alturas"]], 0, "Pista: leé el saludo inicial del zorro en la escena 3."),
    S("¿Qué sucedió en cuanto el cuervo abrió el pico para cantar?", [["🧀", "El queso se le cayó y el zorro lo atrapó en el aire"], ["🎵", "Todos los animales vinieron a escuchar su melodía"], ["🌳", "El zorro se asustó con su graznido y huyó"], ["🦅", "Otro pájaro bajó volando y le quitó el alimento"]], 0, "Pista: revisá qué pasó en la quinta escena cuando intentó cantar."),
    S("¿Qué hizo el zorro inmediatamente después de conseguir el queso?", [["🦊", "Le dio una lección al cuervo sobre la adulación y se marchó"], ["🤝", "Convidó la mitad del queso al cuervo agradecido"], ["😴", "Se acostó a dormir debajo del árbol del cuervo"]], 0, "Pista: mirá las palabras finales del zorro en la escena 6."),
    I("¿Por qué el zorro le pidió al cuervo que cantara una canción?", [["🧀", "Porque sabía que al abrir el pico se le caería el queso"], ["🎵", "Porque le fascinaba la música de las aves del bosque"], ["🤝", "Porque quería hacerse muy amigo del cuervo"], ["😴", "Porque necesitaba una canción de cuna para descansar"]], 0, "Pista: pensá en el verdadero interés del zorro desde que olió la comida."),
    I("¿Qué sentimiento hizo caer al cuervo en la trampa del zorro?", [["🦚", "La vanidad y el orgullo por los halagos recibidos"], ["😨", "El miedo a que el zorro trepara por el árbol"], ["😋", "El hambre desesperada por comerse el queso"]], 0, "Pista: fijate cómo se sintió el cuervo en la escena 4 al escuchar los elogios."),
    V("El zorro le dice: «no creas en todo lo que te dicen para adularte». ¿Qué significa «adularte»?", [["🗣️", "Decir halagos falsos o exagerados para conseguir algo a cambio"], ["😡", "Insultar a alguien para hacerlo enojar"], ["🤫", "Contar un secreto en voz muy baja"], ["❓", "Hacer preguntas difíciles de responder"]], 0, "Pista: pensá por qué el zorro alababa tanto las plumas y la voz del cuervo."),
    E("¿Cuál es la moraleja que nos deja esta fábula de Esopo?", [["💡", "Desconfiar de quienes nos llenan de elogios fingidos por interés"], ["🧀", "No compartir nunca la comida con otros animales"], ["🌳", "Comer siempre en el suelo y nunca en los árboles altos"]], 0, "Pista: las fábulas advierten sobre conductas humanas a través de animales."),
  ],

  // 7. Los músicos de Bremen (cuento)
  "musicos-bremen": [
    L("¿Por qué el burro decidió abandonar su establo e irse a Bremen?", [["🫏", "Porque ya estaba viejo y no podía cargar bolsas pesadas"], ["🎸", "Porque había ganado un concurso de música en el pueblo"], ["🐕", "Porque quería salir a buscar a su amigo el perro"], ["🌾", "Porque no había más pasto para comer en su granja"]], 0, "Pista: leé la primera escena sobre los motivos del burro."),
    L("¿Qué estaban haciendo los ladrones dentro de la casa del bosque?", [["💰", "Comían y contaban monedas a la luz"], ["😴", "Dormían profundamente en sus camas"], ["🎵", "Tocaban instrumentos musicales junto al fuego"]], 0, "Pista: revisá qué vieron los animales por la ventana en la tercera escena."),
    S("¿Cómo se acomodaron los cuatro animales para asustar a los ladrones?", [["🪜", "El perro sobre el burro, el gato sobre el perro y el gallo arriba de todo"], ["🫏", "El burro arriba de todos y los demás sosteniéndolo"], ["🐓", "El gallo abajo de todos y el perro en la cima"], ["🐕", "El perro y el gato hicieron una ronda alrededor de la casa"]], 0, "Pista: mirá el orden en que se treparon en la cuarta escena."),
    S("¿Qué decidieron hacer los cuatro animales después de que los ladrones escaparon?", [["🏡", "Se quedaron a vivir juntos en la casita tocando música"], ["🚶", "Siguieron su viaje a Bremen a pie a la mañana siguiente"], ["👮", "Fueron a la ciudad a entregar la casa a las autoridades"]], 0, "Pista: fijate en la última escena si llegaron o no a su destino inicial."),
    I("¿Qué tenían en común el burro, el perro, el gato y el gallo cuando se encontraron?", [["👵", "Todos eran viejos y buscaban un nuevo propósito juntos"], ["🎸", "Todos sabían tocar la guitarra desde chiquitos"], ["🏡", "Todos vivían antes en la misma granja con el mismo dueño"], ["💰", "Todos querían conseguir una bolsa de monedas de oro"]], 0, "Pista: fijate cómo describe el relato a cada animal al sumarse."),
    I("¿Por qué huyeron los ladrones tan aterrorizados de la cabaña?", [["😱", "Creyeron que una criatura extraña y ruidosa los atacaba en la oscuridad"], ["🪓", "Vieron entrar a un grupo de leñadores armados"], ["🔥", "Se asustaron porque comenzó un incendio en el bosque"]], 0, "Pista: pensá en el impacto de los cuatro ruidos juntos y la sombra alta."),
    V("En la escena 5 se nombran los «rebuznos». ¿Qué son los «rebuznos»?", [["🗣️", "La voz o sonido característico que emite el burro"], ["🐕", "Los ladridos roncos del perro viejo"], ["🐓", "El canto mañanero del gallo"], ["🐱", "Los maullidos agudos del gato"]], 0, "Pista: relacioná el sonido con el animal que iba abajo en la torre."),
    E("¿Qué tipo de texto es «Los músicos de Bremen»?", [["📖", "Un cuento tradicional recopilado por los hermanos Grimm"], ["🫐", "Una leyenda patagónica sobre la música del bosque"], ["🦊", "Una fábula en verso escrita por Esopo"]], 0, "Pista: consultá los datos de autoría y tradición al inicio del texto."),
  ],

  // 8. La leyenda del calafate (leyenda)
  "leyenda-calafate": [
    L("¿Por qué la anciana Koonek no pudo viajar al norte con el resto de su pueblo?", [["👵", "Porque era muy anciana y ya no podía caminar tanto"], ["❄️", "Porque le gustaba mucho la nieve del invierno"], ["🫐", "Porque quería cuidar los frutos del calafate"], ["🐦", "Porque estaba esperando la visita de las aves"]], 0, "Pista: mirá la segunda escena sobre la abuela tehuelche."),
    L("¿De qué color son los frutos dulces que da el arbusto del calafate en verano?", [["🟣", "Violetas"], ["🟡", "Amarillos"], ["🔴", "Rojos"]], 0, "Pista: leé la quinta escena donde describe las flores y los frutos."),
    S("¿En qué se transformó Koonek después de pasar tanto tiempo sola en la meseta?", [["🫐", "En un arbusto con espinas que florece en primavera"], ["🦢", "En un ave blanca que vuela hacia el norte"], ["🏔️", "En una montaña cubierta de nieve eterna"], ["🌧️", "En una nube que trae lluvia a la meseta"]], 0, "Pista: buscá en la cuarta escena la metamorfosis de Koonek."),
    S("¿Qué hacen las aves cuando los frutos del calafate maduran en verano?", [["🐦", "Vuelven a la meseta para alimentarse de sus frutos dulces"], ["❄️", "Se van volando a zonas más frías de la Patagonia"], ["🪺", "Arman nidos con las ramas espinosas del arbusto"]], 0, "Pista: mirá la escena 5 sobre el regreso de los pájaros."),
    I("¿Por qué el pueblo tehuelche se trasladaba hacia el norte al llegar el otoño?", [["❄️", "Para buscar un clima menos frío y refugiarse de las heladas"], ["🫐", "Para cosechar calafate en las playas del norte"], ["🌊", "Para conocer el mar y pescar peces gigantes"], ["👵", "Para construir casas de ladrillos más abrigadas"]], 0, "Pista: leé la primera escena sobre las estaciones y el clima."),
    I("Según la creencia popular patagónica, ¿qué le ocurre a quien come calafate?", [["✨", "Siempre vuelve a visitar la Patagonia"], ["🫐", "Aprende a hablar con las aves de la meseta"], ["❄️", "Nunca más vuelve a sentir frío en el invierno"]], 0, "Pista: revisá la famosa frase tradicional en la última escena."),
    V("En la escena 2 dice que Koonek quedó sola en la «meseta». ¿Qué es una «meseta»?", [["🏔️", "Una planicie extensa ubicada a cierta altura sobre el terreno"], ["🌊", "Un río caudaloso con piedras redondas"], ["🌲", "Un bosque frondoso lleno de árboles gigantes"], ["🏖️", "Una playa de arena a orillas del mar"]], 0, "Pista: pensá en el paisaje geográfico característico de Santa Cruz."),
    E("¿Qué explica fundamentalmente esta leyenda tradicional?", [["🫐", "El nacimiento del calafate y la promesa de regresar a la Patagonia"], ["🏹", "Cómo aprendieron los tehuelches a cazar guanacos con flechas"], ["🐦", "Por qué los pájaros migran sin cantar en el camino"]], 0, "Pista: las leyendas dan origen a plantas, elementos o costumbres de una región."),
  ],

  // 9. La cigarra y la hormiga (fábula)
  "cigarra-hormiga": [
    L("¿Qué hacía la cigarra durante los cálidos días de verano?", [["🎸", "Cantaba todo el día debajo de un árbol con su guitarra"], ["🌾", "Guardaba semillas y granos en su refugio"], ["🐜", "Ayudaba a la hormiga a transportar alimentos"], ["🏡", "Construía un refugio para soportar las heladas"]], 0, "Pista: mirá qué hacía la cigarra en la primera escena."),
    L("¿Qué alimento cargaba la laboriosa hormiga hasta su refugio?", [["🌾", "Granos de trigo"], ["🍎", "Pedacitos de fruta madura"], ["🍃", "Hojas verdes del bosque"]], 0, "Pista: leé la segunda escena sobre el cargamento de la hormiga."),
    S("¿Qué situación desesperada vivió la cigarra al llegar el invierno?", [["❄️", "Hacía mucho frío, nevaba y no tenía nada para comer"], ["🎸", "Se le rompió su guitarra favorita con el viento"], ["🐜", "Perdió el camino para llegar al hormiguero"], ["🚪", "Se quedó encerrada en su propia casa"]], 0, "Pista: leé la cuarta escena cuando cambia la estación del año."),
    S("¿Cómo reaccionó la hormiga cuando la cigarra golpeó a su puerta temblando?", [["🤝", "La hizo pasar a su hogar y compartió su comida"], ["🚪", "Le cerró la puerta y le dijo que fuera a cantar"], ["🏃", "Salió corriendo al bosque a buscar más provisiones"]], 0, "Pista: mirá el noble gesto de la hormiga en la última escena."),
    I("¿Por qué la hormiga no aceptó la invitación de la cigarra para cantar en verano?", [["🐜", "Porque sabía que en invierno escasearía la comida y debía ser previsora"], ["🎸", "Porque no le gustaba la música ni sabía tocar instrumentos"], ["😤", "Porque estaba enojada con la cigarra por no ayudarla"], ["☀️", "Porque prefería trabajar bajo el sol caliente"]], 0, "Pista: leé la respuesta que le da la hormiga en la escena 3."),
    I("¿Qué valiosa lección aprendió la cigarra para el verano siguiente?", [["💡", "Que hay tiempo para disfrutar y cantar, pero también hay que trabajar"], ["🎸", "Que es mejor vender la guitarra antes de que empiece a nevar"], ["🐜", "Que siempre habrá alguien obligado a darle comida gratis"]], 0, "Pista: revisá la última oración de la fábula."),
    V("En la escena 2 se menciona el «hormiguero». ¿Qué es un «hormiguero»?", [["🏠", "El refugio subterráneo donde viven y almacenan provisiones las hormigas"], ["🌾", "Un campo sembrado con espigas de trigo"], ["🪵", "El tronco seco de un árbol caído en el bosque"], ["🪨", "Una piedra hueca donde se junta agua de lluvia"]], 0, "Pista: pensá dónde guardaba la hormiga los granos que cargaba."),
    E("¿A qué género narrativo pertenece «La cigarra y la hormiga»?", [["🦊", "A una fábula tradicional con moraleja sobre la previsión"], ["🫐", "A una leyenda sobre el origen de los insectos del verano"], ["📰", "A una noticia periodística sobre el clima invernal"]], 0, "Pista: los relatos con animales que dejan una enseñanza moral son fábulas."),
  ],

  // 10. Juan y los porotos mágicos (cuento)
  "juan-porotos": [
    L("¿Por qué cosa cambió Juan la vaca de su familia en el camino al mercado?", [["🌱", "Por cinco porotos mágicos"], ["💰", "Por una bolsa llena de monedas de plata"], ["🐔", "Por una gallina común de corral"], ["🪓", "Por un hacha afilada para cortar leña"]], 0, "Pista: leé la segunda escena sobre el trueque que hizo Juan."),
    L("¿Qué animal extraordinario poseía el gigante gruñón en su castillo?", [["🥚", "Una gallina que ponía huevos de oro"], ["🐄", "Una vaca que daba leche chocolatada"], ["🦜", "Un loro que hablaba en todos los idiomas"]], 0, "Pista: mirá qué encontró Juan en el castillo en la cuarta escena."),
    S("¿Qué hizo Juan cuando el gigante se despertó de la siesta y comenzó a perseguirlo?", [["🏃", "Tomó la gallina y bajó rapidísimo por la planta gigante"], ["🚪", "Se escondió adentro de un ropero del castillo"], ["🪓", "Peleó valientemente contra el gigante en las nubes"], ["🌱", "Le ofreció los porotos mágicos para calmarlo"]], 0, "Pista: revisá cómo logró escapar en la quinta escena."),
    S("¿Qué hizo Juan apenas tocó el suelo de su jardín con la gallina?", [["🪓", "Cortó la planta con un hacha para que el gigante no pudiera bajar"], ["🏠", "Entró a la casa a mostrarle los huevos de oro a su mamá"], ["🌱", "Plantó más porotos en la tierra fértil"]], 0, "Pista: leé la acción decisiva de Juan en la sexta escena."),
    I("¿Por qué la mamá de Juan se enojó tanto y tiró los porotos por la ventana?", [["😠", "Porque necesitaban dinero para comer y creyó que habían sido engañados"], ["🌱", "Porque no le gustaban las plantas en su jardín"], ["🐄", "Porque quería conservar a la vaca como mascota"], ["🌧️", "Porque pensó que los porotos iban a pudrirse con la lluvia"]], 0, "Pista: pensá en la pobreza que sufrían Juan y su mamá."),
    I("¿Cómo cambió la vida económica de Juan y su mamá gracias a la gallina?", [["✨", "Nunca más volvieron a pasar necesidades ni hambre"], ["👑", "Se convirtieron en reyes de un gran palacio"], ["🐄", "Pudieron comprar cien vacas para trabajar el campo"]], 0, "Pista: mirá la última oración de la historia."),
    V("En la escena final dice que «nunca más pasaron necesidad». ¿Qué significa «necesidad»?", [["🍲", "Carencia de cosas básicas como comida, abrigo o dinero para vivir"], ["😴", "Ganas irresistibles de dormir una siesta larga"], ["🏃", "Obligación de correr apurado a un lugar"], ["🌧️", "Deseo de que llueva sobre los sembrados"]], 0, "Pista: pensá en lo que sufre una familia que no tiene para comer."),
    E("¿Qué tipo de relato es «Juan y los porotos mágicos»?", [["📖", "Un cuento tradicional maravilloso con elementos mágicos"], ["🫐", "Una leyenda que explica el origen de las plantas trepadoras"], ["🦊", "Una fábula sobre cómo cuidar a las vacas lecheras"]], 0, "Pista: los cuentos maravillosos tienen plantas mágicas y gigantes."),
  ],

  // 11. La leyenda de la yerba mate (leyenda)
  "leyenda-yerba-mate": [
    L("¿Quiénes eran realmente las dos muchachas que bajaron a conocer la selva?", [["🌙", "Yasí la luna y Araí la nube"], ["🌸", "Dos flores mágicas que cobraron vida"], ["🦋", "Dos mariposas gigantes convertidas en personas"], ["⭐", "Dos estrellas que cayeron del cielo nocturno"]], 0, "Pista: leé la primera escena sobre los personajes celestiales."),
    L("¿Qué animal feroz amenazó a las jóvenes entre la vegetación?", [["🐆", "Un yaguareté hambriento"], ["🐍", "Una serpiente cascabel venenosa"], ["🐊", "Un yacaré que salía del agua del río"]], 0, "Pista: mirá la tercera escena sobre el peligro en la selva."),
    S("¿Qué hizo el valiente anciano para salvar a las muchachas del peligro?", [["🏹", "Apareció y espantó al yaguareté con su arco y flechas"], ["🔥", "Encendió una gran fogata para asustar a la fiera"], ["🏃", "Llamó a los guerreros de su tribu para que acudieran"], ["🌳", "Ayudó a las muchachas a subirse a la copa de un árbol"]], 0, "Pista: revisá cómo actuó el anciano en la cuarta escena."),
    S("¿Qué regalo especial le dejaron Yasí y Araí al anciano mientras él dormía?", [["🧉", "Una planta nueva y desconocida: la yerba mate"], ["🏹", "Un arco dorado tallado en madera noble"], ["🍲", "Una canasta repleta de provisiones para el invierno"]], 0, "Pista: leé el obsequio de agradecimiento en la quinta escena."),
    I("¿Por qué el anciano compartió su modesta comida con las dos jóvenes?", [["💛", "Por pura generosidad y hospitalidad, sin saber quiénes eran realmente"], ["🌙", "Porque reconoció de inmediato que eran seres mágicos del cielo"], ["🧉", "Porque quería que a cambio le revelaran un secreto de la selva"], ["🏹", "Porque las jóvenes le habían prometido un arco mágico"]], 0, "Pista: fijate en la quinta escena: 'sin saber quiénes eran'."),
    I("¿Qué significado cultural tiene compartir el mate hoy en día según la tradición?", [["🤝", "Es un símbolo de amistad, encuentro y agradecimiento mutuo"], ["🥇", "Es una competencia para ver quién toma más rápido"], ["🤫", "Es una costumbre para tomar en silencio sin conversar"]], 0, "Pista: leé la última frase de la leyenda."),
    V("En la escena 3 se nombra al «yaguareté». ¿Qué animal es el «yaguareté»?", [["🐆", "Un gran felino autóctono de la selva con manchas negras"], ["🐺", "Un zorro pequeño de las montañas"], ["🐻", "Un oso pardo de los bosques fríos"], ["🦡", "Un tatú con caparazón de placas"]], 0, "Pista: pensá en el gran carnívoro manchado que habita en Misiones."),
    E("¿Qué origen explica esta tradicional leyenda guaraní?", [["🧉", "El nacimiento de la yerba mate y la costumbre de compartirla"], ["🌙", "Cómo se formaron la luna y las nubes en el firmamento"], ["🏹", "El invento del arco y la flecha en los pueblos originarios"]], 0, "Pista: las leyendas narran el origen de costumbres arraigadas en la cultura."),
  ],

  // 12. El pastorcito mentiroso (fábula)
  "pastorcito-mentiroso": [
    L("¿Dónde cuidaba sus ovejas el pastorcito aburrido?", [["🐑", "En una loma cerca del pueblo"], ["🌲", "En lo profundo de un bosque espeso"], ["🌾", "En medio de una granja de vacas"], ["🏠", "En la plaza principal del pueblo"]], 0, "Pista: mirá el lugar donde pastaban las ovejas en la primera escena."),
    L("¿Cuántas veces engañó el pastorcito a los vecinos con la falsa alarma del lobo?", [["2️⃣", "Dos veces"], ["1️⃣", "Una sola vez"], ["3️⃣", "Tres veces seguidas"]], 0, "Pista: contá las escenas 2 y 4 donde gritó mentiras para divertirse."),
    S("¿Qué ocurrió la tercera tarde cuando el lobo apareció de verdad?", [["🐺", "El pastorcito gritó pidiendo socorro pero nadie le creyó ni vino"], ["🏃", "Los vecinos llegaron con palos y ahuyentaron al lobo"], ["🐑", "Las ovejas se metieron solas en el corral del pueblo"], ["😴", "El lobo se quedó dormido debajo de un árbol"]], 0, "Pista: leé la quinta escena sobre la llegada real del depredador."),
    S("¿Qué pasó finalmente con el rebaño de ovejas asustadas?", [["🐑", "Se escaparon y se desparramaron por todo el campo"], ["🏠", "Volvieron tranquilas a la casa del pastorcito"], ["🤝", "Los vecinos ayudaron a juntarlas sin protestar"]], 0, "Pista: mirá qué sucedió en la sexta escena."),
    I("¿Por qué los vecinos del pueblo no subieron a ayudar al pastorcito la última vez?", [["😠", "Porque habían sido engañados antes y pensaron que era otra broma"], ["😴", "Porque estaban durmiendo la siesta y no escucharon nada"], ["🌧️", "Porque llovía torrencialmente y no podían salir"], ["🐺", "Porque le tenían más miedo al lobo que el pastorcito"]], 0, "Pista: pensá en la pérdida de confianza tras las mentiras anteriores."),
    I("¿Qué reflexión o arrepentimiento tuvo el pastorcito al terminar el día?", [["💡", "Entendió que al que miente después no le creen ni cuando dice la verdad"], ["🐑", "Pensó que cuidar ovejas era un trabajo muy divertido"], ["🗣️", "Decidió inventar mentiras más difíciles de descubrir"]], 0, "Pista: revisá la última oración de la fábula."),
    V("En la escena 1 se dice que cuidaba ovejas en una «loma». ¿Qué es una «loma»?", [["⛰️", "Una colina o elevación de terreno suave y redondeada"], ["🕳️", "Un pozo profundo cavado en la tierra"], ["🌊", "Una laguna con agua estancada"], ["🛤️", "Un camino empedrado entre las casas"]], 0, "Pista: pensá en la geografía donde pastaban los animales cerca del pueblo."),
    E("¿A qué género literario corresponde este relato y qué busca transmitir?", [["🦊", "Es una fábula moral que enseña el valor de la verdad y la honestidad"], ["📖", "Es un cuento de hadas sobre animales mágicos del bosque"], ["🫐", "Es una leyenda que explica cómo nacieron los lobos salvajes"]], 0, "Pista: los relatos breves con moraleja son fábulas."),
  ],

  // 13. El traje nuevo del emperador (cuento)
  "traje-emperador": [
    L("¿Qué prenda o gusto especial tenía el emperador al comienzo de la historia?", [["👑", "Le encantaba la ropa nueva y tenía un traje para cada hora del día"], ["🪙", "Juntaba monedas de oro en cofres de hierro"], ["🏰", "Construía castillos con torres de cristal"], ["🎨", "Coleccionaba pinturas de paisajes lejanos"]], 0, "Pista: leé la primera escena sobre la obsesión del monarca."),
    L("¿Qué afirmaban los dos tramposos sobre la tela mágica que decían tejer?", [["🧵", "Que solo la podían ver las personas inteligentes"], ["✨", "Que brillaba en la oscuridad de la noche"], ["🛡️", "Que protegía de cualquier arma o golpe"]], 0, "Pista: revisá el engaño de los tejedores en la escena 2."),
    S("¿Qué hicieron todos los ministros y cortesanos al mirar los telares vacíos?", [["🗣️", "Fingieron ver una tela hermosa para no pasar por tontos"], ["😠", "Echaron a los dos tramposos del palacio de inmediato"], ["🤫", "Le dijeron la verdad al emperador en secreto"], ["🧵", "Se pusieron a ayudar a tejer con hilos de lana"]], 0, "Pista: mirá cómo reaccionaban todos por vergüenza en la escena 3."),
    S("¿Qué suceso inesperado ocurrió durante el gran desfile por la ciudad?", [["👦", "Un nene gritó con inocencia que el emperador estaba en calzoncillos"], ["🌧️", "Comenzó a llover y la supuesta tela se destiñó"], ["👑", "El emperador se tropezó con su capa invisible"]], 0, "Pista: leé la valiente exclamación infantil en la escena 5."),
    I("¿Por qué el emperador no admitió desde el principio que no veía ninguna tela?", [["😳", "Por vanidad y miedo a que pensaran que era un tonto o incapaz"], ["🧵", "Porque estaba seguro de que la tela existía de verdad"], ["🪙", "Porque ya les había pagado muchas monedas a los tejedores"], ["😴", "Porque tenía sueño y no quería discutir con nadie"]], 0, "Pista: pensá en lo que creían sobre quienes no podían ver la tela."),
    I("¿Por qué fue un niño y no un adulto quien dijo la verdad en voz alta?", [["👶", "Porque los niños son espontáneos y dicen lo que ven sin temer el qué dirán"], ["🗣️", "Porque el niño quería burlarse del emperador a propósito"], ["👦", "Porque era el único que no sabía que el rey desfilaba"]], 0, "Pista: reflexioná sobre la sinceridad de los chicos frente a las apariencias."),
    V("En la escena 3 se menciona que hacían como que tejían en «telares». ¿Qué son «telares»?", [["🧵", "Máquinas o armazones de madera utilizados para tejer telas con hilos"], ["🪡", "Tijeras especiales para cortar géneros finos"], ["📦", "Cajas de cartón donde se guardan vestidos"], ["🪞", "Espejos de cuerpo entero para probarse trajes"]], 0, "Pista: pensá en el instrumento tradicional donde se teje la tela."),
    E("¿Qué lección social y ética contiene este cuento de Andersen?", [["💡", "Muestra que es mejor decir la verdad que aparentar por miedo a la opinión ajena"], ["👑", "Enseña que los reyes deben vestirse siempre con capas doradas"], ["🧵", "Explica el método tradicional para hilar seda natural"]], 0, "Pista: el desenlace deja al descubierto la falsedad de las apariencias."),
  ],

  // 14. El Cerro de los Siete Colores (leyenda)
  "leyenda-siete-colores": [
    L("¿De qué color eran originalmente los cerros de Purmamarca según la leyenda?", [["⛰️", "Eran todos grises y marrones"], ["🌈", "Tenían rayas amarillas y rojas"], ["⚪", "Eran blancos por la sal de las salinas"], ["🟢", "Estaban cubiertos de pasto verde brillante"]], 0, "Pista: mirá cómo era el paisaje inicial en la primera escena."),
    L("¿Quiénes idearon el plan secreto para transformar el cerro?", [["👧", "Los chicos del pueblo de Purmamarca"], ["👵", "Los ancianos sabios de la comunidad"], ["🎨", "Un grupo de pintores que llegó de viaje"]], 0, "Pista: revisá quiénes se aburrían del mismo color en la escena 2."),
    S("¿Cómo llevaron a cabo los chicos su misterioso trabajo de pintura?", [["🎨", "Salieron calladitos de noche durante siete noches, pintando un color cada vez"], ["☀️", "Pintaron todos los colores juntos en una sola tarde de sol"], ["🌧️", "Esperaron a que lloviera para mezclar las témperas con barro"], ["🤫", "Le pidieron ayuda a sus padres después de cenar"]], 0, "Pista: leé cómo se organizaron en las escenas 3 y 4."),
    S("¿Qué descubrieron los habitantes del pueblo la mañana del octavo día?", [["🌄", "El cerro resplandecía repleto de franjas de colores hermosos"], ["🎨", "Todos los pinceles tirados en la plaza mayor"], ["🌧️", "Que una tormenta había borrado la pintura"]], 0, "Pista: mirá la gran sorpresa de la comunidad en la escena 5."),
    I("¿Por qué los chicos realizaban su tarea a escondidas en medio de la noche?", [["🤫", "Para que fuera una sorpresa mágica y nadie les impidiera hacerlo"], ["😨", "Porque les daba vergüenza pintar a la luz del día"], ["🎨", "Porque las pinturas brillaban únicamente en la oscuridad"], ["😴", "Porque de día tenían que ayudar en los telares"]], 0, "Pista: pensá en por qué el plan era un secreto de los niños."),
    I("¿Qué representa hoy en día el cerro para la gente del pueblo y los visitantes?", [["🎁", "Un regalo inolvidable de alegría y color dejado por la niñez del lugar"], ["⛰️", "Un lugar sagrado donde está prohibido caminar"], ["🎨", "Una escuela de pintura al aire libre"]], 0, "Pista: revisá la última frase sobre el legado de los chicos."),
    V("En la escena 3 dice que salieron «calladitos». ¿Qué significa «calladitos»?", [["🤫", "En absoluto silencio, con mucho cuidado para no despertar a nadie"], ["🏃", "Corriendo a toda velocidad por las calles"], ["🎵", "Cantando canciones en voz muy baja"], ["🔦", "Con linternas encendidas en la mano"]], 0, "Pista: pensá en cómo debían salir mientras los grandes dormían."),
    E("¿Qué explica poéticamente esta leyenda del norte argentino?", [["⛰️", "La asombrosa variedad de colores que caracterizan al Cerro de los Siete Colores"], ["🎨", "Cómo se inventaron los pinceles de madera en Jujuy"], ["☀️", "Por qué sale el sol temprano en los pueblos de la quebrada"]], 0, "Pista: las leyendas recrean de manera fantástica los paisajes naturales."),
  ],

  // 15. El ratón de campo y el ratón de ciudad (fábula)
  "raton-campo-ciudad": [
    L("¿Qué comida sencilla le ofreció el ratón de campo a su primo cuando lo visitó?", [["🌾", "Granos, raíces y agua fresca"], ["🧀", "Quesos maduros, panes y tortas"], ["🍎", "Manzanas asadas con canela"], ["🌽", "Choclos recién cosechados del huerto"]], 0, "Pista: leé el menú modesto de la segunda escena."),
    L("¿Dónde vivía el ratón de campo en su entorno natural?", [["🌾", "En una cueva tranquila junto al trigal"], ["🌳", "En el hueco de un árbol añoso"], ["🏠", "Debajo del piso de madera de una granja"]], 0, "Pista: mirá la primera escena sobre su hogar."),
    S("¿Qué peligro apareció de repente mientras disfrutaban del banquete en la ciudad?", [["🐱", "Apareció un gato y tuvieron que esconderse en un agujero"], ["🧹", "Un perro guardián empezó a ladrar con fuerza"], ["🧀", "Se acabó la comida de la mesa antes de empezar"], ["🐭", "El ratón de campo se desmayó por el susto"]], 0, "Pista: leé la cuarta escena sobre el primer susto urbano."),
    S("¿Qué nuevo sobresalto vivieron justo cuando intentaban volver a la mesa?", [["🧹", "Entraron personas haciendo mucho ruido con escobas"], ["🐱", "El gato volvió con otros dos felinos"], ["🚪", "Cerraron la puerta con llave y no podían salir"]], 0, "Pista: revisá la quinta escena sobre el segundo peligro."),
    I("¿Por qué el ratón de ciudad despreció al principio la comida de su primo?", [["🧀", "Porque estaba acostumbrado a los manjares y banquetes de la gran casa"], ["😋", "Porque tenía poca hambre esa tarde"], ["🌾", "Porque no le gustaban las raíces ni los granos"], ["💧", "Porque el agua fresca del campo le parecía fría"]], 0, "Pista: fijate en la comparación que hace en la escena 2."),
    I("¿Por qué el ratón de campo decidió regresar a su cueva sin dudarlo?", [["😌", "Porque comprendió que la paz y la tranquilidad valen más que el lujo con peligro"], ["🏃", "Porque extrañaba cosechar trigo bajo el sol"], ["🐱", "Porque el gato lo dejó lastimado"]], 0, "Pista: leé la sabia conclusión del ratón de campo en la escena 6."),
    V("En la escena 1 se nombra el «trigal». ¿Qué es un «trigal»?", [["🌾", "Un terreno o campo sembrado de trigo"], ["🪵", "Un montón de leña apilada en el bosque"], ["🥖", "Una panadería donde hornean panes"], ["🏡", "Un corral cerrado para animales del campo"]], 0, "Pista: pensá en las espigas de las que se alimentaba el ratón campestre."),
    E("¿Cuál es la moraleja central de esta fábula de Esopo?", [["💡", "Más vale una vida simple y en paz que una vida de riquezas llena de miedos"], ["🧀", "Los ratones nunca deben comer quesos ni tortas"], ["🐱", "Hay que aprender a pelear contra los gatos de la ciudad"]], 0, "Pista: la enseñanza contrapone la serenidad a la intranquilidad."),
  ],

  // 16. Las medias de los flamencos (cuento)
  "medias-flamencos": [
    L("¿De qué color eran originalmente las patas de los flamencos al principio del cuento?", [["⚪", "Blancas"], ["🔴", "Coloradas"], ["🟡", "Amarillas"], ["🖤", "Negras"]], 0, "Pista: leé cómo eran sus patas en la segunda escena."),
    L("¿Quién fue el animal bromista que les entregó las supuestas medias a los flamencos?", [["🦔", "Un tatú"], ["🦊", "Un zorro"], ["🦉", "Una lechuza"]], 0, "Pista: buscá qué personaje les dio los cueros en la escena 3."),
    S("¿Qué eran en realidad las llamativas medias rayadas que lucían los flamencos?", [["🐍", "Eran cueros de víboras de coral"], ["🧶", "Eran medias tejidas con lana suave"], ["🎨", "Eran plumas pintadas con rayas de colores"], ["🧵", "Eran telas finas compradas en el almacén"]], 0, "Pista: mirá la revelación impactante en la escena 3."),
    S("¿Qué hicieron las víboras de coral cuando descubrieron el engaño en el baile?", [["🐍", "Se enfurecieron y les mordieron las patas con veneno"], ["🌊", "Se tiraron al agua del río a nadar"], ["🎉", "Siguieron bailando sin darles importancia"]], 0, "Pista: revisá la venganza de las víboras en la escena 5."),
    I("¿Por qué los flamencos estaban tan desesperados por conseguir medias elegantes?", [["🦩", "Por vanidad, para verse tan hermosos y distinguidos como las víboras en la fiesta"], ["❄️", "Porque sentían mucho frío en las patas dentro del río"], ["💃", "Porque el reglamento del baile obligaba a usar calzado"], ["🐍", "Porque querían asustar a los peces de la orilla"]], 0, "Pista: fijate qué querían demostrar al asistir al baile en la escena 2."),
    I("Según el cuento, ¿por qué los flamencos se pasan hoy todo el día parados en el agua?", [["💧", "Para refrescar sus patas coloradas y calmar el ardor de las mordeduras"], ["🐟", "Para aprender a pescar sin moverse del lugar"], ["😴", "Para dormir la siesta sin que nadie los moleste"]], 0, "Pista: leé la explicación final en la última escena."),
    V("En la escena 6 se menciona que buscan calmar el «ardor». ¿Qué significa «ardor»?", [["🔥", "Una sensación intensa de calor, quemazón o dolor en la piel"], ["❄️", "Una sensación de frío helado y cosquilleo"], ["💧", "La humedad de las gotas de agua sobre las plumas"], ["🩸", "El cansancio en los músculos por bailar tanto"]], 0, "Pista: pensá en lo que se siente tras una picadura o mordedura irritante."),
    E("¿Quién es el autor de este célebre cuento de la literatura rioplatense?", [["📖", "Horacio Quiroga, en su libro 'Cuentos de la selva'"], ["📜", "Esopo, en sus fábulas clásicas de animales"], ["🦢", "Hans Christian Andersen, en sus relatos infantiles"]], 0, "Pista: revisá el origen del relato al inicio del texto."),
  ],

  // 17. La leyenda de Elal (leyenda)
  "leyenda-elal": [
    L("¿Qué animal trasladó a Elal sobre su espalda para ponerlo a salvo en la Patagonia?", [["🦢", "Un cisne de cuello negro"], ["🦅", "Un cóndor andino gigante"], ["🦩", "Un flamenco de alas rosadas"], ["🐋", "Una ballena que nadaba por el mar"]], 0, "Pista: leé la segunda escena sobre el viaje del niño."),
    L("¿A la cima de qué famoso cerro patagónico llegó Elal en su arribo?", [["🏔️", "Al cerro Chaltén"], ["⛰️", "Al cerro de los Siete Colores"], ["🌋", "Al volcán Lanín"]], 0, "Pista: buscá el nombre de la montaña en la tercera escena."),
    S("¿Cómo consiguió Elal regalarles el fuego a los primeros habitantes?", [["🔥", "Golpeó dos piedras entre sí, saltaron chispas y encendió el fuego"], ["⚡", "Atrapó un rayo que cayó de una tormenta"], ["☀️", "Subió a la cima a tomar un pedacito de sol"], ["🪵", "Frotó dos ramas secas de árbol durante horas"]], 0, "Pista: mirá qué herramientas de la naturaleza utilizó en la escena 4."),
    S("¿Qué enseñó Elal a los tehuelches para que pudieran vivir y alimentarse?", [["🏹", "A hacer arcos y flechas, cazar guanacos y coser quillangos"], ["🌾", "A sembrar trigo y cocinar panes en hornos"], ["🛶", "A construir canoas grandes para navegar los ríos"]], 0, "Pista: leé la quinta escena sobre las enseñanzas prácticas."),
    I("¿Por qué dicen los tehuelches que el cerro Chaltén casi siempre tiene una nube en la punta?", [["🏔️", "Como recuerdo del humo del primer fuego sagrado que encendió Elal"], ["❄️", "Porque es el cerro más helado de la cordillera"], ["🌧️", "Porque anuncia que se avecina una gran nevada"], ["🦢", "Porque el cisne blanco duerme en la cumbre"]], 0, "Pista: fijate en la relación entre el humo y la nube en la escena 3."),
    I("¿Hacia dónde partió Elal cuando concluyó su labor civilizadora?", [["🌅", "Hacia el este, donde sale el sol, desde donde sigue cuidando la región"], ["🏔️", "Hacia el fondo de las cavernas heladas del Chaltén"], ["🌊", "A vivir en una isla lejana en el medio del mar"]], 0, "Pista: revisá la última escena sobre su despedida en el cisne."),
    V("En la escena 5 se nombran los «quillangos». ¿Qué son los «quillangos»?", [["🧥", "Mantas o capas abrigadas confeccionadas con cueros de guanaco"], ["🏹", "Puntas de flecha talladas en pedernal"], ["🏕️", "Toldos de ramas donde dormían los cazadores"], ["🪢", "Cuerdas trenzadas con tendones de animales"]], 0, "Pista: fijate en el texto: 'coser quillangos para abrigarse'."),
    E("¿Qué tipo de personaje es Elal en la mitología aonikenk?", [["✨", "El héroe protector que enseñó al pueblo a sobrevivir en la Patagonia"], ["👑", "Un cacique guerrero que venció a pueblos vecinos"], ["🐦", "Un pájaro mágico que se convirtió en ser humano"]], 0, "Pista: pensá en todas las enseñanzas y dones que brindó a los tehuelches."),
  ],

  // 18. La gallina de los huevos de oro (fábula)
  "gallina-huevos-oro": [
    L("¿Qué ponía la gallina todas las mañanas en la granja?", [["🥚", "Un huevo de oro"], ["🪙", "Monedas de plata relucientes"], ["🌾", "Granos de maíz dorado"], ["🪶", "Plumas que brillaban como joyas"]], 0, "Pista: leé la primera escena sobre el prodigio de la gallina."),
    L("¿Qué consiguieron el granjero y su esposa vendiendo los huevos en el pueblo?", [["🏡", "Tuvieron una casa linda y todo lo que necesitaban"], ["🏰", "Se construyeron un castillo con murallas"], ["⛵", "Compraron un barco para viajar por el mundo"]], 0, "Pista: mirá las mejoras en su vida en la segunda escena."),
    S("¿Qué actitud impaciente y codiciosa adoptó el granjero al poco tiempo?", [["😡", "Quiso más huevos de golpe, la despertaba de noche y no la dejaba descansar"], ["🤝", "Le construyó un gallinero más grande y cómodo"], ["🌾", "Le dio el doble de comida para que estuviera contenta"], ["😴", "Se fue a descansar confiando en su rutina diaria"]], 0, "Pista: revisá las acciones del granjero en la cuarta escena."),
    S("¿Qué hizo la gallina al sentirse tan cansada y asustada por las exigencias?", [["🌲", "Se escapó del gallinero y se fue lejos al bosque"], ["🥚", "Puso cinco huevos juntos para complacerlo"], ["😴", "Se quedó a vivir adentro de la cocina"]], 0, "Pista: buscá la reacción del animal en la quinta escena."),
    I("¿Por qué el granjero no estaba satisfecho con recibir un huevo de oro cada día?", [["🤑", "Por ambición desmedida y codicia, deseaba hacerse rico de inmediato"], ["🥚", "Porque los huevos eran demasiado pequeños para venderlos"], ["🏡", "Porque la comida en el pueblo era cada vez más cara"], ["🐔", "Porque prefería tener gallinas que pusieran huevos comunes"]], 0, "Pista: fijate en su queja en la tercera escena: '¡Un huevo por día es muy poco!'."),
    I("¿Qué consecuencia final sufrió el granjero por su impaciencia?", [["😔", "Perdió la gallina y se quedó sin los valiosos huevos que ya tenía seguros"], ["🎉", "Logró encontrar el nido secreto en medio del bosque"], ["🤝", "Su esposa le regaló otra gallina igual"]], 0, "Pista: mirá lo que reflexiona el granjero en la última escena."),
    V("En la primera escena se presenta al «granjero». ¿A qué se dedica un «granjero»?", [["🚜", "A cuidar animales, cultivar la tierra y trabajar en el campo"], ["🏪", "A vender telas y ropas finas en la ciudad"], ["⛵", "A navegar por los mares en busca de peces"], ["🔨", "A construir casas de ladrillos en los pueblos"]], 0, "Pista: pensá en las tareas que se realizan en una granja."),
    E("¿Cuál es la moraleja que nos transmite esta fábula?", [["💡", "Quien por codicia quiere todo de golpe, corre el riesgo de perder lo que tiene"], ["🐔", "Las gallinas deben dormir en los árboles del bosque"], ["🪙", "El oro es el único tesoro que vale la pena buscar"]], 0, "Pista: pensá en la advertencia sobre querer apresurar las cosas por avaricia."),
  ],

  // 19. La tortuga gigante (cuento)
  "tortuga-gigante": [
    L("¿Por qué motivo el hombre de Buenos Aires tuvo que viajar a vivir al monte?", [["🩺", "Porque estaba muy enfermo y el médico le recomendó aire libre"], ["🏕️", "Porque le gustaba acampar en lugares salvajes"], ["🐢", "Porque quería cazar una tortuga para su colección"], ["🪵", "Porque trabajaba como leñador en la selva"]], 0, "Pista: leé el consejo médico en la primera escena."),
    L("¿Qué buena acción hizo el hombre cuando encontró a la tortuga lastimada?", [["🩹", "La llevó a su refugio y la curó con paciencia"], ["🌊", "La llevó a nadar al río más cercano"], ["🍎", "Le dejó comida y siguió su camino solo"]], 0, "Pista: mirá el cuidado del hombre en la segunda escena."),
    S("¿Qué hizo la tortuga cuando el hombre cayó enfermo con mucha fiebre?", [["🍎", "Lo cuidó, le trajo agua fresca y frutas para ayudarlo"], ["🏃", "Se escapó al monte por temor a enfermarse"], ["🩺", "Fue a buscar al médico a la orilla del río"], ["😴", "Se acostó a dormir debajo de su caparazón"]], 0, "Pista: revisá cómo la tortuga devolvió el favor en la tercera escena."),
    S("¿Cómo logró la tortuga trasladar a su amigo hasta la ciudad de Buenos Aires?", [["🐢", "Lo cargó sobre su caparazón y caminó días y noches sin rendirse"], ["🛶", "Construyó una balsa de troncos y remó por el río"], ["🚂", "Lo subió a un vagón de tren en la estación"]], 0, "Pista: mirá el increíble esfuerzo de la tortuga en la quinta escena."),
    I("¿Por qué la tortuga decidió emprender un viaje tan largo y agotador hacia la ciudad?", [["❤️", "Porque comprendió que en el monte su amigo no se curaría y moriría sin auxilio"], ["🏙️", "Porque tenía ganas de conocer los edificios de Buenos Aires"], ["🐢", "Porque quería ir a vivir tranquila en el zoológico"], ["🩺", "Porque ella misma necesitaba atención médica urgente"]], 0, "Pista: leé el pensamiento de la tortuga en la cuarta escena."),
    I("¿Cómo continuó la relación entre ambos amigos al final de la historia?", [["🤝", "El hombre la visitaba todos los días en el zoológico con inmenso cariño"], ["🚶", "El hombre volvió a vivir al monte y nunca más la vio"], ["🐢", "La tortuga regresó caminando a su hogar en la selva"]], 0, "Pista: revisá la última oración del cuento."),
    V("En la escena 2 dice que la llevó a su «refugio». ¿Qué es un «refugio»?", [["🏠", "Un lugar seguro que brinda protección y cobijo frente al peligro o el clima"], ["🌲", "Un árbol muy alto con ramas secas"], ["🕳️", "Un pozo profundo en el fondo del río"], ["🛤️", "Un camino largo que cruza el campo"]], 0, "Pista: pensá en el lugar donde el hombre descansaba protegido en el monte."),
    E("¿A qué libro y autor pertenece esta conmovedora historia?", [["📖", "A 'Cuentos de la selva', del escritor rioplatense Horacio Quiroga"], ["📜", "A las fábulas clásicas del escritor griego Esopo"], ["🦢", "A los relatos nórdicos de Hans Christian Andersen"]], 0, "Pista: consultá los datos bibliográficos al inicio del relato."),
  ],
};
