// Preguntas de comprensión auditiva de 1.º grado: 7 por cuento, 3 opciones
// con emoji, de tipo literal, secuencia e inferencial (incluye la
// enseñanza). La opción correcta es la de `answer` (se mezclan al jugar).
import type { ComprehensionKind, CuentoOpt, CuentoQuestion } from "./tipos";

const q = (kind: ComprehensionKind) => (text: string, options: CuentoOpt[], answer: number, hint: string): CuentoQuestion => ({ q: text, kind, options, answer, hint });
const L = q("literal");
const S = q("secuencia");
const I = q("inferencial");

export const PREGUNTAS_G1: Record<string, CuentoQuestion[]> = {
  "liebre-tortuga": [
      L("¿Quiénes corrieron la carrera?", [["🐇🐢", "La liebre y la tortuga"], ["🐶🐱", "El perro y el gato"], ["🦊🐻", "El zorro y el oso"]], 0, "Pista: pensá en el título del cuento."),
      L("¿Cómo era la liebre?", [["⚡", "Muy rápida"], ["🐌", "Muy lenta"], ["😴", "Muy dormilona desde el principio"]], 0, "Pista: salió corriendo a toda velocidad."),
      S("¿Qué hizo la liebre en el medio de la carrera?", [["😴", "Se quedó dormida"], ["🍎", "Comió una manzana"], ["🏊", "Se fue a nadar"]], 0, "Pista: se acostó debajo de un árbol."),
      L("¿Cómo caminaba la tortuga?", [["🐢", "Despacito, sin parar"], ["🏃", "Muy rápido"], ["🦘", "A los saltos"]], 0, "Pista: paso a paso…"),
      S("¿Qué pasó al final?", [["🏆", "Ganó la tortuga"], ["🐇", "Ganó la liebre"], ["🤝", "Empataron"]], 0, "Pista: cuando la liebre se despertó, ya era tarde."),
      I("¿Por qué perdió la liebre?", [["💤", "Porque se confió y se durmió"], ["🦵", "Porque se lastimó"], ["🌧️", "Porque llovió"]], 0, "Pista: pensó que tenía tiempo de sobra."),
      I("¿Qué nos enseña el cuento?", [["👣", "Que con esfuerzo y constancia se llega"], ["😂", "Que hay que reírse de los demás"], ["🛌", "Que hay que dormir mucho"]], 0, "Pista: la tortuga no se detuvo nunca."),
  ],
  "leon-raton": [
      L("¿Qué hacía el león al principio?", [["😴", "Dormía la siesta"], ["🍖", "Comía"], ["🏃", "Corría"]], 0, "Pista: el ratón le pasó por arriba mientras…"),
      L("¿Por qué se despertó el león?", [["🐭", "Porque el ratón le pasó por la nariz"], ["⏰", "Porque sonó un reloj"], ["🌧️", "Porque empezó a llover"]], 0, "Pista: el ratoncito jugaba por ahí."),
      S("¿Qué le prometió el ratón al león?", [["🤝", "Que algún día lo iba a ayudar"], ["🧀", "Que le iba a dar queso"], ["🎵", "Que le iba a cantar"]], 0, "Pista: —Algún día yo te voy a…"),
      L("¿Dónde quedó atrapado el león?", [["🕸️", "En una red"], ["🕳️", "En un pozo"], ["🏠", "En una casa"]], 0, "Pista: la pusieron unos cazadores."),
      S("¿Cómo lo ayudó el ratón?", [["🦷", "Mordió la red"], ["🔑", "Usó una llave"], ["📣", "Llamó a otros leones"]], 0, "Pista: usó sus dientitos."),
      I("¿Por qué el león se rió cuando el ratón le prometió ayudarlo?", [["🐭", "Porque pensó que alguien tan chiquito no podía ayudarlo"], ["😂", "Porque el ratón le contó un chiste"], ["🎉", "Porque era su cumpleaños"]], 0, "Pista: el león es enorme y el ratón muy pequeño."),
      I("¿Qué nos enseña el cuento?", [["💛", "Que todos, grandes o chicos, podemos ayudar"], ["😠", "Que hay que enojarse"], ["💤", "Que hay que dormir la siesta"]], 0, "Pista: el más chiquito salvó al más grande."),
  ],
  "tres-chanchitos": [
      L("¿Cuántos chanchitos había?", [["3️⃣", "Tres"], ["2️⃣", "Dos"], ["5️⃣", "Cinco"]], 0, "Pista: está en el título."),
      L("¿De qué era la casa del primer chanchito?", [["🌾", "De paja"], ["🧱", "De ladrillos"], ["🪵", "De madera"]], 0, "Pista: la hizo muy rápido para ir a jugar."),
      L("¿De qué era la casa más fuerte?", [["🧱", "De ladrillos"], ["🌾", "De paja"], ["🧊", "De hielo"]], 0, "Pista: el lobo no la pudo voltear."),
      S("¿Qué hizo el lobo con las casas?", [["🌬️", "Sopló para tirarlas"], ["🎨", "Las pintó"], ["🔨", "Las arregló"]], 0, "Pista: sopló y sopló…"),
      S("¿A dónde corrieron los chanchitos cuando el lobo voló sus casas?", [["🧱", "A la casa de ladrillos"], ["🌳", "Al bosque"], ["🏫", "A la escuela"]], 0, "Pista: era la casa del tercer hermano."),
      I("¿Por qué la casa de ladrillos no se cayó?", [["💪", "Porque estaba bien construida"], ["🍀", "Porque tuvo suerte"], ["🔒", "Porque tenía llave"]], 0, "Pista: el tercer chanchito trabajó mucho."),
      I("¿Cómo se sintieron los chanchitos al final?", [["🤗", "Contentos y a salvo"], ["😢", "Tristes"], ["😡", "Enojados"]], 0, "Pista: se abrazaron."),
  ],
  "ricitos-osos": [
      L("¿Cuántos osos vivían en la casita?", [["3️⃣", "Tres"], ["1️⃣", "Uno"], ["4️⃣", "Cuatro"]], 0, "Pista: papá, mamá y…"),
      L("¿Cómo era el pelo de la nena?", [["👱‍♀️", "Rubio, con rulos"], ["👩‍🦰", "Colorado"], ["👩", "Negro y lacio"]], 0, "Pista: se llamaba Ricitos de Oro."),
      L("¿Qué sopa le gustó a Ricitos de Oro?", [["🧸", "La del osito"], ["🐻", "La de papá oso"], ["🍲", "Ninguna"]], 0, "Pista: estaba justo como le gustaba."),
      S("¿Qué pasó con la sillita del osito?", [["💥", "Se rompió"], ["🎨", "La pintó"], ["🚪", "La sacó afuera"]], 0, "Pista: el osito lloró por su silla."),
      S("¿Dónde encontraron los osos a Ricitos de Oro?", [["🛏️", "Durmiendo en la camita"], ["🍳", "En la cocina"], ["🌳", "En el bosque"]], 0, "Pista: subieron a la habitación."),
      I("¿Qué hizo mal Ricitos de Oro?", [["🚪", "Entró a una casa sin permiso"], ["🧹", "Barrió la casa"], ["🎁", "Les llevó un regalo"]], 0, "Pista: la puerta estaba abierta, pero no era su casa."),
      I("¿Cómo se sintió el osito al volver?", [["😢", "Triste porque le tomaron la sopa y le rompieron la silla"], ["😄", "Feliz"], ["😴", "Con sueño"]], 0, "Pista: lloraba."),
  ],
  "gallinita-roja": [
      L("¿Qué encontró la gallinita?", [["🌾", "Granos de trigo"], ["🥚", "Un huevo"], ["🪙", "Una moneda"]], 0, "Pista: los sembró en la tierra."),
      L("¿Quiénes no quisieron ayudar?", [["🦆🐱🐷", "El pato, el gato y el chancho"], ["🐶🐄🐴", "El perro, la vaca y el caballo"], ["🐔🐣", "Los pollitos"]], 0, "Pista: siempre decían «Yo no»."),
      S("¿Qué hizo primero la gallinita con el trigo?", [["🌱", "Lo sembró"], ["🍞", "Hizo pan"], ["✂️", "Lo cortó"]], 0, "Pista: el trigo tuvo que crecer."),
      S("¿Qué hizo con la harina?", [["🍞", "Amasó un pan"], ["🎂", "Hizo una torta de cumpleaños"], ["🗑️", "La tiró"]], 0, "Pista: un pan riquísimo."),
      L("¿Cuándo quisieron ayudar los tres amigos?", [["😋", "Cuando había que comer el pan"], ["🌱", "Cuando había que sembrar"], ["✂️", "Cuando había que cortar"]], 0, "Pista: gritaron «¡Yo, yo, yo!»."),
      I("¿Por qué la gallinita no les convidó pan?", [["🙅", "Porque no la ayudaron a hacerlo"], ["🤢", "Porque el pan estaba feo"], ["😴", "Porque estaban dormidos"]], 0, "Pista: hizo todo el trabajo sola."),
      I("¿Qué nos enseña el cuento?", [["🤝", "Que es importante ayudar y trabajar juntos"], ["🍞", "Que el pan es rico"], ["🐔", "Que las gallinas son rojas"]], 0, "Pista: los amigos solo querían comer."),
  ],
  "caperucita": [
      L("¿De qué color era la capa de Caperucita?", [["🔴", "Roja"], ["🔵", "Azul"], ["🟢", "Verde"]], 0, "Pista: está en su nombre."),
      L("¿A quién le llevaba la canasta?", [["👵", "A su abuela"], ["👨‍🏫", "A su maestro"], ["🐺", "Al lobo"]], 0, "Pista: estaba enferma."),
      L("¿Qué le dijo la mamá antes de salir?", [["🛤️", "Que no se saliera del camino"], ["🌸", "Que juntara flores"], ["🏃", "Que corriera rápido"]], 0, "Pista: —No te salgas del…"),
      S("¿Qué hizo el lobo mientras Caperucita juntaba flores?", [["🏃", "Corrió a la casa de la abuela"], ["😴", "Se durmió"], ["🍰", "Comió una torta"]], 0, "Pista: tomó un atajo."),
      S("¿Quién ayudó a Caperucita?", [["🪓", "Un leñador"], ["🐶", "Un perro"], ["👮", "Un policía"]], 0, "Pista: la escuchó gritar."),
      I("¿Por qué el lobo le dijo que juntara flores?", [["⏳", "Para llegar antes a la casa de la abuela"], ["💐", "Porque le gustaban las flores"], ["🎁", "Para hacerle un regalo"]], 0, "Pista: mientras ella se entretenía, él corría."),
      I("¿Qué aprendió Caperucita?", [["🙅", "A no hablar con desconocidos"], ["🌸", "A juntar flores"], ["🧺", "A llevar canastas"]], 0, "Pista: lo prometió al final."),
  ],
  "patito-feo": [
      L("¿De qué color era el patito distinto?", [["🩶", "Gris"], ["💛", "Amarillo"], ["❤️", "Rojo"]], 0, "Pista: los demás eran amarillos."),
      L("¿Qué le decían los otros animales?", [["😝", "Que era feo"], ["😍", "Que era lindo"], ["🏆", "Que era el mejor"]], 0, "Pista: se burlaban de él."),
      S("¿Qué hizo el patito porque estaba triste?", [["🚶", "Se fue del corral"], ["🎉", "Hizo una fiesta"], ["🍞", "Comió pan"]], 0, "Pista: caminó solo por el campo."),
      S("¿Qué estación pasó escondido entre los juncos?", [["❄️", "El invierno"], ["☀️", "El verano"], ["🌸", "La primavera"]], 0, "Pista: hacía mucho frío."),
      L("¿En qué se convirtió el patito?", [["🦢", "En un cisne"], ["🦆", "En un pato grande"], ["🐔", "En una gallina"]], 0, "Pista: un ave blanca y hermosa."),
      I("¿Cómo se sentía el patito cuando se burlaban?", [["😢", "Triste"], ["😄", "Contento"], ["😴", "Con sueño"]], 0, "Pista: nadie quería jugar con él."),
      I("¿Qué nos enseña el cuento?", [["💛", "Que no hay que burlarse de quien es distinto"], ["🦆", "Que los patos son amarillos"], ["❄️", "Que el invierno es frío"]], 0, "Pista: el patito «feo» era especial."),
  ],
  "raton-campo-ciudad": [
      L("¿Dónde vivía el ratón de campo?", [["🌾", "En una cueva junto al trigal"], ["🏙️", "En un edificio"], ["⛵", "En un barco"]], 0, "Pista: en el campo."),
      L("¿Qué comida le sirvió el ratón de campo a su primo?", [["🌾", "Granos, raíces y agua"], ["🧀", "Quesos y tortas"], ["🍕", "Pizza"]], 0, "Pista: era una comida simple."),
      L("¿Qué había en la mesa de la ciudad?", [["🧀🍰", "Quesos, panes y tortas"], ["🌾", "Solo granos"], ["🥕", "Zanahorias"]], 0, "Pista: ¡cuánta comida!"),
      S("¿Qué pasó cuando empezaron a comer en la ciudad?", [["🐈", "Apareció el gato"], ["🎉", "Empezó una fiesta"], ["🌧️", "Llovió"]], 0, "Pista: tuvieron que esconderse en un agujero."),
      S("¿Qué hizo al final el ratón de campo?", [["🏡", "Volvió feliz a su campo"], ["🏙️", "Se quedó a vivir en la ciudad"], ["🐈", "Se hizo amigo del gato"]], 0, "Pista: prefería su vida tranquila."),
      I("¿Por qué prefirió el campo?", [["😌", "Porque allá vivía tranquilo y sin sustos"], ["🧀", "Porque había más queso"], ["🚗", "Porque había autos"]], 0, "Pista: en la ciudad tenía miedo todo el tiempo."),
      I("¿Cómo se sintió el ratón de campo en la ciudad?", [["😨", "Asustado"], ["😴", "Aburrido"], ["😎", "Muy tranquilo"]], 0, "Pista: el gato, las escobas…"),
  ],
  "leyenda-calafate": [
      L("¿Dónde pasa esta leyenda?", [["🏔️", "En la Patagonia"], ["🏝️", "En una isla tropical"], ["🏙️", "En una gran ciudad"]], 0, "Pista: en la meseta, con mucho viento."),
      L("¿Cómo se llamaba la abuela?", [["👵", "Koonek"], ["👧", "Caperucita"], ["🧓", "Ricitos"]], 0, "Pista: un nombre tehuelche."),
      S("¿Por qué se quedó sola Koonek?", [["🚶", "Porque su pueblo se fue y ella ya no podía caminar tanto"], ["😠", "Porque estaba enojada"], ["🏠", "Porque tenía casa nueva"]], 0, "Pista: era muy anciana."),
      S("¿En qué se convirtió Koonek?", [["🌿", "En un arbusto de calafate"], ["🦅", "En un cóndor"], ["⭐", "En una estrella"]], 0, "Pista: un arbusto con espinas."),
      L("¿De qué color son los frutos del calafate?", [["🟣", "Violetas"], ["🔴", "Rojos"], ["🟠", "Naranjas"]], 0, "Pista: son frutos dulces de verano."),
      I("¿Qué dice la leyenda que le pasa a quien come calafate?", [["🔁", "Que siempre vuelve a la Patagonia"], ["💤", "Que se duerme"], ["🦸", "Que vuela"]], 0, "Pista: escuchá el final."),
      I("¿Cómo se habrá sentido Koonek cuando su pueblo se fue?", [["😢", "Sola y triste"], ["🎉", "Con ganas de festejar"], ["😡", "Enojada con las aves"]], 0, "Pista: se quedó sola en el invierno."),
  ],
  "zorro-cuervo": [
      L("¿Qué tenía el cuervo en el pico?", [["🧀", "Un pedazo de queso"], ["🍎", "Una manzana"], ["🪱", "Un gusano"]], 0, "Pista: el zorro lo olió."),
      L("¿Dónde se subió el cuervo?", [["🌳", "A la rama más alta de un árbol"], ["🏠", "Al techo de una casa"], ["⛰️", "A una montaña"]], 0, "Pista: quería comer tranquilo, bien arriba."),
      S("¿Qué le pidió el zorro al cuervo?", [["🎵", "Que cantara una canción"], ["🧀", "Que le diera la mitad"], ["🏃", "Que bajara a jugar"]], 0, "Pista: le dijo que su voz debía ser linda."),
      S("¿Qué pasó cuando el cuervo abrió el pico?", [["⬇️", "Se le cayó el queso"], ["🎶", "Cantó muy lindo"], ["🦊", "Se fue el zorro"]], 0, "Pista: el zorro lo atrapó en el aire."),
      I("¿Por qué el zorro le decía cosas lindas al cuervo?", [["🧀", "Porque quería quedarse con el queso"], ["💛", "Porque eran amigos"], ["🎤", "Porque le gustaba cantar"]], 0, "Pista: pensó «ese queso va a ser mío»."),
      I("¿Cómo se sintió el cuervo cuando el zorro lo halagó?", [["😌", "Orgulloso"], ["😢", "Triste"], ["😨", "Asustado"]], 0, "Pista: se puso muy…"),
      I("¿Qué nos enseña la fábula?", [["🤔", "Que no hay que creer en todo lo que nos dicen para adularnos"], ["🎵", "Que hay que cantar siempre"], ["🧀", "Que el queso es rico"]], 0, "Pista: escuchá lo que dice el zorro al final."),
  ],
  "cigarra-hormiga": [
      L("¿Qué hacía la cigarra en el verano?", [["🎸", "Cantaba todo el día"], ["🌾", "Juntaba trigo"], ["😴", "Dormía"]], 0, "Pista: tenía una guitarra."),
      L("¿Qué cargaba la hormiga?", [["🌾", "Granos de trigo"], ["🪵", "Palitos"], ["🍰", "Tortas"]], 0, "Pista: los llevaba al hormiguero."),
      L("¿Para qué guardaba comida la hormiga?", [["❄️", "Para el invierno"], ["🎉", "Para una fiesta"], ["🎁", "Para regalarla"]], 0, "Pista: se lo dijo a la cigarra."),
      S("¿Qué pasó cuando llegó el invierno?", [["🥶", "La cigarra no tenía comida"], ["☀️", "Hizo mucho calor"], ["🎶", "Hicieron un concierto"]], 0, "Pista: hacía frío y nevaba."),
      S("¿Qué hizo la hormiga cuando la cigarra golpeó la puerta?", [["🤝", "La hizo pasar y compartió su comida"], ["🚪", "No le abrió"], ["🏃", "Se escondió"]], 0, "Pista: escuchá el final."),
      I("¿Por qué la cigarra no tenía comida en invierno?", [["🎸", "Porque en verano solo cantó y no guardó"], ["🐜", "Porque la hormiga se la sacó"], ["🌧️", "Porque se le mojó"]], 0, "Pista: pensá en qué hizo todo el verano."),
      I("¿Qué nos enseña el cuento?", [["📦", "Que hay que prepararse para lo que viene"], ["🎸", "Que no hay que cantar nunca"], ["❄️", "Que el invierno es lindo"]], 0, "Pista: la hormiga guardó a tiempo."),
  ],
  "pastorcito-mentiroso": [
      L("¿Qué cuidaba el pastorcito?", [["🐑", "Ovejas"], ["🐄", "Vacas"], ["🐔", "Gallinas"]], 0, "Pista: estaba en una loma con su rebaño."),
      L("¿Qué gritaba el pastorcito para divertirse?", [["🐺", "¡Viene el lobo!"], ["🔥", "¡Fuego!"], ["🌧️", "¡Llueve!"]], 0, "Pista: un animal que asusta a las ovejas."),
      S("¿Qué hacían los vecinos las primeras veces?", [["🏃", "Subían corriendo a ayudarlo"], ["😴", "Seguían durmiendo"], ["🎉", "Hacían una fiesta"]], 0, "Pista: creían que era verdad."),
      S("¿Qué pasó cuando vino el lobo de verdad?", [["🙅", "Nadie vino a ayudar"], ["🏃", "Vinieron todos los vecinos"], ["🐺", "El lobo se hizo su amigo"]], 0, "Pista: esta vez nadie le creyó."),
      I("¿Por qué los vecinos no fueron la última vez?", [["🤥", "Porque pensaron que era otra mentira"], ["😴", "Porque estaban dormidos"], ["🌧️", "Porque llovía"]], 0, "Pista: ya los había engañado dos veces."),
      I("¿Cómo se sintieron los vecinos cuando descubrieron las mentiras?", [["😠", "Enojados"], ["😄", "Contentos"], ["😴", "Con sueño"]], 0, "Pista: volvieron al pueblo…"),
      I("¿Qué nos enseña el cuento?", [["✅", "Que hay que decir la verdad para que nos crean"], ["🐺", "Que los lobos son buenos"], ["🐑", "Que las ovejas corren rápido"]], 0, "Pista: al final nadie le creyó."),
  ],
  "gallina-huevos-oro": [
      L("¿Qué tenía de especial la gallina?", [["🥚", "Ponía huevos de oro"], ["🗣️", "Hablaba"], ["🎵", "Cantaba"]], 0, "Pista: está en el título."),
      L("¿Qué hacían con los huevos?", [["🏪", "Los vendían en el pueblo"], ["🍳", "Se los comían"], ["🗑️", "Los tiraban"]], 0, "Pista: así tuvieron una casa linda."),
      S("¿Qué empezó a querer el granjero?", [["➕", "Más y más huevos"], ["🐔", "Otra gallina"], ["🏖️", "Ir de vacaciones"]], 0, "Pista: decía que un huevo por día era poco."),
      S("¿Qué hizo la gallina al final?", [["🌲", "Se escapó al bosque"], ["🥚", "Puso diez huevos"], ["😴", "Se durmió"]], 0, "Pista: estaba cansada y asustada."),
      I("¿Por qué se escapó la gallina?", [["😫", "Porque no la dejaban descansar"], ["🌽", "Porque no le daban maíz"], ["🐺", "Porque vino un zorro"]], 0, "Pista: la despertaban de noche y la apuraban."),
      I("¿Cómo era el granjero al final del cuento?", [["😔", "Arrepentido de haber querido tanto"], ["😄", "Más rico que nunca"], ["😴", "Dormilón"]], 0, "Pista: entendió lo que había perdido."),
      I("¿Qué nos enseña la fábula?", [["🌱", "Que querer todo de golpe nos puede hacer perder lo que tenemos"], ["🥚", "Que el oro es lindo"], ["🐔", "Que las gallinas vuelan"]], 0, "Pista: el granjero no tuvo paciencia."),
  ],
  "musicos-bremen": [
      L("¿A dónde quería ir el burro?", [["🎵", "A Bremen, a ser músico"], ["🏖️", "A la playa"], ["🏫", "A la escuela"]], 0, "Pista: está en el título."),
      L("¿Qué animales se sumaron al viaje?", [["🐶🐱🐓", "Un perro, un gato y un gallo"], ["🐷🐮🐑", "Un chancho, una vaca y una oveja"], ["🦊🐻🐰", "Un zorro, un oso y un conejo"]], 0, "Pista: eran viejos como el burro."),
      L("¿Quiénes estaban en la casa del bosque?", [["💰", "Unos ladrones"], ["👵", "Una abuela"], ["🧚", "Un hada"]], 0, "Pista: contaban monedas."),
      S("¿Qué hicieron los animales para asustar a los ladrones?", [["🗼", "Se subieron uno arriba del otro y «cantaron» juntos"], ["🔥", "Prendieron fuego"], ["🚪", "Golpearon la puerta despacito"]], 0, "Pista: rebuznos, ladridos, maullidos y quiquiriquíes."),
      S("¿Qué pasó al final?", [["🏡", "Se quedaron a vivir en la casita"], ["🎵", "Llegaron a Bremen"], ["🏃", "Volvieron a sus casas"]], 0, "Pista: nunca llegaron a Bremen."),
      I("¿Por qué se fueron de sus casas los animales?", [["👴", "Porque eran viejos y nadie los quería"], ["🎉", "Porque querían ir a una fiesta"], ["🌧️", "Porque llovía mucho"]], 0, "Pista: el burro ya no podía cargar bolsas."),
      I("¿Qué nos enseña el cuento?", [["🤝", "Que juntos somos más fuertes"], ["💰", "Que hay que robar"], ["🎵", "Que el burro canta muy bien"]], 0, "Pista: solos no podían, juntos sí."),
  ],
  "juan-porotos": [
      L("¿Por qué cambió Juan la vaca?", [["🫘", "Por cinco porotos"], ["💰", "Por monedas de oro"], ["🐴", "Por un caballo"]], 0, "Pista: el señor dijo que eran mágicos."),
      L("¿Qué hizo la mamá con los porotos?", [["🪟", "Los tiró por la ventana"], ["🍲", "Los cocinó"], ["🎁", "Los guardó"]], 0, "Pista: estaba enojada."),
      S("¿Qué pasó a la mañana siguiente?", [["🌱", "Creció una planta hasta las nubes"], ["🐄", "Volvió la vaca"], ["🌧️", "Llovió todo el día"]], 0, "Pista: los porotos eran mágicos."),
      L("¿Qué había arriba de las nubes?", [["🏰", "Un castillo con un gigante"], ["🌈", "Un arcoíris"], ["🏫", "Una escuela"]], 0, "Pista: un gigante gruñón vivía ahí."),
      S("¿Qué hizo Juan cuando llegó abajo?", [["🪓", "Cortó la planta"], ["🧗", "Volvió a subir"], ["😴", "Se durmió"]], 0, "Pista: usó un hacha."),
      I("¿Por qué Juan cortó la planta?", [["🛡️", "Para que el gigante no pudiera bajar"], ["🔥", "Para hacer leña"], ["🌱", "Porque era fea"]], 0, "Pista: el gigante lo venía siguiendo."),
      I("¿Cómo se sintió la mamá al principio, con los porotos?", [["😠", "Enojada"], ["😄", "Feliz"], ["😴", "Dormida"]], 0, "Pista: los tiró por la ventana."),
  ],
  "medias-flamencos": [
      L("¿Quiénes hicieron el baile?", [["🐍", "Las víboras"], ["🦩", "Los flamencos"], ["🐊", "Los yacarés"]], 0, "Pista: invitaron a todos los animales."),
      L("¿De qué color tenían las patas los flamencos al principio?", [["⚪", "Blancas"], ["🔴", "Coloradas"], ["⚫", "Negras"]], 0, "Pista: por eso querían medias."),
      L("¿Quién les dio las «medias»?", [["🦔", "Un tatú bromista"], ["🦉", "Una lechuza"], ["🐒", "Un mono"]], 0, "Pista: le gustaba hacer bromas."),
      S("¿Qué pasó cuando las víboras descubrieron el engaño?", [["🐍", "Les mordieron las patas"], ["🎉", "Siguieron bailando"], ["🎁", "Les regalaron medias"]], 0, "Pista: estaban enojadas."),
      S("¿Qué hicieron los flamencos después?", [["💧", "Metieron las patas en el agua"], ["🏃", "Se fueron a dormir"], ["🧦", "Compraron otras medias"]], 0, "Pista: el agua del río estaba fresca."),
      I("¿Por qué se enojaron las víboras de coral?", [["🧦", "Porque las «medias» eran cueros de víboras como ellas"], ["🎵", "Porque la música era fea"], ["🍰", "Porque no había torta"]], 0, "Pista: eran coloradas, blancas y negras."),
      I("¿Qué explica este cuento?", [["🦩", "Por qué los flamencos tienen las patas coloradas"], ["🐍", "Por qué las víboras bailan"], ["🦔", "Por qué el tatú tiene caparazón"]], 0, "Pista: escuchá el final."),
  ],
  "traje-emperador": [
      L("¿Qué le encantaba al emperador?", [["👘", "La ropa nueva"], ["🍰", "Las tortas"], ["⚽", "El fútbol"]], 0, "Pista: tenía un traje para cada hora."),
      L("¿Qué decían los tramposos de su tela?", [["🧠", "Que solo la veían las personas inteligentes"], ["🌈", "Que cambiaba de color"], ["🔥", "Que no se quemaba"]], 0, "Pista: era una tela «mágica»."),
      S("¿Qué hizo el emperador con el traje?", [["🚶", "Salió a desfilar por la ciudad"], ["🗑️", "Lo tiró"], ["🎁", "Lo regaló"]], 0, "Pista: la gente aplaudía."),
      L("¿Quién dijo la verdad?", [["👦", "Un nene"], ["👑", "El emperador"], ["🧵", "Los tramposos"]], 0, "Pista: gritó lo que veía."),
      I("¿Por qué la gente decía que la tela era hermosa?", [["🙈", "Para no parecer tontos"], ["👀", "Porque la veían muy bien"], ["💰", "Porque les pagaban"]], 0, "Pista: nadie veía nada."),
      I("¿Cómo se sintió el emperador al final?", [["😳", "Avergonzado"], ["😎", "Orgulloso"], ["😴", "Con sueño"]], 0, "Pista: se puso colorado."),
      I("¿Qué nos enseña el cuento?", [["✅", "Que es mejor decir la verdad que aparentar"], ["👘", "Que la ropa nueva es lo más importante"], ["🧵", "Que hay que aprender a tejer"]], 0, "Pista: el nene se animó a decir lo que veía."),
  ],
  "tortuga-gigante": [
      L("¿A dónde se fue a vivir el hombre?", [["🌳", "Al monte"], ["🏖️", "A la playa"], ["🏙️", "A otra ciudad"]], 0, "Pista: el médico le dijo que necesitaba aire libre."),
      L("¿Qué le pasaba a la tortuga cuando la encontró?", [["🤕", "Estaba lastimada"], ["😴", "Estaba dormida"], ["🍽️", "Estaba comiendo"]], 0, "Pista: el hombre la curó."),
      S("¿Qué pasó después con el hombre?", [["🤒", "Se enfermó otra vez"], ["🏃", "Se fue a correr"], ["🎉", "Hizo una fiesta"]], 0, "Pista: tenía mucha fiebre."),
      S("¿Cómo llevó la tortuga al hombre a la ciudad?", [["🐢", "Sobre su caparazón"], ["🚂", "En tren"], ["🛶", "En una canoa"]], 0, "Pista: caminó días y noches."),
      L("¿Dónde vivió la tortuga al final?", [["🏞️", "En el zoológico"], ["🌳", "En el monte"], ["🏠", "En la casa del hombre"]], 0, "Pista: él la visitaba todos los días."),
      I("¿Por qué la tortuga ayudó al hombre?", [["💛", "Porque él la había curado antes"], ["💰", "Porque le pagó"], ["🍎", "Porque quería frutas"]], 0, "Pista: ella devolvió el favor."),
      I("¿Cómo era la tortuga?", [["💪", "Buena, agradecida y muy fuerte"], ["😠", "Egoísta"], ["😴", "Perezosa"]], 0, "Pista: caminó sin rendirse."),
  ],
  "leyenda-elal": [
      L("¿Cómo se llamaba el héroe de la leyenda?", [["🦢", "Elal"], ["👵", "Koonek"], ["👦", "Juan"]], 0, "Pista: es un héroe tehuelche."),
      L("¿Qué animal llevó a Elal hasta la Patagonia?", [["🦢", "Un cisne de cuello negro"], ["🦅", "Un cóndor"], ["🐋", "Una ballena"]], 0, "Pista: lo llevó volando sobre su espalda."),
      L("¿A qué cerro llegó Elal?", [["⛰️", "Al Chaltén"], ["🌋", "A un volcán"], ["🏔️", "Al Aconcagua"]], 0, "Pista: tiene casi siempre una nube en la punta."),
      S("¿Qué hizo Elal al golpear dos piedras?", [["🔥", "Hizo fuego"], ["💧", "Hizo agua"], ["🌈", "Hizo un arcoíris"]], 0, "Pista: saltaron chispas."),
      S("¿Qué hizo Elal al final?", [["🌅", "Se fue volando hacia donde sale el sol"], ["😴", "Se quedó dormido en el cerro"], ["🏠", "Se hizo una casa"]], 0, "Pista: se subió otra vez al cisne."),
      I("¿Por qué el fuego fue un regalo tan importante?", [["🔥", "Porque la Patagonia era muy fría"], ["🎂", "Porque era su cumpleaños"], ["🌙", "Porque era de noche"]], 0, "Pista: la tierra estaba helada."),
      I("¿Qué cuenta esta leyenda?", [["📜", "Cómo los tehuelches recibieron el fuego y aprendieron a vivir en la Patagonia"], ["🏙️", "Cómo se construyó una ciudad"], ["🚀", "Un viaje a la Luna"]], 0, "Pista: Elal les enseñó muchas cosas."),
  ],
};
