// Preguntas de comprensión auditiva de 1.º grado: 7 por cuento, 3 opciones
// con emoji, de tipo literal, secuencia e inferencial (incluye la
// enseñanza). La opción correcta es la de `answer` (se mezclan al jugar).
import type { ComprehensionKind, CuentoOpt, CuentoQuestion } from "./tipos";

const q = (kind: ComprehensionKind) => (text: string, options: CuentoOpt[], answer: number, hint: string): CuentoQuestion => ({ q: text, kind, options, answer, hint });
const L = q("literal");
const S = q("secuencia");
const I = q("inferencial");

export const PREGUNTAS_G1: Record<string, CuentoQuestion[]> = {
  "liebre-tortuga": [
      L("¿Quiénes corrieron la carrera?", [["🐇🐢", "La liebre y la tortuga"], ["🐶🐱", "Un perro guardián y un gato del pueblo"], ["🦊🐻", "El zorro veloz y el oso pardo"]], 0, "Pista: pensá en el título del cuento."),
      L("¿Cómo era la liebre?", [["⚡", "Muy rápida"], ["🐌", "Muy lenta"], ["😴", "Muy dormilona desde el principio"]], 0, "Pista: salió corriendo a toda velocidad."),
      S("¿Qué hizo la liebre en el medio de la carrera?", [["😴", "Se quedó dormida"], ["🍎", "Comió una manzana roja del árbol"], ["🏊", "Se fue a nadar al río"]], 0, "Pista: se acostó debajo de un árbol."),
      L("¿Cómo caminaba la tortuga?", [["🐢", "Despacito, sin parar"], ["🏃", "Corriendo muy rápido por el sendero"], ["🦘", "A los saltos por las piedras"]], 0, "Pista: paso a paso…"),
      S("¿Qué pasó al final?", [["🏆", "Ganó la tortuga"], ["🐇", "Ganó la liebre"], ["🤝", "Empataron al llegar a la meta"]], 0, "Pista: cuando la liebre se despertó, ya era tarde."),
      I("¿Por qué perdió la liebre?", [["💤", "Porque se confió y se durmió"], ["🦵", "Porque se tropezó con una rama en el camino"], ["🌧️", "Porque una tormenta mojó todo el sendero"]], 0, "Pista: pensó que tenía tiempo de sobra."),
      I("¿Qué nos enseña el cuento?", [["👣", "Que con esfuerzo y constancia se llega"], ["😂", "Que hay que reírse de los demás"], ["🛌", "Que hay que dormir mucho"]], 0, "Pista: la tortuga no se detuvo nunca."),
  ],
  "leon-raton": [
      L("¿Qué hacía el león al principio?", [["😴", "Dormía la siesta"], ["🍖", "Comía tranquilo en su cueva"], ["🏃", "Corría asustado por la selva"]], 0, "Pista: el ratón le pasó por arriba mientras…"),
      L("¿Por qué se despertó el león?", [["🐭", "Porque el ratón le pasó por la nariz"], ["⏰", "Porque sonó un reloj muy fuerte"], ["🌧️", "Porque empezó a llover sobre el pasto"]], 0, "Pista: el ratoncito jugaba por ahí."),
      S("¿Qué le prometió el ratón al león?", [["🤝", "Que algún día lo iba a ayudar"], ["🧀", "Que le iba a traer un pedazo de queso fresco"], ["🎵", "Que le iba a cantar una linda canción"]], 0, "Pista: —Algún día yo te voy a…"),
      L("¿Dónde quedó atrapado el león?", [["🕸️", "En una red"], ["🕳️", "En un pozo profundo"], ["🏠", "En una jaula grande"]], 0, "Pista: la pusieron unos cazadores."),
      S("¿Cómo lo ayudó el ratón?", [["🦷", "Mordió la red"], ["🔑", "Usó una llave dorada"], ["📣", "Llamó a otros animales de la selva"]], 0, "Pista: usó sus dientitos."),
      I("¿Por qué el león se rió cuando el ratón le prometió ayudarlo?", [["🐭", "Porque pensó que alguien tan chiquito no podía ayudarlo"], ["😂", "Porque el ratón le contó un chiste"], ["🎉", "Porque era su cumpleaños"]], 0, "Pista: el león es enorme y el ratón muy pequeño."),
      I("¿Qué nos enseña el cuento?", [["💛", "Que todos, grandes o chicos, podemos ayudar"], ["😠", "Que los leones siempre deben enojarse con todos"], ["💤", "Que hay que dormir siestas largas todo el día"]], 0, "Pista: el más chiquito salvó al más grande."),
  ],
  "tres-chanchitos": [
      L("¿Cuántos chanchitos había?", [["3️⃣", "Tres"], ["2️⃣", "Dos"], ["5️⃣", "Cinco hermanitos"]], 0, "Pista: está en el título."),
      L("¿De qué era la casa del primer chanchito?", [["🌾", "De paja"], ["🧱", "De ladrillos rojos"], ["🪵", "De ramas y madera seca"]], 0, "Pista: la hizo muy rápido para ir a jugar."),
      L("¿De qué era la casa más fuerte?", [["🧱", "De ladrillos"], ["🌾", "De paja seca del campo"], ["🧊", "De bloques gruesos de hielo"]], 0, "Pista: el lobo no la pudo voltear."),
      S("¿Qué hizo el lobo con las casas?", [["🌬️", "Sopló para tirarlas"], ["🎨", "Las pintó de muchos colores"], ["🔨", "Las golpeó con un martillo pesado"]], 0, "Pista: sopló y sopló…"),
      S("¿A dónde corrieron los chanchitos cuando el lobo voló sus casas?", [["🧱", "A la casa de ladrillos"], ["🌳", "A esconderse en el bosque espeso"], ["🏫", "A la escuela del pueblo vecino"]], 0, "Pista: era la casa del tercer hermano."),
      I("¿Por qué la casa de ladrillos no se cayó?", [["💪", "Porque estaba bien construida"], ["🍀", "Porque tuvo suerte"], ["🔒", "Porque tenía llave"]], 0, "Pista: el tercer chanchito trabajó mucho."),
      I("¿Cómo se sintieron los chanchitos al final?", [["🤗", "Contentos y a salvo"], ["😢", "Tristes por sus casitas perdidas"], ["😡", "Enojados con el lobo feroz"]], 0, "Pista: se abrazaron."),
  ],
  "ricitos-osos": [
      L("¿Cuántos osos vivían en la casita?", [["3️⃣", "Tres"], ["1️⃣", "Un oso grande"], ["4️⃣", "Cuatro ositos"]], 0, "Pista: papá, mamá y…"),
      L("¿Cómo era el pelo de la nena?", [["👱‍♀️", "Rubio, con rulos"], ["👩‍🦰", "Colorado y bien largo"], ["👩", "Negro, lacio y cortito"]], 0, "Pista: se llamaba Ricitos de Oro."),
      L("¿Qué sopa le gustó a Ricitos de Oro?", [["🧸", "La del osito"], ["🐻", "La de papá oso que estaba muy caliente"], ["🍲", "Ninguna de las sopas de la mesa"]], 0, "Pista: estaba justo como le gustaba."),
      S("¿Qué pasó con la sillita del osito?", [["💥", "Se rompió"], ["🎨", "La pintó con témperas"], ["🚪", "La sacó afuera de la casa"]], 0, "Pista: el osito lloró por su silla."),
      S("¿Dónde encontraron los osos a Ricitos de Oro?", [["🛏️", "Durmiendo en la camita"], ["🍳", "Cocinando rica sopa en la cocina"], ["🌳", "Caminando sola por el bosque"]], 0, "Pista: subieron a la habitación."),
      I("¿Qué hizo mal Ricitos de Oro?", [["🚪", "Entró a una casa sin permiso"], ["🧹", "Barrió la casa"], ["🎁", "Les llevó un regalo"]], 0, "Pista: la puerta estaba abierta, pero no era su casa."),
      I("¿Cómo se sintió el osito al volver?", [["😢", "Triste porque le tomaron la sopa y le rompieron la silla"], ["😄", "Feliz de haber encontrado una amiga nueva en su camita"], ["😴", "Con mucho sueño después de pasear por el bosque verde"]], 0, "Pista: lloraba."),
  ],
  "gallinita-roja": [
      L("¿Qué encontró la gallinita?", [["🌾", "Granos de trigo"], ["🥚", "Un huevo blanco de pato"], ["🪙", "Una moneda brillante de oro"]], 0, "Pista: los sembró en la tierra."),
      L("¿Quiénes no quisieron ayudar?", [["🦆🐱🐷", "El pato, el gato y el chancho"], ["🐶🐄🐴", "El perro guardián, la vaca y el caballo"], ["🐔🐣", "Los pollitos chiquitos del corral"]], 0, "Pista: siempre decían «Yo no»."),
      S("¿Qué hizo primero la gallinita con el trigo?", [["🌱", "Lo sembró"], ["🍞", "Hizo pan casero"], ["✂️", "Lo cortó con tijeras"]], 0, "Pista: el trigo tuvo que crecer."),
      S("¿Qué hizo con la harina?", [["🍞", "Amasó un pan"], ["🎂", "Hizo una torta de cumpleaños"], ["🗑️", "La tiró a la basura del corral"]], 0, "Pista: un pan riquísimo."),
      L("¿Cuándo quisieron ayudar los tres amigos?", [["😋", "Cuando había que comer el pan"], ["🌱", "Cuando había que sembrar los granos de trigo"], ["✂️", "Cuando había que cortar las espigas secas"]], 0, "Pista: gritaron «¡Yo, yo, yo!»."),
      I("¿Por qué la gallinita no les convidó pan?", [["🙅", "Porque no la ayudaron a hacerlo"], ["🤢", "Porque el pan estaba feo"], ["😴", "Porque estaban dormidos"]], 0, "Pista: hizo todo el trabajo sola."),
      I("¿Qué nos enseña el cuento?", [["🤝", "Que es importante ayudar y trabajar juntos"], ["🍞", "Que el pan recién horneado es muy rico"], ["🐔", "Que las gallinas siempre tienen que cocinar solas"]], 0, "Pista: los amigos solo querían comer."),
  ],
  "caperucita": [
      L("¿De qué color era la capa de Caperucita?", [["🔴", "Roja"], ["🔵", "Azul brillante"], ["🟢", "Verde como las hojas"]], 0, "Pista: está en su nombre."),
      L("¿A quién le llevaba la canasta?", [["👵", "A su abuela"], ["👨‍🏫", "A su maestro de la escuela"], ["🐺", "Al lobo feroz del bosque"]], 0, "Pista: estaba enferma."),
      L("¿Qué le dijo la mamá antes de salir?", [["🛤️", "Que no se saliera del camino"], ["🌸", "Que juntara flores silvestres"], ["🏃", "Que corriera lo más rápido posible"]], 0, "Pista: —No te salgas del…"),
      S("¿Qué hizo el lobo mientras Caperucita juntaba flores?", [["🏃", "Corrió a la casa de la abuela"], ["😴", "Se durmió una siesta bajo un árbol"], ["🍰", "Comió una torta rica en el bosque"]], 0, "Pista: tomó un atajo."),
      S("¿Quién ayudó a Caperucita?", [["🪓", "Un leñador"], ["🐶", "Un perro del pueblo"], ["👮", "Un policía del camino"]], 0, "Pista: la escuchó gritar."),
      I("¿Por qué el lobo le dijo que juntara flores?", [["⏳", "Para llegar antes a la casa de la abuela"], ["💐", "Porque le gustaban las flores"], ["🎁", "Para hacerle un regalo"]], 0, "Pista: mientras ella se entretenía, él corría."),
      I("¿Qué aprendió Caperucita?", [["🙅", "A no hablar con desconocidos"], ["🌸", "A juntar flores silvestres por el bosque"], ["🧺", "A llevar canastas pesadas por el sendero"]], 0, "Pista: lo prometió al final."),
  ],
  "patito-feo": [
      L("¿De qué color era el patito distinto?", [["🩶", "Gris"], ["💛", "Amarillo brillante"], ["❤️", "Rojo como el fuego"]], 0, "Pista: los demás eran amarillos."),
      L("¿Qué le decían los otros animales?", [["😝", "Que era feo"], ["😍", "Que era muy lindo"], ["🏆", "Que era el mejor nadador del corral"]], 0, "Pista: se burlaban de él."),
      S("¿Qué hizo el patito porque estaba triste?", [["🚶", "Se fue del corral"], ["🎉", "Hizo una fiesta en la laguna"], ["🍞", "Comió pedacitos de pan solo"]], 0, "Pista: caminó solo por el campo."),
      S("¿Qué estación pasó escondido entre los juncos?", [["❄️", "El invierno"], ["☀️", "El verano caluroso"], ["🌸", "La primavera florida"]], 0, "Pista: hacía mucho frío."),
      L("¿En qué se convirtió el patito?", [["🦢", "En un cisne"], ["🦆", "En un pato grande"], ["🐔", "En una gallina ponedora"]], 0, "Pista: un ave blanca y hermosa."),
      I("¿Cómo se sentía el patito cuando se burlaban?", [["😢", "Triste"], ["😄", "Contento y divertido"], ["😴", "Con mucho sueño"]], 0, "Pista: nadie quería jugar con él."),
      I("¿Qué nos enseña el cuento?", [["💛", "Que no hay que burlarse de quien es distinto"], ["🦆", "Que los patos son amarillos"], ["❄️", "Que el invierno es frío"]], 0, "Pista: el patito «feo» era especial."),
  ],
  "raton-campo-ciudad": [
      L("¿Dónde vivía el ratón de campo?", [["🌾", "En una cueva junto al trigal"], ["🏙️", "En un departamento de un edificio alto"], ["⛵", "En un barco de pescadores en el río"]], 0, "Pista: en el campo."),
      L("¿Qué comida le sirvió el ratón de campo a su primo?", [["🌾", "Granos, raíces y agua"], ["🧀", "Quesos, frutas y tortas dulces"], ["🍕", "Pizza recién horneada con queso"]], 0, "Pista: era una comida simple."),
      L("¿Qué había en la mesa de la ciudad?", [["🧀🍰", "Quesos, panes y tortas"], ["🌾", "Solo granos secos de trigo"], ["🥕", "Zanahorias frescas de la huerta"]], 0, "Pista: ¡cuánta comida!"),
      S("¿Qué pasó cuando empezaron a comer en la ciudad?", [["🐈", "Apareció el gato"], ["🎉", "Empezó una fiesta ruidosa con música"], ["🌧️", "Llovió fuerte sobre las ventanas"]], 0, "Pista: tuvieron que esconderse en un agujero."),
      S("¿Qué hizo al final el ratón de campo?", [["🏡", "Volvió feliz a su campo"], ["🏙️", "Se quedó a vivir para siempre en la ciudad"], ["🐈", "Se hizo amigo del gato guardián"]], 0, "Pista: prefería su vida tranquila."),
      I("¿Por qué prefirió el campo?", [["😌", "Porque allá vivía tranquilo y sin sustos"], ["🧀", "Porque había más queso"], ["🚗", "Porque había autos"]], 0, "Pista: en la ciudad tenía miedo todo el tiempo."),
      I("¿Cómo se sintió el ratón de campo en la ciudad?", [["😨", "Asustado"], ["😴", "Aburrido de tanta comida"], ["😎", "Muy tranquilo y relajado"]], 0, "Pista: el gato, las escobas…"),
  ],
  "leyenda-calafate": [
      L("¿Dónde pasa esta leyenda?", [["🏔️", "En la Patagonia"], ["🏝️", "En una isla tropical del norte"], ["🏙️", "En una gran ciudad con edificios"]], 0, "Pista: en la meseta, con mucho viento."),
      L("¿Cómo se llamaba la abuela?", [["👵", "Koonek"], ["👧", "Caperucita Roja"], ["🧓", "Ricitos de Oro"]], 0, "Pista: un nombre tehuelche."),
      S("¿Por qué se quedó sola Koonek?", [["🚶", "Porque su pueblo se fue y ella ya no podía caminar tanto"], ["😠", "Porque estaba enojada"], ["🏠", "Porque tenía casa nueva"]], 0, "Pista: era muy anciana."),
      S("¿En qué se convirtió Koonek?", [["🌿", "En un arbusto de calafate"], ["🦅", "En un cóndor de las altas montañas"], ["⭐", "En una estrella brillante del cielo"]], 0, "Pista: un arbusto con espinas."),
      L("¿De qué color son los frutos del calafate?", [["🟣", "Violetas"], ["🔴", "Rojos brillantes"], ["🟠", "Naranjas claros"]], 0, "Pista: son frutos dulces de verano."),
      I("¿Qué dice la leyenda que le pasa a quien come calafate?", [["🔁", "Que siempre vuelve a la Patagonia"], ["💤", "Que se duerme una siesta larga"], ["🦸", "Que aprende a volar como los pájaros"]], 0, "Pista: escuchá el final."),
      I("¿Cómo se habrá sentido Koonek cuando su pueblo se fue?", [["😢", "Sola y triste"], ["🎉", "Con muchas ganas de festejar sola"], ["😡", "Enojada con las aves viajeras"]], 0, "Pista: se quedó sola en el invierno."),
  ],
  "zorro-cuervo": [
      L("¿Qué tenía el cuervo en el pico?", [["🧀", "Un pedazo de queso"], ["🍎", "Una manzana roja y dulce"], ["🪱", "Un gusano de la tierra húmeda"]], 0, "Pista: el zorro lo olió."),
      L("¿Dónde se subió el cuervo?", [["🌳", "A la rama más alta de un árbol"], ["🏠", "Al techo de tejas de una casa del campo"], ["⛰️", "A una montaña llena de piedras y nieve"]], 0, "Pista: quería comer tranquilo, bien arriba."),
      S("¿Qué le pidió el zorro al cuervo?", [["🎵", "Que cantara una canción"], ["🧀", "Que le diera la mitad del queso"], ["🏃", "Que bajara al suelo a jugar una carrera"]], 0, "Pista: le dijo que su voz debía ser linda."),
      S("¿Qué pasó cuando el cuervo abrió el pico?", [["⬇️", "Se le cayó el queso"], ["🎶", "Cantó una hermosa melodía"], ["🦊", "Se fue el zorro corriendo a su cueva"]], 0, "Pista: el zorro lo atrapó en el aire."),
      I("¿Por qué el zorro le decía cosas lindas al cuervo?", [["🧀", "Porque quería quedarse con el queso"], ["💛", "Porque eran amigos desde chiquitos"], ["🎤", "Porque le gustaba mucho cantar en el bosque"]], 0, "Pista: pensó «ese queso va a ser mío»."),
      I("¿Cómo se sintió el cuervo cuando el zorro lo halagó?", [["😌", "Orgulloso"], ["😢", "Triste y preocupado"], ["😨", "Asustado por el zorro astuto"]], 0, "Pista: se puso muy…"),
      I("¿Qué nos enseña la fábula?", [["🤔", "Que no hay que creer en todo lo que nos dicen para adularnos"], ["🎵", "Que hay que cantar siempre"], ["🧀", "Que el queso es rico"]], 0, "Pista: escuchá lo que dice el zorro al final."),
  ],
  "cigarra-hormiga": [
      L("¿Qué hacía la cigarra en el verano?", [["🎸", "Cantaba todo el día"], ["🌾", "Juntaba trigo para el invierno"], ["😴", "Dormía la siesta en su cueva"]], 0, "Pista: tenía una guitarra."),
      L("¿Qué cargaba la hormiga?", [["🌾", "Granos de trigo"], ["🪵", "Palitos y ramas secas del bosque"], ["🍰", "Tortas de chocolate del pueblo"]], 0, "Pista: los llevaba al hormiguero."),
      L("¿Para qué guardaba comida la hormiga?", [["❄️", "Para el invierno"], ["🎉", "Para celebrar una gran fiesta de verano"], ["🎁", "Para regalar a todos sus vecinos"]], 0, "Pista: se lo dijo a la cigarra."),
      S("¿Qué pasó cuando llegó el invierno?", [["🥶", "La cigarra no tenía comida"], ["☀️", "Hizo mucho calor en todo el campo"], ["🎶", "Organizaron un concierto bajo el sol"]], 0, "Pista: hacía frío y nevaba."),
      S("¿Qué hizo la hormiga cuando la cigarra golpeó la puerta?", [["🤝", "La hizo pasar y compartió su comida"], ["🚪", "No le abrió la puerta de su refugio"], ["🏃", "Se escapó corriendo al fondo del bosque"]], 0, "Pista: escuchá el final."),
      I("¿Por qué la cigarra no tenía comida en invierno?", [["🎸", "Porque en verano solo cantó y no guardó"], ["🐜", "Porque la hormiga se la sacó"], ["🌧️", "Porque se le mojó"]], 0, "Pista: pensá en qué hizo todo el verano."),
      I("¿Qué nos enseña el cuento?", [["📦", "Que hay que prepararse para lo que viene"], ["🎸", "Que nunca hay que tocar la guitarra ni cantar canciones"], ["❄️", "Que el invierno frío es la estación más divertida de todas"]], 0, "Pista: la hormiga guardó a tiempo."),
  ],
  "pastorcito-mentiroso": [
      L("¿Qué cuidaba el pastorcito?", [["🐑", "Ovejas"], ["🐄", "Vacas lecheras"], ["🐔", "Gallinas ponedoras"]], 0, "Pista: estaba en una loma con su rebaño."),
      L("¿Qué gritaba el pastorcito para divertirse?", [["🐺", "¡Viene el lobo!"], ["🔥", "¡Fuego en el bosque!"], ["🌧️", "¡Llueve torrencialmente!"]], 0, "Pista: un animal que asusta a las ovejas."),
      S("¿Qué hacían los vecinos las primeras veces?", [["🏃", "Subían corriendo a ayudarlo"], ["😴", "Seguían durmiendo la siesta en sus casas"], ["🎉", "Hacían una fiesta en la plaza del pueblo"]], 0, "Pista: creían que era verdad."),
      S("¿Qué pasó cuando vino el lobo de verdad?", [["🙅", "Nadie vino a ayudar"], ["🏃", "Vinieron todos los vecinos corriendo"], ["🐺", "El lobo se hizo su amigo para siempre"]], 0, "Pista: esta vez nadie le creyó."),
      I("¿Por qué los vecinos no fueron la última vez?", [["🤥", "Porque pensaron que era otra mentira"], ["😴", "Porque estaban durmiendo profundamente la siesta"], ["🌧️", "Porque llovía y los caminos se llenaron de barro"]], 0, "Pista: ya los había engañado dos veces."),
      I("¿Cómo se sintieron los vecinos cuando descubrieron las mentiras?", [["😠", "Enojados"], ["😄", "Muy contentos y risueños"], ["😴", "Con mucho sueño y pereza"]], 0, "Pista: volvieron al pueblo…"),
      I("¿Qué nos enseña el cuento?", [["✅", "Que hay que decir la verdad para que nos crean"], ["🐺", "Que los lobos son buenos"], ["🐑", "Que las ovejas corren rápido"]], 0, "Pista: al final nadie le creyó."),
  ],
  "gallina-huevos-oro": [
      L("¿Qué tenía de especial la gallina?", [["🥚", "Ponía huevos de oro"], ["🗣️", "Hablaba con los vecinos"], ["🎵", "Cantaba canciones alegres"]], 0, "Pista: está en el título."),
      L("¿Qué hacían con los huevos?", [["🏪", "Los vendían en el pueblo"], ["🍳", "Cocinaban tortillas para cenar"], ["🗑️", "Los tiraban al arroyo del campo"]], 0, "Pista: así tuvieron una casa linda."),
      S("¿Qué empezó a querer el granjero?", [["➕", "Más y más huevos"], ["🐔", "Otra gallina igual para el corral"], ["🏖️", "Irse de viaje a descansar a la playa"]], 0, "Pista: decía que un huevo por día era poco."),
      S("¿Qué hizo la gallina al final?", [["🌲", "Se escapó al bosque"], ["🥚", "Puso diez huevos dorados juntos"], ["😴", "Se durmió en el nido toda la tarde"]], 0, "Pista: estaba cansada y asustada."),
      I("¿Por qué se escapó la gallina?", [["😫", "Porque no la dejaban descansar"], ["🌽", "Porque no le daban maíz dorado"], ["🐺", "Porque apareció un zorro hambriento en la granja"]], 0, "Pista: la despertaban de noche y la apuraban."),
      I("¿Cómo era el granjero al final del cuento?", [["😔", "Arrepentido de haber querido tanto"], ["😄", "Más rico que todos los reyes del mundo"], ["😴", "Dormilón y despreocupado en su granja"]], 0, "Pista: entendió lo que había perdido."),
      I("¿Qué nos enseña la fábula?", [["🌱", "Que querer todo de golpe nos puede hacer perder lo que tenemos"], ["🥚", "Que el oro brillante es lindo"], ["🐔", "Que las gallinas vuelan alto"]], 0, "Pista: el granjero no tuvo paciencia."),
  ],
  "musicos-bremen": [
      L("¿A dónde quería ir el burro?", [["🎵", "A Bremen, a ser músico"], ["🏖️", "A descansar a la playa con amigos"], ["🏫", "A la escuela del pueblo vecino"]], 0, "Pista: está en el título."),
      L("¿Qué animales se sumaron al viaje?", [["🐶🐱🐓", "Un perro, un gato y un gallo"], ["🐷🐮🐑", "Un chancho, una vaca y una oveja del corral"], ["🦊🐻🐰", "Un zorro astuto, un oso pardo y un conejo"]], 0, "Pista: eran viejos como el burro."),
      L("¿Quiénes estaban en la casa del bosque?", [["💰", "Unos ladrones"], ["👵", "Una abuelita tejedora"], ["🧚", "Un hada madrina buena"]], 0, "Pista: contaban monedas."),
      S("¿Qué hicieron los animales para asustar a los ladrones?", [["🗼", "Se subieron uno arriba del otro y «cantaron» juntos"], ["🔥", "Prendieron una fogata gigante cerca de la ventana"], ["🚪", "Golpearon la puerta de madera despacito para pedir comida"]], 0, "Pista: rebuznos, ladridos, maullidos y quiquiriquíes."),
      S("¿Qué pasó al final?", [["🏡", "Se quedaron a vivir en la casita"], ["🎵", "Llegaron a la ciudad de Bremen"], ["🏃", "Volvieron corriendo a sus casas de la granja"]], 0, "Pista: nunca llegaron a Bremen."),
      I("¿Por qué se fueron de sus casas los animales?", [["👴", "Porque eran viejos y nadie los quería"], ["🎉", "Porque querían ir a una fiesta"], ["🌧️", "Porque llovía mucho"]], 0, "Pista: el burro ya no podía cargar bolsas."),
      I("¿Qué nos enseña el cuento?", [["🤝", "Que juntos somos más fuertes"], ["💰", "Que hay que robar monedas de oro a los vecinos"], ["🎵", "Que el burro canta mejor que cualquier pájaro"]], 0, "Pista: solos no podían, juntos sí."),
  ],
  "juan-porotos": [
      L("¿Por qué cambió Juan la vaca?", [["🫘", "Por cinco porotos"], ["💰", "Por una bolsa llena de monedas de oro"], ["🐴", "Por un caballo blanco para pasear"]], 0, "Pista: el señor dijo que eran mágicos."),
      L("¿Qué hizo la mamá con los porotos?", [["🪟", "Los tiró por la ventana"], ["🍲", "Los cocinó en una olla con verduras"], ["🎁", "Los guardó en una caja de madera"]], 0, "Pista: estaba enojada."),
      S("¿Qué pasó a la mañana siguiente?", [["🌱", "Creció una planta hasta las nubes"], ["🐄", "Volvió la vaca caminando sola al corral"], ["🌧️", "Llovió torrencialmente durante todo el día"]], 0, "Pista: los porotos eran mágicos."),
      L("¿Qué había arriba de las nubes?", [["🏰", "Un castillo con un gigante"], ["🌈", "Un arcoíris de siete colores"], ["🏫", "Una escuela con muchos chicos jugando"]], 0, "Pista: un gigante gruñón vivía ahí."),
      S("¿Qué hizo Juan cuando llegó abajo?", [["🪓", "Cortó la planta"], ["🧗", "Volvió a subir a las nubes"], ["😴", "Se durmió debajo del árbol"]], 0, "Pista: usó un hacha."),
      I("¿Por qué Juan cortó la planta?", [["🛡️", "Para que el gigante no pudiera bajar"], ["🔥", "Para hacer leña"], ["🌱", "Porque era fea"]], 0, "Pista: el gigante lo venía siguiendo."),
      I("¿Cómo se sintió la mamá al principio, con los porotos?", [["😠", "Enojada"], ["😄", "Muy contenta y feliz"], ["😴", "Dormida profundamente"]], 0, "Pista: los tiró por la ventana."),
  ],
  "medias-flamencos": [
      L("¿Quiénes hicieron el baile?", [["🐍", "Las víboras"], ["🦩", "Los flamencos del río"], ["🐊", "Los yacarés de la laguna"]], 0, "Pista: invitaron a todos los animales."),
      L("¿De qué color tenían las patas los flamencos al principio?", [["⚪", "Blancas"], ["🔴", "Coloradas brillantes"], ["⚫", "Negras como carbón"]], 0, "Pista: por eso querían medias."),
      L("¿Quién les dio las «medias»?", [["🦔", "Un tatú bromista"], ["🦉", "Una lechuza sabia del monte"], ["🐒", "Un mono travieso de los árboles"]], 0, "Pista: le gustaba hacer bromas."),
      S("¿Qué pasó cuando las víboras descubrieron el engaño?", [["🐍", "Les mordieron las patas"], ["🎉", "Siguieron bailando alegremente toda la noche"], ["🎁", "Les regalaron medias tejidas con lana suave"]], 0, "Pista: estaban enojadas."),
      S("¿Qué hicieron los flamencos después?", [["💧", "Metieron las patas en el agua"], ["🏃", "Se fueron a dormir a la selva"], ["🧦", "Fueron a comprar otras medias al almacén"]], 0, "Pista: el agua del río estaba fresca."),
      I("¿Por qué se enojaron las víboras de coral?", [["🧦", "Porque las «medias» eran cueros de víboras como ellas"], ["🎵", "Porque la música era fea"], ["🍰", "Porque no había torta"]], 0, "Pista: eran coloradas, blancas y negras."),
      I("¿Qué explica este cuento?", [["🦩", "Por qué los flamencos tienen las patas coloradas"], ["🐍", "Por qué las víboras bailan en las fiestas"], ["🦔", "Por qué el tatú tiene un caparazón con placas duras"]], 0, "Pista: escuchá el final."),
  ],
  "traje-emperador": [
      L("¿Qué le encantaba al emperador?", [["👘", "La ropa nueva"], ["🍰", "Las tortas de crema"], ["⚽", "El fútbol con sus ministros"]], 0, "Pista: tenía un traje para cada hora."),
      L("¿Qué decían los tramposos de su tela?", [["🧠", "Que solo la veían las personas inteligentes"], ["🌈", "Que cambiaba de color"], ["🔥", "Que no se quemaba"]], 0, "Pista: era una tela «mágica»."),
      S("¿Qué hizo el emperador con el traje?", [["🚶", "Salió a desfilar por la ciudad"], ["🗑️", "Lo tiró a la basura del palacio"], ["🎁", "Lo regaló a los campesinos del pueblo"]], 0, "Pista: la gente aplaudía."),
      L("¿Quién dijo la verdad?", [["👦", "Un nene"], ["👑", "El emperador del reino"], ["🧵", "Los tejedores tramposos"]], 0, "Pista: gritó lo que veía."),
      I("¿Por qué la gente decía que la tela era hermosa?", [["🙈", "Para no parecer tontos"], ["👀", "Porque la veían brillar muy bien al sol"], ["💰", "Porque les pagaban muchas monedas de plata"]], 0, "Pista: nadie veía nada."),
      I("¿Cómo se sintió el emperador al final?", [["😳", "Avergonzado"], ["😎", "Orgulloso y satisfecho"], ["😴", "Con mucho sueño y cansancio"]], 0, "Pista: se puso colorado."),
      I("¿Qué nos enseña el cuento?", [["✅", "Que es mejor decir la verdad que aparentar"], ["👘", "Que estrenar ropa nueva todos los días es lo mejor"], ["🧵", "Que todos los niños deben aprender a tejer trajes"]], 0, "Pista: el nene se animó a decir lo que veía."),
  ],
  "tortuga-gigante": [
      L("¿A dónde se fue a vivir el hombre?", [["🌳", "Al monte"], ["🏖️", "A la playa del mar"], ["🏙️", "A otra ciudad muy lejana"]], 0, "Pista: el médico le dijo que necesitaba aire libre."),
      L("¿Qué le pasaba a la tortuga cuando la encontró?", [["🤕", "Estaba lastimada"], ["😴", "Estaba dormida en la orilla"], ["🍽️", "Estaba comiendo hojas frescas de la selva"]], 0, "Pista: el hombre la curó."),
      S("¿Qué pasó después con el hombre?", [["🤒", "Se enfermó otra vez"], ["🏃", "Se fue a correr por el monte"], ["🎉", "Hizo una gran fiesta con sus vecinos"]], 0, "Pista: tenía mucha fiebre."),
      S("¿Cómo llevó la tortuga al hombre a la ciudad?", [["🐢", "Sobre su caparazón"], ["🚂", "En un tren de pasajeros"], ["🛶", "En una canoa navegando por el río"]], 0, "Pista: caminó días y noches."),
      L("¿Dónde vivió la tortuga al final?", [["🏞️", "En el zoológico"], ["🌳", "En el monte misionero"], ["🏠", "En la casa de campo del hombre"]], 0, "Pista: él la visitaba todos los días."),
      I("¿Por qué la tortuga ayudó al hombre?", [["💛", "Porque él la había curado antes"], ["💰", "Porque él le pagó con monedas"], ["🍎", "Porque quería conseguir frutas dulces del monte"]], 0, "Pista: ella devolvió el favor."),
      I("¿Cómo era la tortuga?", [["💪", "Buena, agradecida y muy fuerte"], ["😠", "Egoísta y quejosa"], ["😴", "Perezosa para caminar"]], 0, "Pista: caminó sin rendirse."),
  ],
  "leyenda-elal": [
      L("¿Cómo se llamaba el héroe de la leyenda?", [["🦢", "Elal"], ["👵", "Koonek la anciana"], ["👦", "Juan el granjero"]], 0, "Pista: es un héroe tehuelche."),
      L("¿Qué animal llevó a Elal hasta la Patagonia?", [["🦢", "Un cisne de cuello negro"], ["🦅", "Un cóndor gigante de la cordillera"], ["🐋", "Una ballena que nadaba por el mar helado"]], 0, "Pista: lo llevó volando sobre su espalda."),
      L("¿A qué cerro llegó Elal?", [["⛰️", "Al Chaltén"], ["🌋", "A un volcán nevado"], ["🏔️", "Al cerro Aconcagua"]], 0, "Pista: tiene casi siempre una nube en la punta."),
      S("¿Qué hizo Elal al golpear dos piedras?", [["🔥", "Hizo fuego"], ["💧", "Hizo brotar agua"], ["🌈", "Hizo un arcoíris en el cielo"]], 0, "Pista: saltaron chispas."),
      S("¿Qué hizo Elal al final?", [["🌅", "Se fue volando hacia donde sale el sol"], ["😴", "Se quedó dormido para siempre en la cima del cerro"], ["🏠", "Se hizo una casa de madera junto al lago"]], 0, "Pista: se subió otra vez al cisne."),
      I("¿Por qué el fuego fue un regalo tan importante?", [["🔥", "Porque la Patagonia era muy fría"], ["🎂", "Porque todos festejaban un gran cumpleaños"], ["🌙", "Porque era de noche y querían salir a jugar"]], 0, "Pista: la tierra estaba helada."),
      I("¿Qué cuenta esta leyenda?", [["📜", "Cómo los tehuelches recibieron el fuego y aprendieron a vivir en la Patagonia"], ["🏙️", "Cómo se construyó una ciudad moderna"], ["🚀", "Un viaje fantástico a la Luna"]], 0, "Pista: Elal les enseñó muchas cosas."),
  ],
  "leyenda-koonch": [
      L("¿Quién estaba al principio de todo?", [["✨", "Kóoch"], ["🦢", "Un cisne blanco"], ["👦", "Elal el héroe"]], 0, "Pista: estaba solo en la oscuridad."),
      L("¿Qué se formó con las lágrimas de Kóoch?", [["🌊", "El mar"], ["🌧️", "La lluvia del cielo"], ["🏔️", "Las grandes montañas nevadas"]], 0, "Pista: lloró tanto, tanto…"),
      S("¿Qué nació cuando Kóoch suspiró?", [["🌬️", "El viento"], ["☀️", "El sol brillante"], ["🌙", "La luna redonda"]], 0, "Pista: fue un suspiro larguísimo."),
      S("¿Qué pasó cuando el viento apartó la oscuridad?", [["💡", "Apareció la luz"], ["🌧️", "Empezó a llover sin parar"], ["❄️", "Nevó sobre toda la tierra"]], 0, "Pista: ya no estaba oscuro."),
      L("¿Qué aparecieron en la isla que levantó Kóoch?", [["🐦🐟", "Pájaros, peces, insectos y animales"], ["🏠", "Casas grandes, plazas y calles del pueblo"], ["🚗", "Autos y colectivos transitando"]], 0, "Pista: los seres vivos."),
      I("¿Por qué lloraba Kóoch?", [["😔", "Porque se sentía muy solo"], ["😠", "Porque estaba enojado con las olas del mar"], ["🤕", "Porque se lastimó un pie caminando"]], 0, "Pista: no tenía a nadie."),
      I("¿Qué explica esta leyenda?", [["🌍", "Cómo empezó el mundo, según los tehuelches"], ["🧁", "Cómo se hace una torta de chocolate"], ["🚀", "Un viaje espacial hacia la Luna"]], 0, "Pista: el mar, el viento, la luz…"),
  ],
  "leyenda-hornero": [
      L("¿Qué le encantaba hacer al joven?", [["🏗️", "Construir"], ["🎵", "Cantar canciones"], ["😴", "Dormir la siesta"]], 0, "Pista: era muy trabajador."),
      L("¿Qué prueba le pidió el cacique?", [["⏳", "Quedarse tres días envuelto en un cuero"], ["🏃", "Correr una carrera veloz hasta el río"], ["🎣", "Pescar un pez gigante en las aguas del río"]], 0, "Pista: era una prueba de paciencia."),
      S("¿Qué pasó cuando abrieron el cuero?", [["🐦", "Salió volando un pajarito"], ["👦", "El joven seguía profundamente dormido"], ["🎁", "Había un regalo de plumas coloridas"]], 0, "Pista: el joven ya no estaba."),
      L("¿De qué color era el pajarito?", [["🟤", "Color canela"], ["🔵", "Azul brillante como el cielo"], ["🟢", "Verde como las hojas del monte"]], 0, "Pista: un marrón clarito."),
      S("¿Con qué construyó su casita?", [["🟫", "Con barro y pajitas"], ["🧱", "Con ladrillos cocidos y cemento"], ["🪵", "Con troncos caídos del monte"]], 0, "Pista: la juntó con el pico."),
      I("¿Por qué su casa se parece a un horno?", [["🥖", "Porque es redonda, de barro, como un horno"], ["🔥", "Porque adentro hace fuego"], ["🍞", "Porque cocina pan"]], 0, "Pista: por eso se llama hornero."),
      I("¿Qué cualidades tenía el joven?", [["💪", "Era trabajador y paciente"], ["😴", "Era perezoso para las tareas"], ["😠", "Era malhumorado y peleador con todos"]], 0, "Pista: aguantó la prueba."),
  ],
  "leyenda-yerba-mate": [
      L("¿Quiénes eran Yasí y Araí?", [["🌙☁️", "La luna y la nube"], ["☀️⭐", "El sol y una estrella brillante"], ["🌧️🌈", "La lluvia y el arcoíris en el cielo"]], 0, "Pista: vivían en el cielo."),
      L("¿Qué querían conocer?", [["🌳", "La selva"], ["🏖️", "La playa de arena blanca"], ["🏙️", "La ciudad con grandes edificios"]], 0, "Pista: con árboles, flores y mariposas."),
      S("¿Qué animal apareció de pronto?", [["🐆", "Un yaguareté"], ["🐒", "Un mono travieso de las ramas"], ["🦜", "Un loro colorido y parlanchín"]], 0, "Pista: las miraba con hambre."),
      S("¿Quién las salvó?", [["👴", "Un anciano"], ["🐶", "Un perro guardián del monte"], ["👧", "Una nena de la comunidad"]], 0, "Pista: tenía un arco."),
      L("¿Qué regalo le dejaron al anciano?", [["🌿", "Una planta nueva: la yerba mate"], ["💰", "Monedas de oro relucientes en un cofre"], ["🛶", "Una canoa de madera para navegar"]], 0, "Pista: con ella hacemos mate."),
      I("¿Por qué le hicieron un regalo?", [["🙏", "Para agradecerle que las salvó y compartió su comida"], ["🎂", "Porque era su cumpleaños"], ["🎲", "Porque ganó un juego"]], 0, "Pista: él las ayudó."),
      I("¿Qué significa compartir un mate, según la leyenda?", [["🤝", "Amistad y agradecimiento"], ["😠", "Enojo entre vecinos"], ["😴", "Que tenemos mucho sueño por las noches"]], 0, "Pista: escuchá el final."),
  ],
  "leyenda-siete-colores": [
      L("¿Dónde pasa esta leyenda?", [["⛰️", "En Purmamarca, Jujuy"], ["🌊", "En la costa fría de Santa Cruz"], ["🏙️", "En Buenos Aires entre los edificios"]], 0, "Pista: un pueblito del norte."),
      L("¿Cómo eran los cerros al principio?", [["🩶", "Grises y marrones"], ["🌈", "De muchos colores brillantes"], ["⚪", "Blancos de nieve durante todo el año"]], 0, "Pista: los chicos se aburrían de verlos."),
      S("¿Cuándo salían los chicos a pintar?", [["🌙", "De noche, mientras los grandes dormían"], ["☀️", "Al mediodía bajo el sol caliente"], ["🏫", "Durante el recreo largo de la escuela del pueblo"]], 0, "Pista: era una idea secreta."),
      L("¿Cuántas noches pintaron?", [["7️⃣", "Siete"], ["2️⃣", "Dos noches seguidas"], ["🔟", "Diez tardes enteras"]], 0, "Pista: está en el nombre del cerro."),
      S("¿Qué vio la gente la mañana del octavo día?", [["🌈", "El cerro lleno de colores"], ["🌧️", "Mucha lluvia cayendo en la plaza"], ["🦙", "Una llama caminando por la cima del cerro"]], 0, "Pista: ¡no lo podían creer!"),
      I("¿Por qué pintaron el cerro?", [["🎨", "Porque se aburrían de ver siempre el mismo color"], ["🏆", "Para ganar un premio"], ["😠", "Porque estaban enojados"]], 0, "Pista: pensá en cómo se sentían al principio."),
      I("¿Cómo se habrán sentido los chicos al ver la sorpresa de todos?", [["😄", "Felices y orgullosos"], ["😢", "Tristes y preocupados"], ["😴", "Aburridos y con ganas de dormir"]], 0, "Pista: su regalo funcionó."),
  ],
  "leyenda-ballena": [
      L("¿Cómo se llamaba la ballena?", [["🐋", "Góos"], ["🐍", "Mboi la serpiente"], ["✨", "Kóoch el creador"]], 0, "Pista: tenía patitas cortas."),
      L("¿Dónde vivía la ballena al principio?", [["🏜️", "En la tierra, cerca de la costa"], ["🌊", "En el fondo más profundo del mar abierto"], ["☁️", "En las nubes blancas del cielo"]], 0, "Pista: caminaba."),
      S("¿En qué se convirtió Elal?", [["🪰", "En un tábano"], ["🦅", "En un cóndor gigante"], ["🐟", "En un pez de agua dulce"]], 0, "Pista: un bichito volador muy chiquito."),
      S("¿Cómo hizo Elal para que todos salieran?", [["🤭", "Le hizo cosquillas por dentro"], ["🎵", "Le cantó una canción de cuna para dormirla"], ["🍖", "Le dio comida fresca para alimentarla"]], 0, "Pista: Góos abrió la boca."),
      S("¿Qué hizo Elal al final?", [["🌊", "Empujó a Góos hasta el mar"], ["🏠", "Le construyó una casa grande de madera"], ["😴", "Se durmió debajo de un arbusto"]], 0, "Pista: le dijo que viviera allí."),
      I("¿Por qué Elal se dejó tragar?", [["🦸", "Para salvar a los que estaban adentro"], ["🍽️", "Porque tenía mucha hambre"], ["🎮", "Para jugar con los peces"]], 0, "Pista: faltaban animales y personas."),
      I("¿Qué explica esta leyenda?", [["🐋", "Por qué las ballenas viven en el mar"], ["🦙", "Por qué los guanacos corren tan rápido por la meseta"], ["🌙", "Por qué hay luna en el cielo nocturno"]], 0, "Pista: escuchá el final."),
  ],
  "leyenda-iguazu": [
      L("¿Quién era Mboi?", [["🐍", "Una serpiente gigante"], ["🐆", "Un yaguareté feroz de la selva"], ["🦜", "Un loro parlanchín de las ramas"]], 0, "Pista: cuidaba el río."),
      L("¿Cómo escaparon Naipí y Tarobá?", [["🛶", "En una canoa por el río"], ["🐎", "A caballo por los senderos"], ["🚶", "Caminando despacito por la selva espesa"]], 0, "Pista: Tarobá la preparó."),
      S("¿Qué hizo Mboi cuando se enojó?", [["🌊", "Partió el río en dos"], ["😴", "Se fue a dormir al fondo de la cueva"], ["🌳", "Plantó árboles gigantes en la orilla"]], 0, "Pista: se retorció con fuerza."),
      S("¿Qué se formó cuando el río se partió?", [["💧", "Las cataratas"], ["🏔️", "Una montaña muy alta de piedra"], ["🏝️", "Una isla de arena en medio del río"]], 0, "Pista: el agua cae desde lo alto."),
      L("¿En qué se convirtió Tarobá?", [["🌴", "En una palmera"], ["🪨", "En una roca gigante en medio del río"], ["🐦", "En un pájaro de plumas coloridas"]], 0, "Pista: está en la orilla, mirándola."),
      I("¿Qué representa el arcoíris en la leyenda?", [["🌈", "Un puente que une a Naipí y Tarobá"], ["🎨", "Una pintura que hicieron los chicos del pueblo"], ["☀️", "Que va a salir el sol muy pronto"]], 0, "Pista: escuchá el final."),
      I("¿Por qué escaparon Naipí y Tarobá?", [["💛", "Porque se querían y no querían separarse"], ["🎣", "Porque querían pescar peces dorados en el río"], ["🌧️", "Porque una tormenta inundaba toda la aldea"]], 0, "Pista: Naipí tenía que irse a vivir junto al río."),
  ],
};
