// Versiones MÁS LARGAS de los textos para 3.º grado (los chicos leen solos;
// la lectura en voz alta cuesta 5 monedas). Mismo relato y mismas 6 escenas.
// Rango: 60–90 palabras por escena (~450 palabras total).
// Recursos: causas y consecuencias, sentimientos, comparaciones y vocabulario en contexto.
// Ver docs/equipo/tareas/AG-06-dictados-y-textos.md.

export const TEXTOS_G3: Record<string, string[]> = {
  // 1. La tortuga gigante (Cuento de Horacio Quiroga)
  "tortuga-gigante": [
    "Vivía en la ciudad de Buenos Aires un hombre honrado, trabajador y muy querido por sus amigos, que un invierno cayó gravemente enfermo de los pulmones. Los médicos le advirtieron con seriedad que las medicinas de la farmacia no alcanzarían y que la única forma de salvar su vida era trasladarse a vivir al monte misionero, donde el aire puro de la selva y el clima cálido le permitirían recuperar las fuerzas perdidas.",
    "El hombre viajó hacia el norte, construyó un refugio abrigado con ramas y comenzó a cazar animales para alimentarse sanamente. Una tarde, mientras recorría la orilla de una laguna silenciosa, descubrió a un enorme tigre que intentaba devorar a una tortuga gigante. El cazador apuntó su escopeta, disparó y espantó a la fiera. Al ver que el quelonio estaba malherido, sintió compasión, lo cargó hasta su choza y le curó las lastimaduras con vendas.",
    "La tortuga agradecida se quedó viviendo junto a la cabaña y los dos entablaron una tierna amistad. Semanas después, el hombre recayó con una fiebre altísima que lo dejó postrado en su cama sin poder moverse ni cocinar. La tortuga comprendió de inmediato la gravedad del peligro y decidió cuidarlo día y noche: le acercaba agua fresca en una cáscara limpia y buscaba raíces y frutas tiernas del monte para alimentarlo con infinita paciencia.",
    "A pesar de los cuidados, el enfermo empeoraba y deliraba murmurando que solo en un hospital de Buenos Aires podrían salvarlo. La tortuga entendió que si se quedaban en la selva su amigo moriría sin remedio. Con un esfuerzo sobrehumano, acomodó al hombre sobre su caparazón ancho y resistente, lo sujetó con lianas flexibles para que no cayera y emprendió la marcha a pie rumbo a la gran ciudad lejana.",
    "Avanzó durante semanas enteras bajo soles ardientes y lluvias torrenciales, cruzando esteros, cañadones y caminos de tierra sin detenerse a descansar ni un solo instante. El peso del hombre era enorme y las patas del reptil sangraban por las piedras del sendero. Cuando estaba a punto de desplomarse por el agotamiento en las afueras de la capital, un ratoncito del campo la animó mostrándole que las luces de los edificios ya brillaban muy cerca.",
    "El director del zoológico de Buenos Aires los auxilió al ver la increíble hazaña y trasladó al hombre al hospital, donde los médicos lograron salvarle la vida. Cuando el hombre se recuperó por completo, no quiso separarse de su salvadora: la tortuga se quedó viviendo en el parque zoológico, donde su amigo la visitaba todas las tardes llevándole lechuga fresca y acariciándole el caparazón en un pacto de gratitud eterna.",
  ],

  // 2. La leyenda de la ballena (Leyenda tehuelche)
  "leyenda-ballena": [
    "Cuentan los abuelos tehuelches que en tiempos muy lejanos la ballena Góos no vivía en las profundidades del océano como ahora, sino que caminaba sobre la tierra firme de la Patagonia. Tenía cuatro patitas cortas y robustas que le permitían andar despacito por la meseta, pastando pastos tiernos junto a los cañadones y descansando a la sombra de los arbustos espinosos bajo el cielo inmenso de Santa Cruz.",
    "Góos era un animal gigantesco, curioso y muy distraído, pero tenía una costumbre peligrosa: cuando sentía sueño o hambre, abría su descomunal bocaza para bostezar y aspiraba todo lo que estaba a su alrededor. De esta manera, sin querer hacer daño pero por pura torpeza, se tragó rebaños enteros de guanacos, bandadas de flamencos, toldos de cuero y hasta a varios cazadores de la comunidad que pasaban cerca.",
    "La meseta patagónica comenzó a quedar vacía y silenciosa, provocando una honda tristeza entre las familias originarias. Al ver la angustia de su pueblo, el héroe protector Elal decidió intervenir para solucionar el problema. Con su poder transformador, se convirtió en un diminuto tábano de alas transparentes y voló velozmente hacia donde descansaba la ballena, esperando el momento exacto en que el animal abriera sus fauces para dejarse tragar.",
    "Una vez adentro de la panza oscura y gigantesca de Góos, Elal encontró a todos los animales y pobladores asustados pero sanos y salvos. Para obligar a la ballena a abrir la boca sin lastimarla, el héroe se acercó volando hasta su garganta y comenzó a hacerle intensas cosquillas con sus patitas y sus alas. La ballena sintió una picazón insoportable y abrió la boca de par en par con un estornudo colosal.",
    "Aprovechando la apertura, todos los prisioneros salieron corriendo en fila hacia la luz del sol, celebrando su libertad con abrazos y cantos de alegría. Pero Elal comprendió que un animal tan inmenso y descuidado no podía seguir viviendo sobre la tierra habitada, ya que cualquier movimiento representaba una amenaza constante para las personas y las especies que poblaban la meseta santacruceña.",
    "Elal tomó a Góos con su fuerza prodigiosa y la empujó suavemente hacia las aguas del mar Argentino, diciéndole con cariño: —El mar será tu verdadero hogar; allí tendrás espacio de sobra para nadar y alimentarte sin perjudicar a nadie. La ballena perdió sus patitas, se adaptó feliz a las olas frías y desde entonces surca los mares australes expulsando chorros de agua con alegría.",
  ],

  // 3. La gallina de los huevos de oro (Fábula de Esopo)
  "gallina-huevos-oro": [
    "En una apacible granja situada en un valle fértil vivía un matrimonio campesino que trabajaba de sol a sol labrando la tierra y cuidando de sus animales. A pesar de sus esfuerzos diarios, el dinero apenas les alcanzaba para pagar las deudas del molino y comprar semillas. Una mañana fresca, al ingresar al gallinero para recoger los huevos del desayuno, el granjero descubrió algo brillante y pesado en un nido de paja.",
    "Al levantarlo con asombro, comprobó que no era un huevo ordinario sino una pieza maciza de oro puro y resplandeciente. Lleno de emoción corrió a mostrárselo a su esposa y viajó al pueblo para venderlo al joyero, quien le entregó una valiosa suma de monedas de plata. A la mañana siguiente el milagro se repitió, y así ocurrió cada amanecer sin fallar ni un solo día durante meses enteros.",
    "Gracias a este regalo extraordinario de la naturaleza, la humilde familia transformó por completo su realidad: construyeron una casa amplia con techos de tejas, compraron ropa abrigada y disfrutaron de comidas abundantes sin pasar privaciones. Pero con el correr de las semanas, en lugar de agradecer su buena fortuna, una peligrosa ambición comenzó a crecer en el corazón del campesino, quien miraba el huevo matinal con fastidio e impaciencia.",
    "—¡Es demasiado lento esperar un solo huevo cada mañana! —se quejaba ante su esposa con ojos codiciosos—. Si esta gallina pone huevos de oro macizo, es porque en su interior debe esconder una mina entera de riquezas fabulosas. Si logro conseguir todo ese tesoro de una sola vez, me convertiré en el hombre más poderoso del reino y no tendré que esperar el paso de los días.",
    "Cegado por su avaricia descontrolada, el granjero comenzó a perturbar la tranquilidad del animalito: lo despertaba en plena noche con faroles encendidos, lo zamarreaba exigiéndole más tesoros y no lo dejaba descansar en su nido. La noble gallina, asustada por los gritos y debilitada por la falta de descanso, aprovechó una tarde en que la puerta del corral quedó entreabierta y escapó volando velozmente hacia la espesura del bosque.",
    "El campesino buscó desesperado durante semanas enteras entre las malezas, pero la gallina jamás regresó a la granja. Se quedó solo en su patio desierto, sin el animal mágico y sin los valiosos huevos que antes tenía asegurados cada mañana. Comprendió con amarga tristeza que la codicia desmedida y la impaciencia destruyen la verdadera prosperidad, dejando con las manos vacías a quien no sabe valorar lo que tiene.",
  ],

  // 4. Las medias de los flamencos (Cuento de Horacio Quiroga)
  "medias-flamencos": [
    "En las selvas misioneras a orillas del gran río Paraná, las víboras organizaron un fastuoso baile nocturno e invitaron a todos los habitantes del monte: los yacarés asistieron con collares de piedras, los sapos llegaron perfumados y los peces asomaban a la superficie para aplaudir. Las dueñas de casa, en especial las peligrosas víboras de coral, eran las reinas de la fiesta luciendo faldas de gasa a rayas coloradas, blancas y negras que hipnotizaban a los invitados.",
    "Los flamencos, que en aquellos tiempos remotos tenían patas totalmente blancas y cuerpos desgarbados, se sentían torpes, poco agraciados y temían ser el hazmerreír de la reunión. Consumidos por la vanidad y el deseo ardiente de lucir tan elegantes como las víboras, decidieron recorrer los almacenes del pueblo buscando comprar medias con rayas coloradas, blancas y negras. Pero en todos los comercios los comerciantes los echaban diciendo que semejante prenda no existía.",
    "Al ver su angustia desmedida, un tatú bromista que pasaba por la orilla quiso jugarles una trampa y les sugirió con picardía: —Vayan a visitar a mi comadre la lechuza del monte; ella es la única que sabe dónde conseguir medias rayadas tan exclusivas. Los ingenuos flamencos volaron hasta la cueva de la lechuza, quien cazó a varias víboras de coral del bañado y les entregó sus cueros secos haciéndolos pasar por llamativas medias.",
    "Antes de despedirlos, la lechuza les advirtió con tono severo: —Pónganse estas medias y bailen toda la noche sin parar ni un solo segundo. Muevan las patas al compás de la música, porque si se detienen a descansar van a llorar amargamente. Los flamencos, felices y orgullosos, se calzaron las pieles rayadas y entraron a la pista de baile levantando las patas con gracia al ritmo de los tambores.",
    "Al principio todos los animales los ovacionaron fascinados por su belleza, pero las víboras de coral comenzaron a desconfiar y se arrastraron pegadas al suelo para inspeccionar el tejido. Cuando un flamenco agotado tropezó y cayó al suelo sin poder levantarse, las víboras descubrieron con horror que aquellas medias eran las pieles desolladas de sus propias hermanas. Enfurecidas por el engaño, se abalanzaron sobre ellos y les mordieron las patas inyectándoles su veneno.",
    "Locos de dolor y espanto, los flamencos huyeron volando hacia el río y zambulleron sus extremidades en el agua fresca para calmar el insoportable ardor de las toxinas. Desde aquella noche trágica han pasado los siglos, y los flamencos continúan parados todo el día dentro del agua de las lagunas, con sus patas teñidas de un color rojo encendido que arde sin consuelo, recordando el alto precio que pagaron por su vanidad.",
  ],

  // 5. La leyenda de las Cataratas del Iguazú (Leyenda guaraní)
  "leyenda-iguazu": [
    "Hace muchos siglos, en las tierras frondosas del litoral selvático, el río Iguazú corría tranquilo, suave y sin saltos entre los árboles gigantes. En las profundidades de sus aguas calmas habitaba Mboi, una serpiente acuática de proporciones descomunales y poderes sobrenaturales, a quien los antiguos pueblos guaraníes temían y respetaban como al guardián todopoderoso de toda la región fluvial.",
    "Una vez al año, los pobladores celebraban una ceremonia sagrada en honor a la deidad para pedir prosperidad y buenas cosechas. En aquella ocasión, la elegida para consagrar su vida al río era Naipí, una hermosa joven de mirada dulce. Pero un valiente guerrero de la tribu llamado Tarobá estaba profundamente enamorado de ella y no estaba dispuesto a perderla ni a permitir que fuera apartada para siempre de su lado.",
    "La misma noche previa a la ceremonia, Tarobá preparó en secreto una canoa de madera resistente a orillas del agua. Tomó a Naipí de la mano, la subió a la embarcación y ambos comenzaron a remar con desesperación río abajo a favor de la corriente, soñando con escapar juntos hacia tierras libres donde nadie pudiera separarlos y pudieran vivir su gran amor en paz.",
    "Al enterarse de la fuga audaz, Mboi entró en una cólera espantosa. La gigantesca serpiente emergió del fondo con ojos de fuego, azotó las aguas con su cuerpo escamoso y se retorció con tanta violencia contra el lecho de piedra que partió la tierra en dos mitades desiguales, abriendo una garganta abismal por donde el río cayó rugiendo al vacío con fuerza descomunal.",
    "La canoa de los enamorados fue alcanzada por la furia del agua y cayó en el precipicio recién formado. Con su magia implacable, la fiera transformó a la bella Naipí en una gran roca situada en el centro del torrente de la cascada, azotada eternamente por la espuma blanca, y convirtió al valiente Tarobá en una palmera solitaria plantada en la orilla del barranco, condenado a mirarla sin poder tocarla.",
    "Satisfecha con su venganza, la fiera se ocultó para siempre en la profunda Garganta del Diablo para vigilar que jamás volvieran a reunirse. Sin embargo, en las mañanas soleadas de Misiones, el rocío del agua que asciende hacia el cielo forma un arcoíris resplandeciente que une la roca de la cascada con la palmera de la orilla, creando un puente luminoso donde las almas de Naipí y Tarobá se abrazan con amor eterno.",
  ],

  // 6. El ratón de campo y el ratón de ciudad (Fábula de Esopo)
  "raton-campo-ciudad": [
    "En una modesta y acogedora cueva cavada al pie de un trigal dorado, vivía un ratoncito de campo muy laborioso y sereno. Su rutina cotidiana consistía en juntar espigas maduras de trigo, recolectar semillas silvestres y raíces tiernas, y calmar su sed con las gotas cristalinas que brotaban de un arroyito cercano. Aunque su vida era muy sencilla y sin lujos, disfrutaba de la paz inmensa que reinaba bajo los cielos abiertos del campo.",
    "Una tarde tibia de verano recibió la inesperada visita de su primo, un ratón distinguido que vivía en una imponente mansión de la ciudad capital. El ratón de campo lo recibió con los brazos abiertos y le ofreció generosamente lo mejor de su despensa: un puñado de granos secos y agua fresca. El visitante probó apenas un bocado con gesto de disgusto y exclamó: —¡Pero qué miseria, querido primo! Vení conmigo a la ciudad y conocerás banquetes dignos de un emperador.",
    "Seducido por las promesas de manjares exquisitos y comodidades asombrosas, el ratón campesino aceptó viajar con él al caer la noche. Llegaron a una suntuosa residencia y entraron sigilosamente al comedor principal, donde los humanos acababan de abandonar una mesa fastuosa tras un gran festejo familiar: sobre los manteles finos descansaban bandejas repletas de jamones ahumados, quesos maduros, tortas de crema esponjosas y frutas confitadas de aromas tentadores.",
    "El ratón de campo miraba maravillado aquel festín de reyes y se disponía a clavar sus dientes en un trozo de pastel cuando, de repente, la puerta crujió y apareció un gato atigrado de garras afiladas y ojos centelleantes. Los dos roedores tuvieron que salir disparados a toda prisa, esquivando zarpazos en la oscuridad hasta meterse con el corazón latiendo a mil por hora en una grieta estrecha y helada del zócalo.",
    "Pasaron largo rato temblando de pánico en su escondite sin atreverse a respirar. Cuando la calma pareció retornar y el hambre los empujó a asomarse nuevamente hacia los manjares, la puerta se abrió con violencia y entraron varias personas armadas con escobas y baldes, haciendo un estrépito aterrador y barriendo el suelo con furia. Los pequeños animales corrieron desesperados para no ser aplastados bajo las suelas de los zapatos.",
    "En cuanto recuperó el aliento dentro de la grieta, el ratón de campo abrazó a su primo, sacudió sus bigotes y se despidió con determinación: —Disfrutá vos de tus ricos quesos y de tus fiestas elegantes; yo me regreso inmediatamente a mi cueva del trigal. He aprendido esta noche una verdad imborrable: más vale alimentarse con granos secos en absoluta paz que saborear los mejores manjares del mundo en medio de miedos y sobresaltos.",
  ],
};
