// Habilidades de 4.º grado según el Diseño Curricular de Santa Cruz.
// Cada actividad declara qué habilidades trabaja y alimenta el progreso del alumno.
import { WorldSubject } from "@/types";

export interface SkillDef {
  id: string;
  subject: WorldSubject;
  label: string;
  axis: string;
  description: string;
  practice: string;
}

export const GRADE4_SKILLS: SkillDef[] = [
  // ==========================================
  // LENGUA
  // ==========================================
  {
    id: "l4-noticia",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "La noticia y sus partes",
    description: "Reconoce los elementos de la noticia (título, copete, cuerpo, epígrafe) y responde a las preguntas básicas.",
    practice: "Analizar noticias de diarios locales y señalar sus partes.",
  },
  {
    id: "l4-noticia-lectura",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Comprensión de noticias patagónicas",
    description: "Lee comprensivamente noticias de actualidad provincial extrayendo hechos, protagonistas y lugares.",
    practice: "Responder preguntas directas e inferenciales sobre notas periodísticas santacruceñas.",
  },
  {
    id: "l4-expositivo",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Texto expositivo e ideas clave",
    description: "Identifica el tema general, los subtemas por párrafo y las ideas principales en textos informativos.",
    practice: "Subrayar ideas clave y titular párrafos de textos de ciencias.",
  },
  {
    id: "l4-expositivo-lectura",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Comprensión de textos de divulgación",
    description: "Comprende textos explicativos sobre la flora, fauna y geografía santacruceña.",
    practice: "Extraer conceptos científicos y responder sobre relaciones de causa y efecto.",
  },
  {
    id: "l4-biografia",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Biografía y orden cronológico",
    description: "Comprende la vida de personajes históricos respetando la secuencia temporal y conectores temporales.",
    practice: "Ordenar líneas de tiempo y redactar biografías breves.",
  },
  {
    id: "l4-biografia-lectura",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Comprensión de biografías de pioneros",
    description: "Lee y analiza relatos biográficos de exploradores, científicos y pobladores de la Patagonia.",
    practice: "Identificar hitos, fechas y legados en biografías de la región austral.",
  },
  {
    id: "l4-instructivo",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Texto instructivo y verbos de acción",
    description: "Identifica materiales/ingredientes y pasos secuenciales con verbos en infinitivo o imperativo.",
    practice: "Seguir y redactar recetas o instrucciones de juegos paso a paso.",
  },
  {
    id: "l4-carta",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Carta personal y correo",
    description: "Reconoce la estructura de la carta personal: lugar, fecha, saludo con dos puntos, cuerpo y despedida.",
    practice: "Escribir cartas familiares respetando la diagramación y fórmulas de cortesía.",
  },
  {
    id: "l4-fabula",
    subject: "lengua",
    axis: "Literatura",
    label: "Fábulas y moraleja",
    description: "Reconoce personajes animales personificados y deduce la enseñanza moral que transmite la fábula.",
    practice: "Lectura y debate de fábulas tradicionales y modernas.",
  },
  {
    id: "l4-poesia",
    subject: "lengua",
    axis: "Literatura",
    label: "Poesía: versos, estrofas y rimas",
    description: "Distingue versos y estrofas, reconoce rimas consonantes y asonantes e imágenes sensoriales.",
    practice: "Recitar poemas patagónicos y crear versos rimados.",
  },
  {
    id: "l4-teatro",
    subject: "lengua",
    axis: "Literatura",
    label: "Texto teatral y acotaciones",
    description: "Distingue parlamentos de personajes y acotaciones escénicas entre paréntesis.",
    practice: "Leer obras teatrales breves dramatizando voces y siguiendo acotaciones.",
  },
  {
    id: "l4-historieta",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Historieta, viñetas y globos",
    description: "Reconoce el código icónico-verbal: viñetas, globos de diálogo/pensamiento y onomatopeyas.",
    practice: "Completar globos de historietas y crear tiras cómicas.",
  },
  {
    id: "l4-parrafo-oracion",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Párrafo, oración y puntuación",
    description: "Reconoce la oración y el párrafo como unidades con sentido gráfico: sangría, mayúscula y puntos.",
    practice: "Puntuar textos separando en oraciones y párrafos.",
  },
  {
    id: "l4-conectores-temporales",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Cohesión y conectores temporales",
    description: "Usa conectores de tiempo (primero, luego, después, finalmente) para ordenar la narración.",
    practice: "Completar relatos utilizando conectores temporales y causales adecuados.",
  },
  {
    id: "l4-sujeto-tacito",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sujeto expreso y desinencial (tácito)",
    description: "Identifica el sujeto en la oración simple y reconoce cuándo está omitido por la desinencia verbal.",
    practice: "Reconocer sujetos expresos y desinenciales en oraciones variadas.",
  },
  {
    id: "l4-predicado-verbal",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Predicado verbal simple y compuesto",
    description: "Identifica el predicado verbal, su núcleo verbal y distingue si tiene uno o más verbos coordinados.",
    practice: "Señalar núcleos verbales y concordancia con el sujeto.",
  },
  {
    id: "l4-sustantivo",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sustantivos comunes, propios y colectivos",
    description: "Clasifica semánticamente sustantivos comunes, propios, individuales y colectivos.",
    practice: "Agrupar sustantivos según su clase e identificar colectivos patagónicos.",
  },
  {
    id: "l4-adjetivo",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Adjetivos: calificativos, gentilicios y numerales",
    description: "Identifica adjetivos y los clasifica según aporten cualidades, procedencia o cantidad.",
    practice: "Completar descripciones con adjetivos pertinentes y variados.",
  },
  {
    id: "l4-concordancia-gn",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Concordancia de género y número",
    description: "Aplica la regla de concordancia morfológica entre sustantivos, adjetivos y artículos.",
    practice: "Corregir discordancias de género y número en frases y oraciones.",
  },
  {
    id: "l4-verbo-persona",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "El verbo: persona y número",
    description: "Reconoce la raíz y la desinencia del verbo y determina la persona gramatical y número.",
    practice: "Conjugación en primera, segunda y tercera persona singular y plural.",
  },
  {
    id: "l4-verbo-tiempo",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Tiempos verbales: presente, pasado y futuro",
    description: "Distingue acciones pasadas, presentes y futuras en el modo indicativo.",
    practice: "Transformar oraciones entre pasado, presente y futuro.",
  },
  {
    id: "l4-preteritos-narrativos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Pretérito perfecto e imperfecto",
    description: "Distingue el pretérito perfecto simple (acción puntual terminada) del imperfecto (duración o hábito).",
    practice: "Elegir entre cantó / cantaba según la función narrativa de la oración.",
  },
  {
    id: "l4-infinitivos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Verbos en infinitivo: terminaciones -ar, -er, -ir",
    description: "Reconoce formas no personales del verbo (infinitivos) y las tres conjugaciones regulares.",
    practice: "Identificar infinitivos en recetas e instrucciones de juegos.",
  },
  {
    id: "l4-sinonimos-antonimos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sinónimos y antónimos contextuales",
    description: "Reconoce relaciones de significado semejante u opuesto según el contexto del texto.",
    practice: "Buscar alternativas para evitar repeticiones en textos narrativos.",
  },
  {
    id: "l4-hiperonimos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Hiperónimos e hipónimos",
    description: "Relaciona palabras que nombran una clase general con las especies o elementos que la componen.",
    practice: "Agrupar palabras en categorías (ej.: ñandú, cóndor, calafate bajo aves y plantas).",
  },
  {
    id: "l4-familias-prefijos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Familias de palabras, prefijos y sufijos",
    description: "Reconoce la raíz común y forma palabras derivadas usando prefijos (des-, re-, in-) y sufijos (-ero, -oso, -ito).",
    practice: "Armar familias léxicas y deducir significados por derivación.",
  },
  {
    id: "l4-acentuacion",
    subject: "lengua",
    axis: "Normativa ortográfica",
    label: "Sílaba tónica: agudas, graves y esdrújulas",
    description: "Separa en sílabas, ubica la tónica y clasifica palabras aplicando reglas de tilde.",
    practice: "Acentuar palabras agudas, graves y esdrújulas justificando con la terminación.",
  },
  {
    id: "l4-puntuacion-dialogo",
    subject: "lengua",
    axis: "Normativa ortográfica",
    label: "Signos de puntuación y raya de diálogo",
    description: "Usa punto seguido, punto y aparte, coma en enumeraciones, dos puntos y raya en diálogos.",
    practice: "Puntuar fragmentos de cuentos con diálogos directos.",
  },
  {
    id: "l4-ortografia-reglas",
    subject: "lengua",
    axis: "Normativa ortográfica",
    label: "Reglas ortográficas: b/v, c/s/z, g/j, h, ll/y",
    description: "Aplica reglas de uso frecuente para grafías dudosas en palabras de segundo ciclo.",
    practice: "Completar palabras y corregir errores ortográficos en oraciones.",
  },
  {
    id: "l4-dictado-palabra",
    subject: "lengua",
    axis: "Normativa ortográfica",
    label: "Dictado de palabras con reglas de 4.º",
    description: "Escribe al oído palabras con combinaciones ortográficas y acentuación precisa de cuarto grado.",
    practice: "Escribir palabras al dictado auditivo y autocorregir acentuación.",
  },
  {
    id: "l4-dictado-oracion",
    subject: "lengua",
    axis: "Normativa ortográfica",
    label: "Dictado de oraciones completas",
    description: "Escribe oraciones completas con mayúscula inicial, punto final y signos de puntuación.",
    practice: "Copiar al dictado oraciones contextualizadas en la cultura santacruceña.",
  },

  // ==========================================
  // MATEMÁTICA
  // ==========================================
  {
    id: "m4-num-100k",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Números hasta 100.000",
    description: "Lee, escribe, ordena y compone números naturales hasta el 100.000.",
    practice: "Escribir números en cifras y en letras y ubicar en escalas.",
  },
  {
    id: "m4-num-1m",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Números hasta el 1.000.000",
    description: "Extiende la serie numérica natural hasta el millón analizando regularidades.",
    practice: "Comparar poblaciones, distancias patagónicas y cifras de 6 dígitos.",
  },
  {
    id: "m4-posicional",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Valor posicional y descomposición",
    description: "Descompone números en sumas y multiplicaciones por potencias de diez.",
    practice: "Expresar números como suma de dieces de mil, miles, cienes, dieces y unos.",
  },
  {
    id: "m4-recta-numerica",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Comparación y recta numérica",
    description: "Ubica números naturales en la recta numérica respetando escalas e intervalos.",
    practice: "Interpolar números intermedios y encontrar distancias entre puntos.",
  },
  {
    id: "m4-romanos",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Sistema de numeración romano",
    description: "Lee y escribe números romanos (I, V, X, L, C, D, M) y los compara con el sistema decimal posicional.",
    practice: "Identificar siglos, capítulos y fechas en numeración romana.",
  },
  {
    id: "m4-sumas-grandes",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Sumas y restas con números grandes",
    description: "Resuelve problemas aditivos con números de hasta seis cifras mediante diversas estrategias.",
    practice: "Calcular distancias recorridas y presupuestos escolares.",
  },
  {
    id: "m4-calculo-mental",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Cálculo mental y estimación",
    description: "Usa descomposiciones y redondeos para anticipar resultados antes de calcular.",
    practice: "Estimar costos y redondear cantidades al millar más cercano.",
  },
  {
    id: "m4-mult-unidad-ceros",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Multiplicación y división por 10, 100 y 1.000",
    description: "Aplica regularidades al multiplicar y dividir números naturales por la unidad seguida de ceros.",
    practice: "Multiplicar cantidades rápidamente agregando o quitando ceros.",
  },
  {
    id: "m4-mult-2cifras",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Multiplicación por dos cifras",
    description: "Domina el algoritmo de la multiplicación y estrategias basadas en la tabla pitagórica.",
    practice: "Calcular compras de paquetes por docenas y productos por bultos.",
  },
  {
    id: "m4-propiedades-mult",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Propiedades de la multiplicación",
    description: "Aplica propiedades asociativa, conmutativa y distributiva para simplificar cálculos.",
    practice: "Descomponer factores como (10 + 4) × 6 para resolver mentalmente.",
  },
  {
    id: "m4-organizaciones-rectangulares",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Organizaciones rectangulares y combinatoria",
    description: "Modela situaciones de filas por columnas y combinaciones simples mediante multiplicación.",
    practice: "Calcular baldosas de un patio y combinaciones de ropa.",
  },
  {
    id: "m4-division-algoritmo",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "División con divisor de una y dos cifras",
    description: "Usa el algoritmo de división estimando cocientes y verificando con la multiplicación.",
    practice: "Resolver repartos equitativos y particiones numéricas.",
  },
  {
    id: "m4-div-resto",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Análisis del resto en la división",
    description: "Interpreta el significado del resto en problemas de transporte, reparto y compras.",
    practice: "Determinar si se necesita un viaje más o cuántos elementos sobran.",
  },
  {
    id: "m4-multiplos-divisores",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Múltiplos y divisores",
    description: "Encuentra múltiplos y divisores de números naturales mediante tablas y repartos exactos.",
    practice: "Descubrir múltiplos comunes en horarios de colectivos y compras por paquetes.",
  },
  {
    id: "m4-proporcionalidad",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Proporcionalidad directa",
    description: "Resuelve problemas de series proporcionales completando tablas con valores enteros y fraccionarios.",
    practice: "Completar tablas de precios por kilogramo o distancias por hora.",
  },
  {
    id: "m4-frac-parte",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Fracciones usuales: 1/2, 1/4, 3/4, 1/8",
    description: "Relaciona partes con el todo en situaciones de medida (litros, kilos) y particiones equitativas.",
    practice: "Calcular ingredientes de cocina en medios y cuartos de kilo.",
  },
  {
    id: "m4-fracciones-reparto",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Fracciones de tercios, quintos y sextos",
    description: "Expresa resultados de repartos equitativos como fracciones numéricas.",
    practice: "Dividir 7 alfajores entre 3 niños y expresar el resultado.",
  },
  {
    id: "m4-frac-equivalentes",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Fracciones equivalentes",
    description: "Reconoce equivalencias entre fracciones usuales (1/2 = 2/4 = 4/8) mediante representaciones gráficas.",
    practice: "Comparar fracciones y verificar si representan la misma cantidad.",
  },
  {
    id: "m4-numeros-mixtos",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Números mixtos y fracciones mayores a 1",
    description: "Convierte entre fracciones impropias y números mixtos (ej. 5/2 = 2 1/2).",
    practice: "Medir longitudes y pesos mayores a la unidad entera.",
  },
  {
    id: "m4-frac-recta",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Fracciones en la recta numérica",
    description: "Ubica fracciones usuales y números mixtos entre los números enteros en la recta.",
    practice: "Marcar 1/2, 3/4 y 1 1/4 en una escala graduada.",
  },
  {
    id: "m4-suma-resta-fracciones",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Suma y resta de fracciones de igual denominador",
    description: "Calcula adiciones y sustracciones simples de fracciones con apoyo mental y gráfico.",
    practice: "Sumar 1/4 + 2/4 y calcular cuánto falta para completar el entero.",
  },
  {
    id: "m4-decimales-dinero",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Decimales en dinero y medidas",
    description: "Usa números decimales (décimos, centésimos) en precios monetarios y longitudes métricas.",
    practice: "Armar montos con monedas de centavos y billetes de pesos.",
  },
  {
    id: "m4-decimales-mult-div",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Decimales multiplicados y divididos por 10, 100 y 1.000",
    description: "Comprende el corrimiento de la coma decimal al multiplicar y dividir por potencias de 10.",
    practice: "Convertir centavos a pesos y centímetros a metros.",
  },
  {
    id: "m4-suma-resta-decimales",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Suma y resta de números decimales",
    description: "Suma y resta expresiones decimales alineando la coma en contextos de compras y medidas.",
    practice: "Calcular el total y el vuelto en compras cotidianas.",
  },
  {
    id: "m4-rectas-angulos-rectos",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Rectas paralelas y perpendiculares",
    description: "Identifica posiciones relativas de rectas y reconoce ángulos rectos usando la escuadra.",
    practice: "Trazar calles perpendiculares y paralelas en planos de cuadrícula.",
  },
  {
    id: "m4-angulos-transportador",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Ángulos y uso del transportador",
    description: "Mide y clasifica ángulos en agudos, rectos y obtusos con respecto al ángulo de 90°.",
    practice: "Medir aberturas de puertas y agujas del reloj con transportador.",
  },
  {
    id: "m4-triangulos",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Triángulos: clasificación por lados y ángulos",
    description: "Clasifica triángulos en equiláteros, isósceles, escalenos y rectángulos.",
    practice: "Construir triángulos dadas las medidas de sus lados con regla y compás.",
  },
  {
    id: "m4-cuadrilateros",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Cuadriláteros y cuerpos geométricos",
    description: "Reconoce propiedades de cuadrados y rectángulos y describe cubos y prismas (caras, aristas, vértices).",
    practice: "Contar elementos de prismas rectangulares y armar desarrollos planos.",
  },
  {
    id: "m4-medidas-peso-cap",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Unidades de peso y capacidad",
    description: "Determina y compara masas y capacidades usando kg, g, mg y litros, mililitros.",
    practice: "Establecer equivalencias como 1 kg = 1.000 g y 1 litro = 1.000 ml.",
  },
  {
    id: "m4-tiempo",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Reloj, calendario y duraciones",
    description: "Mide duraciones de eventos y calcula horarios usando horas, minutos, semanas y meses.",
    practice: "Calcular cuánto dura un viaje o una clase escolar.",
  },
  {
    id: "m4-superficies",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Medición y estimación de superficies",
    description: "Estima y mide áreas de figuras poligonales mediante conteo de cuadrículas o baldosas.",
    practice: "Calcular cuántos azulejos cubren una pared rectangular.",
  },
  {
    id: "m4-perimetro",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Perímetro de figuras poligonales",
    description: "Calcula el contorno de figuras sumando las longitudes de sus lados en metros y centímetros.",
    practice: "Calcular metros de alambrado para un corral rectangular o triangular.",
  },
  {
    id: "m4-estadistica",
    subject: "matematica",
    axis: "Estadística y probabilidad",
    label: "Tablas y gráficos de barras",
    description: "Interpreta y extrae conclusiones de datos organizados en tablas y diagramas de barras.",
    practice: "Leer temperaturas medias y cantidades de alumnos en gráficos de barras.",
  },
  {
    id: "m4-planos",
    subject: "matematica",
    axis: "Geometría y medida",
    label: "Planos, croquis y coordenadas",
    description: "Interpreta planos barriales y croquis identificando sentidos de calles y puntos de referencia.",
    practice: "Indicar recorridos entre la plaza y la escuela en un plano urbano.",
  },
  {
    id: "m4-num-dictado",
    subject: "matematica",
    axis: "Números y operaciones",
    label: "Dictado de números grandes",
    description: "Escribe en cifras números escuchados oralmente hasta el orden de los cientos de miles.",
    practice: "Escribir números al dictado sin confundir el valor posicional de los ceros.",
  },

  // ==========================================
  // CIENCIAS SOCIALES
  // ==========================================
  {
    id: "s4-mapa-sc",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Santa Cruz en el mapa argentino",
    description: "Localiza la provincia de Santa Cruz en el territorio nacional, sus límites interprovinciales e internacionales.",
    practice: "Ubicar Santa Cruz, el mar Argentino y la cordillera de los Andes en el mapa.",
  },
  {
    id: "s4-departamentos-sc",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Departamentos y ciudades cabeceras",
    description: "Reconoce los 7 departamentos provinciales y sus localidades principales (Río Gallegos, Caleta Olivia, etc.).",
    practice: "Identificar las cabeceras departamentales en el mapa político santacruceño.",
  },
  {
    id: "s4-urbano-rural",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Espacios urbanos y rurales en Santa Cruz",
    description: "Compara el modo de vida, los servicios y el trabajo en las ciudades frente al campo santacruceño.",
    practice: "Contrastar actividades en una estancia patagónica frente a una ciudad portuaria.",
  },
  {
    id: "s4-relieve-sc",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Relieves: meseta, cordillera y costa",
    description: "Identifica las tres grandes unidades de relieve: la meseta escalonada, la cordillera andina y la costa atlántica.",
    practice: "Describir el relieve de la meseta con sus cañadones y acantilados costeros.",
  },
  {
    id: "s4-cuencas-lagos",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Ríos y grandes lagos santacruceños",
    description: "Conoce los ríos provinciales (Santa Cruz, Deseado, Chico) y los lagos glaciarios (Argentino, Viedma, San Martín).",
    practice: "Localizar las principales cuencas hídricas que desembocan en el Atlántico.",
  },
  {
    id: "s4-clima-arido",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Clima frío y árido patagónico",
    description: "Describe las características del clima: fuertes vientos del oeste, temperaturas bajas y escasas lluvias en la estepa.",
    practice: "Relacionar los vientos patagónicos con la aridez de la meseta central.",
  },
  {
    id: "s4-riesgos-naturales",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Riesgos naturales en Santa Cruz",
    description: "Identifica amenazas climáticas y geológicas: nevadas extraordinarias, heladas intensas y cenizas volcánicas.",
    practice: "Analizar cómo afecta una gran nevada a las rutas y a la ganadería provincial.",
  },
  {
    id: "s4-areas-protegidas",
    subject: "sociales",
    axis: "Espacio geográfico santacruceño",
    label: "Parques Nacionales y áreas protegidas",
    description: "Reconoce la importancia de proteger ecosistemas: PN Los Glaciares, Monte León, Bosques Petrificados y Cueva de las Manos.",
    practice: "Identificar atractivos y flora/fauna protegida en cada parque nacional de la provincia.",
  },
  {
    id: "s4-ganaderia-ovina",
    subject: "sociales",
    axis: "Actividades económicas y actores sociales",
    label: "Ganadería ovina y zafra lanera",
    description: "Comprende el circuito productivo de la lana ovina: esquila, comparsa, estancias y exportación por puertos.",
    practice: "Secuenciar las etapas de la producción lanera patagónica.",
  },
  {
    id: "s4-energia-mineria",
    subject: "sociales",
    axis: "Actividades económicas y actores sociales",
    label: "Petróleo, gas y minería provincial",
    description: "Ubica las cuencas petroleras (Golfo San Jorge y Austral) y yacimientos de oro y plata en el Macizo del Deseado.",
    practice: "Relacionar los recursos energéticos con ciudades como Caleta Olivia, Las Heras y Río Turbio.",
  },
  {
    id: "s4-turismo-pesca",
    subject: "sociales",
    axis: "Actividades económicas y actores sociales",
    label: "Turismo de montaña y pesca marítima",
    description: "Valora el turismo internacional (El Calafate, El Chaltén) y la actividad pesquera en puertos atlánticos.",
    practice: "Reconocer empleos y servicios vinculados al turismo y al puerto de Puerto Deseado.",
  },
  {
    id: "s4-problemas-ambientales",
    subject: "sociales",
    axis: "Actividades económicas y actores sociales",
    label: "Desertificación y cuidado ambiental",
    description: "Analiza causas del deterioro ambiental: sobrepastoreo ovino en la meseta y medidas de conservación del suelo.",
    practice: "Proponer prácticas sustentables para evitar la pérdida de suelo fértil en la estepa.",
  },
  {
    id: "s4-aonikenk",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "Los Aonikenk (tehuelches de la meseta)",
    description: "Conoce su forma de vida nómada cazadora-recolectora: uso del guanaco, toldos de cuero y cosmovisión.",
    practice: "Describir el quillango de piel de guanaco y la organización en bandas familiares.",
  },
  {
    id: "s4-canoeros-australes",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "Pueblos cazadores y canoeros australes",
    description: "Compara a los Selk'nam (cazadores terrestres) con los Yámanas (canoeros de los canales fueguinos).",
    practice: "Identificar adaptaciones al frío marítimo: grasa de foca, canoas de corteza y arpones.",
  },
  {
    id: "s4-mapuche",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "Pueblos Mapuche y Mapuche-Tehuelche",
    description: "Comprende la movilidad histórica de los pueblos originarios por la Patagonia sin fronteras nacionales.",
    practice: "Reconocer elementos culturales, telares y cosmovisión compartida en la región patagónica.",
  },
  {
    id: "s4-diaguitas",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "Los Diaguitas: agricultores del noroeste",
    description: "Analiza una sociedad sedentaria: terrazas de cultivo, alfarería, metalurgia del bronce y jefaturas.",
    practice: "Comparar la vida sedentaria de los valles calchaquíes con la vida nómada de la meseta austral.",
  },
  {
    id: "s4-incas",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "El Imperio Inca: civilización andina",
    description: "Describe la organización imperial inca: el ayllu, la red de caminos (Qhapaq Ñan), cultivos en terrazas y el Estado.",
    practice: "Identificar cómo el Imperio Inca administraba recursos mediante depósitos (tambos) y chasquis.",
  },
  {
    id: "s4-indigenas-presente",
    subject: "sociales",
    axis: "Sociedades indígenas a través del tiempo",
    label: "Pueblos originarios en el presente",
    description: "Valora la continuidad cultural, las comunidades actuales en Santa Cruz y los derechos reconocidos en la Constitución.",
    practice: "Reconocer la enseñanza bilingüe, celebraciones y la identidad comunitaria actual.",
  },
  {
    id: "s4-viajes-europeos",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "Motivos de los viajes europeos y adelantos",
    description: "Analiza la búsqueda de rutas comerciales a Oriente y adelantos náuticos: brújula, astrolabio, cartas náuticas y carabelas.",
    practice: "Explicar por qué las especias impulsaron las travesías atlánticas del siglo XV y XVI.",
  },
  {
    id: "s4-magallanes",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "Magallanes en San Julián (1520)",
    description: "Relata la invernada de la armada de Magallanes en Puerto San Julián, el primer contacto y la primera vuelta al mundo.",
    practice: "Analizar el viaje de la nao Victoria que completó la primera circunnavegación del planeta.",
  },
  {
    id: "s4-fundacion-ciudades",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "Corrientes colonizadoras y fundación de ciudades",
    description: "Identifica las tres corrientes (Norte, Oeste y Este) y funciones de ciudades como Santiago del Estero y Córdoba.",
    practice: "Localizar ciudades coloniales y explicar su función de defensa y aprovisionamiento.",
  },
  {
    id: "s4-sociedad-colonial",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "La sociedad colonial y sus estamentos",
    description: "Distingue los grupos sociales de la época colonial: españoles peninsulares, criollos, mestizos, indígenas y esclavizados.",
    practice: "Comparar derechos, trabajos y lugares de reunión en la colonia.",
  },
  {
    id: "s4-circuito-potosi",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "El circuito comercial del cerro Potosí",
    description: "Comprende cómo la minería de plata en Potosí articuló las economías regionales: mulas, tejidos y alimentos.",
    practice: "Seguir la ruta de las mulas desde el litoral hasta el Alto Perú.",
  },
  {
    id: "s4-conquista-espiritual",
    subject: "sociales",
    axis: "Conquista y colonización",
    label: "Conquista espiritual y mestizaje cultural",
    description: "Analiza el proceso de evangelización católica, las misiones y la mezcla cultural en el arte, lengua y costumbres.",
    practice: "Identificar elementos sincréticos en celebraciones tradicionales americanas.",
  },
  {
    id: "s4-constitucion",
    subject: "sociales",
    axis: "Organización política y ciudadana",
    label: "La Constitución Nacional y los tres poderes",
    description: "Reconoce la forma representativa, republicana y federal, y la división de poderes: Ejecutivo, Legislativo y Judicial.",
    practice: "Diferenciar funciones de senadores/diputados, presidente y jueces.",
  },
  {
    id: "s4-derechos-nino",
    subject: "sociales",
    axis: "Organización política y ciudadana",
    label: "Constitución de Santa Cruz y Derechos del Niño",
    description: "Conoce las instituciones provinciales (Concejo Deliberante, Legislatura) y los derechos esenciales de la niñez.",
    practice: "Ejemplificar derechos a la educación, salud, identidad y juego en la vida escolar.",
  },

  // ==========================================
  // CIENCIAS NATURALES
  // ==========================================
  {
    id: "n4-ambientes-sc",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Ambientes naturales de Santa Cruz",
    description: "Caracteriza la estepa patagónica, el bosque andino-patagónico y la costa marina atlántica.",
    practice: "Identificar qué seres vivos habitan la estepa árida y el bosque húmedo cordillerano.",
  },
  {
    id: "n4-flora-autoctona",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Flora autóctona santacruceña",
    description: "Reconoce especies nativas: coirón, mata negra, calafate, lenga, ñire y notro.",
    practice: "Diferenciar plantas espinosas de la estepa de árboles del bosque cordillerano.",
  },
  {
    id: "n4-fauna-adaptaciones",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Fauna nativa y adaptaciones morfo-fisiológicas",
    description: "Describe adaptaciones de guanacos, choiques, zorros, huemules y pumas al clima riguroso.",
    practice: "Explicar el pelaje espeso del guanaco y las patas corredoras del choique.",
  },
  {
    id: "n4-adaptaciones-frio",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Adaptaciones al frío y la sequedad",
    description: "Comprende estructuras protectoras en plantas (hojas pequeñas, espinas) y animales (capas de grasa, refugios).",
    practice: "Comparar adaptaciones de cactus y coirones para retener agua en la meseta.",
  },
  {
    id: "n4-reinos-vivos",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Los cuatro reinos de los seres vivos",
    description: "Clasifica organismos en animales, plantas, hongos y microorganismos según nutrición y estructura.",
    practice: "Reconocer que los hongos no hacen fotosíntesis y descomponen materia orgánica.",
  },
  {
    id: "n4-red-trofica",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Redes tróficas: productores, consumidores y descomponedores",
    description: "Explica el flujo de energía y materia en cadenas alimentarias de la estepa y el mar patagónico.",
    practice: "Armar cadenas tróficas uniendo pasto → guanaco → puma → bacterias descomponedoras.",
  },
  {
    id: "n4-impacto-conservacion",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Impacto humano y conservación de especies",
    description: "Analiza amenazas a especies en peligro como el macá tobiano (visón americano, gaviota cocinera) y áreas protegidas.",
    practice: "Proponer medidas de conservación de aves endémicas de las lagunas de la meseta.",
  },
  {
    id: "n4-esqueleto-huesos",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "El sistema osteo-artro-muscular: huesos y esqueleto",
    description: "Describe las funciones de sostén, protección de órganos vitales y reserva mineral del esqueleto humano.",
    practice: "Identificar huesos largos (fémur), cortos (vértebras) y planos (costillas, cráneo).",
  },
  {
    id: "n4-articulaciones-mov",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Articulaciones y movimiento corporal",
    description: "Clasifica articulaciones en móviles (rodilla, hombro), semimóviles (columna) e inmóviles (cráneo).",
    practice: "Observar cómo doblan y giran rodillas, codos, hombros y dedos.",
  },
  {
    id: "n4-musculos-tendones",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Músculos y tendones en movimiento integrado",
    description: "Explica cómo la contracción y relajación muscular mueven los huesos a través de los tendones.",
    practice: "Identificar músculos voluntarios (bíceps) e involuntarios (corazón).",
  },
  {
    id: "n4-cuidado-postura",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Cuidado del sistema osteo-artro-muscular",
    description: "Promueve hábitos saludables: postura correcta, uso de casco, ejercicio regular y nutrición con calcio.",
    practice: "Analizar posturas al sentarse con la mochila y levantar peso sin dañar la columna.",
  },
  {
    id: "n4-materiales-origen",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Materiales naturales y manufacturados",
    description: "Distingue materiales extraídos de la naturaleza (madera, lana, metales) de materiales sintéticos (plásticos).",
    practice: "Clasificar objetos cotidianos según el origen de sus materiales.",
  },
  {
    id: "n4-conductores-electricos",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Conducción térmica y eléctrica de los materiales",
    description: "Distingue buenos conductores de calor y electricidad (metales) de aislantes (madera, plástico, lana, goma).",
    practice: "Comparar cables de cobre recubiertos de plástico y mangos aislantes de ollas.",
  },
  {
    id: "n4-estados-materia",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Estados de la materia y cambios de fase",
    description: "Describe estados sólido, líquido y gaseoso y cambios de estado (fusión, solidificación, evaporación, condensación).",
    practice: "Explicar el deshielo de glaciares y la evaporación del agua al sol.",
  },
  {
    id: "n4-ciclo-del-agua",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "El ciclo del agua y los glaciares patagónicos",
    description: "Comprende las etapas del ciclo hidrológico y la reserva de agua dulce en los campos de hielo patagónicos.",
    practice: "Trazar el camino de una gota desde el océano Atlántico hasta las nieves cordilleranas.",
  },
  {
    id: "n4-mezclas-tipos",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Mezclas homogéneas y heterogéneas",
    description: "Distingue mezclas donde los componentes se diferencian a simple vista de aquellas que parecen uniformes.",
    practice: "Comparar agua con sal disuelta frente a agua con arena o ensaladas.",
  },
  {
    id: "n4-separacion-mezclas",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Métodos de separación de mezclas",
    description: "Elige el método adecuado para separar componentes: tamizado, filtración, decantación o imantación.",
    practice: "Planificar experimentos para separar arena y piedras, agua y harina, o clavos de aserrín.",
  },
  {
    id: "n4-luz-sombras",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "La luz: fuentes, propagación y sombras",
    description: "Explora fuentes naturales y artificiales de luz, su propagación rectilínea y cuerpos opacos, transparentes y translúcidos.",
    practice: "Proyectar sombras a distintas distancias con una linterna.",
  },
  {
    id: "n4-sonido",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "El sonido: vibración, tono, intensidad y timbre",
    description: "Caracteriza el sonido como vibración que viaja por medios materiales (aire, agua, sólidos) y diferencia tono, intensidad y timbre.",
    practice: "Comparar sonidos agudos y graves en cuerdas tensadas y tubos de viento.",
  },
  {
    id: "n4-magnetismo",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "Magnetismo: imanes y polos",
    description: "Explora la atracción y repulsión entre polos magnéticos y el uso de la brújula en la orientación.",
    practice: "Comprobar qué materiales atrae un imán y la repulsión entre polos iguales.",
  },
  {
    id: "n4-electrostatica",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "Electrostática: fuerzas a distancia por frotamiento",
    description: "Reconoce fenómenos electrostáticos al frotar globos, peines o reglas de plástico y observar atracción de papelitos.",
    practice: "Atraer pedacitos de papel frotando una regla con un paño de lana.",
  },
  {
    id: "n4-dimensiones-tierra",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "La Tierra como cuerpo cósmico y sus dimensiones",
    description: "Describe la forma esférica aproximada de la Tierra, sus polos y dimensiones en comparación con la Luna y el Sol.",
    practice: "Comparar el tamaño de la Tierra con una pelota de básquet frente a una bolita (Luna).",
  },
  {
    id: "n4-rotacion-dia-noche",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "Movimiento de rotación: día y noche",
    description: "Explica cómo el giro de la Tierra sobre su propio eje en 24 horas origina la sucesión del día y la noche.",
    practice: "Simular con un globo terráqueo y una lámpara el amanecer, mediodía y anochecer.",
  },
  {
    id: "n4-traslacion-estaciones",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "Movimiento de traslación y ciclo de estaciones",
    description: "Relaciona la órbita terrestre alrededor del Sol y la inclinación del eje con las 4 estaciones del año.",
    practice: "Explicar por qué en verano los días son más largos en Santa Cruz.",
  },
  {
    id: "n4-subsistemas-tierra",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "Subsistemas terrestres: geósfera, hidrósfera, atmósfera y biósfera",
    description: "Reconoce la Tierra como un sistema integrado por cuatro subsistemas en permanente interacción.",
    practice: "Identificar a qué subsistema pertenecen el glaciar, el aire cordillerano, la roca volcánica y los guanacos.",
  },
  {
    id: "n4-terremotos-volcanes",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "Geósfera: terremotos, volcanes y placas",
    description: "Identifica procesos endógenos de la geósfera: fallas, temblores sísmicos y erupciones volcánicas con cenizas.",
    practice: "Analizar el impacto de la ceniza del volcán Hudson en Santa Cruz y medidas de cuidado.",
  },
];
