// Habilidades de 4.º grado según el Diseño Curricular de Santa Cruz.
// Cada actividad declara qué habilidades trabaja y alimenta el progreso del alumno.
import { WorldSubject } from "@/types";

export interface SkillDef {
  id: string;
  subject: WorldSubject;
  label: string;
  axis: string;
  description: string;
  practice: string;
}

export const GRADE4_SKILLS: SkillDef[] = [
  // ==========================================
  // LENGUA
  // ==========================================
  {
    id: "l4-noticia",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "La noticia y sus partes",
    description: "Reconoce los elementos de la noticia (título, copete, cuerpo, epígrafe) y responde a las preguntas básicas.",
    practice: "Analizar noticias de diarios locales y señalar sus partes.",
  },
  {
    id: "l4-expositivo",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Texto expositivo e ideas clave",
    description: "Identifica el tema general, los subtemas por párrafo y las ideas principales en textos informativos.",
    practice: "Subrayar ideas clave y titular párrafos de textos de ciencias.",
  },
  {
    id: "l4-biografia",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Biografía y orden cronológico",
    description: "Comprende la vida de personajes históricos respetando la secuencia temporal y conectores temporales.",
    practice: "Ordenar líneas de tiempo y redactar biografías breves.",
  },
  {
    id: "l4-instructivo",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Texto instructivo y verbos de acción",
    description: "Identifica materiales/ingredientes y pasos secuenciales con verbos en infinitivo o imperativo.",
    practice: "Seguir y redactar recetas o instrucciones de juegos paso a paso.",
  },
  {
    id: "l4-carta",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Carta personal y correo",
    description: "Reconoce la estructura de la carta personal: lugar, fecha, saludo con dos puntos, cuerpo y despedida.",
    practice: "Escribir cartas familiares respetando la diagramación y fórmulas de cortesía.",
  },
  {
    id: "l4-fabula",
    subject: "lengua",
    axis: "Literatura",
    label: "Fábulas y moraleja",
    description: "Reconoce personajes animales personificados y deduce la enseñanza moral que transmite la fábula.",
    practice: "Lectura y debate de fábulas tradicionales y modernas.",
  },
  {
    id: "l4-poesia",
    subject: "lengua",
    axis: "Literatura",
    label: "Poesía: versos, estrofas y rimas",
    description: "Distingue versos y estrofas, reconoce rimas consonantes y asonantes e imágenes sensoriales.",
    practice: "Recitar poemas patagónicos y crear versos rimados.",
  },
  {
    id: "l4-teatro",
    subject: "lengua",
    axis: "Literatura",
    label: "Texto teatral y acotaciones",
    description: "Distingue parlamentos de personajes y acotaciones escénicas entre paréntesis.",
    practice: "Leer obras teatrales breves dramatizando voces y siguiendo acotaciones.",
  },
  {
    id: "l4-historieta",
    subject: "lengua",
    axis: "Lectura y comprensión",
    label: "Historieta, viñetas y globos",
    description: "Reconoce el código icónico-verbal: viñetas, globos de diálogo/pensamiento y onomatopeyas.",
    practice: "Completar globos de historietas y crear tiras cómicas.",
  },
  {
    id: "l4-parrafo-oracion",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Párrafo, oración y puntuación",
    description: "Reconoce la oración y el párrafo como unidades con sentido gráfico: sangría, mayúscula y puntos.",
    practice: "Puntuar textos separando en oraciones y párrafos.",
  },
  {
    id: "l4-sujeto-tacito",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sujeto expreso y sujeto tácito",
    description: "Identifica el sujeto en la oración y comprende la omisión del sujeto (sujeto tácito) como recurso de cohesión.",
    practice: "Transformar oraciones con sujeto expreso a oraciones con sujeto tácito y viceversa.",
  },
  {
    id: "l4-construccion-sustantiva",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Construcción sustantiva y núcleo",
    description: "Reconoce el sustantivo como núcleo de la construcción nominal y sus modificadores directos.",
    practice: "Expandir núcleos sustantivos con artículos y adjetivos concordantes.",
  },
  {
    id: "l4-sustantivo-propio-comun",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sustantivos propios y comunes",
    description: "Distingue sustantivos propios (con mayúscula inicial) de comunes en situaciones de escritura.",
    practice: "Clasificar sustantivos en mapas y relatos santacruceños.",
  },
  {
    id: "l4-sustantivo-colectivo",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Sustantivos individuales y colectivos",
    description: "Reconoce el sustantivo colectivo como aquel que en singular nombra a un conjunto de seres.",
    practice: "Emparejar sustantivos individuales y colectivos (oveja/rebaño, árbol/bosque).",
  },
  {
    id: "l4-adjetivos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Adjetivos calificativos y gentilicios",
    description: "Identifica adjetivos que señalan cualidades y gentilicios que indican origen geográfico.",
    practice: "Describir paisajes y personajes usando adjetivos variados y gentilicios.",
  },
  {
    id: "l4-concordancia",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Concordancia de género y número",
    description: "Aplica la concordancia en género (masculino/femenino) y número (singular/plural) entre sustantivo y adjetivo.",
    practice: "Detectar y corregir errores de concordancia en párrafos.",
  },
  {
    id: "l4-tiempos-verbales",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Tiempos verbales: pasado, presente y futuro",
    description: "Reconoce el tiempo en que ocurre la acción verbal y su adecuación al tipo de texto.",
    practice: "Conjugación de verbos habituales en diferentes tiempos.",
  },
  {
    id: "l4-preteritos",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Pretérito perfecto simple e imperfecto",
    description: "Distingue el pretérito perfecto simple (acción puntual) del imperfecto (acción continua o descripción).",
    practice: "Narrar anécdotas usando adecuadamente ambos pretéritos.",
  },
  {
    id: "l4-infinitivo",
    subject: "lengua",
    axis: "Reflexión sobre la lengua",
    label: "Verbos en infinitivo",
    description: "Identifica los verbos en su forma base terminados en -ar, -er e -ir.",
    practice: "Transformar verbos conjugados a infinitivo y usarlos en instructivos.",
  },
  {
    id: "l4-sinonimos-antonimos",
    subject: "lengua",
    axis: "Vocabulario y cohesión",
    label: "Sinónimos y antónimos",
    description: "Utiliza sinónimos para evitar repeticiones en textos y antónimos para expresar contrastes.",
    practice: "Buscar alternativas léxicas y opuestos en historias breves.",
  },
  {
    id: "l4-hiperonimos-hiponimos",
    subject: "lengua",
    axis: "Vocabulario y cohesión",
    label: "Hiperónimos e hipónimos",
    description: "Reconoce relaciones jerárquicas de significado: términos abarcadores y términos específicos.",
    practice: "Agrupar elementos bajo hiperónimos (calafate, mata negra, lenga -> plantas).",
  },
  {
    id: "l4-familias-palabras",
    subject: "lengua",
    axis: "Vocabulario y ortografía",
    label: "Familias de palabras y raíz común",
    description: "Reconoce la regularidad ortográfica de la raíz en las familias de palabras derivadas.",
    practice: "Construir familias léxicas conservando la ortografía de la raíz.",
  },
  {
    id: "l4-silaba-tonica",
    subject: "lengua",
    axis: "Ortografía y acentuación",
    label: "Separación en sílabas y sílaba tónica",
    description: "Divide palabras en sílabas e identifica la sílaba tónica que suena con mayor intensidad.",
    practice: "Paladear y marcar con aplausos la sílaba más fuerte de las palabras.",
  },
  {
    id: "l4-agudas-graves-esdrujulas",
    subject: "lengua",
    axis: "Ortografía y acentuación",
    label: "Palabras agudas, graves y esdrújulas",
    description: "Clasifica palabras según la posición de la sílaba tónica y aplica las reglas de tildación.",
    practice: "Clasificar palabras en cuadros y justificar por qué llevan o no tilde.",
  },
  {
    id: "l4-puntuacion-dialogo",
    subject: "lengua",
    axis: "Norma y uso",
    label: "Signos de diálogo, interrogación y exclamación",
    description: "Utiliza signos de interrogación (¿?), exclamación (¡!), dos puntos y raya de diálogo (—).",
    practice: "Puntuar diálogos entre personajes y formular preguntas con pronombres tildados.",
  },
  {
    id: "l4-ortografia-reglas",
    subject: "lengua",
    axis: "Norma y uso",
    label: "Reglas ortográficas: B/V, C/S/Z, G/J y homófonos",
    description: "Aplica regularidades ortográficas en palabras de uso frecuente y distingue homófonos usuales.",
    practice: "Ejercicios de selección y justificación ortográfica.",
  },
  {
    id: "l4-dictado-palabra",
    subject: "lengua",
    axis: "Escritura al dictado",
    label: "Dictado de palabras complejas",
    description: "Escribe con precisión ortográfica y tildación palabras con dificultades del grado.",
    practice: "Dictados semanales con sintetizador de voz.",
  },
  {
    id: "l4-dictado-oracion",
    subject: "lengua",
    axis: "Escritura al dictado",
    label: "Dictado de oraciones",
    description: "Escribe oraciones completas respetando mayúscula inicial, tildes y punto final.",
    practice: "Escucha atenta y transcripción de oraciones guiadas.",
  },

  // ==========================================
  // MATEMÁTICA
  // ==========================================
  {
    id: "m4-numeros-10000",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Números hasta 10.000",
    description: "Lee, escribe, compara y ordena números naturales hasta 10.000 con escalas regulares.",
    practice: "Completar escalas de 100 en 100 y 500 en 500 y ubicar en la recta.",
  },
  {
    id: "m4-numeros-100000",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Números hasta 100.000",
    description: "Opera con la familia de las decenas de mil, analizando regularidades y valor posicional.",
    practice: "Escalas de 1.000 en 1.000 y 10.000 en 10.000.",
  },
  {
    id: "m4-numeros-millon",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Números hasta el millón",
    description: "Lee, escribe y compara números de seis cifras hasta el orden de los millones.",
    practice: "Comparar poblaciones de ciudades y distancias astronómicas y terrestres.",
  },
  {
    id: "m4-descomposicion",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Descomposición aditiva y multiplicativa",
    description: "Compone y descompone números según el valor posicional de sus cifras con potencias de diez.",
    practice: "Escribir números como sumas de productos por 10, 100, 1.000 y 10.000.",
  },
  {
    id: "m4-numeros-romanos",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Sistema de numeración romano",
    description: "Interpreta y escribe números con el sistema romano (I, V, X, L, C, D, M) y sus reglas.",
    practice: "Leer siglos, capítulos de libros y fechas en monumentos históricos.",
  },
  {
    id: "m4-calculo-mental-sumaresta",
    subject: "matematica",
    axis: "Operaciones",
    label: "Cálculo mental de suma y resta",
    description: "Resuelve cálculos de sumas y restas utilizando descomposiciones y propiedades numéricas.",
    practice: "Juegos de agilidad mental sumando y restando múltiplos de 100 y 1.000.",
  },
  {
    id: "m4-estimacion",
    subject: "matematica",
    axis: "Operaciones",
    label: "Estimación y redondeo",
    description: "Anticipa y estima resultados de sumas y restas redondeando a centenas o millares cercanos.",
    practice: "Estimar gastos de compras antes de hacer el cálculo exacto.",
  },
  {
    id: "m4-problemas-pasos",
    subject: "matematica",
    axis: "Operaciones",
    label: "Problemas de varios pasos",
    description: "Resuelve situaciones problemáticas combinando sumas, restas y multiplicaciones en contexto real.",
    practice: "Resolver problemas de presupuestos de viaje y compras grupales.",
  },
  {
    id: "m4-tabla-pitagorica",
    subject: "matematica",
    axis: "Operaciones",
    label: "Tabla pitagórica y relaciones",
    description: "Domina el repertorio multiplicativo apoyándose en relaciones de dobles, mitades y propiedad distributiva.",
    practice: "Completar filas y columnas de la tabla pitagórica deduciendo productos desconocidos.",
  },
  {
    id: "m4-organizaciones-rectangulares",
    subject: "matematica",
    axis: "Operaciones",
    label: "Organizaciones rectangulares",
    description: "Resuelve problemas de filas y columnas con multiplicación y división asociada.",
    practice: "Calcular butacas de teatros, baldosas de patios y cajones de frutas.",
  },
  {
    id: "m4-multiplicacion-ceros",
    subject: "matematica",
    axis: "Operaciones",
    label: "Multiplicación por unidad seguida de ceros",
    description: "Aplica la regla de multiplicar por 10, 100 y 1.000 para resolver cálculos mentales con rapidez.",
    practice: "Multiplicar precios por 10, 100 o 1.000 paquetes.",
  },
  {
    id: "m4-multiplicacion-2cifras",
    subject: "matematica",
    axis: "Operaciones",
    label: "Multiplicación por dos cifras",
    description: "Comprende y aplica el algoritmo de la multiplicación por números de dos cifras mediante descomposiciones.",
    practice: "Multiplicar cantidades grandes desglosando decenas y unidades.",
  },
  {
    id: "m4-division-reparto",
    subject: "matematica",
    axis: "Operaciones",
    label: "División: reparto y partición",
    description: "Utiliza la división para repartir en partes iguales o averiguar cuántos grupos se forman.",
    practice: "Distribuir elementos equitativamente en paquetes o cajas.",
  },
  {
    id: "m4-division-resto-iteracion",
    subject: "matematica",
    axis: "Operaciones",
    label: "Análisis del resto e iteración",
    description: "Interpreta el significado del resto en problemas de división y calcula cuántas veces entra un número en otro.",
    practice: "Resolver problemas donde el resto exige agregar un viaje o paquete adicional.",
  },
  {
    id: "m4-division-ceros",
    subject: "matematica",
    axis: "Operaciones",
    label: "División por unidad seguida de ceros",
    description: "Divide números terminados en cero por 10, 100 y 1.000 identificando cociente y resto inmediato.",
    practice: "Cálculos mentales de repartos exactos entre 10, 100 y 1.000.",
  },
  {
    id: "m4-fracciones-usuales",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Fracciones usuales: 1/2, 1/4 y 1/8",
    description: "Reconoce y representa mitades, cuartos y octavos en contextos de medida (litros, kilos) y partición.",
    practice: "Gráficos de pizzas, chocolates y botellas divididas en partes iguales.",
  },
  {
    id: "m4-fracciones-mixtas",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Fracciones mayores que el entero y números mixtos",
    description: "Interpreta fracciones impropias (como 5/4 o 3/2) y su expresión mixta (1 1/4 o 1 1/2).",
    practice: "Medir ingredientes para recetas que requieren más de un kilo o litro.",
  },
  {
    id: "m4-fracciones-equivalentes",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Fracciones equivalentes y comparación",
    description: "Establece equivalencias entre fracciones usuales (2/4 = 1/2, 4/8 = 1/2) y compara tamaños.",
    practice: "Comparar tiras de fracciones y verificar equivalencias visuales.",
  },
  {
    id: "m4-calculo-fracciones",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Suma y resta mental de fracciones",
    description: "Resuelve adiciones y sustracciones sencillas entre fracciones con denominadores afines y enteros.",
    practice: "Sumar 1/4 + 1/4 = 1/2 o restar 1 - 1/4 = 3/4 en situaciones de compra.",
  },
  {
    id: "m4-decimales-dinero",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Números decimales en dinero y medida",
    description: "Interpreta el uso social de los decimales en precios con centavos y longitudes con coma.",
    practice: "Sumar tickets de compras y leer medidas en cintas métricas.",
  },
  {
    id: "m4-decimos-centesimos",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Décimos y centésimos",
    description: "Relaciona expresiones decimales con fracciones decimales: 0,1 con 1/10 y 0,01 con 1/100.",
    practice: "Canjear monedas de 10 centavos por pesos y centímetros por metros.",
  },
  {
    id: "m4-comparar-sumar-decimales",
    subject: "matematica",
    axis: "Fracciones y decimales",
    label: "Comparación y suma de decimales",
    description: "Compara números decimales y realiza sumas mentales sencillas en contexto monetario.",
    practice: "Comparar precios de góndola y calcular vueltos exactos.",
  },
  {
    id: "m4-rectas-angulos",
    subject: "matematica",
    axis: "Geometría",
    label: "Rectas paralelas, perpendiculares y ángulos",
    description: "Identifica rectas paralelas y perpendiculares y clasifica ángulos en rectos, agudos y obtusos.",
    practice: "Identificar ángulos en esquinas de casas, calles de planos y agujas del reloj.",
  },
  {
    id: "m4-triangulos-cuadrilateros",
    subject: "matematica",
    axis: "Geometría",
    label: "Triángulos y cuadriláteros",
    description: "Clasifica triángulos según sus lados (equilátero, isósceles, escaleno) y reconoce rectángulos y cuadrados.",
    practice: "Medir lados de figuras con regla y comprobar ángulos rectos con escuadra.",
  },
  {
    id: "m4-circunferencia-cuerpos",
    subject: "matematica",
    axis: "Geometría",
    label: "Círculo, circunferencia y cuerpos geométricos",
    description: "Reconoce radio, diámetro y centro de la circunferencia, y caras, aristas y vértices en prismas y cubos.",
    practice: "Trazar círculos con compás y contar elementos en cuerpos geométricos 3D.",
  },
  {
    id: "m4-medidas-perimetro",
    subject: "matematica",
    axis: "Medida",
    label: "Medidas y cálculo de perímetro",
    description: "Utiliza unidades de longitud (m, cm, km), peso (kg, g), capacidad (l, ml) y calcula el contorno o perímetro.",
    practice: "Sumar los lados de canchas y terrenos para hallar su perímetro.",
  },
  {
    id: "m4-num-dictado",
    subject: "matematica",
    axis: "Número y numeración",
    label: "Dictado de números grandes",
    description: "Escribe números de cuatro y cinco cifras al escucharlos en el sintetizador.",
    practice: "Dictados regulares de números grandes.",
  },

  // ==========================================
  // CIENCIAS SOCIALES
  // ==========================================
  {
    id: "s4-santa-cruz-argentina",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Santa Cruz en el mapa de Argentina",
    description: "Localiza la provincia de Santa Cruz, sus límites interprovinciales e internacionales y el Mar Argentino.",
    practice: "Señalar en el mapa político de Argentina la provincia y sus límites.",
  },
  {
    id: "s4-departamentos",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Los departamentos de Santa Cruz",
    description: "Identifica los 7 departamentos santacruceños y sus respectivas ciudades cabeceras.",
    practice: "Ubicar departamentos en el mapa provincial (Guer Aike, Deseado, Magallanes, etc.).",
  },
  {
    id: "s4-relieves",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Relieves santacruceños: cordillera, meseta y costa",
    description: "Distingue los tres grandes relieves: la Cordillera de los Andes al oeste, las mesetas al centro y los acantilados costeros al este.",
    practice: "Reconocer en fotos y mapas físicos las tres zonas de relieve.",
  },
  {
    id: "s4-hidrografia-clima",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Ríos, lagos y clima de Santa Cruz",
    description: "Describe los grandes ríos y lagos provinciales y las características del clima árido frío estepario.",
    practice: "Identificar el recorrido del río Santa Cruz y la influencia de los vientos del oeste.",
  },
  {
    id: "s4-recursos-economia",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Recursos naturales y actividades económicas",
    description: "Reconoce las principales actividades productivas: ganadería ovina, petróleo, gas, minería y pesca.",
    practice: "Relacionar los recursos naturales con los centros productivos de la provincia.",
  },
  {
    id: "s4-areas-protegidas",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Parques Nacionales y áreas protegidas",
    description: "Valora la conservación de la naturaleza en los Parques Nacionales de Santa Cruz (Glaciares, Monte León, etc.).",
    practice: "Investigar las características y fauna protegida de cada parque nacional santacruceño.",
  },
  {
    id: "s4-riesgos-ambientales",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Riesgos naturales y problemas ambientales",
    description: "Reconoce fenómenos naturales extremos (nevadas, cenizas volcánicas) y problemas ambientales como la desertificación.",
    practice: "Analizar causas del sobrepastoreo y medidas de protección ambiental.",
  },
  {
    id: "s4-estancia-patagonica",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "La estancia ovina y el espacio rural",
    description: "Describe la organización de la estancia patagónica, el trabajo del puestero y la zafra de esquila.",
    practice: "Secuenciar las etapas de la producción de lana en la estancia.",
  },
  {
    id: "s4-ciudades-servicios",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Las ciudades y los servicios urbanos",
    description: "Identifica las funciones de las ciudades santacruceñas y la importancia de las redes de gas, agua potable y electricidad.",
    practice: "Comparar las condiciones de vida en ciudades grandes y pequeñas de la provincia.",
  },
  {
    id: "s4-rutas-conectividad",
    subject: "sociales",
    axis: "Sociedades y espacios geográficos",
    label: "Rutas y conectividad patagónica",
    description: "Reconoce la importancia de la Ruta 40, la Ruta 3, los puertos y aeropuertos para unir el extenso territorio.",
    practice: "Trazar recorridos por las rutas provinciales uniendo localidades distantes.",
  },
  {
    id: "s4-aonikenk-caza",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Los Aonikenk (Tehuelches) cazadores nómadas",
    description: "Conoce el modo de vida de los cazadores-recolectores de la Patagonia y sus técnicas de caza de guanacos y choiques.",
    practice: "Analizar el uso de boleadoras y el arco en el entorno estepario.",
  },
  {
    id: "s4-aonikenk-vida",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Vida cotidiana Aonikenk: toldo y quillango",
    description: "Comprende la vivienda desmontable (kau), la vestimenta de pieles (quillango) y la figura de Elal en sus creencias.",
    practice: "Describir cómo se fabricaban los toldos y las capas de piel de guanaco.",
  },
  {
    id: "s4-pueblos-fueguinos",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Pueblos de Tierra del Fuego: Selk'nam y Yámanas",
    description: "Distingue a los Selk'nam cazadores terrestres de los Yámanas canoeros y recolectores marinos australes.",
    practice: "Comparar adaptaciones de los pueblos fueguinos al frío extremo y al mar.",
  },
  {
    id: "s4-diaguitas-incas",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Los Diaguitas: agricultores del Noroeste",
    description: "Contrasta los pueblos nómadas patagónicos con los agricultores sedentarios del NOA (terrazas de cultivo y pucarás).",
    practice: "Comparar la vida nómada de la Patagonia con la vida sedentaria andina.",
  },
  {
    id: "s4-magallanes-san-julian",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Magallanes en San Julián (1520)",
    description: "Conoce el arribo de la expedición de Magallanes a Puerto San Julián y el primer encuentro con los habitantes patagónicos.",
    practice: "Reconstruir el viaje de Magallanes y el origen de la palabra 'patagones'.",
  },
  {
    id: "s4-exploradores-patagonia",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "Exploradores de la Patagonia austral",
    description: "Reconoce expediciones científicas y de exploración costera (Darwin, Fitz Roy, Piedra Buena).",
    practice: "Seguir el viaje del bergantín Beagle por los canales y ríos patagónicos.",
  },
  {
    id: "s4-sociedad-colonial",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "La sociedad colonial americana",
    description: "Identifica los diferentes grupos sociales de la época colonial (españoles, criollos, mestizos, indígenas y afrodescendientes).",
    practice: "Analizar roles sociales, oficios y desigualdades en la vida colonial.",
  },
  {
    id: "s4-trabajo-potosi",
    subject: "sociales",
    axis: "Sociedades a través del tiempo",
    label: "El circuito de la plata de Potosí",
    description: "Comprende el eje económico minero de Potosí, el sistema de mita y el comercio con carretas y mulas.",
    practice: "Trazar en el mapa colonial el camino desde el Alto Perú hasta Buenos Aires.",
  },
  {
    id: "s4-gobierno-niveles",
    subject: "sociales",
    axis: "Organización social y ciudadana",
    label: "Niveles de gobierno: Municipio, Provincia y Nación",
    description: "Distingue las autoridades municipales (Intendente), provinciales (Gobernador) y nacionales (Presidente).",
    practice: "Relacionar cada problema comunitario con el nivel de gobierno que debe intervenir.",
  },
  {
    id: "s4-derechos-convivencia",
    subject: "sociales",
    axis: "Organización social y ciudadana",
    label: "Derechos del niño y convivencia democrática",
    description: "Valora las normas de convivencia social, el respeto por las diferencias y los derechos fundamentales de las infancias.",
    practice: "Debatir soluciones pacíficas y consensuadas a conflictos escolares.",
  },

  // ==========================================
  // CIENCIAS NATURALES
  // ==========================================
  {
    id: "n4-ambientes-santa-cruz",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Ambientes naturales de Santa Cruz",
    description: "Caracteriza y compara la estepa patagónica, el bosque andino y el litoral costero marino.",
    practice: "Clasificar imágenes y descripciones según el ambiente santacruceño correspondiente.",
  },
  {
    id: "n4-fauna-autoctona",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Fauna autóctona santacruceña",
    description: "Reconoce especies animales nativas: guanaco, choique, mara, puma, zorro colorado, pingüino y cóndor.",
    practice: "Identificar huellas, siluetas y hábitos de los animales patagónicos.",
  },
  {
    id: "n4-flora-autoctona",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Flora autóctona de la meseta y el bosque",
    description: "Reconoce plantas nativas: coirón, neneo, mata negra y calafate en la estepa; lenga y ñire en el bosque.",
    practice: "Relacionar cada especie vegetal con el ambiente donde crece.",
  },
  {
    id: "n4-adaptaciones-vivos",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Adaptaciones al frío y al viento",
    description: "Explica cómo plantas y animales adaptan sus cuerpos (hojas pequeñas, espinas, pelaje denso, grasa) al clima hostil.",
    practice: "Analizar por qué las hojas del coirón son duras y cómo los pingüinos conservan el calor.",
  },
  {
    id: "n4-reinos-seres-vivos",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Los grandes reinos de la vida",
    description: "Distingue características clave de animales (heterótrofos), plantas (autótrofas), hongos y microorganismos.",
    practice: "Clasificar organismos vivos y explicar por qué los hongos no son plantas.",
  },
  {
    id: "n4-cadenas-troficas",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Cadenas y redes tróficas",
    description: "Comprende el flujo de energía entre productores (plantas), consumidores herbívoros/carnívoros y descomponedores.",
    practice: "Armar cadenas alimentarias de la estepa y del mar patagónico.",
  },
  {
    id: "n4-impacto-conservacion",
    subject: "naturales",
    axis: "Seres vivos y ambientes",
    label: "Impacto humano y conservación",
    description: "Evalúa el efecto de especies invasoras (castor, visón) y la importancia de proteger ecosistemas nativos.",
    practice: "Proponer acciones comunitarias de cuidado del suelo, el agua y la fauna.",
  },
  {
    id: "n4-esqueleto-huesos",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "El esqueleto humano y los huesos",
    description: "Identifica las funciones principales de los huesos: sostén del cuerpo y protección de órganos vitales.",
    practice: "Localizar cráneo, costillas, columna vertebral y fémur en el modelo del esqueleto.",
  },
  {
    id: "n4-articulaciones",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Articulaciones y movimiento",
    description: "Distingue articulaciones fijas, semimóviles y móviles, y la función de ligamentos y cartílagos.",
    practice: "Observar cómo doblan y giran rodillas, codos, hombros y dedos.",
  },
  {
    id: "n4-musculos-tendones",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Músculos y tendones",
    description: "Explica cómo la contracción y relajación muscular mueven los huesos a través de los tendones.",
    practice: "Identificar músculos voluntarios (bíceps) e involuntarios (corazón).",
  },
  {
    id: "n4-cuidado-postura",
    subject: "naturales",
    axis: "El cuerpo humano",
    label: "Cuidado del sistema osteo-artro-muscular",
    description: "Promueve hábitos saludables: postura correcta, uso de casco, ejercicio regular y nutrición con calcio.",
    practice: "Analizar posturas al sentarse con la mochila y levantar peso sin dañar la columna.",
  },
  {
    id: "n4-materiales-origen",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Materiales naturales y artificiales",
    description: "Distingue materiales extraídos de la naturaleza (madera, lana, metales) de materiales sintéticos (plásticos).",
    practice: "Clasificar objetos cotidianos según el origen de sus materiales.",
  },
  {
    id: "n4-propiedades-materiales",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Propiedades de los materiales",
    description: "Relaciona usos con propiedades mecánicas y térmicas: dureza, fragilidad, elasticidad y flexibilidad.",
    practice: "Comprobar qué materiales resisten golpes, se doblan o conducen el calor.",
  },
  {
    id: "n4-estados-materia",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Estados de la materia y cambios de estado",
    description: "Describe estados sólido, líquido y gaseoso y cambios de estado (fusión, solidificación, evaporación, condensación).",
    practice: "Explicar el deshielo de glaciares y la evaporación del agua al sol.",
  },
  {
    id: "n4-ciclo-del-agua",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "El ciclo del agua y los glaciares",
    description: "Comprende las etapas del ciclo hidrológico y la reserva de agua dulce en los campos de hielo patagónicos.",
    practice: "Trazar el camino de una gota desde el océano Atlántico hasta las nieves cordilleranas.",
  },
  {
    id: "n4-mezclas-tipos",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Mezclas homogéneas y heterogéneas",
    description: "Distingue mezclas donde los componentes se diferencian a simple vista de aquellas que parecen uniformes.",
    practice: "Comparar agua con sal disuelta frente a agua con arena o ensaladas.",
  },
  {
    id: "n4-separacion-mezclas",
    subject: "naturales",
    axis: "Los materiales y sus cambios",
    label: "Métodos de separación de mezclas",
    description: "Elige el método adecuado para separar componentes: tamizado, filtración, decantación o imantación.",
    practice: "Planificar experimentos para separar arena y piedras, agua y harina, o clavos de aserrín.",
  },
  {
    id: "n4-calor-temperatura",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "Calor, temperatura y aislantes térmicos",
    description: "Distingue calor (energía en tránsito) de temperatura (°C) y reconoce buenos conductores y aislantes térmicos.",
    practice: "Comparar cucharas de metal y de madera en agua caliente y el abrigo de lana.",
  },
  {
    id: "n4-luz-magnetismo",
    subject: "naturales",
    axis: "Fenómenos del mundo físico",
    label: "Luz, sombras y magnetismo",
    description: "Explora la propagación en línea recta de la luz, formación de sombras y atracción/repulsión entre polos de imanes.",
    practice: "Proyectar sombras a distintas distancias y usar imanes con brújulas.",
  },
  {
    id: "n4-tierra-universo",
    subject: "naturales",
    axis: "La Tierra y el Universo",
    label: "La Tierra: movimientos y subsistemas",
    description: "Explica la rotación (día y noche), la traslación (estaciones) y los cuatro subsistemas: geosfera, hidrosfera, atmósfera y biosfera.",
    practice: "Modelar con una esfera y una linterna el giro de la Tierra y la iluminación solar.",
  },
];
