// Catálogo de mundos de 4.º grado según el Diseño Curricular de Santa Cruz.
// Ids: 4 + materia + número
//   - Lengua: 41001 a 41026 (26 mundos)
//   - Matemática: 42001 a 42026 (26 mundos)
//   - Ciencias Sociales: 43001 a 43020 (20 mundos)
//   - Ciencias Naturales: 44001 a 44020 (20 mundos)
// Total: 92 mundos comunes.
import { WorldDef, WorldDifficultyVars, WorldSubject } from "@/types";

const SUBJECT_BASE: Record<WorldSubject, number> = {
  lengua: 41000,
  matematica: 42000,
  sociales: 43000,
  naturales: 44000,
};

const PALETTES: Record<WorldSubject, [string, string][]> = {
  lengua: [["#fde68a", "#f59e0b"], ["#fbcfe8", "#ec4899"], ["#ddd6fe", "#8b5cf6"], ["#fed7aa", "#f97316"]],
  matematica: [["#bfdbfe", "#3b82f6"], ["#bbf7d0", "#22c55e"], ["#fecaca", "#ef4444"], ["#c7d2fe", "#6366f1"]],
  sociales: [["#bae6fd", "#0284c7"], ["#fde68a", "#ca8a04"], ["#fecdd3", "#e11d48"], ["#d9f99d", "#65a30d"]],
  naturales: [["#bbf7d0", "#16a34a"], ["#a5f3fc", "#0891b2"], ["#fef08a", "#eab308"], ["#e9d5ff", "#9333ea"]],
};

interface Spec {
  n: number;
  name: string;
  emoji: string;
  description: string;
  objective: string;
  contents: string[];
  skills: string[];
  after?: number[];
  vars?: WorldDifficultyVars;
  kind?: WorldDef["kind"];
  activityCount?: number;
}

function build(subject: WorldSubject, specs: Spec[]): WorldDef[] {
  return specs.map((s) => {
    const pal = PALETTES[subject][(s.n - 1) % PALETTES[subject].length];
    return {
      id: SUBJECT_BASE[subject] + s.n,
      grade: 4,
      worldNumber: s.n,
      name: s.name,
      emoji: s.emoji,
      subject,
      category: "oralidad-inicial", // Despacho por grado a grade4/content
      description: s.description,
      objective: s.objective,
      contents: s.contents,
      skills: s.skills,
      prerequisites: (s.after ?? (s.n > 1 ? [s.n - 1] : [])).map((x) => SUBJECT_BASE[subject] + x),
      difficultyVars: s.vars,
      kind: s.kind ?? "normal",
      activityCount: s.activityCount ?? 8,
      colorFrom: pal[0],
      colorTo: pal[1],
      difficulty: "basico",
      assessment:
        "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
    };
  });
}

// ------------------------------------------------------------------
// LENGUA (41001 - 41026)
// ------------------------------------------------------------------
export const GRADE4_LENGUA: WorldDef[] = build("lengua", [
  {
    n: 1,
    name: "La Noticia y sus Partes",
    emoji: "📰",
    description: "Titular, copete, cuerpo y epígrafes en noticias santacruceñas.",
    objective: "Reconocer la superestructura de la noticia periodística y responder a las preguntas básicas de la información.",
    contents: ["La noticia: partes constitutivas (volanta, título, copete, cuerpo)", "Paratextos: epígrafes y fotografías", "Preguntas guía de la noticia"],
    skills: ["l4-noticia"],
    after: [],
  },
  {
    n: 2,
    name: "El Texto Expositivo y sus Claves",
    emoji: "📚",
    description: "Tema general, párrafos y subtemas en artículos de ciencias.",
    objective: "Identificar el tema global, los subtemas por párrafo y las ideas principales en textos explicativos.",
    contents: ["El texto expositivo: propósito informativo", "Organización en párrafos y subtemas", "Ideas principales y secundarias"],
    skills: ["l4-expositivo"],
    after: [1],
  },
  {
    n: 3,
    name: "La Biografía y el Tiempo",
    emoji: "⏳",
    description: "La vida de exploradores y pioneros en orden cronológico.",
    objective: "Comprender la narración biográfica respetando el eje temporal y conectores cronológicos.",
    contents: ["La biografía y autobiografía", "Orden cronológico y causas-consecuencias", "Conectores temporales (primero, luego, más tarde, finalmente)"],
    skills: ["l4-biografia"],
    after: [2],
  },
  {
    n: 4,
    name: "Textos Instructivos y Recetas",
    emoji: "📋",
    description: "Pasos ordenados, ingredientes y verbos de acción precisos.",
    objective: "Interpretar y producir textos instructivos con claridad secuencial y verbos adecuados.",
    contents: ["El texto instructivo: materiales y procedimientos", "Verbos en infinitivo e imperativo", "Orden y jerarquía de las acciones"],
    skills: ["l4-instructivo", "l4-infinitivo"],
    after: [3],
  },
  {
    n: 5,
    name: "La Carta y el Correo Personal",
    emoji: "✉️",
    description: "Lugar, fecha, saludo con dos puntos, mensaje y firma.",
    objective: "Reconocer las convenciones epistolares y las fórmulas de apertura y cierre.",
    contents: ["La carta personal y correo electrónico", "Estructura epistolar: encabezado, cuerpo y despedida", "Los dos puntos tras el saludo inicial"],
    skills: ["l4-carta"],
    after: [4],
  },
  {
    n: 6,
    name: "Fábulas y Moralejas",
    emoji: "🦊",
    description: "Animales que dialogan y dejan una sabia enseñanza moral.",
    objective: "Identificar características de la fábula, la personificación y deducir la moraleja.",
    contents: ["La fábula: estructura narrativa y personajes arquetípicos", "Personificación de animales", "La moraleja como enseñanza reflexiva"],
    skills: ["l4-fabula"],
    after: [5],
  },
  {
    n: 7,
    name: "Poesía: Versos y Rimas",
    emoji: "🪶",
    description: "Estrofas, versos que riman e imágenes sensoriales patagónicas.",
    objective: "Reconocer la estructura del poema (verso, estrofa) y distinguir rima consonante y asonante.",
    contents: ["El poema: versos y estrofas", "Rima consonante y asonante", "Imágenes sensoriales (visuales, auditivas, táctiles)"],
    skills: ["l4-poesia"],
    after: [6],
  },
  {
    n: 8,
    name: "El Teatro y las Acotaciones",
    emoji: "🎭",
    description: "Parlamentos de personajes y acotaciones escénicas entre paréntesis.",
    objective: "Diferenciar diálogos de personajes y acotaciones del director en obras teatrales.",
    contents: ["El texto dramático: personajes y parlamentos", "Las acotaciones escénicas entre paréntesis", "La puesta en escena y el conflicto dramático"],
    skills: ["l4-teatro"],
    after: [7],
  },
  {
    n: 9,
    name: "Historieta: Viñetas y Globos",
    emoji: "💭",
    description: "Globos de diálogo, pensamiento, grito y onomatopeyas.",
    objective: "Interpretar el lenguaje icónico-verbal de la historieta y distinguir tipos de globos.",
    contents: ["La historieta: viñetas y orden de lectura", "Tipos de globos: habla, pensamiento, susurro y grito", "Onomatopeyas y cartuchos narrativos"],
    skills: ["l4-historieta"],
    after: [8],
  },
  {
    n: 10,
    name: "El Párrafo y la Oración",
    emoji: "✍️",
    description: "Sangría, mayúscula inicial, punto y seguido y punto y aparte.",
    objective: "Reconocer el párrafo y la oración como unidades de sentido con límites gráficos claros.",
    contents: ["El párrafo y la oración como unidades de sentido", "Uso de sangría y mayúscula inicial", "Punto seguido, punto aparte y punto final"],
    skills: ["l4-parrafo-oracion"],
    after: [9],
  },
  {
    n: 11,
    name: "Sujeto Expreso y Sujeto Tácito",
    emoji: "🔍",
    description: "Descubrir quién hace la acción cuando está escrito y cuando se omite.",
    objective: "Identificar el sujeto oracional y justificar la omisión del sujeto tácito como recurso de cohesión.",
    contents: ["Estructura oracional: sujeto y predicado", "Sujeto expreso simple y compuesto", "El sujeto tácito para evitar repeticiones"],
    skills: ["l4-sujeto-tacito"],
    after: [10],
  },
  {
    n: 12,
    name: "Construcción Sustantiva y Núcleo",
    emoji: "🧱",
    description: "El sustantivo como núcleo acompañado por artículos y adjetivos.",
    objective: "Analizar construcciones sustantivas reconociendo el núcleo y modificadores directos concordantes.",
    contents: ["La construcción sustantiva", "El núcleo del sujeto", "Modificadores directos: artículos y adjetivos"],
    skills: ["l4-construccion-sustantiva", "l4-concordancia"],
    after: [11],
  },
  {
    n: 13,
    name: "Sustantivos Propios y Comunes",
    emoji: "🏷️",
    description: "Nombres de ciudades, ríos y personas frente a objetos y animales.",
    objective: "Clasificar sustantivos propios y comunes aplicando la mayúscula inicial obligatoria.",
    contents: ["Sustantivos comunes (cosas, animales, seres)", "Sustantivos propios (topónimos, antropónimos)", "Regla de mayúscula en nombres propios"],
    skills: ["l4-sustantivo-propio-comun"],
    after: [12],
  },
  {
    n: 14,
    name: "Sustantivos Colectivos",
    emoji: "🐑",
    description: "Palabras en singular que nombran conjuntos: rebaño, cardumen, bosque.",
    objective: "Diferenciar sustantivos individuales y colectivos y ampliar el campo semántico.",
    contents: ["Sustantivos individuales y sustantivos colectivos", "Correspondencias léxicas en contexto patagónico", "Concordancia singular con sustantivo colectivo"],
    skills: ["l4-sustantivo-colectivo"],
    after: [13],
  },
  {
    n: 15,
    name: "Adjetivos Calificativos y Gentilicios",
    emoji: "🎨",
    description: "Palabras que describen cualidades y lugares de origen.",
    objective: "Emplear adjetivos calificativos para describir con detalle y gentilicios para señalar procedencia.",
    contents: ["Adjetivos calificativos: cualidades y estados", "Adjetivos gentilicios (santacruceño, calafateño)", "Terminaciones típicas de gentilicios"],
    skills: ["l4-adjetivos"],
    after: [14],
  },
  {
    n: 16,
    name: "Concordancia de Género y Número",
    emoji: "⚖️",
    description: "Hacer coincidir artículos, sustantivos y adjetivos sin errores.",
    objective: "Aplicar sistemáticamente la concordancia de género (masculino/femenino) y número (singular/plural).",
    contents: ["Género y número en el sintagma nominal", "Casos especiales de concordancia", "Detección y corrección de discordancias en textos"],
    skills: ["l4-concordancia"],
    after: [15],
  },
  {
    n: 17,
    name: "Tiempos Verbales: Pasado, Presente y Futuro",
    emoji: "⏰",
    description: "Identificar cuándo suceden los hechos según la forma del verbo.",
    objective: "Reconocer y conjugar verbos en presente, pretérito y futuro adecuándolos a la narración.",
    contents: ["La noción de tiempo verbal", "El presente en descripciones y exposiciones", "El pretérito en relatos y el futuro en planes"],
    skills: ["l4-tiempos-verbales"],
    after: [16],
  },
  {
    n: 18,
    name: "Pretérito Perfecto e Imperfecto",
    emoji: "📜",
    description: "Acciones puntuales que terminaron frente a acciones habituales (-aba, -ía).",
    objective: "Diferenciar el pretérito perfecto simple del pretérito imperfecto en la narración.",
    contents: ["Pretérito perfecto simple: acciones concluidas puntuales", "Pretérito imperfecto: acciones duraderas y descripciones", "Terminaciones del pretérito imperfecto: -aba e -ía"],
    skills: ["l4-preteritos"],
    after: [17],
  },
  {
    n: 19,
    name: "Verbos en Infinitivo",
    emoji: "🎯",
    description: "El nombre del verbo terminado en -ar, -er e -ir en textos y consignas.",
    objective: "Reconocer las formas no conjugadas del infinitivo y utilizarlas en instructivos y definiciones.",
    contents: ["El infinitivo verbal y las tres conjugaciones (-ar, -er, -ir)", "Uso del infinitivo en consignas escolares e instructivos", "Reconocimiento del verbo raíz"],
    skills: ["l4-infinitivo"],
    after: [18],
  },
  {
    n: 20,
    name: "Sinónimos y Antónimos",
    emoji: "🔄",
    description: "Palabras de significado semejante para enriquecer el texto y palabras opuestas.",
    objective: "Utilizar sinónimos como mecanismo de cohesión léxica y antónimos para formular contrastes.",
    contents: ["Sinónimos: sustitución para evitar repeticiones", "Antónimos: pares de significados opuestos", "Sinonimia según el contexto de la oración"],
    skills: ["l4-sinonimos-antonimos"],
    after: [19],
  },
  {
    n: 21,
    name: "Hiperónimos e Hipónimos",
    emoji: "🌳",
    description: "Palabras generales que engloban familias de términos específicos.",
    objective: "Organizar el vocabulario en redes semánticas jerarquizadas mediante hiperónimos e hipónimos.",
    contents: ["Hiperónimos como conceptos abarcadores", "Hipónimos como elementos específicos", "Uso de hiperónimos para resumir enumeraciones"],
    skills: ["l4-hiperonimos-hiponimos"],
    after: [20],
  },
  {
    n: 22,
    name: "Familias de Palabras y Raíz Común",
    emoji: "🌱",
    description: "Palabras emparentadas que conservan la ortografía de su raíz.",
    objective: "Identificar la raíz léxica invariable y aplicar la regularidad ortográfica a palabras derivadas.",
    contents: ["La raíz de la palabra y morfemas derivados", "Familias léxicas (viento/ventoso, mar/marino)", "Conservación de la ortografía en la raíz"],
    skills: ["l4-familias-palabras"],
    after: [21],
  },
  {
    n: 23,
    name: "Sílabas y la Sílaba Tónica",
    emoji: "🥁",
    description: "Separar palabras en sílabas y descubrir dónde suena la fuerza de la voz.",
    objective: "Dividir correctamente en sílabas e identificar la sílaba tónica en última, penúltima o antepenúltima posición.",
    contents: ["Segmentación en sílabas", "Sílaba tónica vs. sílabas átonas", "Posición de la sílaba tónica"],
    skills: ["l4-silaba-tonica"],
    after: [22],
  },
  {
    n: 24,
    name: "Palabras Agudas, Graves y Esdrújulas",
    emoji: "⚡",
    description: "Reglas generales de acentuación para saber cuándo llevan tilde escrita.",
    objective: "Clasificar palabras en agudas, graves y esdrújulas y aplicar las reglas de tildación ortográfica.",
    contents: ["Agudas: acento en la última sílaba (tilde en n, s o vocal)", "Graves: acento en la penúltima sílaba (tilde sin n, s o vocal)", "Esdrújulas: acento en la antepenúltima (siempre con tilde)"],
    skills: ["l4-agudas-graves-esdrujulas"],
    after: [23],
  },
  {
    n: 25,
    name: "Signos de Diálogo y Exclamación",
    emoji: "💬",
    description: "La raya de diálogo, dos puntos y signos dobles de pregunta y exclamación.",
    objective: "Puntuar diálogos de manera normativa y tildar pronombres interrogativos y exclamativos.",
    contents: ["La raya de diálogo (—) y dos puntos en el intercambio", "Signos de apertura y cierre (¿? ¡!)", "Tildación de qué, cómo, cuándo, dónde y por qué"],
    skills: ["l4-puntuacion-dialogo"],
    after: [24],
  },
  {
    n: 26,
    name: "El Gran Taller de Ortografía y Redacción",
    emoji: "🏆",
    description: "Integración de reglas ortográficas: B/V, C/S/Z, G/J, homófonos y cohesión.",
    objective: "Integrar convenciones ortográficas, puntuación y clases de palabras en situaciones de revisión.",
    contents: ["Reglas de B/V, C/S/Z y G/J", "Homófonos usuales (hecho/echo, tubo/tuvo, ves/vez)", "Revisión integral de textos breves"],
    skills: ["l4-ortografia-reglas", "l4-concordancia", "l4-agudas-graves-esdrujulas"],
    after: [25],
    kind: "integracion",
  },
]);

// ------------------------------------------------------------------
// MATEMÁTICA (42001 - 42026)
// ------------------------------------------------------------------
export const GRADE4_MATEMATICA: WorldDef[] = build("matematica", [
  {
    n: 1,
    name: "Números hasta 10.000",
    emoji: "🏔️",
    description: "Lectura, escritura y escalas de 100 en 100 y 500 en 500.",
    objective: "Leer, escribir, comparar y ordenar números de cuatro cifras comprendiendo su valor posicional.",
    contents: ["Números hasta el 10.000", "Escalas ascendentes y descendentes", "Valor posicional de miles, cienes, dieces y unos"],
    skills: ["m4-numeros-10000"],
    after: [],
  },
  {
    n: 2,
    name: "La Familia de los 100.000",
    emoji: "🚀",
    description: "Decenas de mil, escalas de 1.000 en 1.000 y 10.000 en 10.000.",
    objective: "Ampliar el campo numérico hasta 100.000 reconociendo regularidades del sistema decimal.",
    contents: ["Números de cinco cifras", "Escalas de 1.000 en 1.000 y 10.000 en 10.000", "Comparación de cantidades y ubicación en rectas"],
    skills: ["m4-numeros-100000"],
    after: [1],
  },
  {
    n: 3,
    name: "Números hasta el Millón",
    emoji: "🌌",
    description: "Centenas de mil y el 1.000.000 en distancias y censos.",
    objective: "Leer y escribir números hasta el orden del millón utilizándolos en situaciones informativas reales.",
    contents: ["Números de seis y siete cifras", "El millón como unidad de orden superior", "Comparación de poblaciones y distancias"],
    skills: ["m4-numeros-millon"],
    after: [2],
  },
  {
    n: 4,
    name: "Descomposición Aditiva y Multiplicativa",
    emoji: "🧩",
    description: "Desarmar números en sumas de productos por 10, 100, 1.000 y 10.000.",
    objective: "Descomponer y componer números analizando el valor relativo de cada cifra con potencias de diez.",
    contents: ["Descomposición aditiva (40.000 + 5.000 + 800 + 30 + 2)", "Descomposición multiplicativa con potencias de diez", "Equivalencias entre órdenes"],
    skills: ["m4-descomposicion"],
    after: [3],
  },
  {
    n: 5,
    name: "El Sistema Romano",
    emoji: "🏛️",
    description: "I, V, X, L, C, D, M: siglos, capítulos y fechas en monumentos.",
    objective: "Interpretar y escribir numerales romanos comparando su sistema aditivo con el sistema decimal posicional.",
    contents: ["Símbolos romanos fundamentales (I, X, C, M) y secundarios (V, L, D)", "Reglas de adición, sustracción y no repetición", "Uso social en siglos y relojes"],
    skills: ["m4-numeros-romanos"],
    after: [4],
  },
  {
    n: 6,
    name: "Cálculo Mental de Suma y Resta",
    emoji: "⚡",
    description: "Estrategias con números redondos, dobles y descomposiciones.",
    objective: "Resolver cálculos mentales de sumas y restas desarmando números y asociando términos conocidos.",
    contents: ["Sumas y restas con múltiplos de 100 y 1.000", "Propiedad conmutativa y asociativa en el cálculo mental", "Compensaciones numéricas"],
    skills: ["m4-calculo-mental-sumaresta"],
    after: [5],
  },
  {
    n: 7,
    name: "Estimación y Redondeo",
    emoji: "🎯",
    description: "Aproximar sumas y restas a la centena o al millar más cercano.",
    objective: "Anticipar resultados y evaluar la razonabilidad de un cálculo redondeando cantidades.",
    contents: ["Redondeo a la decena, centena y millar más cercano", "Cálculo estimativo de gastos", "Control de resultados algorítmicos"],
    skills: ["m4-estimacion"],
    after: [6],
  },
  {
    n: 8,
    name: "Problemas de Varios Pasos",
    emoji: "🧭",
    description: "Compras, presupuestos y viajes por las rutas santacruceñas.",
    objective: "Planificar y resolver problemas de etapas múltiples seleccionando las operaciones adecuadas.",
    contents: ["Problemas que combinan sumas, restas y multiplicaciones", "Extracción de datos en tablas y boletas", "Verificación y respuesta explicada"],
    skills: ["m4-problemas-pasos"],
    after: [7],
  },
  {
    n: 9,
    name: "La Tabla Pitagórica y Propiedades",
    emoji: "🧮",
    description: "Relaciones de dobles, triples y mitades entre productos.",
    objective: "Memorizar y deducir productos a partir de regularidades de la tabla pitagórica y propiedades operacionales.",
    contents: ["La tabla pitagórica completa hasta 10x10", "Relaciones de dobles (tablas del 2, 4 y 8; 3 y 6)", "Propiedad distributiva de la multiplicación"],
    skills: ["m4-tabla-pitagorica"],
    after: [8],
  },
  {
    n: 10,
    name: "Organizaciones Rectangulares",
    emoji: "🧱",
    description: "Butacas de cine, baldosas y cajones en filas y columnas.",
    objective: "Resolver situaciones multiplicativas de filas por columnas y divisiones inversas.",
    contents: ["Problemas de disposición rectangular (filas x columnas)", "La multiplicación como cálculo rápido de áreas cuadriculadas", "La división para hallar filas o columnas faltantes"],
    skills: ["m4-organizaciones-rectangulares"],
    after: [9],
  },
  {
    n: 11,
    name: "Multiplicar por 10, 100 y 1.000",
    emoji: "🔟",
    description: "Agregar ceros con rapidez y entender qué pasa con el valor de posición.",
    objective: "Multiplicar por la unidad seguida de ceros explicando el desplazamiento de las cifras en el sistema posicional.",
    contents: ["Multiplicación por 10, 100 y 1.000", "Multiplicación por múltiplos de 10 (por 20, 30, 400)", "Cálculo del factor faltante"],
    skills: ["m4-multiplicacion-ceros"],
    after: [10],
  },
  {
    n: 12,
    name: "Multiplicación por Dos Cifras",
    emoji: "✖️",
    description: "Desarmar por decenas y unidades para multiplicar números grandes.",
    objective: "Comprender y dominar el algoritmo de la multiplicación por dos cifras mediante productos parciales.",
    contents: ["Multiplicación de un número de 3 o 4 cifras por otro de 2 cifras", "Productos parciales desglosados", "Algoritmo tradicional y estimación previa"],
    skills: ["m4-multiplicacion-2cifras"],
    after: [11],
  },
  {
    n: 13,
    name: "División: Reparto y Partición",
    emoji: "📦",
    description: "Repartir en partes iguales y averiguar cuántos paquetes se arman.",
    objective: "Resolver situaciones de reparto equitativo y de agrupamiento o partición utilizando la división.",
    contents: ["Sentidos de la división: reparto y partición", "Relación entre dividendo, divisor y cociente", "Cálculos mentales de división exacta"],
    skills: ["m4-division-reparto"],
    after: [12],
  },
  {
    n: 14,
    name: "División con Resto e Iteración",
    emoji: "⚖️",
    description: "¿Cuánto sobra? ¿Cuántos viajes se necesitan si no entra todo?",
    objective: "Interpretar el significado del resto en problemas reales y establecer relaciones de iteración.",
    contents: ["La cuenta de dividir con resto (D = d x c + r)", "El resto como sobrante o factor de decisión", "Problemas de cuántas veces entra un número en otro"],
    skills: ["m4-division-resto-iteracion"],
    after: [13],
  },
  {
    n: 15,
    name: "División por 10, 100 y 1.000",
    emoji: "➗",
    description: "Quitar ceros y descubrir cociente y resto en un instante.",
    objective: "Dividir números por la unidad seguida de ceros reconociendo cociente y resto según la posición.",
    contents: ["División exacta por 10, 100 y 1.000", "División con resto en números no redondos", "Relación con el sistema métrico decimal"],
    skills: ["m4-division-ceros"],
    after: [14],
  },
  {
    n: 16,
    name: "Fracciones Usuales: Mitades y Cuartos",
    emoji: "🍕",
    description: "1/2, 1/4, 3/4 y 1/8 en pizzas, chocolates y botellas.",
    objective: "Reconocer, escribir y representar gráficamente fracciones usuales asociadas a particiones de un entero.",
    contents: ["Concepto de fracción: numerador y denominador", "Fracciones usuales: 1/2, 1/4, 3/4 y 1/8", "El entero y sus partes iguales"],
    skills: ["m4-fracciones-usuales"],
    after: [15],
  },
  {
    n: 17,
    name: "Fracciones Mayores que el Entero",
    emoji: "🍫",
    description: "5/4, 3/2 y números mixtos como 1 y 1/4 o 2 y 1/2 en compras.",
    objective: "Comprender fracciones mayores que la unidad y convertirlas a expresiones mixtas de enteros y partes.",
    contents: ["Fracciones impropias (mayores que 1)", "Números mixtos en kilos y litros (1 1/2 kg, 2 1/4 l)", "Representación gráfica en varios enteros"],
    skills: ["m4-fracciones-mixtas"],
    after: [16],
  },
  {
    n: 18,
    name: "Fracciones Equivalentes y Comparación",
    emoji: "🔍",
    description: "2/4 es lo mismo que 1/2; 4/8 es la mitad de la barra.",
    objective: "Establecer equivalencias entre fracciones usuales y comparar cuál es mayor mediante representaciones y cálculos.",
    contents: ["Fracciones equivalentes (2/4 = 1/2, 4/8 = 1/2, 2/8 = 1/4)", "Comparación de fracciones con el entero y la mitad", "Ubicación relativa en la recta numérica"],
    skills: ["m4-fracciones-equivalentes"],
    after: [17],
  },
  {
    n: 19,
    name: "Suma y Resta Mental de Fracciones",
    emoji: "➕",
    description: "1/4 + 1/4 = 1/2; 1 kilo menos 1/4 son 3/4.",
    objective: "Calcular mentalmente sumas y restas sencillas de fracciones con denominadores afines y enteros.",
    contents: ["Suma y resta de fracciones de igual denominador", "Combinación de mitades y cuartos (1/2 + 1/4 = 3/4)", "Resta a un entero (1 - 1/4 = 3/4)"],
    skills: ["m4-calculo-fracciones"],
    after: [18],
  },
  {
    n: 20,
    name: "Decimales en Dinero y Medida",
    emoji: "💵",
    description: "Precios con centavos ($15,50) y medidas con coma (1,50 m).",
    objective: "Reconocer el uso social de los números decimales en monedas, billetes y cintas métricas.",
    contents: ["La coma decimal en precios y monedas", "La relación entre centavos y pesos ($1 = 100 centavos)", "Medidas de longitud con coma (metros y centímetros)"],
    skills: ["m4-decimales-dinero"],
    after: [19],
  },
  {
    n: 21,
    name: "Décimos y Centésimos",
    emoji: "🪙",
    description: "0,1 = 1/10 de peso y 0,01 = 1/100 de metro.",
    objective: "Establecer equivalencias entre expresiones decimales y fracciones decimales (décimos y centésimos).",
    contents: ["Décimos: 0,1 equivale a 1/10", "Centésimos: 0,01 equivale a 1/100", "Canje de monedas de 10 centavos y centímetros en un metro"],
    skills: ["m4-decimos-centesimos"],
    after: [20],
  },
  {
    n: 22,
    name: "Comparar y Sumar Decimales",
    emoji: "🛒",
    description: "¿Qué cuesta más? Sumas mentales de precios en el supermercado.",
    objective: "Comparar números decimales atendiendo a la parte entera y decimal y sumar mentalmente precios.",
    contents: ["Comparación de expresiones decimales ($4,80 vs $4,08)", "Suma mental de precios con centavos redondos ($2,50 + $1,50)", "Cálculo de vueltos exactos"],
    skills: ["m4-comparar-sumar-decimales"],
    after: [21],
  },
  {
    n: 23,
    name: "Rectas Paralelas y Ángulos",
    emoji: "📐",
    description: "Rectas que nunca se tocan, esquinas a 90° y uso de la escuadra.",
    objective: "Reconocer rectas paralelas y perpendiculares y clasificar ángulos rectos, agudos y obtusos.",
    contents: ["Rectas paralelas, perpendiculares y secantes", "Ángulo recto (90°), agudo (<90°) y obtuso (>90°)", "Uso de la escuadra y el transportador"],
    skills: ["m4-rectas-angulos"],
    after: [22],
  },
  {
    n: 24,
    name: "Triángulos y Cuadriláteros",
    emoji: "🔺",
    description: "Equiláteros, isósceles, escalenos, rectángulos y cuadrados.",
    objective: "Clasificar triángulos según sus lados y cuadriláteros según sus ángulos y paralelismo.",
    contents: ["Triángulos según sus lados: equilátero, isósceles y escaleno", "Cuadriláteros: cuadrado y rectángulo", "Propiedades de lados iguales y ángulos rectos"],
    skills: ["m4-triangulos-cuadrilateros"],
    after: [23],
  },
  {
    n: 25,
    name: "Círculo, Circunferencia y Cuerpos 3D",
    emoji: "⚪",
    description: "Radio, diámetro, compás y caras de cubos y prismas.",
    objective: "Distinguir círculo de circunferencia y analizar caras, aristas y vértices en cuerpos geométricos.",
    contents: ["Circunferencia y círculo: centro, radio y diámetro", "Uso del compás para trazar circunferencias", "Cuerpos geométricos (cubo, prisma): caras, aristas y vértices"],
    skills: ["m4-circunferencia-cuerpos"],
    after: [24],
  },
  {
    n: 26,
    name: "Medidas y el Gran Desafío del Perímetro",
    emoji: "🏆",
    description: "Longitud, peso, capacidad y el cálculo del contorno total.",
    objective: "Integrar equivalencias del sistema métrico y calcular el perímetro de figuras geométricas poligonales.",
    contents: ["Unidades de longitud (m, cm, km), peso (kg, g) y capacidad (l, ml)", "Cálculo del perímetro sumando los lados de triángulos y rectángulos", "Resolución de problemas de medición en campos patagónicos"],
    skills: ["m4-medidas-perimetro", "m4-problemas-pasos"],
    after: [25],
    kind: "integracion",
  },
]);

// ------------------------------------------------------------------
// CIENCIAS SOCIALES (43001 - 43020)
// ------------------------------------------------------------------
export const GRADE4_SOCIALES: WorldDef[] = build("sociales", [
  {
    n: 1,
    name: "Santa Cruz en el Mapa de Argentina",
    emoji: "🗺️",
    description: "Límites provinciales, internacionales y el extenso Mar Argentino.",
    objective: "Localizar geográficamente la provincia de Santa Cruz, identificar provincias limítrofes y la frontera internacional.",
    contents: ["Ubicación de Santa Cruz en la República Argentina", "Límites: Chubut al norte, Chile al oeste y sur, Mar Argentino al este", "Representación cartográfica"],
    skills: ["s4-santa-cruz-argentina"],
    after: [],
  },
  {
    n: 2,
    name: "Los 7 Departamentos de Santa Cruz",
    emoji: "🏛️",
    description: "Guer Aike, Deseado, Magallanes, Lago Argentino y sus cabeceras.",
    objective: "Conocer la división política de Santa Cruz en 7 departamentos y reconocer sus ciudades cabeceras.",
    contents: ["División política provincial en siete departamentos", "Ciudades cabeceras departamentales", "Río Gallegos como capital provincial y cabecera de Guer Aike"],
    skills: ["s4-departamentos"],
    after: [1],
  },
  {
    n: 3,
    name: "Relieves y Paisajes Santacruceños",
    emoji: "🏔️",
    description: "Cordillera de los Andes al oeste, mesetas al centro y costa al este.",
    objective: "Diferenciar los tres grandes relieves escalonados de Santa Cruz y sus características geomorfológicas.",
    contents: ["La Cordillera de los Andes y valles glaciarios", "La meseta patagónica escalonada hacia el mar", "La costa marítima con acantilados y rías"],
    skills: ["s4-relieves"],
    after: [2],
  },
  {
    n: 4,
    name: "Ríos, Lagos y Clima Patagónico",
    emoji: "🌊",
    description: "Río Santa Cruz, grandes lagos glaciarios y el viento de la estepa.",
    objective: "Describir la red hidrográfica santacruceña y el clima árido frío estepario con vientos predominantes del oeste.",
    contents: ["Grandes lagos: Argentino, Viedma, Buenos Aires", "Ríos provinciales: Santa Cruz, Chico, Gallegos, Deseado", "Clima frío y seco, vientos constantes y heladas"],
    skills: ["s4-hidrografia-clima"],
    after: [3],
  },
  {
    n: 5,
    name: "Recursos Naturales y Producción",
    emoji: "⛏️",
    description: "Petróleo, gas, minería de oro y carbón, pesca marina y lana.",
    objective: "Identificar los principales recursos naturales de la provincia y su importancia económica.",
    contents: ["Hidrocarburos en Cuenca Austral y Golfo San Jorge", "Minería: carbón en Río Turbio, oro y plata en Cerro Vanguardia", "Recurso pesquero marítimo y ganadería ovina"],
    skills: ["s4-recursos-economia"],
    after: [4],
  },
  {
    n: 6,
    name: "Parques Nacionales y Áreas Protegidas",
    emoji: "🏞️",
    description: "Los Glaciares, Monte León, Bosques Petrificados y Cueva de las Manos.",
    objective: "Valorar las áreas naturales protegidas como patrimonio ambiental y cultural de la humanidad.",
    contents: ["Parque Nacional Los Glaciares (UNESCO)", "Parque Nacional Monte León y fauna costera", "Bosques Petrificados de Jaramillo y Cueva de las Manos"],
    skills: ["s4-areas-protegidas"],
    after: [5],
  },
  {
    n: 7,
    name: "Riesgos Naturales y el Suelo",
    emoji: "❄️",
    description: "Nevadas extraordinarias, cenizas volcánicas y desertificación.",
    objective: "Reconocer riesgos naturales en la provincia y la vulnerabilidad del suelo frente al sobrepastoreo.",
    contents: ["Fenómenos climáticos extremos: nevadas y heladas severas", "Vulcanismo andino y dispersión de cenizas", "Desertificación y degradación de pasturas en la meseta"],
    skills: ["s4-riesgos-ambientales"],
    after: [6],
  },
  {
    n: 8,
    name: "La Estancia Ovina Santacruceña",
    emoji: "🐑",
    description: "El casco, los puestos, la esquila y la vida del trabajador rural.",
    objective: "Comprender la organización espacial y social de la estancia ovina y el circuito lanero.",
    contents: ["La estancia: casco principal, galpones y puestos alejados", "La zafra de esquila y clasificación de vellones", "El puestero y el trabajo con perros ovejeros"],
    skills: ["s4-estancia-patagonica"],
    after: [7],
  },
  {
    n: 9,
    name: "Ciudades y Servicios Urbanos",
    emoji: "🏙️",
    description: "Gas de red, agua potable, electricidad y crecimiento de ciudades.",
    objective: "Analizar los usos del suelo urbano y la necesidad indispensable de servicios básicos de red en el sur.",
    contents: ["Principales ciudades: Río Gallegos, Caleta Olivia, El Calafate", "Redes de gas natural, agua potabilizada y energía eléctrica", "Equipamiento urbano: escuelas, hospitales y transporte"],
    skills: ["s4-ciudades-servicios"],
    after: [8],
  },
  {
    n: 10,
    name: "Rutas y Conectividad Patagónica",
    emoji: "🛣️",
    description: "La mítica Ruta 40, la Ruta 3 y los puertos marítimos de aguas profundas.",
    objective: "Reconocer la red vial y de transporte que permite la conexión de las localidades en distancias extensas.",
    contents: ["Ruta Nacional 40 a lo largo de la cordillera", "Ruta Nacional 3 bordeando el litoral atlántico", "Puertos de ultramar y aeropuertos provinciales"],
    skills: ["s4-rutas-conectividad"],
    after: [9],
  },
  {
    n: 11,
    name: "Los Aonikenk: Cazadores de la Estepa",
    emoji: "🏹",
    description: "Pueblos nómadas que recorrían la meseta tras el guanaco y el choique.",
    objective: "Conocer la preexistencia y modo de vida nómada de los Aonikenk (Tehuelches) en la Patagonia continental.",
    contents: ["Sociedad nómada cazadora-recolectora", "Técnicas de caza: boleadoras, arco y flecha", "Aprovechamiento integral del guanaco: carne, cuero y tendones"],
    skills: ["s4-aonikenk-caza"],
    after: [10],
  },
  {
    n: 12,
    name: "Vida Cotidiana Aonikenk: Kau y Quillango",
    emoji: "⛺",
    description: "El toldo de cueros desmontable, la capa abrigada y el mito de Elal.",
    objective: "Analizar la vivienda, vestimenta y cosmovisión espiritual del pueblo Tehuelche.",
    contents: ["El kau: toldo móvil de postes y cueros engrasados", "El quillango: capa de pieles pintada con motivos geométricos", "Cosmovisión, respeto a la tierra y la figura mítica de Elal"],
    skills: ["s4-aonikenk-vida"],
    after: [11],
  },
  {
    n: 13,
    name: "Pueblos Fueguinos: Selk'nam y Yámanas",
    emoji: "🛶",
    description: "Cazadores pedestres del bosque y canoeros de los canales helados.",
    objective: "Comparar a los Selk'nam de la Isla Grande de Tierra del Fuego con los Yámanas de los canales australes.",
    contents: ["Selk'nam (Onas): cazadores terrestres y ceremonia del Hain", "Yámanas (Yaganes): navegantes canoeros y recolectores marinos", "Adaptaciones al clima subantártico extremo"],
    skills: ["s4-pueblos-fueguinos"],
    after: [12],
  },
  {
    n: 14,
    name: "Los Diaguitas: Agricultores del Noroeste",
    emoji: "🌽",
    description: "Pueblos sedentarios, andenes de cultivo, maíz y fortalezas (pucarás).",
    objective: "Contrastar las sociedades cazadoras patagónicas con los agricultores sedentarios del NOA.",
    contents: ["Sociedad sedentaria agricultora del Noroeste argentino", "Cultivo en terrazas regadas por acequias (maíz, zapallo, papa)", "Alfarería decorada y poblados fortificados (pucarás)"],
    skills: ["s4-diaguitas-incas"],
    after: [13],
  },
  {
    n: 15,
    name: "Magallanes en San Julián (1520)",
    emoji: "⛵",
    description: "El histórico encuentro en la bahía y el origen del nombre patagones.",
    objective: "Relatar la expedición de Hernando de Magallanes en 1520 y el primer contacto documentado con los nativos.",
    contents: ["La expedición española de circunnavegación (1520)", "Invernada en la bahía de Puerto San Julián", "Primer encuentro europeo con los Aonikenk y origen del término 'patagón'"],
    skills: ["s4-magallanes-san-julian"],
    after: [14],
  },
  {
    n: 16,
    name: "Exploradores en la Patagonia Austral",
    emoji: "🔭",
    description: "Drake, Darwin y Fitz Roy navegando el río Santa Cruz.",
    objective: "Identificar expediciones científicas y de exploración por las costas y ríos de Santa Cruz.",
    contents: ["Expedición científica del HMS Beagle con Charles Darwin", "Remonte del río Santa Cruz en 1834", "Dificultades geográficas y climáticas de los primeros asentamientos"],
    skills: ["s4-exploradores-patagonia"],
    after: [15],
  },
  {
    n: 17,
    name: "La Sociedad Colonial Americana",
    emoji: "👑",
    description: "Peninsulares, criollos, mestizos, pueblos originarios y afrodescendientes.",
    objective: "Analizar la estructura jerárquica y desigual de la sociedad colonial española en América.",
    contents: ["Los grupos sociales de la época colonial", "Españoles peninsulares, criollos y mestizos", "Pueblos indígenas y africanos en condición de esclavitud"],
    skills: ["s4-sociedad-colonial"],
    after: [16],
  },
  {
    n: 18,
    name: "El Circuito de Potosí y el Trabajo",
    emoji: "💰",
    description: "La plata del Cerro Rico, las mulas cordobesas y el trabajo forzado.",
    objective: "Explicar el circuito económico con eje en la minería de Potosí y los sistemas de mita y encomienda.",
    contents: ["El Cerro Rico de Potosí como polo de extracción de plata", "Rutas comerciales coloniales hacia Córdoba y Buenos Aires", "Sistemas de trabajo forzado: mita minera y encomienda"],
    skills: ["s4-trabajo-potosi"],
    after: [17],
  },
  {
    n: 19,
    name: "Gobierno: Municipio, Provincia y Nación",
    emoji: "⚖️",
    description: "Intendentes, Gobernadores, Presidente y los tres poderes del Estado.",
    objective: "Distinguir las atribuciones y ámbitos de actuación de los niveles municipal, provincial y nacional de gobierno.",
    contents: ["Nivel municipal: Intendente y Concejo Deliberante", "Nivel provincial: Gobernador y Legislatura Provincial", "Nivel nacional: Presidente y Congreso de la Nación"],
    skills: ["s4-gobierno-niveles"],
    after: [18],
  },
  {
    n: 20,
    name: "Derechos y Convivencia Democrática",
    emoji: "🤝",
    description: "Derechos de las infancias, normas justas y resolución pacífica de conflictos.",
    objective: "Valorar la vida en democracia, el cumplimiento de las normas de convivencia y el respeto por los derechos.",
    contents: ["Los Derechos del Niño (identidad, salud, educación, juego)", "Normas y leyes como reguladoras de la convivencia social", "Resolución pacífica de desacuerdos y diálogo democrático"],
    skills: ["s4-derechos-convivencia"],
    after: [19],
    kind: "integracion",
  },
]);

// ------------------------------------------------------------------
// CIENCIAS NATURALES (44001 - 44020)
// ------------------------------------------------------------------
export const GRADE4_NATURALES: WorldDef[] = build("naturales", [
  {
    n: 1,
    name: "Ambientes Naturales de Santa Cruz",
    emoji: "🏞️",
    description: "La estepa seca, el bosque andino húmedo y el litoral marino.",
    objective: "Caracterizar y comparar los principales ambientes de la provincia de Santa Cruz y sus factores abióticos.",
    contents: ["Estepa patagónica: vientos fuertes, escasez de agua, suelo pedregoso", "Bosque andino-patagónico: precipitaciones abundantes y temperaturas moderadas", "Litoral costero: oleaje, mareas amplias e influencia salina"],
    skills: ["n4-ambientes-santa-cruz"],
    after: [],
  },
  {
    n: 2,
    name: "Fauna Autóctona Santacruceña",
    emoji: "🦙",
    description: "Guanaco, choique, mara, cóndor, puma y pingüino de Magallanes.",
    objective: "Reconocer animales nativos de Santa Cruz y sus hábitos de vida en el ecosistema.",
    contents: ["Mamíferos autóctonos: guanaco, mara, zorro colorado, puma, huemul", "Aves autóctonas: choique, cóndor andino, pingüino de Magallanes", "Importancia de la conservación de la fauna nativa"],
    skills: ["n4-fauna-autoctona"],
    after: [1],
  },
  {
    n: 3,
    name: "Flora Autóctona de la Estepa y el Bosque",
    emoji: "🌿",
    description: "Coirón en matas, calafate con espinas, lengas y ñires.",
    objective: "Identificar especies vegetales autóctonas de la estepa y de la cordillera andina.",
    contents: ["Plantas de la meseta: coirón, neneo, mata negra, calafate", "Árboles del bosque andino: lenga, ñire, guindo y notro", "Ciclos estacionales de las plantas patagónicas"],
    skills: ["n4-flora-autoctona"],
    after: [2],
  },
  {
    n: 4,
    name: "Adaptaciones al Frío y al Viento",
    emoji: "💨",
    description: "Hojas reducidas a espinas, raíces profundas y pelajes densos.",
    objective: "Comprender cómo las características morfo-fisiológicas permiten a los seres vivos sobrevivir en climas rigurosos.",
    contents: ["Adaptaciones vegetales: hojas pequeñas, cutícula cerosa y espinas", "Adaptaciones animales: pelaje tupido de doble capa, almohadillas y reservas grasas", "Aletas natatorias e impermeabilización en aves marinas"],
    skills: ["n4-adaptaciones-vivos"],
    after: [3],
  },
  {
    n: 5,
    name: "Los Grandes Reinos de la Vida",
    emoji: "🍄",
    description: "Animales, plantas, hongos y microorganismos: ¿en qué se diferencian?",
    objective: "Clasificar seres vivos en los grandes reinos reconociendo formas de nutrición (autótrofos vs heterótrofos).",
    contents: ["Reino animal: heterótrofos con locomoción", "Reino vegetal: autótrofos fotosintéticos con clorofila", "Reino hongos: heterótrofos descomponedores por esporas", "Microorganismos microscópicos"],
    skills: ["n4-reinos-seres-vivos"],
    after: [4],
  },
  {
    n: 6,
    name: "Cadenas y Redes Tróficas",
    emoji: "🕸️",
    description: "Productores, herbívoros, carnívoros y el rol clave de los hongos descomponedores.",
    objective: "Construir cadenas y redes tróficas reconociendo los niveles de productores, consumidores y descomponedores.",
    contents: ["Productores (plantas y algas)", "Consumidores primarios (herbívoros) y secundarios (depredadores)", "Descomponedores: reciclaje de materia orgánica en el suelo"],
    skills: ["n4-cadenas-troficas"],
    after: [5],
  },
  {
    n: 7,
    name: "Impacto Humano y Conservación",
    emoji: "🛡️",
    description: "Especies exóticas que alteran el bosque (castor, visón) y áreas protegidas.",
    objective: "Evaluar el impacto de las actividades humanas y especies introducidas en el equilibrio ecológico provincial.",
    contents: ["Especies exóticas invasoras: castor en cursos de agua, visón americano", "Erosión del suelo por sobrepastoreo continuo", "Medidas de protección y rol de los Parques Nacionales"],
    skills: ["n4-impacto-conservacion"],
    after: [6],
  },
  {
    n: 8,
    name: "El Esqueleto Humano y los Huesos",
    emoji: "🦴",
    description: "Huesos fuertes que sostienen el cuerpo y protegen órganos vitales.",
    objective: "Reconocer las funciones del sistema óseo como estructura de sostén, protección de órganos y depósito mineral.",
    contents: ["El esqueleto humano como sostén corporal", "Protección de órganos: cráneo (cerebro), costillas (corazón y pulmones)", "Huesos largos, cortos y planos"],
    skills: ["n4-esqueleto-huesos"],
    after: [7],
  },
  {
    n: 9,
    name: "Las Articulaciones y el Movimiento",
    emoji: "🤸",
    description: "Articulaciones fijas en la cabeza, semimóviles y móviles en codos y rodillas.",
    objective: "Identificar tipos de articulaciones (móviles, semimóviles, fijas) y la función de cartílagos y ligamentos.",
    contents: ["Articulaciones móviles: rodilla, codo, hombro", "Articulaciones semimóviles (columna) y fijas (suturas del cráneo)", "Ligamentos y cartílagos articulares"],
    skills: ["n4-articulaciones"],
    after: [8],
  },
  {
    n: 10,
    name: "Músculos y Tendones en Acción",
    emoji: "💪",
    description: "Contracción y relajación muscular coordinada para caminar y saltar.",
    objective: "Explicar el trabajo coordinado de músculos y tendones en el movimiento voluntario e involuntario.",
    contents: ["Músculos esqueléticos voluntarios y contracción/relajación", "Músculos involuntarios (el corazón, sistema digestivo)", "Los tendones como fijación del músculo al hueso"],
    skills: ["n4-musculos-tendones"],
    after: [9],
  },
  {
    n: 11,
    name: "Cuidado de Huesos y Postura",
    emoji: "🧘",
    description: "Postura correcta al sentarse, uso de casco y alimentos con calcio.",
    objective: "Promover hábitos cotidianos que previenen lesiones en la columna y fortalecen el sistema osteomuscular.",
    contents: ["Higiene postural al sentarse, estudiar y cargar la mochila", "Importancia del ejercicio físico y el descanso reparador", "Nutrición con aporte de calcio y vitamina D para huesos sanos"],
    skills: ["n4-cuidado-postura"],
    after: [10],
  },
  {
    n: 12,
    name: "Materiales Naturales y Artificiales",
    emoji: "🪵",
    description: "Madera, lana y minerales frente a plásticos, vidrio y fibras sintéticas.",
    objective: "Diferenciar materiales de origen natural (animal, vegetal, mineral) de los producidos por transformación humana.",
    contents: ["Materiales naturales: lana de oveja, madera de lenga, metales de mina", "Materiales artificiales o transformados: plásticos, vidrio, nylon", "Relación entre disponibilidad del material y su uso"],
    skills: ["n4-materiales-origen"],
    after: [11],
  },
  {
    n: 13,
    name: "Propiedades de los Materiales",
    emoji: "🔬",
    description: "Dureza, elasticidad, flexibilidad, permeabilidad y transparencia.",
    objective: "Relacionar los usos cotidianos de los objetos con las propiedades físicas y mecánicas de sus materiales.",
    contents: ["Propiedades mecánicas: dureza frente a fragilidad, flexibilidad y elasticidad", "Permeabilidad a los líquidos", "Propiedades ópticas: transparente, translúcido y opaco"],
    skills: ["n4-propiedades-materiales"],
    after: [12],
  },
  {
    n: 14,
    name: "Estados de la Materia y Cambios",
    emoji: "🧊",
    description: "Sólido, líquido y gas: fusión, solidificación y evaporación.",
    objective: "Describir los estados de agregación de la materia y explicar los cambios de estado por variación de temperatura.",
    contents: ["Estados sólido (forma fija), líquido (adopta el envase) y gaseoso", "Fusión (hielo a agua líquida) y solidificación", "Evaporación y condensación en el ambiente"],
    skills: ["n4-estados-materia"],
    after: [13],
  },
  {
    n: 15,
    name: "El Ciclo del Agua y los Glaciares",
    emoji: "💧",
    description: "Evaporación en el mar, nevadas en los Andes y deshielos que forman ríos.",
    objective: "Analizar el ciclo del agua reconociendo el rol de los cambios de estado y las reservas de agua en glaciares.",
    contents: ["Etapas del ciclo hidrológico: evaporación, condensación y precipitación", "Acumulación de nieve y formación de campos de hielo y glaciares", "Ríos de deshielo que abastecen a la provincia"],
    skills: ["n4-ciclo-del-agua"],
    after: [14],
  },
  {
    n: 16,
    name: "Mezclas Homogéneas y Heterogéneas",
    emoji: "🥣",
    description: "Soluciones donde no se distinguen partes y mezclas donde se ve cada componente.",
    objective: "Diferenciar mezclas homogéneas (soluciones) de mezclas heterogéneas según la visibilidad de sus fases.",
    contents: ["Mezclas heterogéneas: fases diferenciables a simple vista (agua y arena)", "Mezclas homogéneas: una sola fase uniforme (agua con sal disuelta)", "Componentes sólidos, líquidos y gaseosos"],
    skills: ["n4-mezclas-tipos"],
    after: [15],
  },
  {
    n: 17,
    name: "Métodos de Separación de Mezclas",
    emoji: "🧪",
    description: "Tamices, filtros, imanes y decantación para separar sustancias.",
    objective: "Seleccionar y fundamentar el método adecuado para separar los componentes de distintas mezclas.",
    contents: ["Tamizado para separar sólidos de distinto tamaño", "Filtración para sólidos no disueltos en líquidos", "Decantación por diferencia de densidad e imantación"],
    skills: ["n4-separacion-mezclas"],
    after: [16],
  },
  {
    n: 18,
    name: "Calor, Temperatura y Aislantes",
    emoji: "🔥",
    description: "El calor viaja, el termómetro mide en °C y la lana nos abriga.",
    objective: "Diferenciar los conceptos de calor y temperatura y distinguir materiales conductores y aislantes térmicos.",
    contents: ["El calor como energía en transferencia entre cuerpos", "La temperatura y el uso del termómetro en grados Celsius", "Conductores térmicos (metales) vs aislantes (madera, lana, telgopor)"],
    skills: ["n4-calor-temperatura"],
    after: [17],
  },
  {
    n: 19,
    name: "La Luz, las Sombras y los Imanes",
    emoji: "🧲",
    description: "Rayos de luz en línea recta, sombras opacas y la atracción de los imanes.",
    objective: "Explorar la propagación rectilínea de la luz, la formación de sombras y los fenómenos de atracción/repulsión magnética.",
    contents: ["Propagación en línea recta de la luz y formación de sombras", "Cuerpos luminosos y cuerpos iluminados", "Polos norte y sur de los imanes: atracción y repulsión"],
    skills: ["n4-luz-magnetismo"],
    after: [18],
  },
  {
    n: 20,
    name: "La Tierra en el Espacio y sus Sistemas",
    emoji: "🌍",
    description: "Rotación (día y noche), traslación y los cuatro subsistemas terrestres.",
    objective: "Explicar la forma de la Tierra, sus movimientos cósmicos y la interacción de geosfera, hidrosfera, atmósfera y biosfera.",
    contents: ["Forma esférica de la Tierra y movimiento de rotación (24 horas: día y noche)", "Movimiento de traslación anual alrededor del Sol", "Los cuatro subsistemas terrestres: geosfera, hidrosfera, atmósfera y biosfera"],
    skills: ["n4-tierra-universo"],
    after: [19],
    kind: "integracion",
  },
]);

export const GRADE4_WORLDS: WorldDef[] = [
  ...GRADE4_LENGUA,
  ...GRADE4_MATEMATICA,
  ...GRADE4_SOCIALES,
  ...GRADE4_NATURALES,
];

export function getGrade4World(id: number): WorldDef | undefined {
  return GRADE4_WORLDS.find((w) => w.id === id);
}
