// Mundos de 4.º grado (segundo ciclo).
// Cada mundo pertenece a un módulo temático y se asocia a paisajes de Santa Cruz.
import { WorldDef } from "@/types";

export const GRADE4_WORLDS: WorldDef[] = [
  {
    id: 41001,
    grade: 4,
    worldNumber: 1,
    subject: "lengua",
    name: "La noticia escolar y barrial",
    emoji: "📰",
    category: "oralidad-inicial",
    description: "Titular, copete, cuerpo y epígrafes en noticias santacruceñas.",
    objective: "Reconocer las partes de la noticia: título, copete, cuerpo y epígrafe",
    contents: ["La noticia","Preguntas básicas: qué, quién, cuándo, dónde","Estructura piramidal"],
    skills: ["l4-noticia"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41002,
    grade: 4,
    worldNumber: 2,
    subject: "lengua",
    name: "Comprensión lectora: Noticias patagónicas",
    emoji: "📚",
    category: "oralidad-inicial",
    description: "Comprensión de noticias reales y de divulgación sobre la provincia.",
    objective: "Comprender noticias reales y de divulgación sobre la provincia",
    contents: ["Lectura comprensiva de noticias","Extracción de información principal e inferencias"],
    skills: ["l4-noticia-lectura"],
    prerequisites: [41001],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41003,
    grade: 4,
    worldNumber: 3,
    subject: "lengua",
    name: "El texto expositivo y sus partes",
    emoji: "📖",
    category: "oralidad-inicial",
    description: "Tema general, párrafos y subtemas en artículos de ciencias.",
    objective: "Identificar el tema general, subtítulos e ideas principales en textos de estudio",
    contents: ["Texto expositivo","Títulos y subtítulos","Párrafos con ideas secundarias"],
    skills: ["l4-expositivo"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41004,
    grade: 4,
    worldNumber: 4,
    subject: "lengua",
    name: "Comprensión lectora: Naturaleza santacruceña",
    emoji: "🌿",
    category: "oralidad-inicial",
    description: "Lectura comprensiva sobre flora, fauna y geografía de Santa Cruz.",
    objective: "Leer y comprender textos explicativos sobre flora, fauna y geografía de Santa Cruz",
    contents: ["Divulgación científica escolar","Causa y efecto en textos naturales","Vocabulario específico"],
    skills: ["l4-expositivo-lectura"],
    prerequisites: [41003],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41005,
    grade: 4,
    worldNumber: 5,
    subject: "lengua",
    name: "Biografías de personajes patagónicos",
    emoji: "⏳",
    category: "oralidad-inicial",
    description: "La vida de exploradores y pioneros en orden cronológico.",
    objective: "Reconocer las características de los relatos biográficos y el orden cronológico",
    contents: ["Biografía","Orden cronológico de los acontecimientos","Hitos de vida y legado"],
    skills: ["l4-biografia"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41006,
    grade: 4,
    worldNumber: 6,
    subject: "lengua",
    name: "Comprensión lectora: Biografías de pioneros",
    emoji: "🧭",
    category: "oralidad-inicial",
    description: "Biografías sobre exploradores, científicos y pobladores australes.",
    objective: "Comprender textos biográficos sobre exploradores, científicos y pobladores australes",
    contents: ["Lectura comprensiva de biografías","Línea de tiempo de personajes históricos"],
    skills: ["l4-biografia-lectura"],
    prerequisites: [41005],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41007,
    grade: 4,
    worldNumber: 7,
    subject: "lengua",
    name: "Textos instructivos y reglamentos escolares",
    emoji: "📋",
    category: "oralidad-inicial",
    description: "Pasos ordenados, ingredientes y verbos de acción precisos.",
    objective: "Interpretar secuencias de pasos e instrucciones con verbos en infinitivo o imperativo",
    contents: ["Texto instructivo","Materiales y pasos seriados","Normas de juegos y convivencia"],
    skills: ["l4-instructivo"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41008,
    grade: 4,
    worldNumber: 8,
    subject: "lengua",
    name: "Cartas y correos de comunicación",
    emoji: "✉️",
    category: "oralidad-inicial",
    description: "Lugar, fecha, saludo con dos puntos, mensaje y firma.",
    objective: "Reconocer la diagramación de cartas familiares: fecha, encabezado, cuerpo y firma",
    contents: ["La carta personal","Remitente y destinatario","Fórmulas de cortesía"],
    skills: ["l4-carta"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41009,
    grade: 4,
    worldNumber: 9,
    subject: "lengua",
    name: "Fábulas tradicionales y moralejas",
    emoji: "🦊",
    category: "oralidad-inicial",
    description: "Animales que dialogan y dejan una sabia enseñanza moral.",
    objective: "Identificar la personificación de animales y la enseñanza moral en las fábulas",
    contents: ["Fábulas","Personajes animales personificados","La moraleja final"],
    skills: ["l4-fabula"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41010,
    grade: 4,
    worldNumber: 10,
    subject: "lengua",
    name: "Poesía: versos, estrofas y rimas",
    emoji: "🪶",
    category: "oralidad-inicial",
    description: "Estrofas, versos que riman e imágenes sensoriales patagónicas.",
    objective: "Distinguir versos y estrofas, y reconocer rimas consonantes y asonantes",
    contents: ["El poema","Verso y estrofa","Rima consonante y asonante","Imágenes sensoriales"],
    skills: ["l4-poesia"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41011,
    grade: 4,
    worldNumber: 11,
    subject: "lengua",
    name: "El texto teatral, personajes y acotaciones",
    emoji: "🎭",
    category: "oralidad-inicial",
    description: "Parlamentos de personajes y acotaciones escénicas entre paréntesis.",
    objective: "Diferenciar los parlamentos de los personajes de las acotaciones escénicas",
    contents: ["Texto dramático","Diálogo de personajes","Acotaciones entre paréntesis"],
    skills: ["l4-teatro"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41012,
    grade: 4,
    worldNumber: 12,
    subject: "lengua",
    name: "La historieta, viñetas y onomatopeyas",
    emoji: "💭",
    category: "oralidad-inicial",
    description: "Globos de diálogo, pensamiento, grito y onomatopeyas.",
    objective: "Interpretar secuencias de viñetas, globos de diálogo y onomatopeyas gráficas",
    contents: ["La historieta","Viñetas y globos de voz/pensamiento","Onomatopeyas"],
    skills: ["l4-historieta"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41013,
    grade: 4,
    worldNumber: 13,
    subject: "lengua",
    name: "El párrafo y la oración: sangría y puntos",
    emoji: "✍️",
    category: "oralidad-inicial",
    description: "Sangría, mayúscula inicial, punto y seguido y punto y aparte.",
    objective: "Delimitar párrafos y oraciones usando sangría, mayúscula inicial y punto",
    contents: ["El párrafo","Punto seguido y punto y aparte","Coherencia de la oración"],
    skills: ["l4-parrafo-oracion"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41014,
    grade: 4,
    worldNumber: 14,
    subject: "lengua",
    name: "Cohesión y conectores temporales y causales",
    emoji: "🔗",
    category: "oralidad-inicial",
    description: "Uso de primero, luego, después y finalmente en relatos.",
    objective: "Utilizar conectores para ordenar secuencias narrativas y relaciones de causa",
    contents: ["Conectores de tiempo (primero, luego, finalmente)","Conectores causales (porque, ya que)"],
    skills: ["l4-conectores-temporales"],
    prerequisites: [41013],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41015,
    grade: 4,
    worldNumber: 15,
    subject: "lengua",
    name: "Sujeto expreso y desinencial (tácito)",
    emoji: "👤",
    category: "oralidad-inicial",
    description: "Sujeto expreso y desinencial en oraciones patagónicas.",
    objective: "Identificar el sujeto en oraciones bimembres y deducirlo cuando está omitido",
    contents: ["Sintaxis oracional","Sujeto expreso simple","Sujeto tácito o desinencial"],
    skills: ["l4-sujeto-tacito"],
    prerequisites: [41013],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41016,
    grade: 4,
    worldNumber: 16,
    subject: "lengua",
    name: "Predicado verbal simple y compuesto",
    emoji: "⚡",
    category: "oralidad-inicial",
    description: "Predicado verbal simple y compuesto en acciones cotidianas.",
    objective: "Reconocer el núcleo verbal del predicado y distinguir predicados simples y compuestos",
    contents: ["Predicado verbal simple","Predicado verbal compuesto","Concordancia sujeto-verbo"],
    skills: ["l4-predicado-verbal"],
    prerequisites: [41015],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41017,
    grade: 4,
    worldNumber: 17,
    subject: "lengua",
    name: "Sustantivos comunes, propios, individuales y colectivos",
    emoji: "🏷️",
    category: "oralidad-inicial",
    description: "Sustantivos comunes, propios y colectivos en el aula.",
    objective: "Clasificar semánticamente los sustantivos y reconocer sustantivos colectivos",
    contents: ["Sustantivo común y propio","Individual y colectivo (arboleda, cardumen, tropilla)"],
    skills: ["l4-sustantivo"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41018,
    grade: 4,
    worldNumber: 18,
    subject: "lengua",
    name: "Adjetivos calificativos, gentilicios y numerales",
    emoji: "🎨",
    category: "oralidad-inicial",
    description: "Adjetivos calificativos, gentilicios y numerales.",
    objective: "Reconocer la función de los adjetivos y clasificarlos semánticamente",
    contents: ["Adjetivos calificativos","Gentilicios (santacruceño, fueguino)","Numerales"],
    skills: ["l4-adjetivo"],
    prerequisites: [41017],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41019,
    grade: 4,
    worldNumber: 19,
    subject: "lengua",
    name: "Concordancia de género y número sustantivo-adjetivo",
    emoji: "📏",
    category: "oralidad-inicial",
    description: "Concordancia de género y número en frases sustantivas.",
    objective: "Asegurar la concordancia gramatical en frases nominales",
    contents: ["Género (femenino/masculino)","Número (singular/plural)","Concordancia artículo-sustantivo-adjetivo"],
    skills: ["l4-concordancia-gn"],
    prerequisites: [41018],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41020,
    grade: 4,
    worldNumber: 20,
    subject: "lengua",
    name: "El verbo: persona y número",
    emoji: "🔍",
    category: "oralidad-inicial",
    description: "El artículo y su función como modificador directo.",
    objective: "Identificar la persona gramatical (primera, segunda, tercera) y el número en el verbo",
    contents: ["El verbo y sus desinencias","Personas gramaticales del singular y plural"],
    skills: ["l4-verbo-persona"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41021,
    grade: 4,
    worldNumber: 21,
    subject: "lengua",
    name: "Tiempos verbales: presente, pasado y futuro",
    emoji: "⏰",
    category: "oralidad-inicial",
    description: "Tiempos verbales: pasado, presente y futuro en oraciones.",
    objective: "Diferenciar acciones en presente, pretérito y futuro en el modo indicativo",
    contents: ["Tiempos del modo indicativo","Presente, pretérito y futuro simple"],
    skills: ["l4-verbo-tiempo"],
    prerequisites: [41020],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41022,
    grade: 4,
    worldNumber: 22,
    subject: "lengua",
    name: "Pretérito perfecto simple y pretérito imperfecto",
    emoji: "⏪",
    category: "oralidad-inicial",
    description: "Pretérito perfecto simple y pretérito imperfecto narrativo.",
    objective: "Distinguir acciones puntuales terminadas de descripciones y hábitos en el pasado",
    contents: ["Pretérito perfecto simple (llegó)","Pretérito imperfecto (llegaba)","Uso narrativo"],
    skills: ["l4-preteritos-narrativos"],
    prerequisites: [41021],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41023,
    grade: 4,
    worldNumber: 23,
    subject: "lengua",
    name: "Verbos en infinitivo: terminaciones -ar, -er, -ir",
    emoji: "🗣️",
    category: "oralidad-inicial",
    description: "Infinitivos terminados en -ar, -er e -ir y conjugaciones.",
    objective: "Reconocer las tres conjugaciones regulares a partir del infinitivo",
    contents: ["Formas no personales del verbo","Infinitivo terminado en -ar, -er, -ir"],
    skills: ["l4-infinitivos"],
    prerequisites: [41020],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41024,
    grade: 4,
    worldNumber: 24,
    subject: "lengua",
    name: "Sinónimos y antónimos contextuales",
    emoji: "🔄",
    category: "oralidad-inicial",
    description: "Sinónimos para no repetir y antónimos para contrastar.",
    objective: "Reemplazar palabras por sinónimos adecuados y hallar antónimos según el contexto",
    contents: ["Sinonimia","Antonimia","Ampliación de vocabulario y precisión léxica"],
    skills: ["l4-sinonimos-antonimos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41025,
    grade: 4,
    worldNumber: 25,
    subject: "lengua",
    name: "Hiperónimos, hipónimos y campos semánticos",
    emoji: "📦",
    category: "oralidad-inicial",
    description: "Hiperónimos e hipónimos en el vocabulario patagónico.",
    objective: "Agrupar vocablos por clases generales y reconocer campos semánticos",
    contents: ["Hiperónimos e hipónimos","Campos semánticos de la fauna y geografía patagónica"],
    skills: ["l4-hiperonimos"],
    prerequisites: [41024],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#f59e0b",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41026,
    grade: 4,
    worldNumber: 26,
    subject: "lengua",
    name: "Familias de palabras, prefijos y sufijos",
    emoji: "🌱",
    category: "oralidad-inicial",
    description: "Prefijos y sufijos en la formación de nuevas palabras.",
    objective: "Reconocer raíces léxicas y formar palabras derivadas mediante afijos",
    contents: ["Raíz léxica","Prefijos (des-, re-, in-)","Sufijos (-ero, -oso, -ito, -ción)"],
    skills: ["l4-familias-prefijos"],
    prerequisites: [41024],
    activityCount: 8,
    colorFrom: "#fbcfe8",
    colorTo: "#ec4899",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41027,
    grade: 4,
    worldNumber: 27,
    subject: "lengua",
    name: "Acentuación: agudas, graves y esdrújulas",
    emoji: "✍️",
    category: "oralidad-inicial",
    description: "Palabras agudas, graves y esdrújulas con tilde ortográfica.",
    objective: "Separar en sílabas, ubicar la tónica y clasificar según las reglas de tildación",
    contents: ["Sílaba tónica","Palabras agudas, graves y esdrújulas","Reglas generales de acentuación"],
    skills: ["l4-acentuacion"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#ddd6fe",
    colorTo: "#8b5cf6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 41028,
    grade: 4,
    worldNumber: 28,
    subject: "lengua",
    name: "Signos de puntuación y reglas ortográficas (b/v, c/s/z, g/j, h, ll/y)",
    emoji: "📝",
    category: "oralidad-inicial",
    description: "Reglas de b/v, nv/mb, c/s/z, h y palabras homófonas.",
    objective: "Aplicar reglas ortográficas en grafías dudosas y signos de puntuación en textos",
    contents: ["Uso de b/v, c/s/z, g/j, h, ll/y","Coma en enumeraciones, dos puntos y raya de diálogo"],
    skills: ["l4-puntuacion-dialogo","l4-ortografia-reglas"],
    prerequisites: [41027],
    activityCount: 8,
    colorFrom: "#fed7aa",
    colorTo: "#f97316",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42001,
    grade: 4,
    worldNumber: 1,
    subject: "matematica",
    name: "Números hasta el 100.000",
    emoji: "🔢",
    category: "calculo-mental",
    description: "Lectura, escritura y orden de números de cinco cifras.",
    objective: "Leer, escribir, ordenar y componer números naturales de cinco cifras",
    contents: ["La serie numérica hasta 100.000","Escalas de 1.000 en 1.000 y de 10.000 en 10.000"],
    skills: ["m4-num-100k"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42002,
    grade: 4,
    worldNumber: 2,
    subject: "matematica",
    name: "Números hasta el 1.000.000",
    emoji: "🚀",
    category: "calculo-mental",
    description: "Descomposición aditiva y multiplicativa hasta 1.000.000.",
    objective: "Comprender la serie numérica hasta el millón y analizar regularidades",
    contents: ["Cien miles y millones","Lectura y escritura de números de 6 cifras"],
    skills: ["m4-num-1m"],
    prerequisites: [42001],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42003,
    grade: 4,
    worldNumber: 3,
    subject: "matematica",
    name: "Valor posicional y descomposición aditiva y multiplicativa",
    emoji: "🏛️",
    category: "calculo-mental",
    description: "Lectura y escritura de I, V, X, L, C, D y M.",
    objective: "Descomponer números analizando el valor posicional de cada cifra",
    contents: ["Descomposición polinómica","Multiplicaciones por 10, 100, 1.000, 10.000 y 100.000"],
    skills: ["m4-posicional"],
    prerequisites: [42002],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42004,
    grade: 4,
    worldNumber: 4,
    subject: "matematica",
    name: "Comparación y recta numérica hasta el millón",
    emoji: "💡",
    category: "calculo-mental",
    description: "Cálculos mentales apoyados en repertorios conocidos.",
    objective: "Ubicar y ordenar números grandes en la recta numérica respetando escalas",
    contents: ["Recta numérica","Escalas e intervalos","Comparación de magnitudes"],
    skills: ["m4-recta-numerica"],
    prerequisites: [42002],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42005,
    grade: 4,
    worldNumber: 5,
    subject: "matematica",
    name: "Sistema de numeración romano y comparación",
    emoji: "🎯",
    category: "calculo-mental",
    description: "Redondeo a dieces, cienes y miles para estimar sumas y restas.",
    objective: "Conocer los símbolos romanos y comparar con el sistema posicional decimal",
    contents: ["Símbolos I, V, X, L, C, D, M","Reglas aditivas y sustractivas romanas"],
    skills: ["m4-romanos"],
    prerequisites: [42001],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42006,
    grade: 4,
    worldNumber: 6,
    subject: "matematica",
    name: "Sumas y restas con números grandes",
    emoji: "🧮",
    category: "calculo-mental",
    description: "Estrategias de cálculo algorítmico y uso de calculadora.",
    objective: "Resolver problemas aditivos con números de hasta seis cifras",
    contents: ["Algoritmos convencionales","Problemas de distancias, presupuestos y poblaciones"],
    skills: ["m4-sumas-grandes"],
    prerequisites: [42002],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42007,
    grade: 4,
    worldNumber: 7,
    subject: "matematica",
    name: "Estrategias de cálculo mental y estimación",
    emoji: "📦",
    category: "calculo-mental",
    description: "Filas y columnas para resolver problemas multiplicativos.",
    objective: "Estimar resultados mediante redondeo a millares antes de operar",
    contents: ["Redondeo a millares","Estrategias de descomposición mental","Anticipación de orden de magnitud"],
    skills: ["m4-calculo-mental"],
    prerequisites: [42006],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42008,
    grade: 4,
    worldNumber: 8,
    subject: "matematica",
    name: "Multiplicación y división por la unidad seguida de ceros",
    emoji: "⚖️",
    category: "calculo-mental",
    description: "Relaciones de doble, triple y constante de proporcionalidad.",
    objective: "Multiplicar y dividir números naturales por 10, 100, 1.000 y 10.000",
    contents: ["Regularidades al agregar ceros","División exacta por unidad seguida de ceros"],
    skills: ["m4-mult-unidad-ceros"],
    prerequisites: [42001],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42009,
    grade: 4,
    worldNumber: 9,
    subject: "matematica",
    name: "Multiplicación por dos cifras y repertorio pitagórico",
    emoji: "✖️",
    category: "calculo-mental",
    description: "Algoritmo tradicional y descomposiciones de factores.",
    objective: "Desarrollar y dominar el algoritmo de multiplicación por dos cifras",
    contents: ["Algoritmo por dos cifras","Productos intermedios y valor posicional"],
    skills: ["m4-mult-2cifras"],
    prerequisites: [42008],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42010,
    grade: 4,
    worldNumber: 10,
    subject: "matematica",
    name: "Propiedades de la multiplicación",
    emoji: "➗",
    category: "calculo-mental",
    description: "Algoritmo de división: dividendo, divisor, cociente y resto.",
    objective: "Aplicar propiedades conmutativa, asociativa y distributiva",
    contents: ["Propiedad distributiva respecto a la suma","Descomposiciones factoriales"],
    skills: ["m4-propiedades-mult"],
    prerequisites: [42009],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42011,
    grade: 4,
    worldNumber: 11,
    subject: "matematica",
    name: "Organizaciones rectangulares y combinatoria",
    emoji: "🧩",
    category: "calculo-mental",
    description: "Problemas combinados con las cuatro operaciones fundamentales.",
    objective: "Resolver problemas de filas por columnas y combinaciones simples",
    contents: ["Filas y columnas","Conteo multiplicativo","Combinatoria elemental"],
    skills: ["m4-organizaciones-rectangulares"],
    prerequisites: [42009],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42012,
    grade: 4,
    worldNumber: 12,
    subject: "matematica",
    name: "División por una y dos cifras",
    emoji: "🍕",
    category: "calculo-mental",
    description: "Medios, cuartos y octavos en contextos de reparto continuo.",
    objective: "Resolver divisiones con divisor de una y dos cifras estimando cocientes",
    contents: ["Algoritmo de la división","Estimación del cociente","Repartos exactos"],
    skills: ["m4-division-algoritmo"],
    prerequisites: [42009],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42013,
    grade: 4,
    worldNumber: 13,
    subject: "matematica",
    name: "Análisis del resto en la división",
    emoji: "🍰",
    category: "calculo-mental",
    description: "Tercios, quintos y sextos en situaciones de reparto equitativo.",
    objective: "Interpretar el significado práctico del resto en problemas cotidianos",
    contents: ["Relación Dividendo = divisor × cociente + resto","Problemas de iteración y sobra"],
    skills: ["m4-div-resto"],
    prerequisites: [42012],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42014,
    grade: 4,
    worldNumber: 14,
    subject: "matematica",
    name: "Proporcionalidad directa y tablas de valores",
    emoji: "✨",
    category: "calculo-mental",
    description: "Equivalencias gráficas y numéricas entre fracciones usuales.",
    objective: "Resolver situaciones de proporcionalidad directa completando tablas",
    contents: ["Series proporcionales","Constante de proporcionalidad","Tablas dobles de valores"],
    skills: ["m4-proporcionalidad","m4-multiplos-divisores"],
    prerequisites: [42009],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42015,
    grade: 4,
    worldNumber: 15,
    subject: "matematica",
    name: "Fracciones de uso social: 1/2, 1/4, 3/4, 1/8",
    emoji: "🥞",
    category: "calculo-mental",
    description: "Fracciones impropias y números mixtos en la vida diaria.",
    objective: "Reconocer partes del todo en kilogramos, litros y particiones equitativas",
    contents: ["Medios, cuartos y octavos","Fracciones en compras de alimentos y bebidas"],
    skills: ["m4-frac-parte"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42016,
    grade: 4,
    worldNumber: 16,
    subject: "matematica",
    name: "Fracciones de tercios, quintos y sextos en repartos",
    emoji: "📏",
    category: "calculo-mental",
    description: "Ubicación de fracciones y mixtos en la escala graduada.",
    objective: "Expresar el resultado de repartos equitativos como fracción",
    contents: ["Fracciones como cociente","Reparto equitativo de enteros"],
    skills: ["m4-fracciones-reparto"],
    prerequisites: [42015],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42017,
    grade: 4,
    worldNumber: 17,
    subject: "matematica",
    name: "Fracciones equivalentes y representaciones",
    emoji: "➕",
    category: "calculo-mental",
    description: "Suma y resta de fracciones con el mismo denominador.",
    objective: "Identificar fracciones que representan la misma cantidad mediante gráficos",
    contents: ["Equivalencias gráficas","Multiplicación y división de numerador y denominador"],
    skills: ["m4-frac-equivalentes"],
    prerequisites: [42015],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42018,
    grade: 4,
    worldNumber: 18,
    subject: "matematica",
    name: "Números mixtos y fracciones mayores que 1",
    emoji: "💵",
    category: "calculo-mental",
    description: "Décimos, centésimos y milésimos en dinero y medidas.",
    objective: "Escribir y operar con fracciones impropias y números mixtos (ej. 2 1/4)",
    contents: ["Fracción impropia y número mixto","Relación con la unidad"],
    skills: ["m4-numeros-mixtos"],
    prerequisites: [42016],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42019,
    grade: 4,
    worldNumber: 19,
    subject: "matematica",
    name: "Fracciones en la recta numérica",
    emoji: "🔄",
    category: "calculo-mental",
    description: "Corrimiento de la coma al multiplicar o dividir por 10 y 100.",
    objective: "Ubicar fracciones y números mixtos entre los enteros en la recta",
    contents: ["Subdivisión de intervalos","Comparación visual en la recta numérica"],
    skills: ["m4-frac-recta"],
    prerequisites: [42017],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42020,
    grade: 4,
    worldNumber: 20,
    subject: "matematica",
    name: "Suma y resta de fracciones de igual denominador",
    emoji: "🛒",
    category: "calculo-mental",
    description: "Suma y resta de números decimales en compras cotidianas.",
    objective: "Sumar y restar fracciones homogéneas apelando al cálculo mental y gráfico",
    contents: ["Suma de numeradores con igual denominador","Cálculo de cuánto falta para el entero"],
    skills: ["m4-suma-resta-fracciones"],
    prerequisites: [42017],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42021,
    grade: 4,
    worldNumber: 21,
    subject: "matematica",
    name: "Números decimales: décimos, centésimos y milésimos",
    emoji: "📐",
    category: "calculo-mental",
    description: "Trazado e identificación de rectas paralelas y perpendiculares.",
    objective: "Vincular fracciones decimales (1/10, 1/100) con monedas, precios y medidas",
    contents: ["Expresiones decimales","Décimos, centésimos y milésimos en dinero y metros"],
    skills: ["m4-decimales-dinero"],
    prerequisites: [42015],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42022,
    grade: 4,
    worldNumber: 22,
    subject: "matematica",
    name: "Decimales multiplicados y divididos por 10, 100 y 1.000",
    emoji: "🧭",
    category: "calculo-mental",
    description: "Medición y clasificación de ángulos con transportador.",
    objective: "Comprender el corrimiento de la coma decimal en conversiones métricas y monetarias",
    contents: ["Multiplicación y división decimal por potencias de 10","Conversión cm a m y g a kg"],
    skills: ["m4-decimales-mult-div"],
    prerequisites: [42021],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42023,
    grade: 4,
    worldNumber: 23,
    subject: "matematica",
    name: "Suma y resta de números decimales cotidianos",
    emoji: "🔺",
    category: "calculo-mental",
    description: "Clasificación de triángulos por lados y por ángulos.",
    objective: "Sumar y restar precios y medidas decimales alineando la coma",
    contents: ["Algoritmo de adición y sustracción decimal","Cálculo de vueltos y totales"],
    skills: ["m4-suma-resta-decimales"],
    prerequisites: [42021],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42024,
    grade: 4,
    worldNumber: 24,
    subject: "matematica",
    name: "Rectas paralelas, secantes y perpendiculares",
    emoji: "🔷",
    category: "calculo-mental",
    description: "Cuadriláteros y cuerpos geométricos (caras, aristas, vértices).",
    objective: "Trazar e identificar rectas paralelas y perpendiculares con escuadra",
    contents: ["Posiciones relativas de rectas","Ángulo recto","Uso de regla y escuadra"],
    skills: ["m4-rectas-angulos-rectos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42025,
    grade: 4,
    worldNumber: 25,
    subject: "matematica",
    name: "Ángulos y uso del transportador",
    emoji: "⚖️",
    category: "calculo-mental",
    description: "Equivalencias entre kilogramos, gramos y miligramos.",
    objective: "Medir y clasificar ángulos en agudos, rectos y obtusos con transportador",
    contents: ["Medición de ángulos en grados","Ángulo agudo, recto y obtuso"],
    skills: ["m4-angulos-transportador"],
    prerequisites: [42024],
    activityCount: 8,
    colorFrom: "#bfdbfe",
    colorTo: "#3b82f6",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42026,
    grade: 4,
    worldNumber: 26,
    subject: "matematica",
    name: "Triángulos: clasificación por lados y ángulos",
    emoji: "🥛",
    category: "calculo-mental",
    description: "Equivalencias entre litros y mililitros en recipientes.",
    objective: "Clasificar triángulos (equilátero, isósceles, escaleno; rectángulo) y construirlos",
    contents: ["Propiedades de los lados del triángulo","Uso del compás y regla graduada"],
    skills: ["m4-triangulos"],
    prerequisites: [42025],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#22c55e",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42027,
    grade: 4,
    worldNumber: 27,
    subject: "matematica",
    name: "Cuadriláteros y cuerpos geométricos (cubos y prismas)",
    emoji: "📊",
    category: "calculo-mental",
    description: "Lectura e interpretación de tablas y gráficos de barras.",
    objective: "Reconocer propiedades de rectángulos y cuadrados, y elementos de prismas (caras, vértices, aristas)",
    contents: ["Propiedades de rectángulos y cuadrados","Cubos y prismas","Interpretación de planos y croquis"],
    skills: ["m4-cuadrilateros","m4-planos"],
    prerequisites: [42024],
    activityCount: 8,
    colorFrom: "#fecaca",
    colorTo: "#ef4444",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 42028,
    grade: 4,
    worldNumber: 28,
    subject: "matematica",
    name: "Medición: peso, capacidad, tiempo, superficies y perímetro",
    emoji: "🗺️",
    category: "calculo-mental",
    description: "Lectura de planos urbanos, referencias y trayectos.",
    objective: "Calcular perímetros, estimar superficies con cuadrícula y usar unidades de peso, capacidad y tiempo",
    contents: ["Perímetro","Superficie por cubrimiento","kg, g, litros, ml","Reloj y calendario","Lectura de gráficos de barras"],
    skills: ["m4-medidas-peso-cap","m4-tiempo","m4-superficies","m4-perimetro","m4-estadistica"],
    prerequisites: [42026],
    activityCount: 8,
    colorFrom: "#c7d2fe",
    colorTo: "#6366f1",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43001,
    grade: 4,
    worldNumber: 1,
    subject: "sociales",
    name: "Santa Cruz en el mapa argentino y continental",
    emoji: "🗺️",
    category: "paisajes-urbano-rural",
    description: "Límites, mar Argentino y cordillera de los Andes.",
    objective: "Localizar Santa Cruz en Argentina, América del Sur y el mundo",
    contents: ["Límites provinciales","Mar Argentino y Cordillera de los Andes","Escala cartográfica"],
    skills: ["s4-mapa-sc"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43002,
    grade: 4,
    worldNumber: 2,
    subject: "sociales",
    name: "División política y departamentos santacruceños",
    emoji: "🏛️",
    category: "paisajes-urbano-rural",
    description: "Los 7 departamentos provinciales y ciudades cabeceras.",
    objective: "Conocer los 7 departamentos de la provincia y sus ciudades cabeceras",
    contents: ["Departamentos santacruceños (Güer Aike, Deseado, Lago Buenos Aires, etc.)","Cabeceras departamentales"],
    skills: ["s4-departamentos-sc"],
    prerequisites: [43001],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43003,
    grade: 4,
    worldNumber: 3,
    subject: "sociales",
    name: "Ciudades y pueblos santacruceños: urbanos y rurales",
    emoji: "🏘️",
    category: "paisajes-urbano-rural",
    description: "Vida, servicios y trabajo en ciudades y en estancias.",
    objective: "Comparar la vida, servicios y trabajos en centros urbanos y en el campo",
    contents: ["Espacios urbanos (Río Gallegos, Caleta Olivia)","Espacios rurales y estancias"],
    skills: ["s4-urbano-rural"],
    prerequisites: [43002],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43004,
    grade: 4,
    worldNumber: 4,
    subject: "sociales",
    name: "Relieves de Santa Cruz: mesetas, cordillera y costa",
    emoji: "🏔️",
    category: "paisajes-urbano-rural",
    description: "Meseta escalonada, cordillera andina y costa atlántica.",
    objective: "Identificar las mesetas escalonadas, cañadones, cordillera y acantilados",
    contents: ["Meseta patagónica","Cordillera andina y valles","Costa atlántica y rías"],
    skills: ["s4-relieve-sc"],
    prerequisites: [43001],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43005,
    grade: 4,
    worldNumber: 5,
    subject: "sociales",
    name: "Cuencas hídricas: ríos y grandes lagos",
    emoji: "💧",
    category: "paisajes-urbano-rural",
    description: "Ríos provinciales y grandes lagos glaciarios.",
    objective: "Localizar los ríos provinciales y los lagos glaciarios cordilleranos",
    contents: ["Río Santa Cruz, Deseado y Chico","Lagos Argentino, Viedma y San Martín"],
    skills: ["s4-cuencas-lagos"],
    prerequisites: [43004],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43006,
    grade: 4,
    worldNumber: 6,
    subject: "sociales",
    name: "Clima frío y árido de la meseta austral",
    emoji: "💨",
    category: "paisajes-urbano-rural",
    description: "Vientos del oeste, temperaturas bajas y escasas lluvias.",
    objective: "Caracterizar las temperaturas, vientos del oeste y escasas precipitaciones",
    contents: ["Clima árido patagónico","Vientos predominantes del oeste","Estepa y amplitud térmica"],
    skills: ["s4-clima-arido"],
    prerequisites: [43004],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43007,
    grade: 4,
    worldNumber: 7,
    subject: "sociales",
    name: "Riesgos naturales patagónicos (heladas, nevadas y cenizas)",
    emoji: "❄️",
    category: "paisajes-urbano-rural",
    description: "Nevadas, heladas y cenizas volcánicas en la Patagonia.",
    objective: "Identificar amenazas climáticas y volcánicas y la prevención comunitaria",
    contents: ["Nevadas extraordinarias y heladas","Cenizas volcánicas y aislamiento de rutas"],
    skills: ["s4-riesgos-naturales"],
    prerequisites: [43006],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43008,
    grade: 4,
    worldNumber: 8,
    subject: "sociales",
    name: "Áreas protegidas y Parques Nacionales de Santa Cruz",
    emoji: "🌲",
    category: "paisajes-urbano-rural",
    description: "Parques Nacionales y conservación de la biodiversidad.",
    objective: "Valorar la conservación en Los Glaciares, Monte León, Bosques Petrificados y Cueva de las Manos",
    contents: ["Parques Nacionales","Patrimonio de la Humanidad","Conservación de biodiversidad"],
    skills: ["s4-areas-protegidas"],
    prerequisites: [43005],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43009,
    grade: 4,
    worldNumber: 9,
    subject: "sociales",
    name: "Actividades económicas: ganadería ovina y zafra lanera",
    emoji: "🐑",
    category: "paisajes-urbano-rural",
    description: "Ganadería ovina, zafra lanera y trabajadores rurales.",
    objective: "Conocer las etapas del circuito de la lana: cría, comparsa de esquila y puertos",
    contents: ["Ganadería ovina en estancias","Esquila y empaque","Trabajadores rurales y zafras"],
    skills: ["s4-ganaderia-ovina"],
    prerequisites: [43004],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43010,
    grade: 4,
    worldNumber: 10,
    subject: "sociales",
    name: "Recursos hidrocarburíferos y mineros de la provincia",
    emoji: "⛏️",
    category: "paisajes-urbano-rural",
    description: "Petróleo, gas, carbón de Río Turbio y minería austral.",
    objective: "Ubicar las cuencas petroleras del Golfo San Jorge y Austral, carbón y metales",
    contents: ["Petróleo y gas natural","Yacimiento carbonífero de Río Turbio","Minería de oro y plata"],
    skills: ["s4-energia-mineria"],
    prerequisites: [43004],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43011,
    grade: 4,
    worldNumber: 11,
    subject: "sociales",
    name: "Actividades terciarias: turismo y pesca marítima",
    emoji: "🐟",
    category: "paisajes-urbano-rural",
    description: "Recursos pesqueros del mar y puertos santacruceños.",
    objective: "Valorar el turismo de naturaleza en la cordillera y la actividad pesquera atlántica",
    contents: ["Circuitos turísticos de El Calafate y El Chaltén","Pesca en Puerto Deseado y Caleta Paula"],
    skills: ["s4-turismo-pesca"],
    prerequisites: [43008],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43012,
    grade: 4,
    worldNumber: 12,
    subject: "sociales",
    name: "Problemas ambientales locales: desertificación de la estepa",
    emoji: "⚡",
    category: "paisajes-urbano-rural",
    description: "Parques eólicos y represas hidroeléctricas santacruceñas.",
    objective: "Analizar causas del deterioro del suelo y proponer medidas de sustentabilidad",
    contents: ["Sobrepastoreo ovino","Erosión eólica del suelo","Uso racional de recursos hídricos"],
    skills: ["s4-problemas-ambientales"],
    prerequisites: [43009],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43013,
    grade: 4,
    worldNumber: 13,
    subject: "sociales",
    name: "Pueblos originarios de la meseta: los Aonikenk (tehuelches)",
    emoji: "🎒",
    category: "paisajes-urbano-rural",
    description: "Circuitos turísticos: Glaciares, Chaltén y Cueva de las Manos.",
    objective: "Comprender la vida nómada de los cazadores-recolectores y su relación con el guanaco",
    contents: ["Aonikenk nómadas","Caza con boleadoras y toldos de cuero","Organización en bandas"],
    skills: ["s4-aonikenk"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43014,
    grade: 4,
    worldNumber: 14,
    subject: "sociales",
    name: "Cazadores y canoeros australes: Selk'nam y Yámanas",
    emoji: "🛣️",
    category: "paisajes-urbano-rural",
    description: "Rutas 3 y 40, puertos marítimos y pasos cordilleranos.",
    objective: "Comparar cazadores terrestres de Tierra del Fuego con canoeros marinos",
    contents: ["Selk'nam en la Isla Grande","Yámanas en los canales fueguinos","Adaptaciones al frío costero"],
    skills: ["s4-canoeros-australes"],
    prerequisites: [43013],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43015,
    grade: 4,
    worldNumber: 15,
    subject: "sociales",
    name: "Pueblos mapuche y mapuche-tehuelche en la Patagonia",
    emoji: "👥",
    category: "paisajes-urbano-rural",
    description: "Población santacruceña y corrientes migratorias históricas.",
    objective: "Comprender la movilidad histórica en la Patagonia sin fronteras republicanas",
    contents: ["Pueblo Mapuche y Mapuche-Tehuelche","Rutas de intercambio y cosmovisión","Telar y platería"],
    skills: ["s4-mapuche"],
    prerequisites: [43013],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43016,
    grade: 4,
    worldNumber: 16,
    subject: "sociales",
    name: "Pueblos agricultores del noroeste: los Diaguitas",
    emoji: "🖐️",
    category: "paisajes-urbano-rural",
    description: "Pinturas rupestres y cazadores-recolectores milenarios.",
    objective: "Analizar una sociedad sedentaria: terrazas de cultivo, alfarería y cacicazgos",
    contents: ["Diaguitas en los valles calchaquíes","Cultivo de maíz en terrazas","Poblados fortificados (pucaráes)"],
    skills: ["s4-diaguitas"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43017,
    grade: 4,
    worldNumber: 17,
    subject: "sociales",
    name: "Una gran civilización americana: el Imperio Inca",
    emoji: "🏹",
    category: "paisajes-urbano-rural",
    description: "Cultura, nomadismo y modo de vida de los aonikenk.",
    objective: "Reconocer la organización estatal inca: caminos (Qhapaq Ñan), ayllu y terrazas",
    contents: ["El Imperio Inca (Tahuantinsuyo)","Red de caminos y chasquis","Agricultura andina y Estado"],
    skills: ["s4-incas"],
    prerequisites: [43016],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43018,
    grade: 4,
    worldNumber: 18,
    subject: "sociales",
    name: "Sociedades indígenas en el presente: derechos y comunidades",
    emoji: "🛶",
    category: "paisajes-urbano-rural",
    description: "Navegantes de los canales fueguinos: yaganes y kawésqar.",
    objective: "Valorar la continuidad cultural y los derechos constitucionales de las comunidades originarias",
    contents: ["Comunidades originarias actuales en Santa Cruz","Derecho a la identidad y educación bilingüe"],
    skills: ["s4-indigenas-presente"],
    prerequisites: [43013],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43019,
    grade: 4,
    worldNumber: 19,
    subject: "sociales",
    name: "Motivos de los viajes europeos y adelantos técnicos",
    emoji: "📜",
    category: "paisajes-urbano-rural",
    description: "Presencia histórica y cosmovisión en el sur argentino.",
    objective: "Comprender la búsqueda de rutas comerciales y los adelantos como brújula, astrolabio y naos",
    contents: ["Comercio de especias y seda con Oriente","Innovaciones en navegación marítima"],
    skills: ["s4-viajes-europeos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43020,
    grade: 4,
    worldNumber: 20,
    subject: "sociales",
    name: "La expedición de Magallanes en San Julián (1520)",
    emoji: "⛵",
    category: "paisajes-urbano-rural",
    description: "El paso interoceánico y el contacto en San Julián.",
    objective: "Conocer la invernada en Puerto San Julián, el estrecho y la primera vuelta al mundo de la nao Victoria",
    contents: ["Armada de Magallanes y Elcano","Invernada en San Julián (1520)","Primera circunnavegación del planeta"],
    skills: ["s4-magallanes"],
    prerequisites: [43019],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43021,
    grade: 4,
    worldNumber: 21,
    subject: "sociales",
    name: "Expediciones y fundación de ciudades en Argentina",
    emoji: "🏛️",
    category: "paisajes-urbano-rural",
    description: "Sucesos de mayo de 1810 y el Cabildo en el Río de la Plata.",
    objective: "Identificar las corrientes colonizadoras y las funciones de las primeras ciudades fundadas",
    contents: ["Corrientes colonizadoras (Norte, Oeste, Este)","Santiago del Estero, Córdoba y Buenos Aires","Defensa y abastecimiento"],
    skills: ["s4-fundacion-ciudades"],
    prerequisites: [43019],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43022,
    grade: 4,
    worldNumber: 22,
    subject: "sociales",
    name: "La sociedad colonial y sus estamentos",
    emoji: "📜",
    category: "paisajes-urbano-rural",
    description: "El Congreso de Tucumán y la declaración emancipadora.",
    objective: "Diferenciar los grupos sociales de la época colonial y sus desigualdades",
    contents: ["Españoles, criollos, mestizos, indígenas y africanos esclavizados","Jerarquías sociales"],
    skills: ["s4-sociedad-colonial"],
    prerequisites: [43021],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43023,
    grade: 4,
    worldNumber: 23,
    subject: "sociales",
    name: "El circuito comercial del Potosí y las economías regionales",
    emoji: "🏘️",
    category: "paisajes-urbano-rural",
    description: "Grupos sociales, costumbres y vida en la época patria.",
    objective: "Comprender cómo la plata de Potosí integró el comercio de mulas, telas y alimentos",
    contents: ["Minas de plata del cerro Potosí","El camino real y las mulas de cría","Comercio colonial"],
    skills: ["s4-circuito-potosi"],
    prerequisites: [43022],
    activityCount: 8,
    colorFrom: "#fecdd3",
    colorTo: "#e11d48",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43024,
    grade: 4,
    worldNumber: 24,
    subject: "sociales",
    name: "Conquista espiritual y mestizaje cultural",
    emoji: "⚖️",
    category: "paisajes-urbano-rural",
    description: "La Constitución Nacional como ley suprema y poderes del Estado.",
    objective: "Analizar la evangelización religiosa y la fusión de tradiciones culturales en América",
    contents: ["Misiones religiosas","Mestizaje cultural, lingüístico y gastronómico","Sincretismo"],
    skills: ["s4-conquista-espiritual"],
    prerequisites: [43022],
    activityCount: 8,
    colorFrom: "#d9f99d",
    colorTo: "#65a30d",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43025,
    grade: 4,
    worldNumber: 25,
    subject: "sociales",
    name: "La Constitución Nacional y la organización federal",
    emoji: "🏛️",
    category: "paisajes-urbano-rural",
    description: "Funciones del municipio, la provincia y la nación.",
    objective: "Reconocer la forma de gobierno representativa, republicana y federal, y los tres poderes",
    contents: ["Constitución de la Nación Argentina","Poder Ejecutivo, Legislativo y Judicial"],
    skills: ["s4-constitucion"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bae6fd",
    colorTo: "#0284c7",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 43026,
    grade: 4,
    worldNumber: 26,
    subject: "sociales",
    name: "Constitución de Santa Cruz, municipios y Derechos del Niño",
    emoji: "🤝",
    category: "paisajes-urbano-rural",
    description: "Derechos de la infancia, participación ciudadana y normas.",
    objective: "Conocer las instituciones locales (Concejo Deliberante) y los derechos de la niñez",
    contents: ["Constitución Provincial de Santa Cruz","Concejos Deliberantes e intendencias","Derechos del Niño"],
    skills: ["s4-derechos-nino"],
    prerequisites: [43025],
    activityCount: 8,
    colorFrom: "#fde68a",
    colorTo: "#ca8a04",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44001,
    grade: 4,
    worldNumber: 1,
    subject: "naturales",
    name: "Diversidad de ambientes en Santa Cruz: estepa, bosque y costa",
    emoji: "🌾",
    category: "seres-vivos-diversidad",
    description: "Estepa, bosque andino y litoral marítimo de Santa Cruz.",
    objective: "Caracterizar los ambientes aeroterrestres y de transición de la provincia",
    contents: ["Estepa patagónica","Bosque andino-patagónico","Costa marina atlántica"],
    skills: ["n4-ambientes-sc"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44002,
    grade: 4,
    worldNumber: 2,
    subject: "naturales",
    name: "Flora autóctona santacruceña (coirón, calafate, lenga)",
    emoji: "🦙",
    category: "seres-vivos-diversidad",
    description: "Guanaco, choique, cóndor, puma y macá tobiano.",
    objective: "Reconocer plantas nativas de la meseta y del bosque andino",
    contents: ["Coirón y mata negra","Lenga, ñire y notro","Calafate con frutos comestibles"],
    skills: ["n4-flora-autoctona"],
    prerequisites: [44001],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44003,
    grade: 4,
    worldNumber: 3,
    subject: "naturales",
    name: "Fauna nativa y adaptaciones (guanaco, choique, huemul)",
    emoji: "🌳",
    category: "seres-vivos-diversidad",
    description: "Lenga, ñire, calafate, mata negra y coirón austral.",
    objective: "Identificar animales autóctonos y sus estructuras de locomoción y protección",
    contents: ["Guanaco, choique, zorro colorado y puma","Huemul en los bosques cordilleranos"],
    skills: ["n4-fauna-adaptaciones"],
    prerequisites: [44001],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44004,
    grade: 4,
    worldNumber: 4,
    subject: "naturales",
    name: "Adaptaciones de seres vivos al frío y la aridez",
    emoji: "❄️",
    category: "seres-vivos-diversidad",
    description: "Grasa subcutánea, pelaje denso y espinas frente al frío.",
    objective: "Explicar estructuras morfo-fisiológicas para soportar bajas temperaturas y vientos secos",
    contents: ["Hojas reducidas y espinas","Capas de grasa y lana densa en mamíferos"],
    skills: ["n4-adaptaciones-frio"],
    prerequisites: [44002,44003],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44005,
    grade: 4,
    worldNumber: 5,
    subject: "naturales",
    name: "Los cuatro reinos de los seres vivos",
    emoji: "🔄",
    category: "seres-vivos-diversidad",
    description: "Productores, consumidores y descomponedores patagónicos.",
    objective: "Clasificar organismos en animales, plantas, hongos y microorganismos",
    contents: ["Criterios biológicos de clasificación","Nutrición autótrofa y heterótrofa","Hongos y bacterias"],
    skills: ["n4-reinos-vivos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44006,
    grade: 4,
    worldNumber: 6,
    subject: "naturales",
    name: "Redes tróficas: productores, consumidores y descomponedores",
    emoji: "🐜",
    category: "seres-vivos-diversidad",
    description: "Mutualismo, depredación, parasitismo y competencia.",
    objective: "Interpretar el flujo de materia y energía en cadenas y redes alimentarias",
    contents: ["Productores fotosintéticos","Consumidores primarios y secundarios","Descomponedores"],
    skills: ["n4-red-trofica"],
    prerequisites: [44005],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44007,
    grade: 4,
    worldNumber: 7,
    subject: "naturales",
    name: "Impacto humano en los ecosistemas y conservación",
    emoji: "⚠️",
    category: "seres-vivos-diversidad",
    description: "Impacto del visón americano, liebre y trucha en el ecosistema.",
    objective: "Analizar amenazas a la biodiversidad y medidas de protección de especies nativas",
    contents: ["Conservación del macá tobiano","Especies introducidas invasoras (visón americano)","Áreas protegidas"],
    skills: ["n4-impacto-conservacion"],
    prerequisites: [44006],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44008,
    grade: 4,
    worldNumber: 8,
    subject: "naturales",
    name: "El esqueleto humano y las funciones de los huesos",
    emoji: "🦴",
    category: "seres-vivos-diversidad",
    description: "Huesos, articulaciones y funciones de sostén y protección.",
    objective: "Describir las funciones de sostén, protección y movimiento del esqueleto humano",
    contents: ["Huesos largos, cortos y planos","Protección de órganos vitales (cráneo, caja torácica)"],
    skills: ["n4-esqueleto-huesos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44009,
    grade: 4,
    worldNumber: 9,
    subject: "naturales",
    name: "Articulaciones y músculos en el movimiento integrado",
    emoji: "💪",
    category: "seres-vivos-diversidad",
    description: "Músculos voluntarios, tendones y movimiento corporal.",
    objective: "Comprender el trabajo coordinado de huesos, articulaciones, ligamentos y músculos",
    contents: ["Articulaciones móviles, semimóviles e inmóviles","Contracción y relajación muscular con tendones"],
    skills: ["n4-articulaciones-mov","n4-musculos-tendones"],
    prerequisites: [44008],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44010,
    grade: 4,
    worldNumber: 10,
    subject: "naturales",
    name: "Cuidado del sistema osteo-artro-muscular y posturas",
    emoji: "🏃",
    category: "seres-vivos-diversidad",
    description: "Postura correcta, actividad física y prevención de lesiones.",
    objective: "Promover hábitos saludables de higiene postural, actividad física y nutrición",
    contents: ["Postura correcta y carga de mochilas","Nutrición con calcio y vitamina D","Prevención de lesiones"],
    skills: ["n4-cuidado-postura"],
    prerequisites: [44009],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44011,
    grade: 4,
    worldNumber: 11,
    subject: "naturales",
    name: "Materiales naturales y manufacturados",
    emoji: "🍎",
    category: "seres-vivos-diversidad",
    description: "Nutrientes esenciales y la gráfica de alimentación diaria.",
    objective: "Diferenciar materiales de origen natural (mineral, vegetal, animal) de manufacturados",
    contents: ["Materiales naturales y sintéticos","Propiedades de resistencia, elasticidad y flexibilidad"],
    skills: ["n4-materiales-origen"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44012,
    grade: 4,
    worldNumber: 12,
    subject: "naturales",
    name: "Conducción térmica y eléctrica de los materiales",
    emoji: "🦷",
    category: "seres-vivos-diversidad",
    description: "Higiene personal, cepillado dental y descanso saludable.",
    objective: "Distinguir materiales conductores de aislantes térmicos y eléctricos",
    contents: ["Conductores (metales) y aislantes (madera, plástico, goma, lana)","Prevención en el uso de la electricidad"],
    skills: ["n4-conductores-electricos"],
    prerequisites: [44011],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44013,
    grade: 4,
    worldNumber: 13,
    subject: "naturales",
    name: "Estados de la materia: sólidos, líquidos y gases",
    emoji: "🪵",
    category: "seres-vivos-diversidad",
    description: "Dureza, flexibilidad, elasticidad y permeabilidad de materiales.",
    objective: "Caracterizar el comportamiento macroscópico de los tres estados de agregación",
    contents: ["Sólidos (forma propia)","Líquidos (toman la forma del recipiente)","Gases (ocupan todo el volumen)"],
    skills: ["n4-estados-materia"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44014,
    grade: 4,
    worldNumber: 14,
    subject: "naturales",
    name: "Cambios de estado de agregación por efecto del calor",
    emoji: "🔌",
    category: "seres-vivos-diversidad",
    description: "Materiales conductores del calor y la electricidad y aislantes.",
    objective: "Describir fusión, solidificación, evaporación y condensación vinculados al calor",
    contents: ["Cambios de estado en el agua","El calor como transferencia de energía"],
    skills: ["n4-estados-materia"],
    prerequisites: [44013],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44015,
    grade: 4,
    worldNumber: 15,
    subject: "naturales",
    name: "Mezclas homogéneas y heterogéneas en la vida cotidiana",
    emoji: "🧱",
    category: "seres-vivos-diversidad",
    description: "Materiales naturales (lana, madera) y sintéticos (plásticos).",
    objective: "Diferenciar mezclas con fases distinguibles de disoluciones de aspecto uniforme",
    contents: ["Mezclas heterogéneas (fases visibles)","Mezclas homogéneas o soluciones"],
    skills: ["n4-mezclas-tipos"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44016,
    grade: 4,
    worldNumber: 16,
    subject: "naturales",
    name: "Métodos de separación de mezclas",
    emoji: "🔊",
    category: "seres-vivos-diversidad",
    description: "Tono (agudo/grave), intensidad (fuerte/débil) y timbre.",
    objective: "Elegir tamizado, filtración, decantación o imantación según los componentes",
    contents: ["Tamizado de sólidos de distinto tamaño","Filtración sólido-líquido","Decantación"],
    skills: ["n4-separacion-mezclas"],
    prerequisites: [44015],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44017,
    grade: 4,
    worldNumber: 17,
    subject: "naturales",
    name: "La luz: fuentes luminosas, sombras y propagación",
    emoji: "🌊",
    category: "seres-vivos-diversidad",
    description: "Ondas sonoras en sólidos, líquidos y gases y el eco.",
    objective: "Explorar fuentes de luz, propagación en línea recta y formación de sombras",
    contents: ["Fuentes naturales y artificiales","Propagación rectilínea de la luz","Cuerpos opacos, transparentes y translúcidos"],
    skills: ["n4-luz-sombras"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44018,
    grade: 4,
    worldNumber: 18,
    subject: "naturales",
    name: "El sonido: vibraciones, tono, intensidad y timbre",
    emoji: "💥",
    category: "seres-vivos-diversidad",
    description: "Fuerzas por contacto y a distancia: deformación y movimiento.",
    objective: "Reconocer que el sonido viaja por medios materiales y clasificarlo por tono e intensidad",
    contents: ["El sonido como vibración","Tono agudo y grave","Intensidad fuerte y débil","Timbre instrumental"],
    skills: ["n4-sonido"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44019,
    grade: 4,
    worldNumber: 19,
    subject: "naturales",
    name: "Magnetismo e imanes: atracción y repulsión",
    emoji: "🍎",
    category: "seres-vivos-diversidad",
    description: "La gravedad terrestre y la diferencia entre masa y peso.",
    objective: "Explorar polos magnéticos (norte y sur) y el funcionamiento de la brújula",
    contents: ["Polos magnéticos iguales se repelen y distintos se atraen","Materiales ferromagnéticos","Brújula"],
    skills: ["n4-magnetismo"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44020,
    grade: 4,
    worldNumber: 20,
    subject: "naturales",
    name: "Electrostática: fuerzas a distancia por frotamiento",
    emoji: "🧲",
    category: "seres-vivos-diversidad",
    description: "Polos magnéticos, atracción, repulsión y la brújula.",
    objective: "Observar atracción y repulsión de cargas electrostáticas generadas por fricción",
    contents: ["Fuerzas electrostáticas a distancia","Frotamiento de globos y reglas","Atracción de cuerpos ligeros"],
    skills: ["n4-electrostatica"],
    prerequisites: [44019],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44021,
    grade: 4,
    worldNumber: 21,
    subject: "naturales",
    name: "El ciclo del agua y los glaciares patagónicos",
    emoji: "🌍",
    category: "seres-vivos-diversidad",
    description: "Forma geoide, dimensiones y posición en el sistema solar.",
    objective: "Describir el ciclo hidrológico y la importancia de los glaciares como reserva de agua dulce",
    contents: ["Evaporación, condensación, precipitación y deshielo","Glaciares de campo de hielo patagónico"],
    skills: ["n4-ciclo-del-agua"],
    prerequisites: [44014],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44022,
    grade: 4,
    worldNumber: 22,
    subject: "naturales",
    name: "La Tierra como cuerpo cósmico y sus dimensiones",
    emoji: "🌅",
    category: "seres-vivos-diversidad",
    description: "Giro sobre el eje terrestre, ciclo día-noche y puntos cardinales.",
    objective: "Comprender la forma esférica de la Tierra y sus dimensiones relativas en el espacio",
    contents: ["Forma esférica achatada en los polos","Dimensiones relativas frente a la Luna y el Sol"],
    skills: ["n4-dimensiones-tierra"],
    prerequisites: [],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44023,
    grade: 4,
    worldNumber: 23,
    subject: "naturales",
    name: "Movimiento de rotación: día y noche",
    emoji: "🌕",
    category: "seres-vivos-diversidad",
    description: "Luna nueva, cuarto creciente, llena y menguante.",
    objective: "Explicar el giro de la Tierra sobre su eje y la alternancia de luz y oscuridad",
    contents: ["Rotación terrestre en 24 horas","Eje imaginario de giro","Amanecer, mediodía y anochecer"],
    skills: ["n4-rotacion-dia-noche"],
    prerequisites: [44022],
    activityCount: 8,
    colorFrom: "#fef08a",
    colorTo: "#eab308",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44024,
    grade: 4,
    worldNumber: 24,
    subject: "naturales",
    name: "Movimiento de traslación y ciclo de las cuatro estaciones",
    emoji: "🍂",
    category: "seres-vivos-diversidad",
    description: "Órbita solar, inclinación del eje y las cuatro estaciones.",
    objective: "Relacionar la órbita terrestre y la inclinación del eje con las estaciones del año",
    contents: ["Traslación anual alrededor del Sol","Inclinación del eje terrestre","Verano, otoño, invierno y primavera"],
    skills: ["n4-traslacion-estaciones"],
    prerequisites: [44022],
    activityCount: 8,
    colorFrom: "#e9d5ff",
    colorTo: "#9333ea",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44025,
    grade: 4,
    worldNumber: 25,
    subject: "naturales",
    name: "Subsistemas terrestres: geósfera, hidrósfera, atmósfera y biósfera",
    emoji: "🌋",
    category: "seres-vivos-diversidad",
    description: "Geósfera, hidrósfera, atmósfera y biósfera integradas.",
    objective: "Reconocer el planeta como un sistema integrado por cuatro subsistemas dinámicos",
    contents: ["Geósfera (rocas y suelo)","Hidrósfera (aguas y hielos)","Atmósfera (aire)","Biósfera (seres vivos)"],
    skills: ["n4-subsistemas-tierra"],
    prerequisites: [44021],
    activityCount: 8,
    colorFrom: "#bbf7d0",
    colorTo: "#16a34a",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
  {
    id: 44026,
    grade: 4,
    worldNumber: 26,
    subject: "naturales",
    name: "Geósfera: terremotos, volcanes y procesos geológicos",
    emoji: "🏔️",
    category: "seres-vivos-diversidad",
    description: "Sismos, fallas geológicas, volcanes y cenizas en Santa Cruz.",
    objective: "Identificar procesos del interior terrestre: sismos, vulcanismo y cordilleras",
    contents: ["Estructura interna terrestre","Temblores y sismos","Erupciones volcánicas y cenizas en la Patagonia"],
    skills: ["n4-terremotos-volcanes"],
    prerequisites: [44025],
    activityCount: 8,
    colorFrom: "#a5f3fc",
    colorTo: "#0891b2",
    difficulty: "basico",
    assessment: "Logrado con 90% o más en una vuelta y una vuelta de repaso. Con 60% se abre el mundo siguiente.",
  },
];
